resource/aws_eks_cluster: Limit UpdateClusterConfig to only nested argument changes
Previous output from acceptance testing:

```
--- FAIL: TestAccAWSEksCluster_Version (2519.24s)
    testing.go:538: Step 2 error: Error applying: 1 error occurred:
        	* aws_eks_cluster.test: 1 error occurred:
        	* aws_eks_cluster.test: error updating EKS Cluster (tf-acc-test-zdu6h) config: InvalidParameterException: Cluster is already at the desired configuration with endpointPrivateAccess: false and endpointPublicAccess: true
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEksClusterDataSource_basic (1320.87s)

--- PASS: TestAccAWSEksCluster_basic (1295.89s)
--- PASS: TestAccAWSEksCluster_VpcConfig_SecurityGroupIds (1327.26s)
--- PASS: TestAccAWSEksCluster_VpcConfig_EndpointPrivateAccess (1490.80s)
--- PASS: TestAccAWSEksCluster_VpcConfig_EndpointPublicAccess (1526.63s)
--- PASS: TestAccAWSEksCluster_Version (2552.56s)
```