tests/provider: Provide helpful error when AWS_ALTERNATE_REGION partition does not match AWS_DEFAULT_REGION partition (#10970)
Certain acceptance tests require multiple regions and when the AWS_ALTERNATE_REGION environment variable is omitted for testing outside AWS Commercial (e.g. AWS GovCloud (US)), previously testing could throw an initially cryptic error:

```console
$ export AWS_DEFAULT_REGION=us-gov-west-1
$ TF_ACC=1 go test ./aws -v -count 1 -timeout 120m -parallel 20 -run='TestAccAWSEbsSnapshotCopy_withRegions'
...
--- FAIL: TestAccAWSEbsSnapshotCopy_withRegions (4.70s)
    testing.go:635: Step 0 error: errors during refresh:

        Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
```

This update allows us to return a custom error before provider initialization:

```
--- FAIL: TestAccAWSEbsSnapshotCopy_withRegions (2.06s)
    provider_test.go:248: AWS_ALTERNATE_REGION partition (aws) does not match AWS_DEFAULT_REGION partition (aws-us-gov)
```

When AWS_ALTERNATE_REGION is set correctly, testing passes as expected:

```console
$ export AWS_ALTERNATE_REGION=us-gov-east-1
$ TF_ACC=1 go test ./aws -v -count 1 -timeout 120m -parallel 20 -run='TestAccAWSEbsSnapshotCopy_withRegions'
...
--- PASS: TestAccAWSEbsSnapshotCopy_withRegions (67.50s)
```