Revert "resource/aws_acm_certificate: Retry logic refactor" (#10184)
* Revert "Merge pull request #9863 from terraform-providers/rfd-retry-acm"

This reverts commit 4879c29ec772f5393f7653020e43585a7af59f84, reversing
changes made to 38fc3b97370dcfccd27761e0654245cafaa5ff98.

Before Change
```
--- FAIL: TestAccAWSAcmCertificate_tags (76.71s)
    testing.go:569: Step 0 error: errors during apply:

        Error: error getting validation options for ACM certificate: no validation options need to retry.

          on /tmp/tf-test030858259/main.tf line 2:
          (source code not available)

--- FAIL: TestAccAWSAcmCertificate_san_TrailingPeriod (76.93s)
--- FAIL: TestAccAWSAcmCertificate_disableCTLogging (77.52s)
--- FAIL: TestAccAWSAcmCertificate_san_single (78.13s)
--- FAIL: TestAccAWSAcmCertificate_root_TrailingPeriod (81.75s)

--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsEmail (74.93s)
    testing.go:562: Step 0, expected error:

        errors during apply: error getting validation options for ACM certificate: no validation options need to retry.

        To match:

        validation_record_fqdns is only valid for DNS validation
--- FAIL: TestAccAWSAcmCertificateValidation_timeout (75.22s)
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdns (77.35s)
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsRoot (79.41s)
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot (79.65s)
--- FAIL: TestAccAWSAcmCertificateValidation_basic (79.71s)
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsRootAndWildcard (80.34s)
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsSan (80.93s)
--- FAIL: TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcard (82.78s)

```

After Revert
```
--- PASS: TestAccAWSAcmCertificate_imported_IpAddress (24.53s)
--- PASS: TestAccAWSAcmCertificate_emailValidation (27.48s)
--- PASS: TestAccAWSAcmCertificate_root (27.82s)
--- PASS: TestAccAWSAcmCertificate_root_TrailingPeriod (29.32s)
--- PASS: TestAccAWSAcmCertificate_dnsValidation (29.96s)
--- PASS: TestAccAWSAcmCertificate_disableCTLogging (30.17s)
--- PASS: TestAccAWSAcmCertificate_san_TrailingPeriod (30.38s)
--- PASS: TestAccAWSAcmCertificate_wildcardAndRootSan (30.80s)
--- PASS: TestAccAWSAcmCertificate_wildcard (30.85s)
--- PASS: TestAccAWSAcmCertificate_rootAndWildcardSan (32.26s)
--- PASS: TestAccAWSAcmCertificate_privateCert (34.07s)
--- PASS: TestAccAWSAcmCertificate_san_single (36.02s)
--- PASS: TestAccAWSAcmCertificate_imported_DomainName (37.99s)
--- PASS: TestAccAWSAcmCertificate_tags (66.36s)

--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdnsEmail (17.38s)
--- PASS: TestAccAWSAcmCertificateValidation_timeout (24.80s)
--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcard (668.03s)
--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdnsRootAndWildcard (672.25s)
--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdnsWildcardAndRoot (672.72s)
--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdns (698.98s)
--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdnsSan (700.61s)
--- PASS: TestAccAWSAcmCertificateValidation_validationRecordFqdnsRoot (702.39s)
--- PASS: TestAccAWSAcmCertificateValidation_basic (708.19s)
```

* CHANGELOG: remove entry for #9863