resource/aws_autoscaling_group: Ignore ordering differences for `tags` argument
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13469

Now that we are properly setting this attribute into the Terraform state, it highlighted ordering issues, which was not previously caught by the acceptance testing for the resource.

Previously (after test configuration adjustment):

```
--- FAIL: TestAccAWSAutoScalingGroup_basic (147.82s)
    TestAccAWSAutoScalingGroup_basic: testing.go:684: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_autoscaling_group.bar
...
          tags.#:                     "3" => "3"
          tags.0.key:                 "FromTags1" => "FromTags1"
          tags.0.propagate_at_launch: "true" => "true"
          tags.0.value:               "value1" => "value1"
          tags.1.key:                 "FromTags2" => "FromTags3"
          tags.1.propagate_at_launch: "true" => "true"
          tags.1.value:               "value2" => "value3"
          tags.2.key:                 "FromTags3" => "FromTags2"
          tags.2.propagate_at_launch: "true" => "true"
          tags.2.value:               "value3" => "value2"
...
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups (187.12s)
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups_ELBCapacity (342.93s)
--- PASS: TestAccAWSAutoScalingGroup_autoGeneratedName (79.14s)
--- PASS: TestAccAWSAutoScalingGroup_basic (267.48s)
--- PASS: TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier (78.67s)
--- PASS: TestAccAWSAutoScalingGroup_emptyAvailabilityZones (91.64s)
--- PASS: TestAccAWSAutoScalingGroup_enablingMetrics (207.54s)
--- PASS: TestAccAWSAutoScalingGroup_initialLifecycleHook (304.85s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate (87.94s)
--- PASS: TestAccAWSAutoScalingGroup_LaunchTemplate_IAMInstanceProfile (99.20s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate_update (175.02s)
--- PASS: TestAccAWSAutoScalingGroup_launchTempPartitionNum (90.52s)
--- PASS: TestAccAWSAutoScalingGroup_LoadBalancers (569.76s)
--- PASS: TestAccAWSAutoScalingGroup_MaxInstanceLifetime (87.50s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy (83.65s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandAllocationStrategy (56.61s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandBaseCapacity (160.95s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandPercentageAboveBaseCapacity (83.85s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotAllocationStrategy (116.76s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotInstancePools (112.29s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotMaxPrice (160.14s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_LaunchTemplateName (88.11s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_Version (116.78s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_Override_InstanceType (123.93s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_Override_WeightedCapacity (168.12s)
--- PASS: TestAccAWSAutoScalingGroup_namePrefix (78.08s)
--- PASS: TestAccAWSAutoScalingGroup_serviceLinkedRoleARN (53.32s)
--- PASS: TestAccAWSAutoScalingGroup_suspendingProcesses (242.59s)
--- PASS: TestAccAWSAutoScalingGroup_tags (287.70s)
--- PASS: TestAccAWSAutoScalingGroup_TargetGroupArns (316.34s)
--- PASS: TestAccAWSAutoScalingGroup_terminationPolicies (154.29s)
--- PASS: TestAccAWSAutoScalingGroup_VpcUpdates (175.10s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer (423.35s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer_ToTargetGroup (428.41s)
--- PASS: TestAccAWSAutoScalingGroup_withMetrics (114.18s)
--- PASS: TestAccAWSAutoScalingGroup_withPlacementGroup (175.16s)
```