tests/service/appsync: Add PreCheck for service availability
Previously in AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSAppsyncGraphqlApi_basic (6.36s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating AppSync GraphQL API: RequestError: send request failed
        caused by: Post https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
```

Output from AWS Standard acceptance testing:

```
--- PASS: TestAccAWSAppsyncGraphqlApi_disappears (11.00s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey (12.86s)
--- PASS: TestAccAwsAppsyncDatasource_Type_HTTP (14.70s)
--- PASS: TestAccAWSAppsyncApiKey_basic (15.89s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL (19.99s)
--- PASS: TestAccAwsAppsyncDatasource_Type (20.55s)
--- PASS: TestAccAWSAppsyncGraphqlApi_basic (23.15s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType (23.45s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect (10.83s)
--- PASS: TestAccAwsAppsyncDatasource_Type_None (24.06s)
--- PASS: TestAccAWSAppsyncGraphqlApi_LogConfig (13.60s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AWSIAM (24.69s)
--- FAIL: TestAccAwsAppsyncDatasource_Type_Lambda (25.53s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.
        	status code: 400, request id: 2ad8fdcd-78dd-11e9-82e1-0b28c3b9519b

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test220210354/main.tf line 21:
          (source code not available)

--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_Issuer (27.02s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_IatTTL (28.93s)
--- PASS: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion (29.85s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Schema (30.41s)
--- PASS: TestAccAwsAppsyncDatasource_Type_DynamoDB (30.73s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools (16.64s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Name (31.69s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_ClientID (31.98s)
--- PASS: TestAccAWSAppsyncGraphqlApi_LogConfig_FieldLogLevel (32.35s)
--- PASS: TestAccAwsAppsyncResolver_disappears (17.48s)
--- PASS: TestAccAwsAppsyncResolver_basic (18.71s)
--- PASS: TestAccAwsAppsyncDatasource_basic (14.51s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Tags (19.65s)
--- PASS: TestAccAwsAppsyncDatasource_HTTPConfig_Endpoint (20.76s)
--- PASS: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction (21.72s)
--- PASS: TestAccAWSAppsyncApiKey_Expires (18.96s)
--- PASS: TestAccAwsAppsyncDatasource_Description (20.44s)
--- PASS: TestAccAWSAppsyncApiKey_Description (18.41s)
--- PASS: TestAccAwsAppsyncResolver_ResponseTemplate (23.14s)
--- PASS: TestAccAwsAppsyncResolver_DataSource (22.28s)
--- PASS: TestAccAwsAppsyncResolver_RequestTemplate (26.09s)
--- PASS: TestAccAwsAppsyncResolver_multipleResolvers (47.98s)
--- PASS: TestAccAwsAppsyncDatasource_DynamoDBConfig_UseCallerCredentials (122.51s)
--- PASS: TestAccAwsAppsyncDatasource_DynamoDBConfig_Region (124.23s)
--- PASS: TestAccAwsAppsyncDatasource_ElasticsearchConfig_Region (551.20s)
--- PASS: TestAccAwsAppsyncDatasource_Type_Elasticsearch (648.43s)
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAwsAppsyncDatasource_Type_Elasticsearch (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_AuthenticationType (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_Type_HTTP (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_Type_DynamoDB (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_Type_None (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_ElasticsearchConfig_Region (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_basic (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncApiKey_basic (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AWSIAM (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncApiKey_Expires (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_Type_Lambda (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_HTTPConfig_Endpoint (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_Type (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_DynamoDBConfig_UseCallerCredentials (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_Schema (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_disappears (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_Description (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_basic (2.55s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncDatasource_DynamoDBConfig_Region (3.32s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_Tags (1.86s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncResolver_RequestTemplate (1.90s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL (1.90s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncResolver_disappears (1.91s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncResolver_DataSource (1.92s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect (1.92s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncResolver_basic (1.93s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncResolver_ResponseTemplate (1.93s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion (1.93s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_ClientID (1.93s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_LogConfig (1.93s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncApiKey_Description (1.95s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_LogConfig_FieldLogLevel (1.95s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsAppsyncResolver_multipleResolvers (1.96s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_Issuer (2.00s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools (2.00s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction (2.01s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_Name (2.03s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_IatTTL (2.04s)
    resource_aws_appsync_graphql_api_test.go:790: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
```