tests/resource/aws_db_security_group: Fix CheckDestroy and CheckExists Provider
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17392

Currently the `TestAccAWSDBSecurityGroup_basic` acceptance test fails in TeamCity:

```
=== CONT  TestAccAWSDBSecurityGroup_basic
resource_aws_db_security_group_test.go:20: Step 1/2 error: Check failed: Check 1/8 error: DBSecurityGroupNotFound: DBSecurityGroup tf-acc-fwy4o not found.
  status code: 404, request id: fd813712-f78f-435a-99f5-cee60d22d51d
--- FAIL: TestAccAWSDBSecurityGroup_basic (15.08s)
```

The resource can only exist in an EC2-Classic enabled region. While the test function and configuration are set up to switch the region, the `testAccCheckAWSDBSecurityGroupDestroy` and `testAccCheckAWSDBSecurityGroupExists` use `testAccProvider` instead of `testAccProviderEc2Classic`.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSDBSecurityGroup_basic (14.52s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSDBSecurityGroup_basic (2.76s)
```