resource/aws_network_interface_sg_attachment: Properly handle InvalidNetworkInterfaceID.NotFound errors
Changes:
* Refactor `aws_network_interface_sg_attachments` acceptance testing to align with other resources
* Add `testAccCheckAWSENIDisappears`
* Add `TestAccAWSNetworkInterfaceSGAttachment_disappears` acceptance test for verifying error handling
* Ensure `aws_network_interface_sg_attachment` resource removes resource during Read and exits successfully during Delete if it receives `InvalidNetworkInterfaceID.NotFound` error

Previously (before code updates):

```
--- PASS: TestAccAWSENI_disappears (35.81s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_Multiple (33.03s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_basic (34.00s)
--- FAIL: TestAccAWSNetworkInterfaceSGAttachment_disappears (41.18s)
    testing.go:527: Step 1 error: Error on follow-up refresh: 1 error occurred:
        	* aws_network_interface_sg_attachment.test: 1 error occurred:
        	* aws_network_interface_sg_attachment.test: aws_network_interface_sg_attachment.test: InvalidNetworkInterfaceID.NotFound: The networkInterface ID 'eni-06f5470ea633d8b1c' does not exist
        	status code: 400, request id: 8f424390-cf91-4ef7-9d03-ed6e8711244c
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_DataSource (113.03s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_Instance (119.99s)
```

Now:

```
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_Multiple (33.00s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_basic (35.31s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_disappears (50.21s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_DataSource (115.76s)
--- PASS: TestAccAWSNetworkInterfaceSGAttachment_Instance (131.26s)
```