r/aws_vpc_route_table_association: return non-zero value for `ready` status
With the move from the Plugin SDK V2 retry package to our internal `retry` package, zero values returned by status functions will now imply a resource is `NotFound`. This replaces the empty string return with `true` such that the intended meaning is supplied to the upstream polling logic.

Before:

```console
%  make t K=vpc T=TestAccVPCEndpointRouteTableAssociation_basic
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 td-go-vcr-ec2 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpointRouteTableAssociation_basic'  -timeout 360m -vet=off
2026/03/02 11:16:16 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/02 11:16:16 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCEndpointRouteTableAssociation_basic
=== PAUSE TestAccVPCEndpointRouteTableAssociation_basic
=== CONT  TestAccVPCEndpointRouteTableAssociation_basic
    vpc_endpoint_route_table_association_test.go:24: Step 1/2 error: Error running apply: exit status 1

        Error: waiting for VPC Endpoint Route Table Association (vpce-03ca60250cdfa1136/rtb-0508b35eb18d684ff) to become available: couldn't find resource (21 retries)

          with aws_vpc_endpoint_route_table_association.test,
          on terraform_plugin_test.tf line 39, in resource "aws_vpc_endpoint_route_table_association" "test":
          39: resource "aws_vpc_endpoint_route_table_association" "test" {

--- FAIL: TestAccVPCEndpointRouteTableAssociation_basic (178.60s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        185.702s
```

After:

```console
% make t K=vpc T=TestAccVPCEndpointRouteTableAssociation_basic
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 td-go-vcr-ec2 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpointRouteTableAssociation_basic'  -timeout 360m -vet=off
2026/03/02 11:23:47 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/02 11:23:47 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCEndpointRouteTableAssociation_basic
=== PAUSE TestAccVPCEndpointRouteTableAssociation_basic
=== CONT  TestAccVPCEndpointRouteTableAssociation_basic
--- PASS: TestAccVPCEndpointRouteTableAssociation_basic (32.71s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        39.819s
```