resource/aws_elasticsearch_domain: Clarify zone_awareness_enabled argument (#12296)
* zone_awareness_enabled - elaboration

Its not clear that you have to set zone_awareness_enabled to true for muli-az deployments.  Yes its logical however I battled this for a while today until I came across a stack overflow article that cleared up the confusion.  

This is the error you get when specifying two subnets with zone_awwareness_enabled set to false:
```
Error: Error applying plan:
1 error(s) occurred:
* module.elasticsearch.aws_elasticsearch_domain.example: 1 error(s) occurred:
* aws_elasticsearch_domain.example: ValidationException: You must specify exactly one subnet.
        status code: 400, request id: 80a3e9fa-ef83-45bb-a869-95c406b046f1
```

* backticks on true

forgot backtics on true