tests/resource/aws_transfer_server: Refactor VPC endpoint testing configuration to remove error, 0.12 syntax, and formatting
Previously:

```
=== CONT  TestAccAWSTransferServer_Vpc
    resource_aws_transfer_server_test.go:119: Step 1/3 error: terraform failed: exit status 1

        stderr:

        Error: Reference to undeclared resource

          on ../../../../../../../../var/folders/w8/05f3x02n27x72g0mc2jy6_180000gp/T/tftest338659464/work499087943/config361699947/terraform_plugin_test.tf line 43, in resource "aws_security_group" "test":
          43:   vpc_id      = data.aws_vpc.test.id

        A data resource "aws_vpc" "test" has not been declared in the root module.
```

Output from acceptance testing:

```
--- PASS: TestAccAWSTransferServer_Vpc (231.03s)
```