r/aws_security_group: Tidy up resource Delete.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccVPCSecurityGroup_' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCSecurityGroup_ -timeout 180m
=== RUN   TestAccVPCSecurityGroup_basic
=== PAUSE TestAccVPCSecurityGroup_basic
=== RUN   TestAccVPCSecurityGroup_basicEC2Classic
=== PAUSE TestAccVPCSecurityGroup_basicEC2Classic
=== RUN   TestAccVPCSecurityGroup_disappears
=== PAUSE TestAccVPCSecurityGroup_disappears
=== RUN   TestAccVPCSecurityGroup_nameGenerated
=== PAUSE TestAccVPCSecurityGroup_nameGenerated
=== RUN   TestAccVPCSecurityGroup_nameTerraformPrefix
=== PAUSE TestAccVPCSecurityGroup_nameTerraformPrefix
=== RUN   TestAccVPCSecurityGroup_namePrefix
=== PAUSE TestAccVPCSecurityGroup_namePrefix
=== RUN   TestAccVPCSecurityGroup_namePrefixTerraform
=== PAUSE TestAccVPCSecurityGroup_namePrefixTerraform
=== RUN   TestAccVPCSecurityGroup_tags
=== PAUSE TestAccVPCSecurityGroup_tags
=== RUN   TestAccVPCSecurityGroup_allowAll
=== PAUSE TestAccVPCSecurityGroup_allowAll
=== RUN   TestAccVPCSecurityGroup_sourceSecurityGroup
=== PAUSE TestAccVPCSecurityGroup_sourceSecurityGroup
=== RUN   TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules
=== PAUSE TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules
=== RUN   TestAccVPCSecurityGroup_ipRangesWithSameRules
=== PAUSE TestAccVPCSecurityGroup_ipRangesWithSameRules
=== RUN   TestAccVPCSecurityGroup_egressMode
=== PAUSE TestAccVPCSecurityGroup_egressMode
=== RUN   TestAccVPCSecurityGroup_ingressMode
=== PAUSE TestAccVPCSecurityGroup_ingressMode
=== RUN   TestAccVPCSecurityGroup_ruleGathering
=== PAUSE TestAccVPCSecurityGroup_ruleGathering
=== RUN   TestAccVPCSecurityGroup_forceRevokeRulesTrue
=== PAUSE TestAccVPCSecurityGroup_forceRevokeRulesTrue
=== RUN   TestAccVPCSecurityGroup_forceRevokeRulesFalse
=== PAUSE TestAccVPCSecurityGroup_forceRevokeRulesFalse
=== RUN   TestAccVPCSecurityGroup_change
=== PAUSE TestAccVPCSecurityGroup_change
=== RUN   TestAccVPCSecurityGroup_ipv6
=== PAUSE TestAccVPCSecurityGroup_ipv6
=== RUN   TestAccVPCSecurityGroup_self
=== PAUSE TestAccVPCSecurityGroup_self
=== RUN   TestAccVPCSecurityGroup_vpc
=== PAUSE TestAccVPCSecurityGroup_vpc
=== RUN   TestAccVPCSecurityGroup_vpcNegOneIngress
=== PAUSE TestAccVPCSecurityGroup_vpcNegOneIngress
=== RUN   TestAccVPCSecurityGroup_vpcProtoNumIngress
=== PAUSE TestAccVPCSecurityGroup_vpcProtoNumIngress
=== RUN   TestAccVPCSecurityGroup_multiIngress
=== PAUSE TestAccVPCSecurityGroup_multiIngress
=== RUN   TestAccVPCSecurityGroup_ruleDescription
=== PAUSE TestAccVPCSecurityGroup_ruleDescription
=== RUN   TestAccVPCSecurityGroup_defaultEgressVPC
=== PAUSE TestAccVPCSecurityGroup_defaultEgressVPC
=== RUN   TestAccVPCSecurityGroup_drift
=== PAUSE TestAccVPCSecurityGroup_drift
=== RUN   TestAccVPCSecurityGroup_driftComplex
=== PAUSE TestAccVPCSecurityGroup_driftComplex
=== RUN   TestAccVPCSecurityGroup_invalidCIDRBlock
=== PAUSE TestAccVPCSecurityGroup_invalidCIDRBlock
=== RUN   TestAccVPCSecurityGroup_cidrAndGroups
=== PAUSE TestAccVPCSecurityGroup_cidrAndGroups
=== RUN   TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC
=== PAUSE TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC
=== RUN   TestAccVPCSecurityGroup_ingressWithCIDRAndSGsClassic
=== PAUSE TestAccVPCSecurityGroup_ingressWithCIDRAndSGsClassic
=== RUN   TestAccVPCSecurityGroup_egressWithPrefixList
=== PAUSE TestAccVPCSecurityGroup_egressWithPrefixList
=== RUN   TestAccVPCSecurityGroup_ingressWithPrefixList
=== PAUSE TestAccVPCSecurityGroup_ingressWithPrefixList
=== RUN   TestAccVPCSecurityGroup_ipv4AndIPv6Egress
=== PAUSE TestAccVPCSecurityGroup_ipv4AndIPv6Egress
=== RUN   TestAccVPCSecurityGroup_failWithDiffMismatch
=== PAUSE TestAccVPCSecurityGroup_failWithDiffMismatch
=== RUN   TestAccVPCSecurityGroup_ruleLimitExceededAppend
=== PAUSE TestAccVPCSecurityGroup_ruleLimitExceededAppend
=== RUN   TestAccVPCSecurityGroup_ruleLimitCIDRBlockExceededAppend
=== PAUSE TestAccVPCSecurityGroup_ruleLimitCIDRBlockExceededAppend
=== RUN   TestAccVPCSecurityGroup_ruleLimitExceededPrepend
=== PAUSE TestAccVPCSecurityGroup_ruleLimitExceededPrepend
=== RUN   TestAccVPCSecurityGroup_ruleLimitExceededAllNew
=== PAUSE TestAccVPCSecurityGroup_ruleLimitExceededAllNew
=== RUN   TestAccVPCSecurityGroup_rulesDropOnError
=== PAUSE TestAccVPCSecurityGroup_rulesDropOnError
=== CONT  TestAccVPCSecurityGroup_basic
=== CONT  TestAccVPCSecurityGroup_vpcNegOneIngress
=== CONT  TestAccVPCSecurityGroup_ingressWithCIDRAndSGsClassic
--- PASS: TestAccVPCSecurityGroup_ingressWithCIDRAndSGsClassic (15.01s)
=== CONT  TestAccVPCSecurityGroup_failWithDiffMismatch
--- PASS: TestAccVPCSecurityGroup_basic (22.78s)
=== CONT  TestAccVPCSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccVPCSecurityGroup_vpcNegOneIngress (23.12s)
=== CONT  TestAccVPCSecurityGroup_rulesDropOnError
--- PASS: TestAccVPCSecurityGroup_failWithDiffMismatch (24.63s)
=== CONT  TestAccVPCSecurityGroup_ruleLimitExceededAllNew
=== CONT  TestAccVPCSecurityGroup_ruleLimitExceededAppend
    vpc_security_group_test.go:2070: Step 2/3, expected an error but got none
--- FAIL: TestAccVPCSecurityGroup_ruleLimitExceededAppend (37.23s)
=== CONT  TestAccVPCSecurityGroup_ipv4AndIPv6Egress
--- PASS: TestAccVPCSecurityGroup_rulesDropOnError (40.55s)
=== CONT  TestAccVPCSecurityGroup_ingressWithPrefixList
=== CONT  TestAccVPCSecurityGroup_ruleLimitExceededAllNew
    vpc_security_group_test.go:2223: Step 2/3, expected an error but got none
--- FAIL: TestAccVPCSecurityGroup_ruleLimitExceededAllNew (38.39s)
=== CONT  TestAccVPCSecurityGroup_egressWithPrefixList
--- PASS: TestAccVPCSecurityGroup_ipv4AndIPv6Egress (31.90s)
=== CONT  TestAccVPCSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccVPCSecurityGroup_ingressWithPrefixList (35.11s)
=== CONT  TestAccVPCSecurityGroup_ruleLimitCIDRBlockExceededAppend
--- PASS: TestAccVPCSecurityGroup_egressWithPrefixList (36.02s)
=== CONT  TestAccVPCSecurityGroup_forceRevokeRulesFalse
=== CONT  TestAccVPCSecurityGroup_ruleLimitExceededPrepend
    vpc_security_group_test.go:2178: Step 2/3, expected an error but got none
=== CONT  TestAccVPCSecurityGroup_ruleLimitCIDRBlockExceededAppend
    vpc_security_group_test.go:2117: Step 2/3, expected an error but got none
--- FAIL: TestAccVPCSecurityGroup_ruleLimitExceededPrepend (38.44s)
=== CONT  TestAccVPCSecurityGroup_drift
--- FAIL: TestAccVPCSecurityGroup_ruleLimitCIDRBlockExceededAppend (33.88s)
=== CONT  TestAccVPCSecurityGroup_vpc
--- PASS: TestAccVPCSecurityGroup_drift (16.76s)
=== CONT  TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC
--- PASS: TestAccVPCSecurityGroup_vpc (21.76s)
=== CONT  TestAccVPCSecurityGroup_self
--- PASS: TestAccVPCSecurityGroup_ingressWithCIDRAndSGsVPC (27.27s)
=== CONT  TestAccVPCSecurityGroup_cidrAndGroups
--- PASS: TestAccVPCSecurityGroup_self (26.29s)
=== CONT  TestAccVPCSecurityGroup_ipv6
--- PASS: TestAccVPCSecurityGroup_cidrAndGroups (26.27s)
=== CONT  TestAccVPCSecurityGroup_ipRangesWithSameRules
--- PASS: TestAccVPCSecurityGroup_ipv6 (21.15s)
=== CONT  TestAccVPCSecurityGroup_forceRevokeRulesTrue
--- PASS: TestAccVPCSecurityGroup_ipRangesWithSameRules (23.13s)
=== CONT  TestAccVPCSecurityGroup_ruleGathering
--- PASS: TestAccVPCSecurityGroup_ruleGathering (35.64s)
=== CONT  TestAccVPCSecurityGroup_ingressMode
--- PASS: TestAccVPCSecurityGroup_ingressMode (46.97s)
=== CONT  TestAccVPCSecurityGroup_change
--- PASS: TestAccVPCSecurityGroup_change (35.98s)
=== CONT  TestAccVPCSecurityGroup_driftComplex
--- PASS: TestAccVPCSecurityGroup_driftComplex (27.53s)
=== CONT  TestAccVPCSecurityGroup_namePrefixTerraform
--- PASS: TestAccVPCSecurityGroup_namePrefixTerraform (25.87s)
=== CONT  TestAccVPCSecurityGroup_invalidCIDRBlock
--- PASS: TestAccVPCSecurityGroup_invalidCIDRBlock (1.92s)
=== CONT  TestAccVPCSecurityGroup_ruleDescription
--- PASS: TestAccVPCSecurityGroup_ruleDescription (53.56s)
=== CONT  TestAccVPCSecurityGroup_defaultEgressVPC
--- PASS: TestAccVPCSecurityGroup_defaultEgressVPC (21.75s)
=== CONT  TestAccVPCSecurityGroup_multiIngress
--- PASS: TestAccVPCSecurityGroup_multiIngress (28.36s)
=== CONT  TestAccVPCSecurityGroup_allowAll
--- PASS: TestAccVPCSecurityGroup_allowAll (23.68s)
=== CONT  TestAccVPCSecurityGroup_sourceSecurityGroup
--- PASS: TestAccVPCSecurityGroup_sourceSecurityGroup (24.54s)
=== CONT  TestAccVPCSecurityGroup_egressMode
--- PASS: TestAccVPCSecurityGroup_egressMode (47.72s)
=== CONT  TestAccVPCSecurityGroup_nameGenerated
--- PASS: TestAccVPCSecurityGroup_nameGenerated (20.78s)
=== CONT  TestAccVPCSecurityGroup_namePrefix
--- PASS: TestAccVPCSecurityGroup_namePrefix (20.63s)
=== CONT  TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules
--- PASS: TestAccVPCSecurityGroup_ipRangeAndSecurityGroupWithSameRules (27.02s)
=== CONT  TestAccVPCSecurityGroup_disappears
--- PASS: TestAccVPCSecurityGroup_disappears (17.98s)
=== CONT  TestAccVPCSecurityGroup_basicEC2Classic
--- PASS: TestAccVPCSecurityGroup_basicEC2Classic (11.14s)
=== CONT  TestAccVPCSecurityGroup_tags
--- PASS: TestAccVPCSecurityGroup_tags (48.04s)
=== CONT  TestAccVPCSecurityGroup_vpcProtoNumIngress
--- PASS: TestAccVPCSecurityGroup_vpcProtoNumIngress (21.33s)
=== CONT  TestAccVPCSecurityGroup_nameTerraformPrefix
--- PASS: TestAccVPCSecurityGroup_nameTerraformPrefix (22.17s)
--- PASS: TestAccVPCSecurityGroup_forceRevokeRulesFalse (952.64s)
--- PASS: TestAccVPCSecurityGroup_forceRevokeRulesTrue (981.09s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1187.205s