resource/aws_kms_external_key: Remove extraneous ListResourceTags logic
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10905#discussion_r348022738

Output from acceptance testing (failures due to unrelated eventual consistency issues):

```
--- PASS: TestAccAWSKmsExternalKey_disappears (33.81s)
--- PASS: TestAccAWSKmsExternalKey_basic (38.62s)
--- FAIL: TestAccAWSKmsExternalKey_Policy (45.11s)
--- PASS: TestAccAWSKmsExternalKey_DeletionWindowInDays (46.43s)
--- FAIL: TestAccAWSKmsExternalKey_Description (47.13s)
--- PASS: TestAccAWSKmsExternalKey_Tags (57.37s)
--- PASS: TestAccAWSKmsExternalKey_KeyMaterialBase64 (140.85s)
--- PASS: TestAccAWSKmsExternalKey_ValidTo (249.45s)
--- PASS: TestAccAWSKmsExternalKey_Enabled (349.97s)
```