tests/service/batch: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSBatchJobDefinition_basic (0.90s)
    testing.go:568: Step 0 error: errors during apply:

        Error: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/registerjobdefinition: dial tcp: lookup batch.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host "tf_acctest_batch_job_definition_4884891207041435957"
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSBatchJobQueue_update (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_updateInstanceType (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_updateState (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsBatchJobQueue (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchJobQueue_disappears (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createEc2 (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createUnmanaged (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createSpot (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_updateMaxvCpus (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchJobDefinition_updateForcesNewResource (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createEc2WithTags (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsBatchComputeEnvironment (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchJobDefinition_basic (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_launchTemplate (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBatchJobQueue_basic (2.35s)
    resource_aws_batch_compute_environment_test.go:384: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://batch.us-gov-west-1.amazonaws.com/v1/describecomputeenvironments: dial tcp: lookup batch.us-gov-west-1.amazonaws.com: no such host
```