tests/resource/aws_redshift_cluster: Add all virtual attribute to ImportStateVerifyIgnore list
In the Terraform 0.12 Provider SDK acceptance testing framework, removed
attributes that do not call ResourceData.Set() are no longer
automatically ignored during ImportStateVerify testing. Here we add the
removed attribute to the ImportStateVerifyIgnore list to match similar
behavior of Terraform 0.11 acceptance testing. This change is backwards
compatible.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAWSRedshiftCluster_importBasic (577.26s)
testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

  (map[string]string) {
  }

  (map[string]string) (len=1) {
   (string) (len=14) "enable_logging": (string) (len=5) "false"
  }
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSRedshiftCluster_basic (476.37s)
```