resource/aws_lambda_function: Properly handle `vpc_config` removal
Includes preventing panics as started by https://github.com/terraform-providers/terraform-provider-aws/pull/5792

* Adds acceptance test (`TestAccAWSLambdaFunction_VPCRemoval`) to cover `vpc_config` removal
* Prevents panic when removing `vpc_config`
* Properly handles vpc_config removal to prevent perpetual difference

Previously:

```
--- FAIL: TestAccAWSLambdaFunction_VPCRemoval (42.52s)
    testing.go:527: Step 1 error: Check failed: Check 2/2 error: aws_lambda_function.lambda_function_test: Attribute 'vpc_config.#' expected "0", got "1"
```

Now:

```
--- PASS: TestAccAWSLambdaFunction_VPCRemoval (51.23s)
```