internal/keyvaluetags: Use Go 1.13 error wrapping with UpdateTags errors
Reference: https://blog.golang.org/go1.13-errors
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10411

Found via acceptance testing prior to an actual release:

```
--- FAIL: TestAccAWSEMRCluster_basic (19.03s)
    testing.go:615: Step 0 error: errors during apply:

        Error: error adding tags: error tagging resource (subnet-04c4088b2c7f3aa42): InvalidSubnetID.NotFound: The subnet ID 'subnet-04c4088b2c7f3aa42' does not exist
        	status code: 400, request id: 2dafd3b1-ffef-49f9-98e0-1ede0726e8bb
```

Any logic attempting to check the returned AWS Go SDK error code/message from `keyvaluetags` package `UpdateTags` usage will not work since the errors are currently wrapped by value, which was the only option in Go 1.12 and earlier. Go 1.13 introduced the new `%w` verb for `fmt.Errorf()` for wrapping errors, which allows downstream logic to check wrapped error types via `errors.As()`.

Updated via:

```console
$ make gen
```