resource/aws_wafregional_web_acl_association: Ensure missing resource triggers state removal
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/9203

Previous to code change:

```
--- FAIL: TestAccAWSWafRegionalWebAclAssociation_disappears (175.64s)
    testing.go:569: Step 0 error: errors during follow-up refresh:

        Error: error getting WAF Regional Web ACL for resource (arn:aws:elasticloadbalancing:us-west-2:--OMITTED--:loadbalancer/app/tf-lb-20190924095723723200000001/e2739f0d448dc712): empty response
```

Output from acceptance testing:

```
--- PASS: TestAccAWSWafRegionalWebAclAssociation_disappears (207.92s)
```