tests/service/macie: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSMacieS3BucketAssociation_basic (2.26s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Macie S3 bucket association: RequestError: send request failed
        caused by: Post https://macie.us-gov-west-1.amazonaws.com/: dial tcp: lookup macie.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSMacieMemberAccountAssociation_self (2.42s)
    resource_aws_macie_s3_bucket_association_test.go:152: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://macie.us-gov-west-1.amazonaws.com/: dial tcp: lookup macie.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMacieS3BucketAssociation_accountIdAndPrefix (2.42s)
    resource_aws_macie_s3_bucket_association_test.go:152: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://macie.us-gov-west-1.amazonaws.com/: dial tcp: lookup macie.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMacieS3BucketAssociation_basic (2.42s)
    resource_aws_macie_s3_bucket_association_test.go:152: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://macie.us-gov-west-1.amazonaws.com/: dial tcp: lookup macie.us-gov-west-1.amazonaws.com: no such host
```