r/aws_rds_global_cluster: remove `engine` and `source_db_cluster_identifier` conflict
This enables both arguments to be set upon creation, rather than requiring users to set a source DB for the initial global cluster creation and removing it to set `engine` and `engine_version` for subsequent major version upgrades. During create operations the `engine` and `engine_version` values will be ignored if `source_db_cluster_identifier` is set. If the engine version varies from what is inherited from the source cluster a second change will be planned immediately following the initial apply.

To support future major version upgrades on a promoted global cluster, the following configuration is now valid.

```terraform
resource "aws_rds_global_cluster" "test" {
  force_destroy                = true
  global_cluster_identifier    = "my-cluster"
  engine                       = local.engine
  engine_version               = local.engine_version
  source_db_cluster_identifier = aws_rds_cluster.test.arn
}
```

```console
% make testacc PKG=rds TESTS=TestAccRDSGlobalCluster_SourceDBClusterIdentifier
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-rds_global_cluster-rm-engine-conflict 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSGlobalCluster_SourceDBClusterIdentifier'  -timeout 360m -vet=off
2025/09/11 13:05:11 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/11 13:05:11 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_databaseName (192.02s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_storageEncrypted (192.05s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_EngineVersion_updateMajor (1849.39s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        1855.979s
```

```console
% make testacc PKG=rds TESTS=TestAccRDSGlobalCluster_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-rds_global_cluster-rm-engine-conflict 🌿...
TF_ACC=1 go1.24.6 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSGlobalCluster_'  -timeout 360m -vet=off
2025/09/12 10:00:33 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/12 10:00:33 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccRDSGlobalCluster_forceDestroy (31.24s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_auroraPostgreSQL
=== NAME  TestAccRDSGlobalCluster_storageEncrypted
    global_cluster_test.go:602: Step 3/3 error: Error running apply: exit status 1

        Error: creating RDS Global Cluster (tf-acc-test-1266092778766974036): operation error RDS: CreateGlobalCluster, https response error StatusCode: 400, RequestID: 15aa4798-dc3b-40c7-98b1-4e1d443d2d14, GlobalClusterAlreadyExistsFault: Global cluster tf-acc-test-1266092778766974036 already exists

          with aws_rds_global_cluster.test,
          on terraform_plugin_test.tf line 12, in resource "aws_rds_global_cluster" "test":
          12: resource "aws_rds_global_cluster" "test" {

--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_emptyProviderOnlyTag (42.04s)
=== CONT  TestAccRDSGlobalCluster_sourceDBClusterIdentifier
--- FAIL: TestAccRDSGlobalCluster_storageEncrypted (42.79s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_auroraMySQL
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_nullOverlappingResourceTag (44.13s)
=== CONT  TestAccRDSGlobalCluster_tags_AddOnUpdate
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_emptyResourceTag (44.16s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyTag_OnCreate
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_nullNonOverlappingResourceTag (44.55s)
=== CONT  TestAccRDSGlobalCluster_disappears
--- PASS: TestAccRDSGlobalCluster_tags_ComputedTag_OnCreate (45.52s)
=== CONT  TestAccRDSGlobalCluster_databaseName
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_updateToProviderOnly (65.49s)
=== CONT  TestAccRDSGlobalCluster_basic
--- PASS: TestAccRDSGlobalCluster_EngineVersion_auroraPostgreSQL (35.94s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyMap
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_updateToResourceOnly (67.40s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_updateMajor
--- PASS: TestAccRDSGlobalCluster_tags_ComputedTag_OnUpdate_Add (69.44s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_updateMinorMultiRegion
--- PASS: TestAccRDSGlobalCluster_tags_ComputedTag_OnUpdate_Replace (73.49s)
=== CONT  TestAccRDSGlobalCluster_tags_null
--- PASS: TestAccRDSGlobalCluster_disappears (30.15s)
=== CONT  TestAccRDSGlobalCluster_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccRDSGlobalCluster_EngineVersion_auroraMySQL (35.53s)
=== CONT  TestAccRDSGlobalCluster_tags_DefaultTags_providerOnly
=== NAME  TestAccRDSGlobalCluster_databaseName
    global_cluster_test.go:171: Step 3/3 error: Error running apply: exit status 1

        Error: creating RDS Global Cluster (tf-acc-test-5146216102148161976): operation error RDS: CreateGlobalCluster, https response error StatusCode: 400, RequestID: bf20209e-2aa5-4eca-89c9-2f7c8065cfe0, GlobalClusterAlreadyExistsFault: Global cluster tf-acc-test-5146216102148161976 already exists

          with aws_rds_global_cluster.test,
          on terraform_plugin_test.tf line 12, in resource "aws_rds_global_cluster" "test":
          12: resource "aws_rds_global_cluster" "test" {

--- FAIL: TestAccRDSGlobalCluster_databaseName (38.02s)
=== CONT  TestAccRDSGlobalCluster_tags_DefaultTags_nonOverlapping
--- PASS: TestAccRDSGlobalCluster_tags_IgnoreTags_Overlap_DefaultTag (84.98s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_updateMinor
--- PASS: TestAccRDSGlobalCluster_deletionProtection (87.05s)
=== CONT  TestAccRDSGlobalCluster_engineLifecycleSupport_disabled
--- PASS: TestAccRDSGlobalCluster_basic (30.27s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Add (95.97s)
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_overlapping (101.57s)
--- PASS: TestAccRDSGlobalCluster_tags_AddOnUpdate (58.35s)
--- PASS: TestAccRDSGlobalCluster_tags_EmptyTag_OnCreate (60.96s)
--- PASS: TestAccRDSGlobalCluster_tags_EmptyMap (44.07s)
--- PASS: TestAccRDSGlobalCluster_engineLifecycleSupport_disabled (24.83s)
--- PASS: TestAccRDSGlobalCluster_tags_null (40.28s)
--- PASS: TestAccRDSGlobalCluster_tags (116.69s)
--- PASS: TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Replace (35.37s)
--- PASS: TestAccRDSGlobalCluster_tags_IgnoreTags_Overlap_ResourceTag (59.60s)
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_nonOverlapping (58.38s)
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_providerOnly (76.94s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_storageEncrypted (194.09s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_databaseName (204.21s)
--- PASS: TestAccRDSGlobalCluster_sourceDBClusterIdentifier (193.83s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMinor (1283.77s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMajor (1709.34s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_EngineVersion_updateMajor (1865.42s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMinorMultiRegion (3051.41s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMajorMultiRegion (3467.62s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/rds        3474.432s
```

Failures are pre-existing and unrelated to this change.