resource/aws_sqs_queue: Always refresh all attributes into Terraform state, add import testing to all tests
In the Terraform 0.12 Provider SDK acceptance testing framework, attributes that do not call `ResourceData.Set()` are no longer automatically ignored during `ImportStateVerify` testing. Here we explicitly refresh all attributes into the Terraform state and remove the schema parsing logic during `Read`, which is an anti-pattern for resources due to its complexity. We also add import testing to all acceptance tests to ensure we have covered all attributes properly. This change is backwards compatible.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAWSSQSQueue_importBasic (7.48s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=33) "kms_data_key_reuse_period_seconds": (string) (len=1) "0"
        }

--- FAIL: TestAccAWSSQSQueue_importFifo (7.63s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=33) "kms_data_key_reuse_period_seconds": (string) (len=1) "0"
        }
```

Output from Terraform 0.11 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSSQSQueue_FIFOExpectNameError (4.71s)
--- PASS: TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError (4.78s)
--- PASS: TestAccAWSSQSQueue_Encryption (14.17s)
--- PASS: TestAccAWSSQSQueue_namePrefix_fifo (14.19s)
--- PASS: TestAccAWSSQSQueue_FIFO (14.27s)
--- PASS: TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication (14.29s)
--- PASS: TestAccAWSSQSQueue_redrivePolicy (18.54s)
--- PASS: TestAccAWSSQSQueue_policy (18.60s)
--- PASS: TestAccAWSSQSQueue_Policybasic (18.82s)
--- PASS: TestAccAWSSQSQueue_namePrefix (24.31s)
--- PASS: TestAccAWSSQSQueue_basic (30.62s)
--- PASS: TestAccAWSSQSQueue_tags (30.73s)
--- PASS: TestAccAWSSQSQueue_queueDeletedRecently (93.16s)
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSSQSQueue_FIFOExpectNameError (6.95s)
--- PASS: TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError (7.24s)
--- PASS: TestAccAWSSQSQueue_Encryption (15.35s)
--- PASS: TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication (15.41s)
--- PASS: TestAccAWSSQSQueue_namePrefix (15.41s)
--- PASS: TestAccAWSSQSQueue_FIFO (15.46s)
--- PASS: TestAccAWSSQSQueue_namePrefix_fifo (15.50s)
--- PASS: TestAccAWSSQSQueue_policy (19.05s)
--- PASS: TestAccAWSSQSQueue_redrivePolicy (19.14s)
--- PASS: TestAccAWSSQSQueue_Policybasic (19.68s)
--- PASS: TestAccAWSSQSQueue_basic (30.59s)
--- PASS: TestAccAWSSQSQueue_tags (31.16s)
--- PASS: TestAccAWSSQSQueue_queueDeletedRecently (94.39s)
```