Update Terraform github to v2.9.2 (#14021)
* Update Terraform github to v2.9.2

* infrastructure/repository: Use organization argument instead of owner in github provider configuration

Appears that the provider reverted the deprecation of the `organization` argument and inclusion of the new `owner` argument in 2.9.x, delaying until 3.0.0.

Previously:

```
Error: Unsupported argument

  on main.tf line 14, in provider "github":
  14:   owner = "terraform-providers"

An argument named "owner" is not expected here.
```

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Brian Flad <bflad417@gmail.com>