tests/resource/aws_api_gateway_domain_name: Create and use EDGE endpoint CheckExists and CheckDestroy (#17426)
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17420

Currently the `TestAccAWSAPIGatewayDomainName_CertificateArn` acceptance test fails in TeamCity:

```
=== CONT  TestAccAWSAPIGatewayDomainName_CertificateArn
resource_aws_api_gateway_domain_name_test.go:24: Step 1/2 error: Check failed: Check 1/6 error: NotFoundException: Invalid domain name identifier specified
--- FAIL: TestAccAWSAPIGatewayDomainName_CertificateArn (964.31s)
```

EDGE endpoint type resources can only exist in us-east-1 region. While the test function and configuration are set up to switch the region, the test is using `testAccCheckAWSAPIGatewayDomainNameDestroy` and `testAccCheckAWSAPIGatewayDomainNameExists` which use `testAccProvider` instead of `testAccProviderApigatewayEdgeDomainName`.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSAPIGatewayDomainName_CertificateArn (972.57s)
--- PASS: TestAccAWSAPIGatewayDomainName_disappears (25.73s)
--- PASS: TestAccAWSAPIGatewayDomainName_MutualTlsAuthentication (198.61s)
--- PASS: TestAccAWSAPIGatewayDomainName_RegionalCertificateArn (249.05s)
--- PASS: TestAccAWSAPIGatewayDomainName_SecurityPolicy (129.72s)
--- PASS: TestAccAWSAPIGatewayDomainName_Tags (223.17s)
--- SKIP: TestAccAWSAPIGatewayDomainName_CertificateName (0.00s)
--- SKIP: TestAccAWSAPIGatewayDomainName_RegionalCertificateName (0.00s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSAPIGatewayDomainName_disappears (42.47s)
--- PASS: TestAccAWSAPIGatewayDomainName_RegionalCertificateArn (80.03s)
--- PASS: TestAccAWSAPIGatewayDomainName_SecurityPolicy (171.64s)
--- PASS: TestAccAWSAPIGatewayDomainName_Tags (112.22s)
--- SKIP: TestAccAWSAPIGatewayDomainName_CertificateArn (0.00s)
--- SKIP: TestAccAWSAPIGatewayDomainName_CertificateName (0.00s)
--- SKIP: TestAccAWSAPIGatewayDomainName_MutualTlsAuthentication (0.00s)
--- SKIP: TestAccAWSAPIGatewayDomainName_RegionalCertificateName (0.00s)
```