tests/data-source/aws_storagegateway_local_disk: Support m5 instance class DiskPath, ensure resources are destroyed
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/12247

Uses the replace() function since data sources cannot use depends_on and we need the implicit dependency on both sides of the conditional.

Previously:

```
--- FAIL: TestAccAWSStorageGatewayLocalDiskDataSource_DiskPath (140.13s)
    testing.go:669: Step 0 error: errors during apply:

        Error: no results found for query, try adjusting your search criteria
```

Output from acceptance testing:

```
--- PASS: TestAccAWSStorageGatewayLocalDiskDataSource_DiskPath (289.53s)
--- PASS: TestAccAWSStorageGatewayLocalDiskDataSource_DiskNode (313.84s)
```