resource/aws_network_interface: Refresh private_ips_count into Terraform state and allow updates from 0 to greater than 0
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/3210

The Terraform 0.12 Provider SDK acceptance testing was catching that the `private_ips_count` attribute (used to signify _secondary_ private IPs) was not properly being read into the Terraform state during import.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAWSENI_importBasic (13.57s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "private_ips_count": (string) (len=1) "0"
        }
```

To fix this particular issue, we prefer to always read this attribute into the Terraform state during `Read`. While looking through previous bug reports for this attribute, came across a report that the resource was not properly updating the count when going from 0 to greater than 0. Added a covering acceptance test and fixed the update logic.

Previous output from acceptance testing before `private_ips_count` update logic changes:

```
--- FAIL: TestAccAWSENI_PrivateIpsCount (82.51s)
    testing.go:568: Step 6 error: Check failed: Check 2/2 error: aws_network_interface.test: Attribute 'private_ips_count' expected "1", got "0"
```

Output from Terraform 0.11 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSENI_computedIPs (33.48s)
--- PASS: TestAccAWSENI_sourceDestCheck (35.03s)
--- PASS: TestAccAWSENI_disappears (36.04s)
--- PASS: TestAccAWSENI_basic (39.30s)
--- PASS: TestAccAWSENI_updatedDescription (64.26s)
--- PASS: TestAccAWSENI_PrivateIpsCount (90.29s)
--- PASS: TestAccAWSENI_ignoreExternalAttachment (119.86s)
--- PASS: TestAccAWSENI_attached (257.95s)
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSENI_computedIPs (35.09s)
--- PASS: TestAccAWSENI_sourceDestCheck (36.54s)
--- PASS: TestAccAWSENI_disappears (37.25s)
--- PASS: TestAccAWSENI_basic (39.92s)
--- PASS: TestAccAWSENI_updatedDescription (64.87s)
--- PASS: TestAccAWSENI_PrivateIpsCount (91.51s)
--- PASS: TestAccAWSENI_ignoreExternalAttachment (121.11s)
--- PASS: TestAccAWSENI_attached (261.48s)
```