tests/resource/aws_eks_node_group: Fix test failures (#16164)
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16146
Reference: https://github.com/aws/containers-roadmap/issues/771
Reference: https://github.com/awslabs/amazon-eks-ami/issues/559

Previously:

```
=== CONT  TestAccAWSEksNodeGroup_LaunchTemplate_Version
TestAccAWSEksNodeGroup_LaunchTemplate_Version: resource_aws_eks_node_group_test.go:394: Step 3/3, expected an error but got none
--- FAIL: TestAccAWSEksNodeGroup_LaunchTemplate_Version (2495.73s)

=== CONT  TestAccAWSEksNodeGroup_ReleaseVersion
TestAccAWSEksNodeGroup_ReleaseVersion: resource_aws_eks_node_group_test.go:433: Step 3/3 error: Error running apply: 2020/11/11 10:20:03 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: error updating EKS Node Group (tf-acc-test-7656789780485850868:tf-acc-test-7656789780485850868) version: InvalidParameterException: Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107
{
RespMetadata: {
StatusCode: 400,
RequestID: "17a52d81-285a-4e03-924c-874d3d895e3b"
},
ClusterName: "tf-acc-test-7656789780485850868",
Message_: "Requested Nodegroup release version 1.16.13-20201007 is invalid. Allowed release version is 1.16.15-20201107",
NodegroupName: "tf-acc-test-7656789780485850868"
}
--- FAIL: TestAccAWSEksNodeGroup_ReleaseVersion (4466.46s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEksNodeGroup_LaunchTemplate_Version (2424.12s)
--- PASS: TestAccAWSEksNodeGroup_ReleaseVersion (4059.77s)
```