tests/resource/aws_ecr_repository: Manually construct registry_url in testAccCheckAWSEcrRepositoryRepositoryURL
Reference: https://github.com/aws/aws-sdk-go/issues/2441

The "ecr" endpoint service name was removed in the default endpoint resolvers in the AWS Go SDK in preference of "api.ecr" for PrivateLink support. Instead of updating this small test function to perform additional string manipulation of the endpoint result from the AWS Go SDK, this simply constructs the repository_url value with the region name and AWS Standard/GovCloud domain.

Previous output from acceptance testing (since AWS Go SDK v1.16.26):

```
--- FAIL: TestAccAWSEcrRepository_basic (2.62s)
    testing.go:568: Step 0 error: Check failed: Check 5/5 error: aws_ecr_repository.default: Attribute 'repository_url' expected "*******.dkr./tf-acc-test-1198045183293346913", got "*******.dkr.ecr.us-west-2.amazonaws.com/tf-acc-test-1198045183293346913"
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEcrRepository_basic (12.22s)
```