tests/resource/aws_ecs_service: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion Out of Date (#17439)
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17395
Reference: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html
Reference: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform-versions-retired.html
Reference: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_Operations.html

The `TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion` acceptance test currently fails because it references an out of date platform version:

```
=== CONT  TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion
resource_aws_ecs_service_test.go:873: Step 1/3 error: Error running apply:
Error: AccessDeniedException: You do not have authorization to access the specified platform. "tf-acc-svc-ltf-w-pv-kje3nytw"
--- FAIL: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (19.51s)
```

The ECS API does not provide a lookup operation for these. For now we can switch from `1.3.0` to `1.4.0` and from `1.2.0` to `1.3.0`. Note the `LATEST` move from step 3 to 2 is to keep existing test behavior since `LATEST` is confusingly still `1.3.0`.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (159.33s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (170.16s)
```