service/databasemigrationservice: Refactor to use keyvaluetags package (#11238)
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10688

Output from acceptance testing (`aws_dms_replication_task` resource testing failure with `replication_task_settings` difference present on master):

```
--- PASS: TestAccAwsDmsEndpoint_Basic (29.32s)
--- PASS: TestAccAwsDmsEndpoint_DocDB (29.35s)
--- PASS: TestAccAwsDmsEndpoint_Db2 (29.61s)
--- PASS: TestAccAwsDmsEndpoint_MongoDb (36.91s)
--- PASS: TestAccAwsDmsEndpoint_DynamoDb (37.59s)
--- PASS: TestAccAwsDmsEndpoint_S3 (41.09s)

--- PASS: TestAccAWSDmsReplicationInstance_Basic (329.72s)
--- PASS: TestAccAWSDmsReplicationInstance_AvailabilityZone (427.60s)
--- PASS: TestAccAWSDmsReplicationInstance_VpcSecurityGroupIds (456.62s)
--- PASS: TestAccAWSDmsReplicationInstance_PreferredMaintenanceWindow (489.54s)
--- PASS: TestAccAWSDmsReplicationInstance_ReplicationSubnetGroupId (497.67s)
--- PASS: TestAccAWSDmsReplicationInstance_PubliclyAccessible (509.31s)
--- PASS: TestAccAWSDmsReplicationInstance_Tags (510.55s)
--- PASS: TestAccAWSDmsReplicationInstance_KmsKeyArn (518.31s)
--- PASS: TestAccAWSDmsReplicationInstance_AutoMinorVersionUpgrade (531.60s)
--- PASS: TestAccAWSDmsReplicationInstance_ReplicationInstanceClass (654.45s)
--- PASS: TestAccAWSDmsReplicationInstance_EngineVersion (866.60s)
--- PASS: TestAccAWSDmsReplicationInstance_AllocatedStorage (1083.58s)
--- PASS: TestAccAWSDmsReplicationInstance_MultiAz (1780.33s)

--- PASS: TestAccAWSDmsReplicationSubnetGroupBasic (55.93s)

--- FAIL: TestAccAWSDmsReplicationTaskBasic (539.60s)
    testing.go:635: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_dms_replication_task.dms_replication_task
```