tests/resource/aws_api_gateway_stage: Ensure variables TypeMap configuration includes equals
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAPIGatewayStage_basic (0.68s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "variables" are not expected here. Did you mean to define argument "variables"? If so, use the equals sign to assign it a value.
--- FAIL: TestAccAWSAPIGatewayStage_accessLogSettings (0.61s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "variables" are not expected here. Did you mean to define argument "variables"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 acceptance testing (new test failure will need to be addressed separately):

```
--- PASS: TestAccAWSAPIGatewayStage_basic (436.76s)
--- FAIL: TestAccAWSAPIGatewayStage_accessLogSettings (230.29s)
    testing.go:568: Step 1 error: errors during apply:

        Error: Updating API Gateway Stage failed: BadRequestException: Access Log value must not be empty
```