r/aws_inspector_resource_group: use checkDestroyNoop annotation instead of custom destroy function
Updated to use @Testing(checkDestroyNoop=true) annotation instead of adding
a custom destroy function, since Inspector Classic is deprecated and cannot
be tested. Regenerated identity tests to use acctest.CheckDestroyNoop.

=== RUN   TestAccInspectorResourceGroup_Identity_Basic
=== PAUSE TestAccInspectorResourceGroup_Identity_Basic
=== CONT  TestAccInspectorResourceGroup_Identity_Basic
    resource_group_identity_gen_test.go:30: Step 1/4 error: Error running apply: exit status 1

        Error: creating Inspector Classic Resource Group: operation error Inspector: CreateResourceGroup, https response error StatusCode: 400, RequestID: 72fea562-48da-45df-82aa-4bfaf0b26c64, AccessDeniedException:

--- FAIL: TestAccInspectorResourceGroup_Identity_Basic (4.35s)
FAIL