Demonstrate that lowercase pg var causes failures
AWS provided variables for rds parameter groups are case sensitive.  These test updates demonstrate the failure returned from AWS.  Proving that "join_buffer_size" = "{dbInstanceClassMemory/10000}" is invalid

    TestAccAWSDBParameterGroup_basic: testing.go:669: Step 0 error: errors during apply:

        Error: Error modifying DB Parameter Group: InvalidParameterValue: value does not match pattern
        	status code: 400, request id: <redacted>

          on /var/folders/7b/22x5nfns40gb2qkfgjh7s2k40000gp/T/tf-test908586078/main.tf line 2:
          (source code not available)