resource/aws_lb_listener_certificate: Retry CertificateNotFound errors on creation, use internal implementation for test TLS key/certificate
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10023

Fixes the following issue discovered during acceptance testing due to IAM eventual consistency:

```
--- FAIL: TestAccAwsLbListenerCertificate_multiple (326.35s)
    testing.go:569: Step 1 error: errors during apply:

        Error: Error creating LB Listener Certificate: CertificateNotFound: Certificate 'arn:aws:iam::187416307283:server-certificate/tf-acc-test-3065966466410433081-additional-3' not found
```

This also refactors the testing configurations so they can share a common base configuration.

Output from acceptance testing:

```
--- PASS: TestAccAwsLbListenerCertificate_basic (186.16s)
--- PASS: TestAccAwsLbListenerCertificate_multiple (271.64s)
```