fix(kendra): datasource retry if iam perm not prop
ValidationException: Secrets Manager throws the exception: User
is not authorized to perform: secretsmanager:GetSecretValue on resource:
because no identity-based policy allows the
secretsmanager:GetSecretValue action