tests/data-source/aws_workspaces_workspace: Fix TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName for any Terraform CLI version
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17401

This acceptance test is currently failing on Terraform 0.14:

```
=== CONT  TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName
data_source_aws_workspaces_workspace_test.go:48: Step 1/1 error: Expected a non-empty plan, but got an empty plan
--- FAIL: TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName (1701.01s)
```

Using `depends_on` with a data source after Terraform 0.12 (or 0.13, I forget off the top of head) will not show a perpetual plan difference. Instead of using `depends_on`, we should be able to passthrough the graph ordering via  `directory_id = aws_workspace_workspace.test.directory_id` and remove the `ExpectNonEmptyPlan` for all Terraform versions.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName (1736.18s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- FAIL: TestAccDataSourceAwsWorkspacesWorkspace_byDirectoryID_userName (21.31s) # https://github.com/hashicorp/terraform-provider-aws/issues/17401
```