tests/service/elasticache: Replace deprecated cache.m1 with cache.t3, refactor data source testing (#11956)
* tests/service/elasticache: Replace deprecated cache.m1 with cache.t3, refactor data source testing

Previously (since Feb 5, 2020):

```
--- FAIL: TestAccAWSElasticacheReplicationGroup_basic (11.22s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating Elasticache Replication Group: InvalidParameterValue: Invalid Cache Node Type: cache.m1.small
```

* tests/service/elasticache: Remove extraneous EC2-Classic handling from tests that do not need it

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/11543

EC2-Classic handling is only necessary for testing Elasticache Security Groups. Otherwise its possible to get errors like the following in the tests:

```
--- FAIL: TestAccAWSElasticacheReplicationGroup_basic (10.94s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating Elasticache Replication Group: InvalidParameterCombination: Instance type cache.t3.small can only be created in a VPC.
```

* tests/data-source/aws_elasticache_replication_group: auth_token_enabled is only available in the data source (auth_token in the resource)

Otherwise testing fails with:

```
--- FAIL: TestAccDataSourceAwsElasticacheReplicationGroup_basic (819.58s)
    testing.go:640: Step 0 error: Check failed: 1 error occurred:
        	* Check 1/10 error: data.aws_elasticache_replication_group.test: Attribute "auth_token_enabled" is "false", but "auth_token_enabled" is not set in aws_elasticache_replication_group.test
```

* tests/resource/aws_elasticache_cluster: Fix TestAccAWSElasticacheCluster_snapshotsWithUpdates test configuration