resource/aws_redshift_parameter_group: Return Read instead of Update after Create
Reference: https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#resource-contribution-guidelines

Previously, the handling of the `tags` argument would trigger an error because it was not protected by an `if d.IsNewResource()` conditional (since the `arn` attribute was not set yet):

```
--- FAIL: TestAccAWSRedshiftParameterGroup_withTags (8.02s)
    testing.go:568: Step 0 error: errors during apply:

        Error: AccessDenied: User: arn:aws:iam::--OMITTED--:user/bflad is not authorized to perform: redshift:CreateTags on resource: *
```

Output from acceptance testing:

```
--- PASS: TestAccAWSRedshiftParameterGroup_withParameters (10.94s)
--- PASS: TestAccAWSRedshiftParameterGroup_withoutParameters (11.17s)
--- PASS: TestAccAWSRedshiftParameterGroup_importBasic (12.02s)
--- PASS: TestAccAWSRedshiftParameterGroup_withTags (24.15s)
```