tests/resource/aws_swf_domain: Add environment variable PreCheck
SWF imposes limits on the number of SWF Domains without providing a method to delete Domains after deprecation. The daily acceptance testing will repeatedly exhaust this limit and cause perpetual errors like the below:

```
--- FAIL: TestAccAWSSwfDomain_basic (2.17s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_swf_domain.test: 1 error occurred:
        	* aws_swf_domain.test: LimitExceededFault: Limit on maximum number of domains per account reached
```

We allow the use of an environment variable to gate these tests with anticipation that they will only be run as necessary during development work. Semi-arbitrarily named `SWF_DOMAIN_TESTING_ENABLED` to be similar to other `ACM_*`, `API_GATEWAY_*`, `GUARDDUTY_*` environment variables used for other acceptance tests.

Output from acceptance testing:

```
--- SKIP: TestAccAWSSwfDomain_basic (1.78s)
    resource_aws_swf_domain_test.go:18: Environment variable SWF_DOMAIN_TESTING_ENABLED is not set. SWF limits domains per region and the API does not support deletions. Set the environment variable to any value to enable.
--- SKIP: TestAccAWSSwfDomain_GeneratedName (1.79s)
    resource_aws_swf_domain_test.go:18: Environment variable SWF_DOMAIN_TESTING_ENABLED is not set. SWF limits domains per region and the API does not support deletions. Set the environment variable to any value to enable.
--- SKIP: TestAccAWSSwfDomain_NamePrefix (1.80s)
    resource_aws_swf_domain_test.go:18: Environment variable SWF_DOMAIN_TESTING_ENABLED is not set. SWF limits domains per region and the API does not support deletions. Set the environment variable to any value to enable.
--- SKIP: TestAccAWSSwfDomain_Description (1.80s)
    resource_aws_swf_domain_test.go:18: Environment variable SWF_DOMAIN_TESTING_ENABLED is not set. SWF limits domains per region and the API does not support deletions. Set the environment variable to any value to enable.
```