tests/resource/aws_budgets_budget: Add decimal to budget limit amount configuration
Test failures for this began last week. For now we simiply fix the test configuration, but this may be indicative of new API behavior that will require resource updates.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSBudgetsBudget_basic (8.61s)
    testing.go:568: Step 0 error: Check failed: Check 1/8 error: budget limit incorrectly set 100 != 100.0
--- FAIL: TestAccAWSBudgetsBudget_prefix (8.83s)
    testing.go:568: Step 0 error: Check failed: Check 1/8 error: budget limit incorrectly set 100 != 100.0
--- FAIL: TestAccAWSBudgetsBudget_notification (13.01s)
    testing.go:568: Step 1 error: Check failed: Check 1/1 error: budget limit incorrectly set 100 != 100.0
```

Output from acceptance testing:

```
--- PASS: TestAccAWSBudgetsBudget_prefix (17.80s)
--- PASS: TestAccAWSBudgetsBudget_basic (19.90s)
--- PASS: TestAccAWSBudgetsBudget_notification (59.14s)
```