tests/resource/aws_route_table: Fix syntax for Terraform 0.12
This change is backwards compatible with Terraform 0.11. Please note the new test failure highlights an issue with "complex" importing that can be seen with other resources and will be reported upstream.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSRouteTable_complex (0.73s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Missing resource instance key: Because aws_route_table.mod has "count" set, its attributes must be accessed on specific instances.

        For example, to correlate with indices of a referring resource, use:
            aws_route_table.mod[count.index]
        - Missing resource instance key: Because aws_route_table.mod has "count" set, its attributes must be accessed on specific instances.

        For example, to correlate with indices of a referring resource, use:
            aws_route_table.mod[count.index]
```

Output from acceptance testing:

```
--- FAIL: TestAccAWSRouteTable_complex (211.83s)
    testing.go:568: Step 1 error: 2 problems:

        - Cannot import non-existent remote object: While attempting to import an existing object to aws_route_table.mod-2, the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
        - Cannot import non-existent remote object: While attempting to import an existing object to aws_route_table.mod-1, the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
```