tests/resource/aws_s3_bucket_object: Fix etag and non-versions test configurations
Previously:

```
=== CONT  TestAccAWSS3BucketObject_etagEncryption
TestAccAWSS3BucketObject_etagEncryption: resource_aws_s3_bucket_object_test.go:199: Step 1/1 error: terraform failed: exit status 1
stderr:
Error: Invalid expression
on config027201552/terraform_plugin_test.tf line 10, in resource "aws_s3_bucket_object" "object":
10:   source                 = %!q(int=5634537717392942380)
Expected the start of an expression, but found an invalid expression token.
Error: Missing argument separator
on config027201552/terraform_plugin_test.tf line 11, in resource "aws_s3_bucket_object" "object":
11:   etag                   = filemd5(%!q(int=5634537717392942380))
A comma is required to separate each function argument from the next.
--- FAIL: TestAccAWSS3BucketObject_etagEncryption (1.67s)

=== CONT  TestAccAWSS3BucketObject_NonVersioned
TestAccAWSS3BucketObject_NonVersioned: resource_aws_s3_bucket_object_test.go:272: Step 1/1 error: terraform failed: exit status 1
stderr:
Error: Invalid expression
on config020903983/terraform_plugin_test.tf line 16, in resource "aws_s3_bucket_object" "object":
16:   source = %!q(int=1805044611502807977)
Expected the start of an expression, but found an invalid expression token.
Error: Missing argument separator
on config020903983/terraform_plugin_test.tf line 17, in resource "aws_s3_bucket_object" "object":
17:   etag   = filemd5(%!q(int=1805044611502807977))
A comma is required to separate each function argument from the next.
--- FAIL: TestAccAWSS3BucketObject_NonVersioned (2.34s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSS3BucketObject_etagEncryption (23.09s)
--- PASS: TestAccAWSS3BucketObject_NonVersioned (23.34s)
```