tests/resource/aws_iam_policy_attachment: Temporarily use expanded users references
This change is both backwards (0.11) and forwards (0.12) compatible to allow the configuration on both versions. Eventually the temporary workaround will be removed when we switch the provider test configurations to 0.12-only syntax.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSIAMPolicyAttachment_paginatedEntities (2.16s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test032782444/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "users": element 0: string required.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSIAMPolicyAttachment_paginatedEntities (57.78s)
```