r/aws_vpc_security_group_ingress_rule: Correct 'TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags'.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccVPCSecurityGroupIngressRule_' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCSecurityGroupIngressRule_ -timeout 180m
=== RUN   TestAccVPCSecurityGroupIngressRule_basic
=== PAUSE TestAccVPCSecurityGroupIngressRule_basic
=== RUN   TestAccVPCSecurityGroupIngressRule_disappears
=== PAUSE TestAccVPCSecurityGroupIngressRule_disappears
=== RUN   TestAccVPCSecurityGroupIngressRule_tags
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag
=== RUN   TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
=== PAUSE TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
=== RUN   TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
=== PAUSE TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
=== RUN   TestAccVPCSecurityGroupIngressRule_ignoreTags
=== PAUSE TestAccVPCSecurityGroupIngressRule_ignoreTags
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv4
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv4
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== RUN   TestAccVPCSecurityGroupIngressRule_description
=== PAUSE TestAccVPCSecurityGroupIngressRule_description
=== RUN   TestAccVPCSecurityGroupIngressRule_prefixListID
=== PAUSE TestAccVPCSecurityGroupIngressRule_prefixListID
=== RUN   TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
=== PAUSE TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
=== RUN   TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
=== PAUSE TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
=== RUN   TestAccVPCSecurityGroupIngressRule_updateSourceType
=== PAUSE TestAccVPCSecurityGroupIngressRule_updateSourceType
=== CONT  TestAccVPCSecurityGroupIngressRule_basic
=== CONT  TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_basic (26.98s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly (38.78s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags (47.49s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag (1.36s)
=== CONT  TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly (46.93s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly (37.94s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag
--- PASS: TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply (48.02s)
=== CONT  TestAccVPCSecurityGroupIngressRule_prefixListID
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag (46.94s)
=== CONT  TestAccVPCSecurityGroupIngressRule_updateSourceType
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag (45.10s)
=== CONT  TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
    acctest.go:645: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC (0.00s)
=== CONT  TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
--- PASS: TestAccVPCSecurityGroupIngressRule_prefixListID (50.11s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags
--- PASS: TestAccVPCSecurityGroupIngressRule_updateSourceType (39.02s)
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv6
--- PASS: TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID (41.17s)
=== CONT  TestAccVPCSecurityGroupIngressRule_description
--- PASS: TestAccVPCSecurityGroupIngressRule_cidrIPv6 (40.12s)
=== CONT  TestAccVPCSecurityGroupIngressRule_disappears
--- PASS: TestAccVPCSecurityGroupIngressRule_tags (54.73s)
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv4
--- PASS: TestAccVPCSecurityGroupIngressRule_description (40.89s)
=== CONT  TestAccVPCSecurityGroupIngressRule_ignoreTags
--- PASS: TestAccVPCSecurityGroupIngressRule_disappears (23.19s)
=== CONT  TestAccVPCSecurityGroupIngressRule_ignoreTags
    vpc_security_group_ingress_rule_test.go:551: Step 2/3 error: After applying this test step, the plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_vpc_security_group_ingress_rule.test will be updated in-place
          ~ resource "aws_vpc_security_group_ingress_rule" "test" {
                id                     = "sgr-0d4ae0e4a4d081341"
              - tags                   = {} -> null
                # (8 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccVPCSecurityGroupIngressRule_ignoreTags (29.06s)
--- PASS: TestAccVPCSecurityGroupIngressRule_cidrIPv4 (39.88s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	246.353s
FAIL
make: *** [testacc] Error 1