service/rds: Increase default proxy deletion timeout, ensure proxy target import includes all attributes
The Terraform Plugin SDK version 2.0.4 upgrade fixed something with `ImportStateVerify` testing, which now catches these arguments were not properly being set during `Read`.

The timeout issue was occurring inconsistently across tests, but is a good signal that our initial default deletion timeout value might have been too low.

Previously:

```
=== CONT  TestAccAWSDBProxyTarget_Cluster
TestAccAWSDBProxyTarget_Cluster: resource_aws_db_proxy_target_test.go:51: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=2) {
(string) (len=13) "db_proxy_name": (string) (len=31) "tf-acc-test-7766132173812142965",
(string) (len=17) "target_group_name": (string) (len=7) "default"
}
--- FAIL: TestAccAWSDBProxyTarget_Cluster (600.94s)

=== CONT  TestAccAWSDBProxyTarget_Instance
TestAccAWSDBProxyTarget_Instance: resource_aws_db_proxy_target_test.go:20: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=2) {
(string) (len=13) "db_proxy_name": (string) (len=31) "tf-acc-test-4517387436607757033",
(string) (len=17) "target_group_name": (string) (len=7) "default"
}
TestAccAWSDBProxyTarget_Instance: testing_new.go:62: Error running post-test destroy, there may be dangling resources: 2020/10/07 06:29:56 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Error waiting for DB Proxy deletion: timeout while waiting for state to become '' (last state: 'deleting', timeout: 30m0s)
--- FAIL: TestAccAWSDBProxyTarget_Instance (2044.98s)

=== CONT  TestAccAWSDBProxyTarget_disappears
TestAccAWSDBProxyTarget_disappears: testing_new.go:62: Error running post-test destroy, there may be dangling resources: 2020/10/07 06:31:38 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Error waiting for DB Proxy deletion: timeout while waiting for state to become '' (last state: 'deleting', timeout: 30m0s)
--- FAIL: TestAccAWSDBProxyTarget_disappears (2010.78s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSDBProxy_AuthDescription (636.54s)
--- PASS: TestAccAWSDBProxy_AuthIamAuth (628.26s)
--- PASS: TestAccAWSDBProxy_AuthSecretArn (784.97s)
--- PASS: TestAccAWSDBProxy_basic (665.92s)
--- PASS: TestAccAWSDBProxy_DebugLogging (790.23s)
--- PASS: TestAccAWSDBProxy_disappears (631.87s)
--- PASS: TestAccAWSDBProxy_IdleClientTimeout (860.70s)
--- PASS: TestAccAWSDBProxy_Name (718.38s)
--- PASS: TestAccAWSDBProxy_RequireTls (721.11s)
--- PASS: TestAccAWSDBProxy_RoleArn (690.45s)
--- PASS: TestAccAWSDBProxy_Tags (695.16s)
--- PASS: TestAccAWSDBProxy_VpcSecurityGroupIds (652.93s)

--- PASS: TestAccAWSDBProxyTarget_Cluster (621.13s)
--- PASS: TestAccAWSDBProxyTarget_disappears (618.64s)
--- PASS: TestAccAWSDBProxyTarget_Instance (640.24s)
```