tests/resource/aws_db_instance: Prevent overlap errors with backup_window and maintenance_window in acceptance testing
When omitted, the backup and maintenance windows for RDS Database Instances are randomly generated by the API. When restoring from snapshot or creating a replication database, the parameter setting occurs in a followup ModifyDBInstance call after the initial creation calls because the creation calls do not support the parameters directly. Injecting an expected value for one but not both of the parameters meant the testing could randomly fail with errors similar to the below during that ModifyDBInstance call:

```
--- FAIL: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1136.04s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_db_instance.test: 1 error occurred:
        	* aws_db_instance.test: error modifying DB Instance (tf-acc-test-418376986433548694): InvalidParameterValue: The backup window and maintenance window must not overlap.
```

Passing in both parameters with non-overlapping values allows us to prevent errors consistently:

```
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1220.63s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1283.60s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1386.51s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1470.98s)
```