tests/resource/aws_ec2_fleet: Implement PreCheck for EC2 Fleet support
EC2 Fleet is a newer resource type that is not supported in all AWS regions and partitions. Here we implement a PreCheck function to skip their acceptance tests until they are supported instead of failing.

Previous output from acceptance testing (AWS GovCloud (US)):

```
--- FAIL: TestAccAWSEc2Fleet_basic (10.35s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_ec2_fleet.test: 1 error occurred:
        	* aws_ec2_fleet.test: error creating EC2 Fleet: UnsupportedOperation: The functionality you requested is not available in this region.
```

Output from acceptance testing (AWS GovCloud (US)):

```
--- SKIP: TestAccAWSEc2Fleet_basic (2.09s)
--- SKIP: TestAccAWSEc2Fleet_disappears (1.89s)
--- SKIP: TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy (1.86s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId (1.76s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName (2.11s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version (1.84s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone (1.82s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType (2.09s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority (2.13s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple (2.11s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId (2.10s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity (2.11s)
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple (2.12s)
--- SKIP: TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy (2.09s)
--- SKIP: TestAccAWSEc2Fleet_ReplaceUnhealthyInstances (2.11s)
--- SKIP: TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy (2.12s)
--- SKIP: TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior (2.11s)
--- SKIP: TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount (2.13s)
--- SKIP: TestAccAWSEc2Fleet_Tags (2.10s)
--- SKIP: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType (2.11s)
--- SKIP: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand (2.10s)
--- SKIP: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot (2.11s)
--- SKIP: TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity (2.10s)
--- SKIP: TestAccAWSEc2Fleet_TerminateInstancesWithExpiration (2.09s)
--- SKIP: TestAccAWSEc2Fleet_Type (2.13s)

PASS
ok    github.com/terraform-providers/terraform-provider-aws/aws 4.808s
```

Output from acceptance testing (AWS Standard):

```
--- PASS: TestAccAWSEc2Fleet_basic (37.22s)
```