resource/aws_lambda_function: Use Terraform 0.11.12 and later compatible file hashing function in documentation and testing
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content. Also adds Terraform 0.12 compatible `ExpectError` condition for `TestAccAWSLambdaFunction_runtimeValidation_noRuntime`.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSLambdaFunction_runtimeValidation_noRuntime (0.64s)
    testing.go:561: Step 0, expected error:

        config is invalid: Missing required argument: The argument "runtime" is required, but no definition was found.

        To match:

        "runtime": required field is not set

--- FAIL: TestAccAWSLambdaFunction_localUpdate (2.02s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/lambda_localUpdate083548067 are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSLambdaFunction_s3Update_unversioned (1.62s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/lambda_s3Update704916359 are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSLambdaFunction_s3Update_basic (0.68s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/lambda_s3Update316607176 are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_noRuntime (1.83s)
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (26.03s)
--- PASS: TestAccAWSLambdaFunction_localUpdate (27.82s)
--- PASS: TestAccAWSLambdaFunction_s3Update_unversioned (49.97s)
--- PASS: TestAccAWSLambdaFunction_s3Update_basic (51.00s)
```

Output from Terraform 0.12 acceptance testing (new failure will need to be addressed separately):

```
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_noRuntime (1.04s)
--- FAIL: TestAccAWSLambdaFunction_localUpdate (33.35s)
    testing.go:568: Step 1 error: Check failed: Check 5/5 error: Expected time attribute data.template_file.last_modified.rendered with value 2019-03-13T03:02:00.589+0000 was not before 2019-03-12T23:02:04-0400
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (35.23s)
--- PASS: TestAccAWSLambdaFunction_s3Update_unversioned (51.66s)
--- PASS: TestAccAWSLambdaFunction_s3Update_basic (51.78s)
```