tests/service/mediapackage: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSMediaPackageChannel_basic (0.79s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating MediaPackage Channel: RequestError: send request failed
        caused by: Post https://mediapackage.us-gov-west-1.amazonaws.com/channels: dial tcp: lookup mediapackage.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSMediaPackageChannel_tags (2.37s)
    resource_aws_media_package_channel_test.go:172: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mediapackage.us-gov-west-1.amazonaws.com/channels: dial tcp: lookup mediapackage.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMediaPackageChannel_description (2.37s)
    resource_aws_media_package_channel_test.go:172: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mediapackage.us-gov-west-1.amazonaws.com/channels: dial tcp: lookup mediapackage.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMediaPackageChannel_basic (2.37s)
    resource_aws_media_package_channel_test.go:172: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mediapackage.us-gov-west-1.amazonaws.com/channels: dial tcp: lookup mediapackage.us-gov-west-1.amazonaws.com: no such host
```