r/aws_ecs_service: Add 'TestAccECSService_ServiceConnect_remove'.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccECSService_ServiceConnect_remove' PKG=ecs ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 3  -run=TestAccECSService_ServiceConnect_remove -timeout 180m
=== RUN   TestAccECSService_ServiceConnect_remove
=== PAUSE TestAccECSService_ServiceConnect_remove
=== CONT  TestAccECSService_ServiceConnect_remove
    service_test.go:1247: Step 2/2 error: Error running apply: exit status 1

        Error: error updating ECS Service (arn:aws:ecs:us-west-2:187416307283:service/tf-acc-test-1138227086795760796/tf-acc-test-1138227086795760796): InvalidParameter: 1 validation error(s) found.
        - missing required field, UpdateServiceInput.ServiceConnectConfiguration.Enabled.

          with aws_ecs_service.test,
          on terraform_plugin_test.tf line 38, in resource "aws_ecs_service" "test":
          38: resource "aws_ecs_service" "test" {

--- FAIL: TestAccECSService_ServiceConnect_remove (169.39s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	174.639s
FAIL
make: *** [testacc] Error 1