resource/aws_codepipeline: Ensure configuration argument configurations include equals
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSCodePipeline_basic (0.56s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Unsupported block type: Blocks of type "configuration" are not expected here. Did you mean to define argument "configuration"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "configuration" are not expected here. Did you mean to define argument "configuration"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- FAIL: TestAccAWSCodePipeline_emptyArtifacts (24.29s)
    testing.go:568: Step 0 error: Check failed: Check 11/11 error: aws_codepipeline.bar: Attribute 'stage.1.action.0.output_artifacts.#' expected "0", got "1"
--- PASS: TestAccAWSCodePipeline_Import_basic (34.30s)
--- FAIL: TestAccAWSCodePipeline_basic (38.42s)
    testing.go:568: Step 1 error: errors during apply:

        Error: [ERROR] Error updating CodePipeline (test-pipeline-w293z0i8jk): InvalidParameter: 3 validation error(s) found.
        - minimum field size of 3, UpdatePipelineInput.Pipeline.ArtifactStore.Location.
        - minimum field size of 1, UpdatePipelineInput.Pipeline.Stages[0].Name.
        - minimum field size of 1, UpdatePipelineInput.Pipeline.Stages[1].Name.

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test341704784/main.tf line 108:
          (source code not available)

    testing.go:629: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: Default error in CodePipeline Test

        State: <no state>
--- PASS: TestAccAWSCodePipeline_deployWithServiceRole (48.08s)

--- PASS: TestAccAWSCodePipelineWebhook_basic (40.64s)
--- PASS: TestAccAWSCodePipelineWebhook_ipAuth (35.35s)
--- PASS: TestAccAWSCodePipelineWebhook_unauthenticated (35.66s)
```