tests/resource/aws_neptune_cluster: Add apply_immediately virtual attribute to ImportStateVerifyIgnore list
In the Terraform 0.12 Provider SDK acceptance testing framework, virtual
attributes that do not call ResourceData.Set() are no longer
automatically ignored during ImportStateVerify testing. Here we add the
virtual attribute to the ImportStateVerifyIgnore list to match similar
behavior of Terraform 0.11 acceptance testing. This change is backwards
compatible.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAWSNeptuneCluster_iamAuth (113.49s)                                                                                                                                                                                                                                                                  [61/437]
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_updateTags (135.95s)
    testing.go:568: Step 2 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_updateIamRoles (138.68s)
    testing.go:568: Step 3 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_kmsKey (153.26s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_namePrefix (154.10s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_encrypted (154.13s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_basic (154.75s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

--- FAIL: TestAccAWSNeptuneCluster_takeFinalSnapshot (179.76s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=17) "apply_immediately": (string) (len=5) "false"
        }

```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSNeptuneCluster_iamAuth (122.22s)
--- PASS: TestAccAWSNeptuneCluster_namePrefix (122.26s)
--- PASS: TestAccAWSNeptuneCluster_encrypted (122.72s)
--- PASS: TestAccAWSNeptuneCluster_basic (122.94s)
--- PASS: TestAccAWSNeptuneCluster_kmsKey (142.70s)
--- PASS: TestAccAWSNeptuneCluster_updateTags (145.47s)
--- PASS: TestAccAWSNeptuneCluster_updateIamRoles (148.15s)
--- PASS: TestAccAWSNeptuneCluster_takeFinalSnapshot (186.39s)

```