tests/resource/aws_lb: Fix TestAccAWSLB_networkLoadbalancerEIP configuration
Previously:

```
=== CONT  TestAccAWSLB_networkLoadbalancerEIP
TestAccAWSLB_networkLoadbalancerEIP: resource_aws_lb_test.go:241: Step 1/1 error: Error running pre-apply plan: 2020/11/10 23:20:59 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Incorrect attribute value type
on config604754392/terraform_plugin_test.tf line 45, in resource "aws_route_table_association" "a":
45:   subnet_id      = aws_subnet.public[*].id[count.index]
|----------------
| aws_subnet.public is tuple with 4 elements
| count.index is 2
Inappropriate value for attribute "subnet_id": string required.
Error: Incorrect attribute value type
on config604754392/terraform_plugin_test.tf line 45, in resource "aws_route_table_association" "a":
45:   subnet_id      = aws_subnet.public[*].id[count.index]
|----------------
| aws_subnet.public is tuple with 4 elements
| count.index is 3
Inappropriate value for attribute "subnet_id": string required.
```

Output from acceptance testing:

```
--- PASS: TestAccAWSLB_networkLoadbalancerEIP (248.09s)
```