tests/resource/aws_emr_managed_scaling_policy: CheckDestroy update for API changes
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17400

Due to an EMR API change, there are test failures with the following acceptance tests:

```
=== CONT  TestAccAwsEmrManagedScalingPolicy_basic
testing_new.go:63: Error running post-test destroy, there may be dangling resources: Error: EMR Managed Scaling Policy still exists
--- FAIL: TestAccAwsEmrManagedScalingPolicy_basic (499.57s)

=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits
testing_new.go:63: Error running post-test destroy, there may be dangling resources: Error: EMR Managed Scaling Policy still exists
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits (426.45s)

=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits
testing_new.go:63: Error running post-test destroy, there may be dangling resources: Error: EMR Managed Scaling Policy still exists
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (476.03s)
```

The `CheckDestroy` function needs to account for the API response with a successful response, but no object.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits (464.08s)
--- PASS: TestAccAwsEmrManagedScalingPolicy_basic (468.20s)
--- PASS: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (472.76s)
--- PASS: TestAccAwsEmrManagedScalingPolicy_disappears (476.09s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (421.03s) # https://github.com/hashicorp/terraform-provider-aws/issues/17442
--- FAIL: TestAccAwsEmrManagedScalingPolicy_disappears (445.83s) # https://github.com/hashicorp/terraform-provider-aws/issues/17442
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits (462.71s) # https://github.com/hashicorp/terraform-provider-aws/issues/17442
--- FAIL: TestAccAwsEmrManagedScalingPolicy_basic (466.76s) # https://github.com/hashicorp/terraform-provider-aws/issues/17442
```