tests/provider: Add missing ErrorCheck
Previously:

```
Error: /home/runner/work/terraform-provider-aws/terraform-provider-aws/aws/resource_aws_config_configuration_aggregator_test.go:209:36: XAT001: missing ErrorCheck
208
209		resource.ParallelTest(t, resource.TestCase{
210			PreCheck:     func() { testAccPreCheck(t) },
Error: /home/runner/work/terraform-provider-aws/terraform-provider-aws/aws/resource_aws_ecr_repository_policy_test.go:84:36: XAT001: missing ErrorCheck
83
84		resource.ParallelTest(t, resource.TestCase{
85			PreCheck:     func() { testAccPreCheck(t) },
Error: /home/runner/work/terraform-provider-aws/terraform-provider-aws/aws/resource_aws_ecr_repository_policy_test.go:105:36: XAT001: missing ErrorCheck
104
105		resource.ParallelTest(t, resource.TestCase{
106			PreCheck:     func() { testAccPreCheck(t) },
Error: /home/runner/work/terraform-provider-aws/terraform-provider-aws/aws/resource_aws_sns_topic_subscription_test.go:444:36: XAT001: missing ErrorCheck
443
444		resource.ParallelTest(t, resource.TestCase{
445			PreCheck:     func() { testAccPreCheck(t) },
Error: /home/runner/work/terraform-provider-aws/terraform-provider-aws/aws/resource_aws_sns_topic_subscription_test.go:466:36: XAT001: missing ErrorCheck
465
466		resource.ParallelTest(t, resource.TestCase{
467			PreCheck:     func() { testAccPreCheck(t) },
make: *** [GNUmakefile:92: awsproviderlint] Error 3
```