Acceptance test output:
% make testacc TESTARGS='-run=TestAccDataSyncLocationFSxONTAPFileSystem_basic\|TestAccDataSyncLocationFSxONTAPFileSystem_smb' PKG=datasync
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 20  -run=TestAccDataSyncLocationFSxONTAPFileSystem_basic\|TestAccDataSyncLocationFSxONTAPFileSystem_smb -timeout 360m
=== RUN   TestAccDataSyncLocationFSxONTAPFileSystem_basic
=== PAUSE TestAccDataSyncLocationFSxONTAPFileSystem_basic
=== RUN   TestAccDataSyncLocationFSxONTAPFileSystem_smb
=== PAUSE TestAccDataSyncLocationFSxONTAPFileSystem_smb
=== CONT  TestAccDataSyncLocationFSxONTAPFileSystem_basic
=== CONT  TestAccDataSyncLocationFSxONTAPFileSystem_smb
    location_fsx_ontap_file_system_test.go:103: Step 1/2 error: Error running apply: exit status 1

        Error: creating DataSync Location FSx for NetApp ONTAP File System: InvalidParameter: 2 validation error(s) found.
        - missing required field, CreateLocationFsxOntapInput.Protocol.SMB.Password.
        - missing required field, CreateLocationFsxOntapInput.Protocol.SMB.User.

          with aws_datasync_location_fsx_ontap_file_system.test,
          on terraform_plugin_test.tf line 72, in resource "aws_datasync_location_fsx_ontap_file_system" "test":
          72: resource "aws_datasync_location_fsx_ontap_file_system" "test" {

--- PASS: TestAccDataSyncLocationFSxONTAPFileSystem_basic (2365.08s)
--- FAIL: TestAccDataSyncLocationFSxONTAPFileSystem_smb (2408.72s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/datasync	2414.085s
FAIL
make: *** [testacc] Error 1