resource/aws_lambda_function: Various Terraform 0.12 syntax fixes
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSLambdaFunction_importLocalFile_VPC (0.58s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "vpc_config" is not expected here. Did you mean to define a block of type "vpc_config"?

--- FAIL: TestAccAWSLambdaFunction_versioned (1.12s)
    testing.go:568: Step 0 error: config is invalid: 3 problems:

        - Unsupported block type: Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSLambdaFunction_versionedUpdate (1.05s)
    testing.go:568: Step 0 error: config is invalid: 3 problems:

        - Unsupported block type: Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "vars" are not expected here. Did you mean to define argument "vars"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSLambdaFunction_VPC (0.73s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "vpc_config" is not expected here. Did you mean to define a block of type "vpc_config"?

--- FAIL: TestAccAWSLambdaFunction_VPCRemoval (0.65s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "vpc_config" is not expected here. Did you mean to define a block of type "vpc_config"?

--- FAIL: TestAccAWSLambdaFunction_VPCUpdate (0.62s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "vpc_config" is not expected here. Did you mean to define a block of type "vpc_config"?

--- FAIL: TestAccAWSLambdaFunction_VPC_withInvocation (0.61s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "vpc_config" is not expected here. Did you mean to define a block of type "vpc_config"?
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- PASS: TestAccAWSLambdaFunction_importLocalFile_VPC (36.77s)
--- PASS: TestAccAWSLambdaFunction_versioned (42.28s)
--- FAIL: TestAccAWSLambdaFunction_versionedUpdate (48.84s)
    testing.go:568: Step 1 error: Check failed: Check 5/8 error: data.template_file.function_version: Attribute 'rendered' didn't match "^2$", got "1"
--- PASS: TestAccAWSLambdaFunction_VPC (35.31s)
--- FAIL: TestAccAWSLambdaFunction_VPCRemoval (47.13s)
    testing.go:568: Step 1 error: Check failed: Check 2/2 error: aws_lambda_function.lambda_function_test: Attribute 'vpc_config.#' expected "0", got "1"
--- FAIL: TestAccAWSLambdaFunction_VPCUpdate (50.22s)
    testing.go:568: Step 1 error: Check failed: Check 6/7 error: aws_lambda_function.lambda_function_test: Attribute 'vpc_config.0.subnet_ids.#' expected "2", got "1"
--- PASS: TestAccAWSLambdaFunction_VPC_withInvocation (88.76s)
```