tests/resource/aws_ssm_maintenance_window_task: Switch to using… (#9367)
The benefits here include executing faster, removing the EC2 dependency, and now works in AWS GovCloud (US).

Previous output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationStepFunctionParameters (126.33s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_basic (127.14s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_updateForcesNewResource (157.65s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParameters (158.38s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationAutomationParameters (178.09s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationLambdaParameters (233.40s)
```

Previous output from acceptance testing in AWS GovCloud (US):

```
--- FAIL: TestAccAWSSSMMaintenanceWindowTask_basic (12.54s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist

--- FAIL: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationStepFunctionParameters (12.62s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist

--- FAIL: TestAccAWSSSMMaintenanceWindowTask_updateForcesNewResource (12.63s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist

--- FAIL: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParameters (12.64s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist

--- FAIL: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationAutomationParameters (12.71s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist

--- FAIL: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationLambdaParameters (26.90s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-4fccb37f]' does not exist
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationStepFunctionParameters (18.46s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_updateForcesNewResource (28.33s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_basic (28.60s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationAutomationParameters (40.14s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParameters (41.51s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationLambdaParameters (41.72s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationStepFunctionParameters (24.90s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_updateForcesNewResource (38.84s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_basic (39.69s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationLambdaParameters (39.93s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationAutomationParameters (49.56s)
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParameters (50.92s)
```