tests/resource/aws_db_cluster_snapshot: Temporarily expand subnet_ids argument
This change is backwards (0.11) and forwards (0.12) compatible. This temporary workaround can be removed when the provider test configurations are updated to 0.12-only syntax.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSDBClusterSnapshot_basic (2.18s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test573904954/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "subnet_ids": element 0: string required.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSDBClusterSnapshot_basic (167.81s)
```