r/aws_lakeformation_resource_lf_tag: handle `nil` tag pointers in `findTag` methods
This prevents a crash when the method receiver struct has a nil `LFTag` value. The same patch is applied for the `dbTagger`, `tbTagger`, and `tbcTagger` types.

```
Stack trace from the terraform-provider-aws_v6.50.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x11a7c8428]

goroutine 13 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation.(*dbTagger).findTag(0x0?, {0x1347d0e08, 0x591e8e44a2a0}, 0x591e8ec95d40, 0x591e8f32c0a0)
        github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation/resource_lf_tag.go:587 +0x178
github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation.(*resourceLFTagResource).Read(0x13493fbe0?, {0x1347d0e08, 0x591e8e44a2a0}, {{{{0x13492b440, 0x591e8f5017d0}, {0x1323f8480, 0x591e8f501290}}, {0x1349addb8, 0x591e8eb432c0}}, 0x0, ...}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation/resource_lf_tag.go:406 +0x25c
github.com/hashicorp/terraform-provider-aws/internal/provider/framework.(*wrappedResource).Read.interceptedHandler[...].func1(...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/framework/intercept.go:403
github.com/hashicorp/terraform-provider-aws/internal/provider/framework.(*wrappedResource).Read(0x591e8ebb04b0, {0x1347d0e08?, 0x591e8ebb31d0?}, {{{{0x13492b440, 0x591e8f5017d0}, {0x1323f8480, 0x591e8f501290}}, {0x1349addb8, 0x591e8eb432c0}}, 0x0, ...}, ...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/framework/wrap.go:684 +0x2f8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x591e8e115888, {0x1347d0e08, 0x591e8ebb31d0}, 0x591e8f15e050, 0x591e8dcad570)
        github.com/hashicorp/terraform-plugin-framework@v1.19.0/internal/fwserver/server_readresource.go:156 +0x894
github.com/hashicorp/terraform-plugin-framework/internal/proto5server.(*Server).ReadResource(0x591e8e115888, {0x1347d0e08?, 0x591e8ebb30e0?}, 0x591e8dc54870)
        github.com/hashicorp/terraform-plugin-framework@v1.19.0/internal/proto5server/server_readresource.go:72 +0x444
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x591e8e250480, {0x1347d0e08?, 0x591e8ebb2e10?}, 0x591e8dc54870)
        github.com/hashicorp/terraform-plugin-mux@v0.23.1/tf5muxserver/mux_server_ReadResource.go:35 +0x178
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x591e8e17bd60, {0x1347d0e08?, 0x591e8ebb26c0?}, 0x591e8e493ce0)
        github.com/hashicorp/terraform-plugin-go@v0.31.0/tfprotov5/tf5server/server.go:862 +0x1f8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x13419fde0, 0x591e8e17bd60}, {0x1347d0e08, 0x591e8ebb26c0}, 0x591e8d6bf400, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.31.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:769 +0x1b8
google.golang.org/grpc.(*Server).processUnaryRPC(0x591e8d0b66c8, {0x1347d0e08, 0x591e8ebb2630}, 0x591e8ee4e680, 0x591e8e33f3e0, 0x1350ab598, 0x0)
        google.golang.org/grpc@v1.79.3/server.go:1429 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x591e8d0b66c8, {0x1347d17b8, 0x591e8e3aa000}, 0x591e8ee4e680)
        google.golang.org/grpc@v1.79.3/server.go:1855 +0x89c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.79.3/server.go:1064 +0x70
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 71
        google.golang.org/grpc@v1.79.3/server.go:1075 +0x120

Error: The terraform-provider-aws_v6.50.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```