resource/aws_lb: Enable NLB access logs, remove Computed from access_logs attributes, properly read subnet_mappings
References:

* https://github.com/terraform-providers/terraform-provider-aws/issues/8208
* https://github.com/terraform-providers/terraform-provider-aws/issues/7397
* https://github.com/terraform-providers/terraform-provider-aws/issues/2145

Here we remove the previous behavior in the resource of ignoring access_logs configuration if the load_balancer_type is set to network. This enables NLB access log support.

The access_logs configuration block was previously also set to Optional and Computed, which prevents proper updates when removing the configuration block and also requires additional logic within Sentinel policies to handle both the configured and unconfigured scenarios. The configuration block logic has been updated to always set Terraform state information (effectively `enabled = false`) even when the configuration block is not present. Updating from `enabled = true` to no configuration block will disable access logs.

While acceptance testing this entirety of the resource in preparation for submitting the above changes, it was discovered that an ELBv2 API update sometime around January 25th changed the API response associated with the subnet_mapping configuration block. If a configuration like the following was present, the resource began showing a resource recreation difference.

Example configuration:

```hcl
resource "aws_lb" "example" {
  # ... other configuration ...

  subnet_mapping {
    subnet_id = "..."
  }
}
```

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSLB_networkLoadbalancerBasic (209.90s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        DESTROY/CREATE: aws_lb.lb_test
...
          subnet_mapping.#:                        "0" => "1" (forces new resource)
          subnet_mapping.3505487146.allocation_id: "" => ""
          subnet_mapping.3505487146.subnet_id:     "" => "subnet-03ba23f771f369617" (forces new resource)
          subnets.#:                               "1" => "<computed>"
...
```

The subnet_mapping logic was incorrectly only setting the subnet_id information in the Terraform state if an EIP allocation was present in the API response. This has been fixed.

Output from acceptance testing (the test failure below is present on master but out of scope for these fixes):

```
--- PASS: TestAccAWSLB_noSecurityGroup (190.29s)
--- PASS: TestAccAWSLB_generatedName (199.02s)
--- PASS: TestAccAWSLB_namePrefix (212.43s)
--- PASS: TestAccAWSLB_ALB_basic (221.72s)
--- FAIL: TestAccAWSLB_updatedSubnets (234.95s)
    testing.go:538: Step 1 error: Check failed: 1 error occurred:
        	* Check 2/3 error: aws_lb.lb_test: Attribute 'subnets.#' expected "3", got "2"

--- PASS: TestAccAWSLB_networkLoadbalancer_subnet_change (248.20s)
--- PASS: TestAccAWSLB_updatedIpAddressType (252.16s)
--- PASS: TestAccAWSLB_NLB_basic (266.47s)
--- PASS: TestAccAWSLB_generatesNameForZeroValue (268.23s)
--- PASS: TestAccAWSLB_tags (271.86s)
--- PASS: TestAccAWSLB_networkLoadbalancerEIP (289.22s)
--- PASS: TestAccAWSLB_updatedSecurityGroups (300.53s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateHttp2 (306.13s)
--- PASS: TestAccAWSLB_ALB_AccessLogs_Prefix (311.18s)
--- PASS: TestAccAWSLB_networkLoadbalancer_updateCrossZone (327.15s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateDeletionProtection (329.09s)
--- PASS: TestAccAWSLB_NLB_AccessLogs_Prefix (361.17s)
--- PASS: TestAccAWSLB_ALB_AccessLogs (384.53s)
--- PASS: TestAccAWSLB_NLB_AccessLogs (393.48s)
```