tests/service/waf: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSWafRule_basic (1.22s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Failed to acquire change token: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- PASS: TestAccAWSWafRegexMatchSet (7.12s)
    --- SKIP: TestAccAWSWafRegexMatchSet/disappears (2.51s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
    --- SKIP: TestAccAWSWafRegexMatchSet/basic (2.03s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
    --- SKIP: TestAccAWSWafRegexMatchSet/changePatterns (1.36s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
    --- SKIP: TestAccAWSWafRegexMatchSet/noPatterns (1.23s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- PASS: TestAccAWSWafRegexPatternSet (4.90s)
    --- SKIP: TestAccAWSWafRegexPatternSet/noPatterns (1.22s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
    --- SKIP: TestAccAWSWafRegexPatternSet/disappears (1.22s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
    --- SKIP: TestAccAWSWafRegexPatternSet/basic (1.25s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
    --- SKIP: TestAccAWSWafRegexPatternSet/changePatterns (1.22s)
        resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
            caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafByteMatchSet_basic (1.23s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRule_disappears (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafWebAcl_basic (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSqlInjectionMatchSet_changeNameForceNew (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSizeConstraintSet_disappears (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRuleGroup_noActivatedRules (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRule_changePredicates (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRule_basic (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafWebAcl_Rules (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSizeConstraintSet_changeNameForceNew (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRule_noPredicates (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRule_changeNameForceNew (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSqlInjectionMatchSet_basic (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSizeConstraintSet_noConstraints (1.27s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafWebAcl_DefaultAction (1.28s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSizeConstraintSet_changeConstraints (1.28s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSqlInjectionMatchSet_disappears (1.28s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSizeConstraintSet_basic (1.28s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRule_geoMatchSetPredicate (1.28s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafWebAcl_changeNameForceNew (1.29s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRuleGroup_changeNameForceNew (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafXssMatchSet_changeTuples (1.23s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRateBasedRule_disappears (1.21s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRateBasedRule_changePredicates (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRuleGroup_disappears (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRuleGroup_changeActivatedRules (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafXssMatchSet_changeNameForceNew (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafXssMatchSet_disappears (1.23s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRuleGroup_basic (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRateBasedRule_noPredicates (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafXssMatchSet_noTuples (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafWebAcl_LoggingConfiguration (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafWebAcl_disappears (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafXssMatchSet_basic (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafGeoMatchSet_basic (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafGeoMatchSet_changeConstraints (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafByteMatchSet_noTuples (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRateBasedRule_changeNameForceNew (1.23s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSqlInjectionMatchSet_noTuples (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafByteMatchSet_disappears (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafByteMatchSet_changeTuples (1.21s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafGeoMatchSet_disappears (1.21s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafGeoMatchSet_changeNameForceNew (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafSqlInjectionMatchSet_changeTuples (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafIPSet_changeDescriptors (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafIPSet_changeNameForceNew (1.22s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafGeoMatchSet_noConstraints (1.23s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafIPSet_IpSetDescriptors_1000UpdateLimit (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafIPSet_basic (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafIPSet_disappears (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafByteMatchSet_changeNameForceNew (1.24s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafIPSet_noDescriptors (1.25s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWafRateBasedRule_basic (1.26s)
    resource_aws_waf_rule_test.go:370: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://waf.us-gov-west-1.amazonaws.com/: dial tcp: lookup waf.us-gov-west-1.amazonaws.com: no such host
```