tests/service/storagegateway: Fix base configurations to ensure Gateway EC2 Instance depends on IGW Route
In the old setup, Terraform would remove the Route Table while removing Storage Gateway resources, which would break Storage Gateway connectivity and leave operations such as deleting File Shares forever stuck in a DELETING status.

Previously:

```
--- FAIL: TestAccAWSStorageGatewayNfsFileShare_basic (738.88s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_KMSEncrypted (744.62s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_DefaultStorageClass (790.15s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_GuessMIMETypeEnabled (786.40s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_tags (862.03s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_ObjectACL (785.49s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_NFSFileShareDefaults (813.11s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_KMSKeyArn (848.89s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_RequesterPays (788.63s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewayNfsFileShare_ReadOnly (848.65s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess (1040.95s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_DefaultStorageClass (1087.84s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_KMSEncrypted (1070.64s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_GuessMIMETypeEnabled (1089.11s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_Authentication_ActiveDirectory (1293.10s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_KMSKeyArn (1149.98s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_ObjectACL (1088.03s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_InvalidUserList (1401.37s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_ReadOnly (1091.03s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_RequesterPays (1086.02s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)

--- FAIL: TestAccAWSStorageGatewaySmbFileShare_ValidUserList (1404.94s)
    testing.go:730: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: error waiting for Storage Gateway SMB File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 15m0s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSStorageGatewayGateway_CloudWatchLogs (233.16s)
--- PASS: TestAccAWSStorageGatewayGateway_GatewayName (312.89s)
--- PASS: TestAccAWSStorageGatewayGateway_GatewayTimezone (292.99s)
--- PASS: TestAccAWSStorageGatewayGateway_GatewayType_Cached (234.41s)
--- PASS: TestAccAWSStorageGatewayGateway_GatewayType_FileS3 (264.08s)
--- PASS: TestAccAWSStorageGatewayGateway_GatewayType_Stored (182.68s)
--- PASS: TestAccAWSStorageGatewayGateway_GatewayType_Vtl (171.88s)
--- PASS: TestAccAWSStorageGatewayGateway_SmbActiveDirectorySettings (773.02s)
--- PASS: TestAccAWSStorageGatewayGateway_SmbGuestPassword (265.99s)
--- PASS: TestAccAWSStorageGatewayGateway_tags (273.16s)

--- PASS: TestAccAWSStorageGatewayNfsFileShare_basic (294.19s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_ClientList (422.73s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_DefaultStorageClass (402.22s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_GuessMIMETypeEnabled (376.49s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_KMSEncrypted (309.02s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_KMSKeyArn (436.81s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_NFSFileShareDefaults (359.46s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_ObjectACL (361.76s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_ReadOnly (363.16s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_RequesterPays (371.13s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_Squash (387.27s)
--- PASS: TestAccAWSStorageGatewayNfsFileShare_tags (393.14s)

--- PASS: TestAccAWSStorageGatewaySmbFileShare_Authentication_ActiveDirectory (821.89s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_Authentication_GuestAccess (275.38s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_DefaultStorageClass (335.98s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_GuessMIMETypeEnabled (373.83s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_InvalidUserList (989.04s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_KMSEncrypted (287.89s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_KMSKeyArn (423.78s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_ObjectACL (388.27s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_ReadOnly (339.32s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_RequesterPays (381.81s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_Tags (444.68s)
--- PASS: TestAccAWSStorageGatewaySmbFileShare_ValidUserList (919.79s)
```