tests/service/cognitoidentityprovider: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSCognitoUserPool_basic (1.98s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Cognito User Pool: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSCognitoUserPool_withAdminCreateUserConfiguration (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withLambdaConfig (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withSchemaAttributes (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withSmsConfiguration (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPoolDomain_basic (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withEmailConfiguration (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_update (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withEmailVerificationMessage (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withTags (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withPasswordPolicy (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsCognitoUserPools_basic (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withSmsConfigurationUpdated (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withSmsVerificationMessage (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPoolClient_allFields (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPoolClient_RefreshTokenValidity (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withAliasAttributes (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withAdvancedSecurityMode (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPoolClient_allFieldsUpdatingOneField (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withVerificationMessageTemplate (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_withDeviceConfiguration (2.38s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoResourceServer_scope (1.23s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserGroup_RoleArn (1.23s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityProvider_basic (1.23s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_basic (1.23s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPoolClient_basic (1.24s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoResourceServer_basic (1.24s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserGroup_complex (1.24s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPoolClient_importBasic (1.25s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserPool_importBasic (1.25s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserGroup_basic (1.25s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoUserGroup_importBasic (1.26s)
    resource_aws_cognito_user_pool_test.go:732: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
```