service/kms: Refactor to use keyvaluetags package (#10905)
Output from acceptance testing (test failures related to other eventual consistency issues):

```
--- PASS: TestAccAWSKmsKey_disappears (14.51s)
--- PASS: TestAccAWSKmsExternalKey_disappears (27.70s)
--- PASS: TestAccAWSKmsExternalKey_basic (30.90s)
--- PASS: TestAccAWSKmsKey_policy (31.55s)
--- PASS: TestAccAWSKmsKey_tags (32.21s)
--- FAIL: TestAccAWSKmsExternalKey_Policy (33.26s)
--- FAIL: TestAccAWSKmsExternalKey_Description (34.63s)
--- PASS: TestAccAWSKmsExternalKey_DeletionWindowInDays (36.15s)
--- PASS: TestAccAWSKmsKey_basic (37.37s)
--- PASS: TestAccAWSKmsExternalKey_Tags (42.58s)
--- PASS: TestAccAWSKmsExternalKey_KeyMaterialBase64 (112.95s)
--- PASS: TestAccAWSKmsExternalKey_ValidTo (239.86s)
--- PASS: TestAccAWSKmsExternalKey_Enabled (257.72s)
--- PASS: TestAccAWSKmsKey_isEnabled (362.06s)
```