tests/resource/aws_lambda_alias: Use Terraform 0.11.12 and later compatible file hashing function
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSLambdaAlias_basic (1.78s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSLambdaAlias_nameupdate (1.79s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSLambdaAlias_routingconfig (1.79s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambdatest.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.

--- FAIL: TestAccAWSLambdaAlias_routingconfig (24.51s)
    testing.go:568: Step 1 error: config is invalid: Unsupported argument: An argument named "routing_config" is not expected here. Did you mean to define a block of type "routing_config"?
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSLambdaAlias_basic (19.97s)
--- PASS: TestAccAWSLambdaAlias_nameupdate (29.19s)
--- PASS: TestAccAWSLambdaAlias_routingconfig (38.83s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSLambdaAlias_basic (34.62s)
--- PASS: TestAccAWSLambdaAlias_nameupdate (39.36s)
--- PASS: TestAccAWSLambdaAlias_routingconfig (49.33s)
```