tests/data-source/aws_internet_gateway: Remove hardcoded provider region and ExpectNonEmptyPlan
Previously in the acceptance testing:

```
--- FAIL: TestAccDataSourceAwsInternetGateway_typical (11.00s)
    testing.go:654: Step 0 error: errors during apply:

        Error: Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
```

Since this hardcoded region is not part of our normal sweeping regions, it went unchecked and hit the 5 VPC limit. Running the sweeper in that region cleaned up dangling VPC resources.

Output from acceptance testing:

```
--- PASS: TestAccDataSourceAwsInternetGateway_typical (43.46s)
```