tests/service/elasticsearchservice: Replace t2.micro.elasticsearch and m3.medium.elasticsearch instance types with those also available in AWS GovCloud (US)
t2.micro.elasticsearch and m3.medium.elasticsearch are not available in AWS GovCloud (US):

```
--- FAIL: TestAccAWSDataElasticsearchDomain_basic (11.82s)
    testing.go:569: Step 0 error: errors during apply:

        Error: Error creating ElasticSearch domain: InvalidTypeException: Invalid instance type: t2.micro.elasticsearch

--- FAIL: TestAccAWSElasticSearchDomain_vpc (29.57s)
    testing.go:569: Step 0 error: errors during apply:

        Error: Error creating ElasticSearch domain: InvalidTypeException: Invalid instance type: m3.medium.elasticsearch
```

`t2.small.elasticsearch` requires EBS:

```
--- FAIL: TestAccAWSElasticSearchDomain_vpc (27.40s)
    testing.go:569: Step 0 error: errors during apply:

        Error: Error creating ElasticSearch domain: ValidationException: EBS storage must be selected for t2.small.elasticsearch
```

The test failures below are unrelated and outside this timeboxed test fixing.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSElasticSearchDomain_duplicate (474.12s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions (683.94s)
--- PASS: TestAccAWSDataElasticsearchDomain_basic (776.88s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_default_key (1080.62s)
--- PASS: TestAccAWSElasticSearchDomain_policy (1085.77s)
--- PASS: TestAccAWSElasticSearchDomain_tags (1200.87s)
--- PASS: TestAccAWSDataElasticsearchDomain_advanced (1286.42s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key (1359.59s)
--- PASS: TestAccAWSElasticSearchDomain_complex (863.71s)
--- PASS: TestAccAWSElasticSearchDomain_vpc (1197.43s)
--- FAIL: TestAccAWSElasticSearchDomain_update_version (1853.26s)
    testing.go:569: Step 1 error: errors during apply:

        Error: unexpected state '', wanted target 'SUCCEEDED'. last error: %!s(<nil>)

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test840863232/main.tf line 2:
          (source code not available)

--- PASS: TestAccAWSElasticSearchDomain_importBasic (1926.44s)
--- PASS: TestAccAWSElasticSearchDomain_v23 (1933.81s)
--- PASS: TestAccAWSElasticSearchDomain_update (2150.40s)
--- PASS: TestAccAWSElasticSearchDomain_basic (1572.62s)
--- PASS: TestAccAWSElasticSearchDomain_internetToVpcEndpoint (2532.29s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove (2569.90s)
--- PASS: TestAccAWSElasticSearchDomain_NodeToNodeEncryption (2828.32s)
--- PASS: TestAccAWSElasticSearchDomain_vpc_update (2847.08s)
--- PASS: TestAccAWSElasticSearchDomain_withDedicatedMaster (3432.49s)
--- PASS: TestAccAWSElasticSearchDomain_update_volume_type (3918.28s)
--- PASS: TestAccAWSElasticSearchDomain_CognitoOptionsUpdate (4135.44s)
--- PASS: TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig (4836.72s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSElasticSearchDomain_CognitoOptionsUpdate (23.74s)
    resource_aws_cognito_user_pool_test.go:760: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticSearchDomain_CognitoOptionsCreateAndRemove (29.73s)
    resource_aws_cognito_user_pool_test.go:760: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-idp.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-idp.us-gov-west-1.amazonaws.com: no such host
--- PASS: TestAccAWSElasticSearchDomain_duplicate (396.68s)
--- PASS: TestAccAWSElasticSearchDomain_complex (635.22s)
--- PASS: TestAccAWSElasticSearchDomain_policy (636.07s)
--- PASS: TestAccAWSElasticSearchDomain_NodeToNodeEncryption (705.29s)
--- PASS: TestAccAWSElasticSearchDomain_v23 (702.20s)
--- PASS: TestAccAWSDataElasticsearchDomain_basic (755.19s)
--- FAIL: TestAccAWSElasticSearchDomain_update_version (900.69s)
    testing.go:569: Step 1 error: Check failed: Check 3/3 error: aws_elasticsearch_domain.example: Attribute 'elasticsearch_version' expected "5.6", got "5.5"
--- PASS: TestAccAWSElasticSearchDomain_importBasic (879.55s)
--- PASS: TestAccAWSElasticSearchDomain_basic (1091.51s)
--- PASS: TestAccAWSElasticSearchDomain_encrypt_at_rest_specify_key (1117.72s)
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions (1135.15s)
--- PASS: TestAccAWSElasticSearchDomain_vpc (1143.39s)
--- PASS: TestAccAWSElasticSearchDomain_tags (1147.12s)
--- PASS: TestAccAWSDataElasticsearchDomain_advanced (1173.96s)
--- PASS: TestAccAWSElasticSearchDomain_internetToVpcEndpoint (1603.77s)
--- PASS: TestAccAWSElasticSearchDomain_vpc_update (1918.00s)
--- PASS: TestAccAWSElasticSearchDomain_update_volume_type (2939.14s)
--- PASS: TestAccAWSElasticSearchDomain_withDedicatedMaster (3658.41s)
```