Change description regex after aws lambda eni enhancement rollout
* aws/resource_aws_security_group.go: As part of this AWS
  announcement (https://aws.amazon.com/blogs/compute/announcing-improved-vpc-networking-for-aws-lambda-functions/),
  eni's created by lambda will now have a different description. This is not explicitly
  documented, but was found in region 'eu-west-1', and will affect more regions over the next
  few months as AWS rolls out this change. This description, which used to be a string of the
  form "AWS Lambda VPC ENI: .*", now will look like this: "AWS Lambda VPC
  ENI-xxx-xxxxxxx-xxxxx-xxxxxx-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx". As such, the regex used
  to determine lingering lambda eni's no longer works in all regions, and in the future, when
  this rollout is completed, will not work at all. This will appear to the user as a dependency
  error, if they have any security groups attached to a lambda eni. For example:

Error: Error deleting security group: DependencyViolation: resource sg-xxxxxxxxxxxxxxxxx has a dependent object
	status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Signed-off-by: Collin J. Doering <collin@rekahsoft.ca>