resource/aws_dynamodb_table: Perform individual replica creations/deletions
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13132

Also includes slight changes to the acceptance testing recommendations for cross-region testing since we now are introducing the framework to test a third region. If approved, will followup this change with refactoring of the existing testing to use the newer functions.

Previously:

```
--- FAIL: TestAccAWSDynamoDbTable_Replica_Multiple (41.02s)
    TestAccAWSDynamoDbTable_Replica_Multiple: testing.go:684: Step 0 error: errors during apply:

        Error: error creating DynamoDB Table (TerraformTestTable--8440396559818741779) replicas: error creating DynamoDB Table (TerraformTestTable--8440396559818741779) replicas: ValidationException: Update table operation with more than one create or delete replica actions not allowed
          status code: 400, request id: 5MA0CQ5LJAVOKM671RT7QTKRTJVV4KQNSO5AEMVJF66Q9ASUAAJG

          on /var/folders/w8/05f3x02n27x72g0mc2jy6_180000gp/T/tf-test945359260/main.tf line 20:
          (source code not available)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSDynamoDbTable_attributeUpdate (756.09s)
--- PASS: TestAccAWSDynamoDbTable_attributeUpdateValidation (17.31s)
--- PASS: TestAccAWSDynamoDbTable_basic (82.00s)
--- PASS: TestAccAWSDynamoDbTable_BillingMode_GSI_PayPerRequestToProvisioned (135.99s)
--- PASS: TestAccAWSDynamoDbTable_BillingMode_GSI_ProvisionedToPayPerRequest (1296.50s)
--- PASS: TestAccAWSDynamoDbTable_BillingMode_PayPerRequestToProvisioned (134.93s)
--- PASS: TestAccAWSDynamoDbTable_BillingMode_ProvisionedToPayPerRequest (934.09s)
--- PASS: TestAccAWSDynamoDbTable_disappears (59.40s)
--- PASS: TestAccAWSDynamoDbTable_disappears_PayPerRequestWithGSI (140.30s)
--- PASS: TestAccAWSDynamoDbTable_enablePitr (152.34s)
--- PASS: TestAccAWSDynamoDbTable_encryption (249.98s)
--- PASS: TestAccAWSDynamoDbTable_extended (443.38s)
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateCapacity (144.47s)
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateNonKeyAttributes (443.69s)
--- PASS: TestAccAWSDynamoDbTable_gsiUpdateOtherAttributes (757.61s)
--- PASS: TestAccAWSDynamoDbTable_Replica_Multiple (1193.16s)
--- PASS: TestAccAWSDynamoDbTable_Replica_Single (1077.60s)
--- PASS: TestAccAWSDynamoDbTable_streamSpecification (148.25s)
--- PASS: TestAccAWSDynamoDbTable_streamSpecificationValidation (12.21s)
--- PASS: TestAccAWSDynamoDbTable_tags (88.24s)
--- PASS: TestAccAWSDynamoDbTable_Ttl_Disabled (116.66s)
--- PASS: TestAccAWSDynamoDbTable_Ttl_Enabled (81.82s)
```