resource/aws_wafregional_byte_match_set: Properly read byte_match_tuple into Terraform state
This converts the `field_to_match` `schema.TypeSet` with `MaxItems: 1` to `schema.TypeList` for simplification and ensures its properly handled during read.

This also fixes the invalid test configuration being used in `TestAccAWSWafRegionalByteMatchSet_changeByteMatchTuples` (`METHOD` `fields_to_match` `type` does not use `data` and the API strips the extraneous `data` value).

Previously (after adding `d.Set()` error check):

```
--- FAIL: TestAccAWSWafRegionalRateBasedRule_changePredicates (21.39s)
    testing.go:527: Step 1 error: Error applying: 1 error occurred:
        	* aws_wafregional_byte_match_set.set: 1 error occurred:
        	* aws_wafregional_byte_match_set.set: error setting byte_match_tuple: Invalid address to set: []string{"byte_match_tuple", "0", "field_to_match"}
```

Now:

```
$  make testacc TEST=./aws TESTARGS='-run=TestAccAWSWafRegional\(ByteMatchSet\|RateBasedRule\)_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSWafRegional\(ByteMatchSet\|RateBasedRule\)_ -timeout 120m
=== RUN   TestAccAWSWafRegionalByteMatchSet_basic
--- PASS: TestAccAWSWafRegionalByteMatchSet_basic (14.74s)
=== RUN   TestAccAWSWafRegionalByteMatchSet_changeNameForceNew
--- PASS: TestAccAWSWafRegionalByteMatchSet_changeNameForceNew (25.20s)
=== RUN   TestAccAWSWafRegionalByteMatchSet_changeByteMatchTuples
--- PASS: TestAccAWSWafRegionalByteMatchSet_changeByteMatchTuples (25.18s)
=== RUN   TestAccAWSWafRegionalByteMatchSet_noByteMatchTuples
--- PASS: TestAccAWSWafRegionalByteMatchSet_noByteMatchTuples (10.37s)
=== RUN   TestAccAWSWafRegionalByteMatchSet_disappears
--- PASS: TestAccAWSWafRegionalByteMatchSet_disappears (11.83s)
=== RUN   TestAccAWSWafRegionalRateBasedRule_basic
--- PASS: TestAccAWSWafRegionalRateBasedRule_basic (20.16s)
=== RUN   TestAccAWSWafRegionalRateBasedRule_changeNameForceNew
--- PASS: TestAccAWSWafRegionalRateBasedRule_changeNameForceNew (40.48s)
=== RUN   TestAccAWSWafRegionalRateBasedRule_disappears
--- PASS: TestAccAWSWafRegionalRateBasedRule_disappears (21.64s)
=== RUN   TestAccAWSWafRegionalRateBasedRule_changePredicates
--- PASS: TestAccAWSWafRegionalRateBasedRule_changePredicates (44.00s)
=== RUN   TestAccAWSWafRegionalRateBasedRule_changeRateLimit
--- PASS: TestAccAWSWafRegionalRateBasedRule_changeRateLimit (21.72s)
=== RUN   TestAccAWSWafRegionalRateBasedRule_noPredicates
--- PASS: TestAccAWSWafRegionalRateBasedRule_noPredicates (14.49s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	250.679s
```