resource/aws_launch_template: Properly recreate existing resource when deleted
Previously:

```
--- FAIL: TestAccAWSLaunchTemplate_disappears (10.27s)
    testing.go:527: Step 0 error: Error on follow-up refresh: 1 error occurred:
        	* aws_launch_template.foo: 1 error occurred:
        	* aws_launch_template.foo: aws_launch_template.foo: Error getting launch template: InvalidLaunchTemplateId.NotFound: Atleast one of the launch templates specified in the request does not exist.
```

Now:

```
--- PASS: TestAccAWSLaunchTemplate_disappears (10.60s)
```