tests/service/rds: Acceptance test configuration fixes for deprecated Oracle instance class and for matching instance to option group engine version (#11686)
Reference: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Oracle.html#Oracle.Concepts.InstanceClasses

Previously in the acceptance testing:

```
--- FAIL: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (2.65s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=oracle-se, EngineVersion=11.2.0.4.v22, LicenseModel=bring-your-own-license. For supported combinations of instance class and database engine version, see the documentation.

--- FAIL: TestAccAWSDbInstanceRoleAssociation_basic (6.44s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=oracle-se, EngineVersion=11.2.0.4.v22, LicenseModel=bring-your-own-license. For supported combinations of instance class and database engine version, see the documentation.

--- FAIL: TestAccAWSDbInstanceRoleAssociation_disappears (7.24s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating DB Instance: InvalidParameterCombination: RDS does not support creating a DB instance with the following combination: DBInstanceClass=db.t2.micro, Engine=oracle-se, EngineVersion=11.2.0.4.v22, LicenseModel=bring-your-own-license. For supported combinations of instance class and database engine version, see the documentation.

--- FAIL: TestAccAWSDBInstance_optionGroup (4.95s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating DB Instance: InvalidParameterCombination: The option group tf-option-test-6882627030637036293 is for mysql 5.6, and your DB instance is mysql 5.7.
```

As noted by the RDS User Guide, the db.t2 instance class has been deprecated for db.t3. As for the option group testing, the testing configuration has been updated so the instance references the option group engine and engine version to ensure the two do not drift due to RDS changing the instance creation default.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSDBInstance_optionGroup (522.01s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (626.95s)
--- PASS: TestAccAWSDbInstanceRoleAssociation_disappears (727.60s)
--- PASS: TestAccAWSDbInstanceRoleAssociation_basic (741.36s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSDBInstance_optionGroup (494.57s)
--- PASS: TestAccAWSDbInstanceRoleAssociation_disappears (719.47s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (785.29s)
--- PASS: TestAccAWSDbInstanceRoleAssociation_basic (841.34s)
```