tests/resource/aws_ssm_association: Fix Terraform 0.12 syntax
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSSSMAssociation_basic (0.44s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test861046325/main.tf:53,26-27: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMAssociation_withAssociationName (0.45s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test907381073/main.tf:3,43-44: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMAssociation_withAssociationNameAndScheduleExpression (0.45s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test724321574/main.tf:3,43-44: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMAssociation_withDocumentVersion (0.45s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test392197379/main.tf:3,51-52: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMAssociation_withOutputLocation (0.41s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test294655612/main.tf:8,48-49: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMAssociation_withParameters (0.52s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test200950895/main.tf:3,48-49: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMAssociation_withScheduleExpression (0.42s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test520368594/main.tf:3,48-49: Missing newline after argument; An argument definition must end with a newline.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- PASS: TestAccAWSSSMAssociation_basic (130.96s)
--- PASS: TestAccAWSSSMAssociation_withAssociationName (27.60s)
--- PASS: TestAccAWSSSMAssociation_withAssociationNameAndScheduleExpression (25.77s)
--- PASS: TestAccAWSSSMAssociation_withDocumentVersion (15.81s)
--- PASS: TestAccAWSSSMAssociation_withParameters (24.19s)
--- PASS: TestAccAWSSSMAssociation_withScheduleExpression (25.88s)

--- FAIL: TestAccAWSSSMAssociation_withTargets (18.79s)
    testing.go:568: Step 1 error: errors during apply:

        Error: Error updating SSM association: InvalidParameter: 1 validation error(s) found.
        - minimum field size of 1, UpdateAssociationInput.Targets[0].Key.

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test477585431/main.tf line 37:
          (source code not available)

    testing.go:629: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: Default error in SSM Association Test

        State: <no state>

--- FAIL: TestAccAWSSSMAssociation_withOutputLocation (45.09s)
    testing.go:568: Step 1 error: Check failed: Check 3/3 error: aws_ssm_association.foo: Attribute 'output_location.0.s3_key_prefix' expected "SSMAssociation", got ""
```