r/aws_backup_plan: Add missing `tags_all` attribute.
Before fix:

% make testacc TEST=./aws TESTARGS='-run=TestAccAWSBackupPlanDataSource_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSBackupPlanDataSource_basic -timeout 180m
=== RUN   TestAccAWSBackupPlanDataSource_basic
=== PAUSE TestAccAWSBackupPlanDataSource_basic
=== CONT  TestAccAWSBackupPlanDataSource_basic
    data_source_aws_backup_plan_test.go:18: Step 2/2 error: Error running pre-apply plan: exit status 1
        2021/04/28 14:33:26 [DEBUG] Using modified User-Agent: Terraform/0.12.30 HashiCorp-terraform-exec/0.13.3

        Error: error setting new tags_all diff: SetNew: invalid key: tags_all

          on terraform_plugin_test.tf line 6, in resource "aws_backup_plan" "test":
           6: resource "aws_backup_plan" "test" {

--- FAIL: TestAccAWSBackupPlanDataSource_basic (5.09s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	8.254s
FAIL
make: *** [testacc] Error 1

Acceptance test output:

% make testacc TEST=./aws TESTARGS='-run=TestAccAWSBackupPlanDataSource_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSBackupPlanDataSource_basic -timeout 180m
=== RUN   TestAccAWSBackupPlanDataSource_basic
=== PAUSE TestAccAWSBackupPlanDataSource_basic
=== CONT  TestAccAWSBackupPlanDataSource_basic
--- PASS: TestAccAWSBackupPlanDataSource_basic (18.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	22.042s