resource/aws_vpc_peering_connection_options: Only modify VPC Peering options that have actually changed (#12126)
* Only modify VPC Peering options that have actually changed.

r/aws_vpc_peering_connection_options: Revert acceptance test changes (for now).

* r/aws_vpc_peering_connection_options: Fix crash ('accepter' and 'requester' are lists, not sets).

* r/aws_vpc_peering_connection_options: Fix 'TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount' (copypasta from #14067).

* r/aws_vpc_peering_connection_options: Test updating options in 'TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount'.

* r/aws_vpc_peering_connection: Wait for peering connection acceptance before modifying any options.

* r/aws_vpc_peering_connection_options: Test updating options in 'TestAccAWSVpcPeeringConnectionOptions_basic'.

* r/aws_vpc_peering_connection_options: Minimize acceptance test diffs.

* r/aws_vpc_peering_connection_options: Comment out import test until Plugin SDK correctly handles import testing with multiple providers.

Acceptance test output:

$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSVpcPeeringConnectionOptions_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSVpcPeeringConnectionOptions_ -timeout 120m
=== RUN   TestAccAWSVpcPeeringConnectionOptions_basic
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_basic
=== RUN   TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== RUN   TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== CONT  TestAccAWSVpcPeeringConnectionOptions_basic
=== CONT  TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
--- PASS: TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount (32.41s)
=== CONT  TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
--- PASS: TestAccAWSVpcPeeringConnectionOptions_basic (44.41s)
--- PASS: TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount (48.80s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	81.275s

* r/aws_vpc_peering_connection: Fix 'TestAccAWSVPCPeeringConnection_peerRegionAutoAccept'.

Failing acceptance test output:

=== CONT  TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
    testing.go:677: Step 0, expected error:

        Error initializing context: 2 problems:

        - Could not satisfy plugin requirements:
        Plugin reinitialization required. Please run "terraform init".

        Plugins are external binaries that Terraform uses to access and manipulate
        resources. The configuration provided requires plugins which can't be located,
        don't satisfy the version constraints, or are otherwise incompatible.

        Terraform automatically discovers provider requirements from your
        configuration, including providers used in child modules. To see the
        requirements and constraints from each module, run "terraform providers".

        - provider "awsalternate" is not available

        To match:

        .*peer_region cannot be set whilst auto_accept is true when creating a vpc peering connection.*

--- FAIL: TestAccAWSVPCPeeringConnection_peerRegionAutoAccept (0.87s)

Successful acceptance test output:

$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSVPCPeeringConnection_peerRegionAutoAccept'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSVPCPeeringConnection_peerRegionAutoAccept -timeout 120m
=== RUN   TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
=== PAUSE TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
=== CONT  TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
--- PASS: TestAccAWSVPCPeeringConnection_peerRegionAutoAccept (13.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	13.986s

* r/aws_vpc_peering_connection_options: Plugin SDK now handles import testing with multiple providers.

* r/aws_vpc_peering_connection_options: Don't use 'tfawsresource.TestCheckTypeSetElemNestedAttrs' as 'requester' and 'accepter' are TypeList, not TypeSet.

Acceptance test output:

$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSVpcPeeringConnectionOptions_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSVpcPeeringConnectionOptions_ -timeout 120m
=== RUN   TestAccAWSVpcPeeringConnectionOptions_basic
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_basic
=== RUN   TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== RUN   TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== CONT  TestAccAWSVpcPeeringConnectionOptions_basic
=== CONT  TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== CONT  TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== CONT  TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
    resource_aws_vpc_peering_connection_options_test.go:205: Step 1/2 error: Check failed: Check 2/9 error: aws_vpc_peering_connection_options.test: Attribute 'requester.0.allow_remote_vpc_dns_resolution' expected "true", got "false"
--- FAIL: TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount (26.03s)
--- PASS: TestAccAWSVpcPeeringConnectionOptions_basic (57.26s)
--- PASS: TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount (70.71s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	71.016s
FAIL
GNUmakefile:27: recipe for target 'testacc' failed
make: *** [testacc] Error 1

* r/aws_vpc_peering_connection_options: Retry reading back the modified options to deal with eventual consistency.

Acceptance test output:

$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSVpcPeeringConnectionOptions_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSVpcPeeringConnectionOptions_ -timeout 120m
=== RUN   TestAccAWSVpcPeeringConnectionOptions_basic
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_basic
=== RUN   TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
=== RUN   TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== PAUSE TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== CONT  TestAccAWSVpcPeeringConnectionOptions_basic
=== CONT  TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount
=== CONT  TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount
--- PASS: TestAccAWSVpcPeeringConnectionOptions_sameRegionDifferentAccount (46.81s)
--- PASS: TestAccAWSVpcPeeringConnectionOptions_basic (61.15s)
--- PASS: TestAccAWSVpcPeeringConnectionOptions_differentRegionSameAccount (73.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	73.598s

* r/aws_vpc_peering_connection: Fix failing test 'TestAccAWSVPCPeeringConnection_failedState'.

Acceptance test output:

$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSVPCPeeringConnection_' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSVPCPeeringConnection_ -timeout 120m
=== RUN   TestAccAWSVPCPeeringConnection_basic
=== PAUSE TestAccAWSVPCPeeringConnection_basic
=== RUN   TestAccAWSVPCPeeringConnection_plan
=== PAUSE TestAccAWSVPCPeeringConnection_plan
=== RUN   TestAccAWSVPCPeeringConnection_tags
=== PAUSE TestAccAWSVPCPeeringConnection_tags
=== RUN   TestAccAWSVPCPeeringConnection_options
=== PAUSE TestAccAWSVPCPeeringConnection_options
=== RUN   TestAccAWSVPCPeeringConnection_failedState
=== PAUSE TestAccAWSVPCPeeringConnection_failedState
=== RUN   TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
=== PAUSE TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
=== RUN   TestAccAWSVPCPeeringConnection_region
=== PAUSE TestAccAWSVPCPeeringConnection_region
=== RUN   TestAccAWSVPCPeeringConnection_accept
=== PAUSE TestAccAWSVPCPeeringConnection_accept
=== RUN   TestAccAWSVPCPeeringConnection_optionsNoAutoAccept
=== PAUSE TestAccAWSVPCPeeringConnection_optionsNoAutoAccept
=== CONT  TestAccAWSVPCPeeringConnection_basic
=== CONT  TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
--- PASS: TestAccAWSVPCPeeringConnection_peerRegionAutoAccept (14.54s)
=== CONT  TestAccAWSVPCPeeringConnection_failedState
--- PASS: TestAccAWSVPCPeeringConnection_failedState (13.27s)
=== CONT  TestAccAWSVPCPeeringConnection_options
--- PASS: TestAccAWSVPCPeeringConnection_basic (35.23s)
=== CONT  TestAccAWSVPCPeeringConnection_tags
--- PASS: TestAccAWSVPCPeeringConnection_options (62.47s)
=== CONT  TestAccAWSVPCPeeringConnection_plan
--- PASS: TestAccAWSVPCPeeringConnection_plan (24.99s)
=== CONT  TestAccAWSVPCPeeringConnection_optionsNoAutoAccept
--- PASS: TestAccAWSVPCPeeringConnection_tags (86.90s)
=== CONT  TestAccAWSVPCPeeringConnection_accept
=== CONT  TestAccAWSVPCPeeringConnection_region
--- PASS: TestAccAWSVPCPeeringConnection_optionsNoAutoAccept (14.51s)
--- PASS: TestAccAWSVPCPeeringConnection_region (36.92s)
--- PASS: TestAccAWSVPCPeeringConnection_accept (90.20s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	212.871s