resource/aws_cloudfront_distribution: Import into ordered_cache_behavior instead of deprecated cache_behavior
Previously:

--- FAIL: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (739.56s)
	testing.go:527: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

		(map[string]string) (len=59) {
		 (string) (len=16) "cache_behavior.#": (string) (len=1) "2",
...
		 (string) (len=48) "cache_behavior.1203603591.viewer_protocol_policy": (string) (len=9) "allow-all"
		}

		(map[string]string) (len=59) {
		 (string) (len=24) "ordered_cache_behavior.#": (string) (len=1) "2",
...
		 (string) (len=47) "ordered_cache_behavior.1.viewer_protocol_policy": (string) (len=9) "allow-all"
		}

Now:

--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (820.16s)