tests/resource/aws_ssm_activation: Remove broken ExpectError testing from TestAccAWSSSMActivation_expirationDate (#12173)
Previously from the acceptance testing:

```
--- FAIL: TestAccAWSSSMActivation_expirationDate (1.08s)
    testing.go:647: Step 0, expected error:

        config is invalid: expected "expiration_date" to be a valid RFC3339 date, got "2018-03-01": parsing time "2018-03-01" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"

        To match:

        invalid RFC3339 timestamp
```

It appears the error messaging changed with the RFC3339 timestamp validation around January 31, 2020. We typically do not use `ExpectError` testing too often with plan-time value validations, since its usually an unnecessary maintenance burden, so here we remove the extra test step rather than manually update the expected error messaging to match disconnected code.

Output from acceptance testing:

```
--- PASS: TestAccAWSSSMActivation_expirationDate (36.94s)
```