internal/vault/helper/pgpkeys: Add missing error checking for new internalized code
Previously reported linter error:

```
aws/internal/vault/helper/pgpkeys/encrypt_decrypt.go:114:16: Error return value of `ptBuf.ReadFrom` is not checked (errcheck)
	ptBuf.ReadFrom(md.UnverifiedBody)
	              ^
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAccessKey_basic (10.83s)
--- PASS: TestAccAWSAccessKey_encrypted (10.89s)
--- PASS: TestAccAWSAccessKey_inactive (18.69s)

--- PASS: TestAccAWSLightsailKeyPair_basic (25.49s)
--- PASS: TestAccAWSLightsailKeyPair_encrypted (24.46s)
--- PASS: TestAccAWSLightsailKeyPair_nameprefix (25.67s)
--- PASS: TestAccAWSLightsailKeyPair_publicKey (24.93s)

--- PASS: TestAccAWSUserLoginProfile_basic (21.19s)
--- PASS: TestAccAWSUserLoginProfile_keybase (12.62s)
--- PASS: TestAccAWSUserLoginProfile_keybaseDoesntExist (7.63s)
--- PASS: TestAccAWSUserLoginProfile_notAKey (7.41s)
--- PASS: TestAccAWSUserLoginProfile_PasswordLength (14.54s)
```