tests/provider: Temporarily expand TypeList arguments for Terraform 0.11 and 0.12 compatibility
These changes are backwards (0.11) and forwards (0.12) compatible so the acceptance testing can be run in either dependency environment. This temporarily workaround will be removed when the acceptance testing configurations are switched to 0.12-only syntax.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAPIGatewayAuthorizer_cognito (1.62s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test743589365/main.tf line 15:
          (source code not available)

        Inappropriate value for attribute "provider_arns": element 0: string required.

--- FAIL: TestAccAWSASGNotification_Pagination (1.78s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test668166509/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "group_names": element 0: string required.

--- FAIL: TestAccAWSCodeBuildProject_VpcConfig (1.69s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test876060979/main.tf line 101:
          (source code not available)

        Inappropriate value for attribute "subnets": element 0: string required.

--- FAIL: TestAccAWSCodeDeployDeploymentGroup_ECS_BlueGreen (2.27s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test610692362/main.tf line 55:
          (source code not available)

        Inappropriate value for attribute "subnets": element 0: string required.

--- FAIL: TestAccAWSDbClusterSnapshotDataSource_DbClusterSnapshotIdentifier (2.87s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test886332704/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "subnet_ids": element 0: string required.

--- FAIL: TestAccAWSDbClusterSnapshotDataSource_DbClusterIdentifier (3.82s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test558959475/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "subnet_ids": element 0: string required.

--- FAIL: TestAccAWSDbClusterSnapshotDataSource_MostRecent (3.77s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test648461943/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "subnet_ids": element 0: string required.
```

Output from Terraform 0.12 acceptance testing (additional fixes required in Terraform Provider SDK):

```
--- PASS: TestAccAWSAPIGatewayAuthorizer_cognito (28.76s)
--- PASS: TestAccAWSASGNotification_Pagination (118.33s)

--- FAIL: TestAccAWSCodeBuildProject_VpcConfig (58.08s)
    testing.go:568: Step 2 error: errors during apply:

        Error: [ERROR] Error updating CodeBuild project (arn:aws:codebuild:us-west-2:187416307283:project/tf-acc-test-4139231503421636272): InvalidParameter: 1 validation error(s) found.
        - minimum field size of 1, UpdateProjectInput.VpcConfig.VpcId.

--- PASS: TestAccAWSCodeDeployDeploymentGroup_ECS_BlueGreen (291.56s)
--- PASS: TestAccAWSDbClusterSnapshotDataSource_DbClusterIdentifier (194.77s)
--- PASS: TestAccAWSDbClusterSnapshotDataSource_DbClusterSnapshotIdentifier (214.89s)
--- PASS: TestAccAWSDbClusterSnapshotDataSource_MostRecent (285.00s)
```