Acceptance test output:
% make testacc TESTARGS='-run=TestAccS3BucketReplicationConfiguration_' PKG=s3 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 2  -run=TestAccS3BucketReplicationConfiguration_ -timeout 360m
=== RUN   TestAccS3BucketReplicationConfiguration_basic
=== PAUSE TestAccS3BucketReplicationConfiguration_basic
=== RUN   TestAccS3BucketReplicationConfiguration_disappears
=== PAUSE TestAccS3BucketReplicationConfiguration_disappears
=== RUN   TestAccS3BucketReplicationConfiguration_multipleDestinationsEmptyFilter
=== PAUSE TestAccS3BucketReplicationConfiguration_multipleDestinationsEmptyFilter
=== RUN   TestAccS3BucketReplicationConfiguration_multipleDestinationsNonEmptyFilter
=== PAUSE TestAccS3BucketReplicationConfiguration_multipleDestinationsNonEmptyFilter
=== RUN   TestAccS3BucketReplicationConfiguration_twoDestination
=== PAUSE TestAccS3BucketReplicationConfiguration_twoDestination
=== RUN   TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAccessControlTranslation
=== PAUSE TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAccessControlTranslation
=== RUN   TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAddAccessControlTranslation
=== PAUSE TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAddAccessControlTranslation
=== RUN   TestAccS3BucketReplicationConfiguration_replicationTimeControl
=== PAUSE TestAccS3BucketReplicationConfiguration_replicationTimeControl
=== RUN   TestAccS3BucketReplicationConfiguration_replicaModifications
=== PAUSE TestAccS3BucketReplicationConfiguration_replicaModifications
=== RUN   TestAccS3BucketReplicationConfiguration_withoutId
=== PAUSE TestAccS3BucketReplicationConfiguration_withoutId
=== RUN   TestAccS3BucketReplicationConfiguration_withoutStorageClass
=== PAUSE TestAccS3BucketReplicationConfiguration_withoutStorageClass
=== RUN   TestAccS3BucketReplicationConfiguration_schemaV2
=== PAUSE TestAccS3BucketReplicationConfiguration_schemaV2
=== RUN   TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
=== PAUSE TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
=== RUN   TestAccS3BucketReplicationConfiguration_schemaV2DestinationMetrics
=== PAUSE TestAccS3BucketReplicationConfiguration_schemaV2DestinationMetrics
=== RUN   TestAccS3BucketReplicationConfiguration_existingObjectReplication
    bucket_replication_configuration_test.go:768: skipping test: AWS Technical Support request required to allow ExistingObjectReplication
--- SKIP: TestAccS3BucketReplicationConfiguration_existingObjectReplication (0.00s)
=== RUN   TestAccS3BucketReplicationConfiguration_filter_emptyConfigurationBlock
=== PAUSE TestAccS3BucketReplicationConfiguration_filter_emptyConfigurationBlock
=== RUN   TestAccS3BucketReplicationConfiguration_filter_emptyPrefix
=== PAUSE TestAccS3BucketReplicationConfiguration_filter_emptyPrefix
=== RUN   TestAccS3BucketReplicationConfiguration_filter_tagFilter
=== PAUSE TestAccS3BucketReplicationConfiguration_filter_tagFilter
=== RUN   TestAccS3BucketReplicationConfiguration_filter_andOperator
=== PAUSE TestAccS3BucketReplicationConfiguration_filter_andOperator
=== RUN   TestAccS3BucketReplicationConfiguration_filter_withoutId
=== PAUSE TestAccS3BucketReplicationConfiguration_filter_withoutId
=== RUN   TestAccS3BucketReplicationConfiguration_withoutPrefix
=== PAUSE TestAccS3BucketReplicationConfiguration_withoutPrefix
=== RUN   TestAccS3BucketReplicationConfiguration_migrate_noChange
=== PAUSE TestAccS3BucketReplicationConfiguration_migrate_noChange
=== RUN   TestAccS3BucketReplicationConfiguration_migrate_withChange
=== PAUSE TestAccS3BucketReplicationConfiguration_migrate_withChange
=== CONT  TestAccS3BucketReplicationConfiguration_basic
=== CONT  TestAccS3BucketReplicationConfiguration_schemaV2
    bucket_replication_configuration_test.go:650: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-6775954691988083781-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: GA72W41YDTY423YG, HostID: R4EvQ3jw6z1kLbbXRz75OmtnzhLSIpMJPWx37OCnwcLgiuImd++kewlsooUCOw1BVeMw6zDC0Y89cZug4VBiLg==, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_schemaV2 (21.77s)
=== CONT  TestAccS3BucketReplicationConfiguration_filter_andOperator
    bucket_replication_configuration_test.go:962: Step 1/4 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-6534660829213118586-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: 3DGJ4BX5ZPK4E11Q, HostID: huOKd5kX7+Eeh9VQ96t9xeuqMKrw3otpQhtZdj2uH6qaGrchvlIwgyWvdhRTwzA9hxtdiv7LKA0=, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_filter_andOperator (21.73s)
=== CONT  TestAccS3BucketReplicationConfiguration_migrate_withChange
--- PASS: TestAccS3BucketReplicationConfiguration_basic (100.15s)
=== CONT  TestAccS3BucketReplicationConfiguration_migrate_noChange
--- PASS: TestAccS3BucketReplicationConfiguration_migrate_withChange (65.41s)
=== CONT  TestAccS3BucketReplicationConfiguration_withoutPrefix
--- PASS: TestAccS3BucketReplicationConfiguration_withoutPrefix (52.32s)
=== CONT  TestAccS3BucketReplicationConfiguration_filter_withoutId
--- PASS: TestAccS3BucketReplicationConfiguration_migrate_noChange (74.50s)
=== CONT  TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAddAccessControlTranslation
=== NAME  TestAccS3BucketReplicationConfiguration_filter_withoutId
    bucket_replication_configuration_test.go:1038: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-8159618831180413580-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: NQ03NXMAM1ETFXE4, HostID: yo+HCNWHl1JPhWhSaDHjP05rLVc/BzqWBeNplSyv75cLXsb3QlxKKS8OGEYcbdNRTtfqOh/X4/jpMks06HVjbw==, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_filter_withoutId (21.05s)
=== CONT  TestAccS3BucketReplicationConfiguration_withoutStorageClass
--- PASS: TestAccS3BucketReplicationConfiguration_withoutStorageClass (43.11s)
=== CONT  TestAccS3BucketReplicationConfiguration_withoutId
--- PASS: TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAddAccessControlTranslation (76.48s)
=== CONT  TestAccS3BucketReplicationConfiguration_replicaModifications
    bucket_replication_configuration_test.go:516: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-8332156920861849885-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: 29PCZPX2WV74TDDR, HostID: PPs8ma+yJy9EQ+xuJUIXa3SAWyi+NlUOJnl/w6DFwz3wmM0lqGidrC02i4TX+o4qYmjeCLN6Jrs=, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- PASS: TestAccS3BucketReplicationConfiguration_withoutId (43.82s)
=== CONT  TestAccS3BucketReplicationConfiguration_replicationTimeControl
--- FAIL: TestAccS3BucketReplicationConfiguration_replicaModifications (20.84s)
=== CONT  TestAccS3BucketReplicationConfiguration_multipleDestinationsNonEmptyFilter
=== NAME  TestAccS3BucketReplicationConfiguration_replicationTimeControl
    bucket_replication_configuration_test.go:462: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-8901063465684459691-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: FBH2JY4RV3BNVHEP, HostID: /pWlew1zpzhqOgceLbDbYZl5f42cxudsce6YA4OmLyVrSiUoSvbScIgIxtOfHlucbAz/Duhp6QQ=, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_replicationTimeControl (21.02s)
=== CONT  TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAccessControlTranslation
--- PASS: TestAccS3BucketReplicationConfiguration_multipleDestinationsNonEmptyFilter (44.27s)
=== CONT  TestAccS3BucketReplicationConfiguration_twoDestination
--- PASS: TestAccS3BucketReplicationConfiguration_twoDestination (42.86s)
=== CONT  TestAccS3BucketReplicationConfiguration_filter_emptyConfigurationBlock
--- PASS: TestAccS3BucketReplicationConfiguration_configurationRuleDestinationAccessControlTranslation (83.67s)
=== CONT  TestAccS3BucketReplicationConfiguration_filter_tagFilter
=== NAME  TestAccS3BucketReplicationConfiguration_filter_emptyConfigurationBlock
    bucket_replication_configuration_test.go:827: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-7069375532507503824-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: 15KPYW749Q1CTJMX, HostID: 8O1U/qE1AxjMa0oFaPk3HhFWyoTIInnoVy40BKffa7pNM1uTVQH+13QNndw/mRB8Q+qcINjuko8=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_filter_emptyConfigurationBlock (21.13s)
=== CONT  TestAccS3BucketReplicationConfiguration_filter_emptyPrefix
=== NAME  TestAccS3BucketReplicationConfiguration_filter_tagFilter
    bucket_replication_configuration_test.go:917: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-559494889894129713-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: SY9T57K1P75D4H64, HostID: uRE6mb6Puo2z8oKyWZyKJ+qMbV1+bTSLLzftUDfKswNFdL7j0g8OswA3Xh/3DFaQ2za/5+rbizA=, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_filter_tagFilter (20.81s)
=== CONT  TestAccS3BucketReplicationConfiguration_multipleDestinationsEmptyFilter
=== NAME  TestAccS3BucketReplicationConfiguration_filter_emptyPrefix
    bucket_replication_configuration_test.go:870: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-5984674732763602379-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: QAD8CWR1Q92K9YWX, HostID: BTyFRhVxCWADOOZFsaIrpvF2SeI7a0SIqFt0TAbRj6jTZUcVcfNd2D0OGZUDPFxpeNIqUIEX5g4=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_filter_emptyPrefix (20.99s)
=== CONT  TestAccS3BucketReplicationConfiguration_schemaV2DestinationMetrics
=== NAME  TestAccS3BucketReplicationConfiguration_multipleDestinationsEmptyFilter
    bucket_replication_configuration_test.go:133: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-6934307818895341033-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: AA024YVGR2TC3ZFS, HostID: Nuqzt6Z4gc+adin2NsynxVoy8jAn5+ew9ddnyFzR7uDsB0jRvpXstRlzRTJ+cDEeKNsQuAT2fAI=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 71, in resource "aws_s3_bucket_replication_configuration" "test":
          71: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_multipleDestinationsEmptyFilter (21.06s)
=== CONT  TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
=== NAME  TestAccS3BucketReplicationConfiguration_schemaV2DestinationMetrics
    bucket_replication_configuration_test.go:737: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-2374667212311572152-source) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: Y1BMZTM31B43ZJPD, HostID: hoEm0fsaBoPhvVQ7B9WsUa710BUPgDfTw/n8HfjQJoCBNt+WVgA8RpFkjipXmG1cs8+oQl2SosM=, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 47, in resource "aws_s3_bucket_replication_configuration" "test":
          47: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_schemaV2DestinationMetrics (20.36s)
=== CONT  TestAccS3BucketReplicationConfiguration_disappears
=== NAME  TestAccS3BucketReplicationConfiguration_schemaV2SameRegion
    bucket_replication_configuration_test.go:695: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-6796932585806202747) Replication Configuration: operation error S3: PutBucketReplication, https response error StatusCode: 400, RequestID: 6ZN9J4XZFB5NJ9FY, HostID: DVDrCsqqC2u3qRdsvD3WUplL9Y6l6YwrjWTTKBMJk2mgpVqGlQgmfCAv3/+s/GdGegA0Dv5ga68=, api error InvalidRequest: Priority must be specified for this version of Cross Region Replication configuration schema. Please refer to S3 Developer Guide for more information.

          with aws_s3_bucket_replication_configuration.test,
          on terraform_plugin_test.tf line 44, in resource "aws_s3_bucket_replication_configuration" "test":
          44: resource "aws_s3_bucket_replication_configuration" "test" {

--- FAIL: TestAccS3BucketReplicationConfiguration_schemaV2SameRegion (33.61s)
--- PASS: TestAccS3BucketReplicationConfiguration_disappears (54.31s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/s3	482.251s
FAIL
make: *** [testacc] Error 1