tests/service/glue: Syntax fixes for Terraform 0.12
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSGlueCatalogDatabase_full (3.41s)
    testing.go:568: Step 1 error: config is invalid: Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCatalogDatabase_importBasic (0.63s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCatalogTable_full (0.78s)
    testing.go:568: Step 0 error: config is invalid: 7 problems:

        - Unsupported argument: An argument named "partition_keys" is not expected here. Did you mean to define a block of type "partition_keys"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported argument: An argument named "sort_columns" is not expected here. Did you mean to define a block of type "sort_columns"?
        - Unsupported argument: An argument named "columns" is not expected here. Did you mean to define a block of type "columns"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "skewed_column_value_location_maps" are not expected here. Did you mean to define argument "skewed_column_value_location_maps"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCatalogTable_importBasic (0.60s)
    testing.go:568: Step 0 error: config is invalid: 7 problems:

        - Unsupported argument: An argument named "partition_keys" is not expected here. Did you mean to define a block of type "partition_keys"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported argument: An argument named "columns" is not expected here. Did you mean to define a block of type "columns"?
        - Unsupported argument: An argument named "sort_columns" is not expected here. Did you mean to define a block of type "sort_columns"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "skewed_column_value_location_maps" are not expected here. Did you mean to define argument "skewed_column_value_location_maps"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCatalogTable_update_addValues (3.57s)
    testing.go:568: Step 1 error: config is invalid: 7 problems:

        - Unsupported argument: An argument named "partition_keys" is not expected here. Did you mean to define a block of type "partition_keys"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported argument: An argument named "columns" is not expected here. Did you mean to define a block of type "columns"?
        - Unsupported argument: An argument named "sort_columns" is not expected here. Did you mean to define a block of type "sort_columns"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "skewed_column_value_location_maps" are not expected here. Did you mean to define argument "skewed_column_value_location_maps"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCatalogTable_update_replaceValues (0.62s)
    testing.go:568: Step 0 error: config is invalid: 7 problems:

        - Unsupported argument: An argument named "partition_keys" is not expected here. Did you mean to define a block of type "partition_keys"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported argument: An argument named "columns" is not expected here. Did you mean to define a block of type "columns"?
        - Unsupported argument: An argument named "sort_columns" is not expected here. Did you mean to define a block of type "sort_columns"?
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "parameters" are not expected here. Did you mean to define argument "parameters"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "skewed_column_value_location_maps" are not expected here. Did you mean to define argument "skewed_column_value_location_maps"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCrawler_JdbcTarget (0.64s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Missing required argument: The argument "connection_properties" is required, but no definition was found.
        - Unsupported block type: Blocks of type "connection_properties" are not expected here. Did you mean to define argument "connection_properties"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCrawler_JdbcTarget_Exclusions (0.70s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Missing required argument: The argument "connection_properties" is required, but no definition was found.
        - Unsupported block type: Blocks of type "connection_properties" are not expected here. Did you mean to define argument "connection_properties"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCrawler_JdbcTarget_Multiple (0.64s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Missing required argument: The argument "connection_properties" is required, but no definition was found.
        - Unsupported block type: Blocks of type "connection_properties" are not expected here. Did you mean to define argument "connection_properties"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSGlueCrawler_S3Target_Exclusions (0.76s)
    testing.go:568: Step 0 error: config is invalid: Incorrect attribute value type: Inappropriate value for attribute "exclusions": element 0: string required.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- PASS: TestAccAWSGlueCatalogDatabase_recreates (12.65s)
--- PASS: TestAccAWSGlueCatalogDatabase_importBasic (12.99s)
--- FAIL: TestAccAWSGlueCatalogDatabase_full (16.24s)
    testing.go:568: Step 1 error: Check failed: Check 5/6 error: aws_glue_catalog_database.test: Attribute 'parameters.param2' expected "1", got "true"

--- PASS: TestAccAWSGlueCatalogTable_basic (12.99s)
--- PASS: TestAccAWSGlueCatalogTable_full (13.35s)
--- PASS: TestAccAWSGlueCatalogTable_importBasic (14.59s)
--- FAIL: TestAccAWSGlueCatalogTable_update_replaceValues (18.40s)
    testing.go:568: Step 1 error: Check failed: Check 7/43 error: aws_glue_catalog_table.test: Attribute 'storage_descriptor.0.columns.0.name' not found
--- PASS: TestAccAWSGlueCatalogTable_update_addValues (21.70s)

--- FAIL: TestAccAWSGlueCrawler_JdbcTarget (33.59s)
    testing.go:568: Step 1 error: errors during apply:

        Error: error updating Glue crawler: InvalidInputException: Connection name cannot be equal to null or empty.
          status code: 400, request id: b4f2f66a-1f35-11e9-a914-47fb9cd5a754

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test537421395/main.tf line 51:
          (source code not available)

--- FAIL: TestAccAWSGlueCrawler_JdbcTarget_Multiple (35.33s)
    testing.go:568: Step 1 error: errors during apply:

        Error: One of the following configurations is required: dynamodb_target, jdbc_target, s3_target

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test042624312/main.tf line 51:
          (source code not available)

--- FAIL: TestAccAWSGlueCrawler_JdbcTarget_Exclusions (35.73s)
    testing.go:568: Step 1 error: errors during apply:

        Error: error updating Glue crawler: InvalidInputException: Connection name cannot be equal to null or empty.
          status code: 400, request id: b65ebaad-1f35-11e9-a914-47fb9cd5a754

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test890607927/main.tf line 52:
          (source code not available)

--- FAIL: TestAccAWSGlueCrawler_S3Target_Exclusions (71.37s)
    testing.go:568: Step 1 error: errors during apply:

        Error: error updating Glue crawler: InvalidInputException: Targets are not defined
          status code: 400, request id: cb6dcfdc-1f35-11e9-8ead-81f74e5dfe82

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test443078466/main.tf line 41:
          (source code not available)

--- FAIL: TestAccAWSGlueCrawler_S3Target_Multiple (80.94s)
    testing.go:568: Step 1 error: errors during apply:

        Error: One of the following configurations is required: dynamodb_target, jdbc_target, s3_target

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test023933725/main.tf line 40:
          (source code not available)
```