tests/service/eks: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSEksCluster_basic (32.31s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating IAM Role tf-acc-test-pgb4h: MalformedPolicyDocument: Invalid principal in policy: "SERVICE":"eks.amazonaws.com"
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSEksClusterDataSource_basic (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSEksCluster_VpcConfig_EndpointPublicAccess (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSEksCluster_VpcConfig_EndpointPrivateAccess (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSEksCluster_VpcConfig_SecurityGroupIds (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSEksCluster_Logging (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSEksCluster_Version (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSEksCluster_basic (2.28s)
    resource_aws_eks_cluster_test.go:401: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://eks.us-gov-west-1.amazonaws.com/clusters: dial tcp: lookup eks.us-gov-west-1.amazonaws.com: no such host
```