mwaa: enable `go-vcr` support
2025/09/23 17:53:23 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/23 17:53:23 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccMWAAEnvironment_basic
=== PAUSE TestAccMWAAEnvironment_basic
=== RUN   TestAccMWAAEnvironment_disappears
=== PAUSE TestAccMWAAEnvironment_disappears
=== RUN   TestAccMWAAEnvironment_airflowOptions
=== PAUSE TestAccMWAAEnvironment_airflowOptions
=== RUN   TestAccMWAAEnvironment_log
=== PAUSE TestAccMWAAEnvironment_log
=== RUN   TestAccMWAAEnvironment_full
=== PAUSE TestAccMWAAEnvironment_full
=== RUN   TestAccMWAAEnvironment_pluginsS3ObjectVersion
=== PAUSE TestAccMWAAEnvironment_pluginsS3ObjectVersion
=== RUN   TestAccMWAAEnvironment_customerVPCE
=== PAUSE TestAccMWAAEnvironment_customerVPCE
=== RUN   TestAccMWAAEnvironment_updateAirflowVersionMinor
=== PAUSE TestAccMWAAEnvironment_updateAirflowVersionMinor
=== RUN   TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy
=== PAUSE TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy
=== CONT  TestAccMWAAEnvironment_basic
=== CONT  TestAccMWAAEnvironment_pluginsS3ObjectVersion
=== CONT  TestAccMWAAEnvironment_full
=== CONT  TestAccMWAAEnvironment_customerVPCE
=== CONT  TestAccMWAAEnvironment_airflowOptions
=== CONT  TestAccMWAAEnvironment_log
=== CONT  TestAccMWAAEnvironment_disappears
=== CONT  TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy
=== CONT  TestAccMWAAEnvironment_updateAirflowVersionMinor
=== NAME  TestAccMWAAEnvironment_pluginsS3ObjectVersion
    environment_test.go:334: Step 3/4 error: Error running apply: exit status 1

        Error: Invalid provider configuration

        Provider "registry.terraform.io/hashicorp/aws" requires explicit
        configuration. Add a provider block to the root module and configure the
        provider's required arguments as described in the provider documentation.

        Error: Retrieving AWS account details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 5f9c3d11-a1ca-4c00-9f3f-8f0a6bce99b6, api error SignatureDoesNotMatch: Signature expired: 20250923T222133Z is now earlier than 20250923T222133Z (20250923T223633Z - 15 min.)

          with provider["registry.terraform.io/hashicorp/aws"],
          on <empty> line 0:
          (source code not available)

=== NAME  TestAccMWAAEnvironment_airflowOptions
    environment_test.go:123: Step 4/4 error: Error running apply: exit status 1

        Error: updating MWAA Environment (tf-acc-test-6355555031766628094): operation error MWAA: UpdateEnvironment, https response error StatusCode: 400, RequestID: b1691b17-4aee-455b-8e65-b6b555b26e91, ValidationException: The scheduler count for environment class mw1.micro must be 1.

          with aws_mwaa_environment.test,
          on terraform_plugin_test.tf line 218, in resource "aws_mwaa_environment" "test":
         218: resource "aws_mwaa_environment" "test" {

--- PASS: TestAccMWAAEnvironment_customerVPCE (808.90s)
--- PASS: TestAccMWAAEnvironment_basic (808.95s)
--- PASS: TestAccMWAAEnvironment_disappears (882.36s)
--- PASS: TestAccMWAAEnvironment_full (1140.11s)
--- FAIL: TestAccMWAAEnvironment_airflowOptions (1358.08s)
--- FAIL: TestAccMWAAEnvironment_pluginsS3ObjectVersion (1766.58s)
--- PASS: TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy (1776.28s)
--- PASS: TestAccMWAAEnvironment_log (2701.17s)
--- PASS: TestAccMWAAEnvironment_updateAirflowVersionMinor (4009.26s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/mwaa	4015.889s
FAIL

2025/09/23 19:47:38 Creating Terraform AWS Provider (SDKv2-style)...
2025/09/23 19:47:38 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccMWAAEnvironment_basic
=== PAUSE TestAccMWAAEnvironment_basic
=== RUN   TestAccMWAAEnvironment_disappears
=== PAUSE TestAccMWAAEnvironment_disappears
=== RUN   TestAccMWAAEnvironment_airflowOptions
=== PAUSE TestAccMWAAEnvironment_airflowOptions
=== RUN   TestAccMWAAEnvironment_log
=== PAUSE TestAccMWAAEnvironment_log
=== RUN   TestAccMWAAEnvironment_full
=== PAUSE TestAccMWAAEnvironment_full
=== RUN   TestAccMWAAEnvironment_pluginsS3ObjectVersion
=== PAUSE TestAccMWAAEnvironment_pluginsS3ObjectVersion
=== RUN   TestAccMWAAEnvironment_customerVPCE
=== PAUSE TestAccMWAAEnvironment_customerVPCE
=== RUN   TestAccMWAAEnvironment_updateAirflowVersionMinor
=== PAUSE TestAccMWAAEnvironment_updateAirflowVersionMinor
=== RUN   TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy
=== PAUSE TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy
=== CONT  TestAccMWAAEnvironment_basic
=== CONT  TestAccMWAAEnvironment_pluginsS3ObjectVersion
=== CONT  TestAccMWAAEnvironment_log
=== CONT  TestAccMWAAEnvironment_full
=== CONT  TestAccMWAAEnvironment_updateAirflowVersionMinor
=== CONT  TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy
=== CONT  TestAccMWAAEnvironment_customerVPCE
=== CONT  TestAccMWAAEnvironment_airflowOptions
=== CONT  TestAccMWAAEnvironment_disappears
=== NAME  TestAccMWAAEnvironment_airflowOptions
    environment_test.go:123: Step 4/4 error: Error running apply: exit status 1

        Error: updating MWAA Environment (tf-acc-test-7940181435684514975): operation error MWAA: UpdateEnvironment, https response error StatusCode: 400, RequestID: 63f41d65-025a-4ff6-b50e-6c6e2cd8c79f, ValidationException: The scheduler count for environment class mw1.micro must be 1.

          with aws_mwaa_environment.test,
          on terraform_plugin_test.tf line 218, in resource "aws_mwaa_environment" "test":
         218: resource "aws_mwaa_environment" "test" {

--- PASS: TestAccMWAAEnvironment_customerVPCE (1890.96s)
--- PASS: TestAccMWAAEnvironment_disappears (2305.76s)
--- PASS: TestAccMWAAEnvironment_basic (2680.64s)
--- PASS: TestAccMWAAEnvironment_log (2963.37s)
--- FAIL: TestAccMWAAEnvironment_airflowOptions (3151.46s)
--- PASS: TestAccMWAAEnvironment_updateAirflowWorkerReplacementStrategy (3203.16s)
--- PASS: TestAccMWAAEnvironment_full (3230.44s)
--- PASS: TestAccMWAAEnvironment_pluginsS3ObjectVersion (3372.68s)
--- PASS: TestAccMWAAEnvironment_updateAirflowVersionMinor (4159.73s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/mwaa	4166.454s
FAIL