r/aws_rds_global_cluster: fix minor version upgrade workflow
This addresses a regression caused by a change in the text of the `InvalidParameterValue` exception returned by the AWS API when a minor version upgrade is attempted on the global cluster. The provider does not attempt to parse various engine version combinations, and instead always first attempts a major version upgrade before falling back to a minor version upgrade when specific error text is received. The upstream change in message caused this mechanism to break. Updating the expected message text restores the intended behavior.

Before:

```console
% make t K=rds T=TestAccRDSGlobalCluster_EngineVersion_updateMinor
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 tmp2 🌿...
TF_ACC=1 go1.24.11 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSGlobalCluster_EngineVersion_updateMinor'  -timeout 360m -vet=off
2025/12/15 13:37:39 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/15 13:37:39 Initializing Terraform AWS Provider (SDKv2-style)...

=== NAME  TestAccRDSGlobalCluster_EngineVersion_updateMinor
    global_cluster_test.go:279: Step 2/3 error: Error running apply: exit status 1

        Error: upgrading major version of RDS Global Cluster (tf-acc-test-8163082142476779811): modifying RDS Global Cluster (tf-acc-test-8163082142476779811) EngineVersion: operation error RDS: ModifyGlobalCluster, https response error StatusCode: 400, RequestID: e2c33581-584e-4bae-8f20-ffddca8ccaf9, api error InvalidParameterValue: ModifyGlobalCluster doesn't support minor version upgrades for Aurora global databases. To upgrade to a newer minor version, call ModifyDBCluster for each member of your global cluster.

          with aws_rds_global_cluster.test,
          on terraform_plugin_test.tf line 44, in resource "aws_rds_global_cluster" "test":
          44: resource "aws_rds_global_cluster" "test" {

=== NAME  TestAccRDSGlobalCluster_EngineVersion_updateMinorMultiRegion
    global_cluster_test.go:365: Step 2/2 error: Error running apply: exit status 1

        Error: upgrading major version of RDS Global Cluster (tf-acc-test-6322879870747030243): modifying RDS Global Cluster (tf-acc-test-6322879870747030243) EngineVersion: operation error RDS: ModifyGlobalCluster, https response error StatusCode: 400, RequestID: 9ae57ef4-ff0e-4076-be38-49c9fef642a6, api error InvalidParameterValue: ModifyGlobalCluster doesn't support minor version upgrades for Aurora global databases. To upgrade to a newer minor version, call ModifyDBCluster for each member of your global cluster.

          with aws_rds_global_cluster.test,
          on terraform_plugin_test.tf line 63, in resource "aws_rds_global_cluster" "test":
          63: resource "aws_rds_global_cluster" "test" {

--- FAIL: TestAccRDSGlobalCluster_EngineVersion_updateMinor (6492.85s)

--- FAIL: TestAccRDSGlobalCluster_EngineVersion_updateMinorMultiRegion (8039.50s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/rds        8046.072s
```

After:

```console
% make t K=rds T='^TestAccRDSGlobalCluster_EngineVersion_updateMinor$$'
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 tmp2 🌿...
TF_ACC=1 go1.24.11 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='^TestAccRDSGlobalCluster_EngineVersion_updateMinor$'  -timeout 360m -vet=off
2025/12/15 16:08:30 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/15 16:08:30 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMinor (6794.77s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        6801.457s
```

```console
% make t K=rds T="TestAccRDSGlobalCluster_"
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-rds_global_cluster-minor-upgrade 🌿...
TF_ACC=1 go1.24.11 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSGlobalCluster_'  -timeout 360m -vet=off
2025/12/16 10:06:37 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/16 10:06:37 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccRDSGlobalCluster_disappears (33.89s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Add
=== NAME  TestAccRDSGlobalCluster_storageEncrypted
    global_cluster_test.go:602: Step 3/3 error: Error running apply: exit status 1

        Error: creating RDS Global Cluster (tf-acc-test-3117278625220647550): operation error RDS: CreateGlobalCluster, https response error StatusCode: 400, RequestID: b23e02ea-13d3-46aa-8d7b-d2e2cf40dbbe, GlobalClusterAlreadyExistsFault: Global cluster tf-acc-test-3117278625220647550 already exists

          with aws_rds_global_cluster.test,
          on terraform_plugin_test.tf line 12, in resource "aws_rds_global_cluster" "test":
          12: resource "aws_rds_global_cluster" "test" {

--- FAIL: TestAccRDSGlobalCluster_storageEncrypted (42.92s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_updateMajor
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_nullNonOverlappingResourceTag (43.70s)
=== CONT  TestAccRDSGlobalCluster_tags_DefaultTags_overlapping
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_nullOverlappingResourceTag (43.74s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_updateMinorMultiRegion
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_emptyProviderOnlyTag (44.10s)
=== CONT  TestAccRDSGlobalCluster_tags_DefaultTags_nonOverlapping
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_emptyResourceTag (44.43s)
=== CONT  TestAccRDSGlobalCluster_tags_DefaultTags_providerOnly
--- PASS: TestAccRDSGlobalCluster_tags_ComputedTag_OnCreate (46.37s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccRDSGlobalCluster_databaseName (61.82s)
=== CONT  TestAccRDSGlobalCluster_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_updateToResourceOnly (67.45s)
=== CONT  TestAccRDSGlobalCluster_basic
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_updateToProviderOnly (69.06s)
=== CONT  TestAccRDSGlobalCluster_tags_AddOnUpdate
--- PASS: TestAccRDSGlobalCluster_tags_ComputedTag_OnUpdate_Replace (72.44s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyMap
--- PASS: TestAccRDSGlobalCluster_tags_ComputedTag_OnUpdate_Add (72.79s)
=== CONT  TestAccRDSGlobalCluster_tags_EmptyTag_OnCreate
--- PASS: TestAccRDSGlobalCluster_tags_IgnoreTags_Overlap_DefaultTag (80.97s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_auroraPostgreSQL
--- PASS: TestAccRDSGlobalCluster_deletionProtection (87.53s)
=== CONT  TestAccRDSGlobalCluster_forceDestroy
--- PASS: TestAccRDSGlobalCluster_basic (30.16s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_auroraMySQL
--- PASS: TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Replace (58.83s)
=== CONT  TestAccRDSGlobalCluster_tags_null
--- PASS: TestAccRDSGlobalCluster_forceDestroy (22.88s)
=== CONT  TestAccRDSGlobalCluster_EngineVersion_updateMinor
--- PASS: TestAccRDSGlobalCluster_EngineVersion_auroraPostgreSQL (30.56s)
=== CONT  TestAccRDSGlobalCluster_engineLifecycleSupport_disabled
--- PASS: TestAccRDSGlobalCluster_tags_EmptyMap (46.40s)
--- PASS: TestAccRDSGlobalCluster_tags_AddOnUpdate (52.32s)
--- PASS: TestAccRDSGlobalCluster_tags_EmptyTag_OnUpdate_Add (87.55s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_auroraMySQL (28.41s)
--- PASS: TestAccRDSGlobalCluster_tags (127.37s)
--- PASS: TestAccRDSGlobalCluster_tags_EmptyTag_OnCreate (55.86s)
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_nonOverlapping (87.05s)
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_overlapping (88.60s)
--- PASS: TestAccRDSGlobalCluster_engineLifecycleSupport_disabled (22.33s)
--- PASS: TestAccRDSGlobalCluster_tags_IgnoreTags_Overlap_ResourceTag (73.65s)
--- PASS: TestAccRDSGlobalCluster_tags_null (34.70s)
--- PASS: TestAccRDSGlobalCluster_tags_DefaultTags_providerOnly (102.82s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_databaseName (194.43s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_storageEncrypted (204.01s)
--- PASS: TestAccRDSGlobalCluster_sourceDBClusterIdentifier (204.54s)
--- PASS: TestAccRDSGlobalCluster_SourceDBClusterIdentifier_EngineVersion_updateMajor (1685.84s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMajor (1724.32s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMajorMultiRegion (3442.45s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMinor (6766.50s)
--- PASS: TestAccRDSGlobalCluster_EngineVersion_updateMinorMultiRegion (8361.36s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/rds        8411.788s
```

Failure is unrelated to this change.