New Resource: aws_imagebuilder_distribution_configuration (#16180)
* Add aws_imagebuilder_component

* Add test for data_source_aws_imagebuilder_component

* Add aws_imagebuilder_infrastructureconfiguration

* Add aws_imagebuilder_recipe

* Rename to aws_imagebuilder_infrastructure_configuration

* Fix issue with infraconfig logging

* Fix incorrect MaxItems on res

* Fix S024

* Fix AWSR002

* Fix linting

* [#11084] Fix the imagebuilder resource, add test and docs

# Conflicts:
#	aws/provider.go

* Fix incorrect import on error handling

* Update to v2 SDK

* Fix R004 lint issue

* Remove changes to aws.erb

* Add imagebuilder_distribution_configuration

* Add imagebuilder_image_pipeline

* fixed some lint issues and fixed terminate_instance_on_failure not being set on create

* description can be updated in place

* service/imagebuilder: Remove non-aws_imagebuilder_distribution_configuration files

* New Resource: aws_imagebuilder_distribution_configuration

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/11084
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/13316
Reference: https://github.com/hashicorp/terraform-provider-aws/pull/13485

Changes:

```
* **New Data Source:** `aws_imagebuilder_distribution_configuration`
* **New Resource:** `aws_imagebuilder_distribution_configuration`
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_basic (23.95s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Description (39.52s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_disappears (18.57s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution (42.99s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_AmiTags (40.02s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_Description (39.36s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_KmsKeyId (46.31s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_LaunchPermission_UserGroups (23.66s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_LaunchPermission_UserIds (40.12s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_Name (39.12s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_TargetAccountIds (40.12s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_LicenseConfigurationArns (40.75s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Tags (49.75s)

--- PASS: TestAccAwsImageBuilderDistributionConfigurationDataSource_Arn (18.52s)
```

Output from acceptance testing in AWS GovCloud (US) (failure information: https://github.com/hashicorp/terraform-provider-aws/issues/16178):

```
--- FAIL: TestAccAwsImageBuilderDistributionConfiguration_Distribution_LicenseConfigurationArns (10.88s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_basic (27.00s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Description (40.22s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_disappears (21.76s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_AmiTags (42.09s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_Description (42.89s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_KmsKeyId (51.80s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_LaunchPermission_UserGroups (26.70s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_LaunchPermission_UserIds (41.44s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_Name (42.32s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Distribution_AmiDistributionConfiguration_TargetAccountIds (42.42s)
--- PASS: TestAccAwsImageBuilderDistributionConfiguration_Tags (55.37s)

--- PASS: TestAccAwsImageBuilderDistributionConfigurationDataSource_Arn (25.62s)
```

Output from sweeper in AWS Commercial:

```
2020/11/13 09:11:34 [DEBUG] Running Sweepers for region (us-west-2):
2020/11/13 09:11:34 [DEBUG] Running Sweeper (aws_imagebuilder_distribution_configuration) in region (us-west-2)
2020/11/13 09:11:37 Sweeper Tests ran successfully:
  - aws_imagebuilder_distribution_configuration
2020/11/13 09:11:37 [DEBUG] Running Sweepers for region (us-east-1):
2020/11/13 09:11:37 [DEBUG] Running Sweeper (aws_imagebuilder_distribution_configuration) in region (us-east-1)
2020/11/13 09:11:39 Sweeper Tests ran successfully:
  - aws_imagebuilder_distribution_configuration
ok    github.com/terraform-providers/terraform-provider-aws/aws 7.724s
```
Output from sweeper in AWS GovCloud (US):

```
2020/11/13 09:30:11 [DEBUG] Running Sweepers for region (us-gov-west-1):
2020/11/13 09:30:11 [DEBUG] Running Sweeper (aws_imagebuilder_distribution_configuration) in region (us-gov-west-1)
2020/11/13 09:30:14 Sweeper Tests ran successfully:
  - aws_imagebuilder_distribution_configuration
ok    github.com/terraform-providers/terraform-provider-aws/aws 4.971s
```

* docs/resource/aws_imagebuilder_distribution_configuration: Fix typo

Co-authored-by: Dogers <Dogers@users.noreply.github.com>
Co-authored-by: Jakub Kania <jakubkania@blackcat.rocks>
Co-authored-by: Bill Schneider <bill.schneider@optum.com>