fix: required field that was marked as optional
The `rule.noncurrent_version_expiration.noncurrent_days` field was
marked as optional in both the TF provider code and docs, but it is
actually required by AWS.

The [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html?icmpid=docs_amazons3_console#intro-lifecycle-rules-actions)
are not 100% clear on this, but attempting to create a
`aws_s3_bucket_lifecycle_configuration` without this field will result
in this error:

```
Error: creating S3 Lifecycle Configuration for bucket (<bucket_name>):
InvalidArgument: 'NoncurrentDays' for NoncurrentVersionExpiration action
must be a positive integer status code: 400, request id: <>, host id: <>
```