tests/data-source/aws_ami: Filter AMIs in TestAccAWSAmiDataSource_ownersEmpty
Previously this acceptance test was attempting to return all public AWS AMIs and occassionally OOMing or would pass with 600MB debug logs (yikes!):

=== RUN   TestAccAWSAmiDataSource_ownersEmpty

------- Stderr: -------
fatal error: runtime: out of memory

Now, we will continue to test for the owners = [""] regression, but also perform filtering of the AMI result set:

=== RUN   TestAccAWSAmiDataSource_ownersEmpty
--- PASS: TestAccAWSAmiDataSource_ownersEmpty (14.57s)