r/aws_vpc_security_group_ingress_rule: Add default_tags and ignore_tags tests.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccVPCSecurityGroupIngressRule_' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCSecurityGroupIngressRule_ -timeout 180m
=== RUN   TestAccVPCSecurityGroupIngressRule_basic
=== PAUSE TestAccVPCSecurityGroupIngressRule_basic
=== RUN   TestAccVPCSecurityGroupIngressRule_disappears
=== PAUSE TestAccVPCSecurityGroupIngressRule_disappears
=== RUN   TestAccVPCSecurityGroupIngressRule_tags
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag
=== RUN   TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag
=== RUN   TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
=== PAUSE TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
=== RUN   TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
=== PAUSE TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
=== RUN   TestAccVPCSecurityGroupIngressRule_ignoreTags
=== PAUSE TestAccVPCSecurityGroupIngressRule_ignoreTags
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv4
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv4
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== RUN   TestAccVPCSecurityGroupIngressRule_description
=== PAUSE TestAccVPCSecurityGroupIngressRule_description
=== RUN   TestAccVPCSecurityGroupIngressRule_prefixListID
=== PAUSE TestAccVPCSecurityGroupIngressRule_prefixListID
=== RUN   TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
=== PAUSE TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
=== RUN   TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
=== PAUSE TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
=== RUN   TestAccVPCSecurityGroupIngressRule_updateSourceType
=== PAUSE TestAccVPCSecurityGroupIngressRule_updateSourceType
=== CONT  TestAccVPCSecurityGroupIngressRule_basic
=== CONT  TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly
=== CONT  TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags
    vpc_security_group_ingress_rule_test.go:514: Step 2/3 error: After applying this test step, the plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_vpc_security_group_ingress_rule.test will be updated in-place
          ~ resource "aws_vpc_security_group_ingress_rule" "test" {
                id                     = "sgr-0b355a5c28413701c"
              - tags                   = {
                  - "key1" = "value1"
                } -> null
              ~ tags_all               = {
                  - "key1" = "value1" -> null
                }
                # (7 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- PASS: TestAccVPCSecurityGroupIngressRule_basic (52.10s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_duplicateTag (1.77s)
=== CONT  TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
--- FAIL: TestAccVPCSecurityGroupIngressRule_defaultAndIgnoreTags (56.06s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag
=== CONT  TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply
    vpc_security_group_ingress_rule_test.go:478: Step 1/3 error: Error running apply: exit status 1

        Error: Provider produced inconsistent final plan

        When expanding the plan for aws_vpc_security_group_ingress_rule.test to
        include new values learned so far during apply, provider
        "registry.terraform.io/hashicorp/aws" produced an invalid new value for
        .tags_all: new element "key1" has appeared.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToResourceOnly (69.42s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly
--- FAIL: TestAccVPCSecurityGroupIngressRule_updateTagsKnownAtApply (19.18s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTags_updateToProviderOnly (61.85s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTags_providerOnly (67.68s)
=== CONT  TestAccVPCSecurityGroupIngressRule_disappears
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_overlappingTag (100.23s)
=== CONT  TestAccVPCSecurityGroupIngressRule_prefixListID
--- PASS: TestAccVPCSecurityGroupIngressRule_disappears (64.15s)
=== CONT  TestAccVPCSecurityGroupIngressRule_updateSourceType
--- PASS: TestAccVPCSecurityGroupIngressRule_tags (92.67s)
=== CONT  TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
    acctest.go:645: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC (0.00s)
=== CONT  TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
--- PASS: TestAccVPCSecurityGroupIngressRule_prefixListID (110.35s)
=== CONT  TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag
--- PASS: TestAccVPCSecurityGroupIngressRule_updateSourceType (74.46s)
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv6
--- PASS: TestAccVPCSecurityGroupIngressRule_DefaultTagsProviderAndResource_nonOverlappingTag (69.04s)
=== CONT  TestAccVPCSecurityGroupIngressRule_description
--- PASS: TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID (109.01s)
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv4
--- PASS: TestAccVPCSecurityGroupIngressRule_cidrIPv6 (67.42s)
=== CONT  TestAccVPCSecurityGroupIngressRule_ignoreTags
    vpc_security_group_ingress_rule_test.go:551: Step 2/3 error: After applying this test step, the plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_vpc_security_group_ingress_rule.test will be updated in-place
          ~ resource "aws_vpc_security_group_ingress_rule" "test" {
                id                     = "sgr-0cd0557bd391113d3"
              - tags                   = {} -> null
                # (8 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccVPCSecurityGroupIngressRule_ignoreTags (81.58s)
--- PASS: TestAccVPCSecurityGroupIngressRule_cidrIPv4 (95.10s)
--- PASS: TestAccVPCSecurityGroupIngressRule_description (97.22s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	439.298s
FAIL
make: *** [testacc] Error 1