Acceptance test output:
% make testacc TESTARGS='-run=TestAccBedrockAgentCoreGatewayTarget_credentialProviderGatewayIAMRoleSigV4' PKG=bedrockagentcore
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Validating schemas
ok      github.com/hashicorp/terraform-provider-aws/internal/provider/sdkv2     (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/provider/framework (cached)
make: Running acceptance tests on branch: 🌿 HEAD 🌿...
TF_ACC=1 go1.26.3 test ./internal/service/bedrockagentcore/... -v -count 1 -parallel 20  -run=TestAccBedrockAgentCoreGatewayTarget_credentialProviderGatewayIAMRoleSigV4 -timeout 360m -vet=off -buildvcs=false
2026/05/29 11:25:14 Creating Terraform AWS Provider (SDKv2-style)...
2026/05/29 11:25:14 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccBedrockAgentCoreGatewayTarget_credentialProviderGatewayIAMRoleSigV4
=== PAUSE TestAccBedrockAgentCoreGatewayTarget_credentialProviderGatewayIAMRoleSigV4
=== CONT  TestAccBedrockAgentCoreGatewayTarget_credentialProviderGatewayIAMRoleSigV4
    gateway_target_test.go:534: Step 1/3 error: Error running apply: exit status 1

        Error: creating Bedrock AgentCore Gateway Target

          with aws_bedrockagentcore_gateway_target.test,
          on terraform_plugin_test.tf line 109, in resource "aws_bedrockagentcore_gateway_target" "test":
         109: resource "aws_bedrockagentcore_gateway_target" "test" {

        ID: L7ZEUIEXCH
        Cause: While waiting, unexpected state 'FAILED', wanted target 'READY'. last
        error: Failed to connect and fetch tools from the provided MCP target server.
        Error - {"jsonrpc": "2.0", "id": null, "error": {"code": -32700, "message":
        "Unsupported Media Type"}}"

--- FAIL: TestAccBedrockAgentCoreGatewayTarget_credentialProviderGatewayIAMRoleSigV4 (50.49s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagentcore   56.206s
FAIL
make: *** [testacc] Error 1