resource/aws_db_instance: During S3 restore, lower retry threshold for IAM eventual consistency from 5 minutes to 2 minutes and retry on additional error
IAM eventual consistency should only retry to up to 2 minutes instead of potentially retrying on permanent failures like a misconfigured IAM role for 5 minutes.

The additional IAM eventual consistency error was found via daily acceptance testing:

--- FAIL: TestAccAWSDBInstance_s3 (16.18s)
	testing.go:518: Step 0 error: Error applying: 1 error occurred:
			* aws_db_instance.s3: 1 error occurred:
			* aws_db_instance.s3: Error creating DB Instance: InvalidParameterValue: Files from the specified Amazon S3 bucket cannot be downloaded. Make sure that you have created an AWS Identity and Access Management (IAM) role that lets Amazon RDS access Amazon S3 for you.

Passes acceptance testing:

=== RUN   TestAccAWSDBInstance_s3
--- PASS: TestAccAWSDBInstance_s3 (763.92s)