Acceptance test output:
% make testacc TESTARGS='-run=TestAccLakeFormation_serial/OptIn/lfTag' PKG=lakeformation
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 t-aws_lakeformation_opt_in.resource_data.lf_tag 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/OptIn/lfTag -timeout 360m -vet=off
2026/03/16 11:37:23 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/16 11:37:23 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/OptIn
=== RUN   TestAccLakeFormation_serial/OptIn/lfTag
    opt_in_test.go:145: Step 1/1 error: Error running apply: exit status 1

        Error: creating AWS Lake Formation Opt In (arn:aws:iam::187416307283:role/tf-acc-test-7544501633864376339): operation error LakeFormation: CreateLakeFormationOptIn, 2 validation error(s) found.
        - missing required field, CreateLakeFormationOptInInput.Resource.LFTag.TagKey.
        - missing required field, CreateLakeFormationOptInInput.Resource.LFTag.TagValues.

          with aws_lakeformation_opt_in.test,
          on terraform_plugin_test.tf line 108, in resource "aws_lakeformation_opt_in" "test":
         108: resource "aws_lakeformation_opt_in" "test" {

        operation error LakeFormation: CreateLakeFormationOptIn, 2 validation
        error(s) found.
        - missing required field,
        CreateLakeFormationOptInInput.Resource.LFTag.TagKey.
        - missing required field,
        CreateLakeFormationOptInInput.Resource.LFTag.TagValues.

--- FAIL: TestAccLakeFormation_serial (16.95s)
    --- FAIL: TestAccLakeFormation_serial/OptIn (16.95s)
        --- FAIL: TestAccLakeFormation_serial/OptIn/lfTag (16.95s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	22.522s
FAIL
make: *** [testacc] Error 1