tests/service/worklink: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSWorkLinkFleet_Basic (0.52s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Worklink Fleet: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/createFleet: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSWorkLinkWorkLinkWebsiteCertificateAuthorityAssociation_DisplayName (2.40s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_OptimizeForEndUserLocation (2.40s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_DisplayName (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_Disappears (2.40s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkWorkLinkWebsiteCertificateAuthorityAssociation_Disappears (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_Basic (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkWorkLinkWebsiteCertificateAuthorityAssociation_Basic (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_Network (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_DeviceCaCertificate (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_AuditStreamArn (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSWorkLinkFleet_IdentityProvider (2.41s)
    resource_aws_worklink_fleet_test.go:350: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://worklink.us-gov-west-1.amazonaws.com/listFleets: dial tcp: lookup worklink.us-gov-west-1.amazonaws.com: no such host
```