tests/resource/aws_neptunce_cluster_instance: Add missing third availability zone from cluster configuration
Similar to RDS, Neptune requires clusters to have three availability zones if manually configured.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSNeptuneClusterInstance_withaz (865.51s)
    testing.go:538: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        DESTROY/CREATE: aws_neptune_cluster.default
...
          availability_zones.#:                 "3" => "2" (forces new resource)
          availability_zones.2050015877:        "us-west-2c" => "" (forces new resource)
          availability_zones.221770259:         "us-west-2b" => "us-west-2b"
          availability_zones.2487133097:        "us-west-2a" => "us-west-2a"
...
```

Output from acceptance testing:

```
--- PASS: TestAccAWSNeptuneClusterInstance_withaz (801.98s)
```