tests/resource/aws_cloud9_environment_ec2: Remove dependency on Default VPC and blacklist usw2-az4 (#11704)
Previously in the acceptance testing:

```
--- FAIL: TestAccAWSCloud9EnvironmentEc2_basic (660.80s)
    testing.go:640: Step 0 error: errors during apply:

        Error: timeout while waiting for state to become 'ready' (last state: 'connecting', timeout: 10m0s)
```

Without `subnet_id` configured, Cloud9 uses the Default VPC and has compatibility requirements such as permissive ingress NACL so the service can connect to the EC2 Instance. Rather than depending on a shared resource that will be potentially be affected by other acceptance testing, we prefer to always create a self-contained VPC for each test.

Output from acceptance testing:

```
--- PASS: TestAccAWSCloud9EnvironmentEc2_basic (212.49s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_allFields (302.97s)
```