resource/aws_emr_managed_scaling_policy: Ensure cluster_id attribute is saved during import and handle additional disappears cases
The Terraform Plugin SDK version 2.0.4 upgrade fixed something with `ImportStateVerify` testing, which now catches these arguments taht were not properly being set during `Read`.

The EMR API behavior seems to have changed since the initial resource release where it will now return an error on `GetManagedScalingPolicy` when the Cluster is shutting down or finished and not returning an error when the policy has been removed. This change set updates the `Read` logic to handle these two new scenarios.

The test configuration change to include `keep_job_flow_alive_when_no_steps` is to ensure the EMR Cluster shutting down is not because it has no pre-defined steps to execute and prevent any inconsistent behaviors because of that timing.

Previously:

```
=== CONT  TestAccAwsEmrManagedScalingPolicy_basic
TestAccAwsEmrManagedScalingPolicy_basic: resource_aws_emr_managed_scaling_policy_test.go:17: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=10) "cluster_id": (string) (len=15) "j-16JIKGI1IWJ4W"
}
TestAccAwsEmrManagedScalingPolicy_basic: testing_new.go:62: Error running post-test destroy, there may be dangling resources: ValidationException: A job flow that is shutting down, terminated, or finished may not be modified.
  status code: 400, request id: d29fc848-2bcc-459c-ad4a-bb4b09f90060
--- FAIL: TestAccAwsEmrManagedScalingPolicy_basic (480.77s)

=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits
TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits: resource_aws_emr_managed_scaling_policy_test.go:41: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=10) "cluster_id": (string) (len=15) "j-3Q9RF3NQJGV46"
}
TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits: testing_new.go:62: Error running post-test destroy, there may be dangling resources: ValidationException: A job flow that is shutting down, terminated, or finished may not be modified.
  status code: 400, request id: 3faa75d9-7536-4289-9684-4ea6a13f2bfa
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits (457.36s)

=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits
TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits: resource_aws_emr_managed_scaling_policy_test.go:65: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=10) "cluster_id": (string) (len=14) "j-9DEX7HNVJG1N"
}
TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits: testing_new.go:62: Error running post-test destroy, there may be dangling resources: ValidationException: A job flow that is shutting down, terminated, or finished may not be modified.
  status code: 400, request id: 712836ec-ab7e-4f9f-95ed-413fd9a7729c
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (474.25s)

=== CONT  TestAccAwsEmrManagedScalingPolicy_disappears
TestAccAwsEmrManagedScalingPolicy_disappears: resource_aws_emr_managed_scaling_policy_test.go:89: Step 1/1 error: Expected a non-empty plan, but got an empty plan!
TestAccAwsEmrManagedScalingPolicy_disappears: testing_new.go:62: Error running post-test destroy, there may be dangling resources: ValidationException: A job flow that is shutting down, terminated, or finished may not be modified.
  status code: 400, request id: 98a29b6f-3c80-47ca-99ac-3f870426a93c
--- FAIL: TestAccAwsEmrManagedScalingPolicy_disappears (483.72s)
```

Output from acceptance testing:

```
--- PASS: TestAccAwsEmrManagedScalingPolicy_disappears (453.77s)
--- PASS: TestAccAwsEmrManagedScalingPolicy_basic (456.74s)
--- PASS: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumCoreCapacityUnits (467.67s)
--- PASS: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (490.01s)
```