data-source/aws_vpc_endpoint_service: Keep non-filtered aws_availability_zones data source configuration
Since the expected return value of availability_zones applies to all Availability Zones and Local Zones:

```
--- FAIL: TestAccDataSourceAwsVpcEndpointService_gateway (6.13s)
    testing.go:654: Step 0 error: Check failed: Check 3/10 error: data.aws_vpc_endpoint_service.test: Attribute 'availability_zones.#' expected "4", got "5"
```

Output from acceptance testing:

```
--- PASS: TestAccDataSourceAwsVpcEndpointService_gateway (15.03s)
```