tests/resource/aws_emr_cluster: Use configuration block syntax for instance_group name argument test configuration
Previously, the test configuration was relying on undocumented behavior with using a list variable to assign the instance_group configuration blocks. The acceptance testing framework in the Terraform 0.12 Provider SDK rightfully notes the unexpected handling of the variable:

```
--- FAIL: TestAccAWSEMRCluster_instance_group_names (0.84s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test731826738/main.tf:4,13-39,4: Invalid default value for variable; This default value is not compatible with the variable's type constraint: all list elements must have the same type.
```

Since this test is valuable (no others are testing the `name` argument within `instance_group` configuration blocks), we update the test configuration syntax to use configuration blocks in a backwards and forwards compatible manner.

Output from Terraform 0.11 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSEMRCluster_instance_group_names (580.28s)
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAWSEMRCluster_instance_group_names (420.79s)
```