tests/service/mq: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSMqBroker_basic (2.63s)
    testing.go:568: Step 0 error: errors during apply:

        Error: RequestError: send request failed
        caused by: Post https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSMqBroker_basic (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqBroker_allFieldsCustomVpc (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqConfiguration_updateTags (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqBroker_updateUsers (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqConfiguration_withData (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqBroker_allFieldsDefaultVpc (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqConfiguration_basic (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMqBroker_updateTags (2.41s)
    resource_aws_mq_broker_test.go:648: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://mq.us-gov-west-1.amazonaws.com/v1/brokers: dial tcp: lookup mq.us-gov-west-1.amazonaws.com: no such host
```