tests/resource/aws_security_group: Allow security group rules per group limit to be configurable via environment variable
EC2 regions may manually or automatically had their rules per group limit increased, which will cause the acceptance tests to fail expecting the limit errors at the wrong value. Unfortunately, there is no EC2 or Trusted Advisor API lookup for this particular limit so for now we will allow configuration via `EC2_SECURITY_GROUP_RULES_PER_GROUP_LIMIT` environment variable or it will default to 50.

Previously:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSecurityGroup_ruleLimit'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_ruleLimit -timeout 120m
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededAppend (45.77s)
    testing.go:508: Step 1, no error received, but expected a match to:

        RulesPerSecurityGroupLimitExceeded

=== RUN   TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- FAIL: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (43.41s)
    testing.go:508: Step 1, no error received, but expected a match to:

        RulesPerSecurityGroupLimitExceeded

=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (46.29s)
    testing.go:508: Step 1, no error received, but expected a match to:

        RulesPerSecurityGroupLimitExceeded

=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAllNew
--- FAIL: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (44.27s)
    testing.go:508: Step 1, no error received, but expected a match to:

        RulesPerSecurityGroupLimitExceeded

FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	180.597s
```

Now (in EC2 region with 60 limit):

```
$ export EC2_SECURITY_GROUP_RULES_PER_GROUP_LIMIT=60
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSecurityGroup_ruleLimit'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSSecurityGroup_ruleLimit -timeout 120m
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAppend (69.34s)
=== RUN   TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend
--- PASS: TestAccAWSSecurityGroup_ruleLimitCidrBlockExceededAppend (57.70s)
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededPrepend
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededPrepend (54.87s)
=== RUN   TestAccAWSSecurityGroup_ruleLimitExceededAllNew
--- PASS: TestAccAWSSecurityGroup_ruleLimitExceededAllNew (53.67s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	236.333s
```