tests/service/kinesisanalytics: Add PreCheck for service availablility
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSKinesisAnalyticsApplication_basic (1.04s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Unable to create Kinesis Analytics application: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSKinesisAnalyticsApplication_outputsMultiple (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_referenceDataSource (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_outputsKinesisStream (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Add (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_updateCloudwatchLoggingOptions (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_inputsKinesisFirehose (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_Outputs_Lambda_Create (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_outputsAdd (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_inputsUpdateKinesisStream (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_outputsUpdateKinesisStream (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_tags (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_inputsAdd (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_addCloudwatchLoggingOptions (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_update (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_referenceDataSourceUpdate (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_inputsKinesisStream (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSKinesisAnalyticsApplication_basic (2.45s)
    resource_aws_kinesis_analytics_application_test.go:695: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://kinesisanalytics.us-gov-west-1.amazonaws.com/: dial tcp: lookup kinesisanalytics.us-gov-west-1.amazonaws.com: no such host
```