tests/service/cloudfront: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSCloudFrontDistribution_S3Origin (2.34s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating CloudFront Distribution: RequestError: send request failed
        caused by: Post https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution?WithTags=: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn_ConflictsWithCloudFrontDefaultCertificate (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_WaitForDeployment (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Headers (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontPublicKey_basic (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Headers (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_RetainOnDelete (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontOriginAccessIdentity_basic (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_Enabled (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontOriginAccessIdentity_importBasic (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontPublicKey_update (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontOriginAccessIdentity_noComment (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_OriginGroups (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_Origin_EmptyOriginID (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_disappears (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontPublicKey_namePrefix (3.27s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_HTTP11Config (1.88s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_customOrigin (1.89s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_multiOrigin (1.91s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_S3OriginWithTags (1.93s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_S3Origin (1.98s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (1.98s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_Origin_EmptyDomainName (1.99s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (2.03s)
    resource_aws_cloudfront_distribution_test.go:1022: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://cloudfront.us-gov-west-1.amazonaws.com/2018-11-05/distribution: dial tcp: lookup cloudfront.us-gov-west-1.amazonaws.com: no such host
```