tests/service/ses: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSSESDomainIdentity_basic (2.91s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error requesting SES domain identity verification: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSSESEventDestination_basic (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESReceiptRule_order (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESActiveReceiptRuleSet_basic (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESReceiptRuleSet_basic (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSesTemplate_Import (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESReceiptRule_s3Action (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSesDomainIdentityVerification_timeout (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainMailFrom_disappears_Identity (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESReceiptFilter_basic (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainMailFrom_behaviorOnMxFailure (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESEmailIdentity_trailingPeriod (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESReceiptRule_basic (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESReceiptRule_actions (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSesDomainIdentityVerification_nonexistent (2.47s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainIdentity_trailingPeriod (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESEmailIdentity_basic (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSESIdentityNotificationTopic_basic (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainMailFrom_disappears (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSesTemplate_Basic (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainMailFrom_basic (2.48s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainDkim_basic (2.99s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainIdentity_basic (2.99s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESConfigurationSet_basic (2.99s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSSESDomainIdentity_disappears (3.17s)
    resource_aws_ses_domain_identity_test.go:184: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://email.us-gov-west-1.amazonaws.com/: dial tcp: lookup email.us-gov-west-1.amazonaws.com: no such host
```