Remove MaxItems for profile_properties due to error
--- FAIL: TestProvider (0.17s)
    provider_test.go:22: err: 1 error occurred:
        	* resource aws_appflow_connector_profile: profile_properties: MaxItems and MinItems are only supported on lists or sets