resource/aws_launch_configuration: Fix regression from version 2.22.0 with instance store AMIs returning an unexpected error (#9810)
New test prior to fix:

```
--- FAIL: TestAccAWSLaunchConfiguration_withInstanceStoreAMI (13.84s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Instance store backed AMIs do not provide a root device name - Use an EBS AMI
```

Output from acceptance testing:

```
--- PASS: TestAccAWSLaunchConfiguration_withSpotPrice (19.05s)
--- PASS: TestAccAWSLaunchConfiguration_withInstanceStoreAMI (20.40s)
--- PASS: TestAccAWSLaunchConfiguration_withBlockDevices (20.90s)
--- PASS: TestAccAWSLaunchConfiguration_withEncryption (21.66s)
--- PASS: TestAccAWSLaunchConfiguration_ebs_noDevice (21.67s)
--- PASS: TestAccAWSLaunchConfiguration_withIAMProfile (29.41s)
--- PASS: TestAccAWSLaunchConfiguration_encryptedRootBlockDevice (34.32s)
--- PASS: TestAccAWSLaunchConfiguration_basic (35.35s)
--- PASS: TestAccAWSLaunchConfiguration_userData (37.26s)
--- PASS: TestAccAWSLaunchConfiguration_updateEbsBlockDevices (37.48s)
--- PASS: TestAccAWSLaunchConfiguration_updateRootBlockDevice (39.25s)
--- PASS: TestAccAWSLaunchConfiguration_withVpcClassicLink (39.58s)
```