tests/resource/aws_kinesis_firehose_delivery_stream: Ensure configuration is partition agnostic and fix ExpectError checks
Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (653.45s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Deserializer_Update (215.70s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Enabled (189.37s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_HiveJsonSerDe_Empty (182.29s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_OpenXJsonSerDe_Empty (165.26s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_OrcSerDe_Empty (154.40s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_ParquetSerDe_Empty (143.67s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Serializer_Update (191.00s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_ErrorOutputPrefix (156.16s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (209.33s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (38.37s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (38.40s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (241.14s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (207.75s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_importBasic (157.08s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration (198.34s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (724.35s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basic (184.91s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basicWithTags (244.73s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates (287.46s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource (128.86s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging (159.12s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (203.12s)
```

Output from acceptance testing in AWS GovCloud (US) (the failures will require a non-trivial `PreCheck` function):

```
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (839.83s)
--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Deserializer_Update (25.71s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Enabled (27.14s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_HiveJsonSerDe_Empty (26.12s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_OpenXJsonSerDe_Empty (23.92s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_OrcSerDe_Empty (23.87s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_ParquetSerDe_Empty (23.21s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Serializer_Update (25.91s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Firehose record format conversion is not available in the current region.

--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_ErrorOutputPrefix (121.55s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (129.95s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (36.08s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (34.17s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (150.64s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (144.37s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_importBasic (129.66s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration (99.24s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (565.82s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basic (115.40s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basicWithTags (163.68s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates (203.74s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource (130.98s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging (111.15s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (150.08s)
```