tests/service/cloud9: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSCloud9EnvironmentEc2_basic (0.80s)
    testing.go:568: Step 0 error: errors during apply:

        Error: RequestError: send request failed
        caused by: Post https://cloud9.us-gov-west-1.amazonaws.com/: dial tcp: lookup cloud9.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSCloud9EnvironmentEc2_allFields (2.35s)
    resource_aws_cloud9_environment_ec2_test.go:191: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cloud9.us-gov-west-1.amazonaws.com/: dial tcp: lookup cloud9.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloud9EnvironmentEc2_basic (2.35s)
    resource_aws_cloud9_environment_ec2_test.go:191: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cloud9.us-gov-west-1.amazonaws.com/: dial tcp: lookup cloud9.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCloud9EnvironmentEc2_importBasic (2.35s)
    resource_aws_cloud9_environment_ec2_test.go:191: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cloud9.us-gov-west-1.amazonaws.com/: dial tcp: lookup cloud9.us-gov-west-1.amazonaws.com: no such host
```