data-source/aws_glue_script: Provide full example and test configurations
During original development, the configuration of a working setup with dag_edges and dag_nodes was unknown. It turns out a working configuration is required for Terraform 0.12 anyways since the previous empty list syntax (`= []`) is incompatible with the configuration parser and is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccDataSourceAWSGlueScript_Language_Python (0.58s)
    testing.go:568: Step 0 error: config is invalid: 4 problems:

        - Unsupported argument: An argument named "dag_edge" is not expected here. Did you mean to define a block of type "dag_edge"?
        - Unsupported argument: An argument named "dag_node" is not expected here. Did you mean to define a block of type "dag_node"?
        - Insufficient dag_edge blocks: At least 1 "dag_edge" blocks are required.
        - Insufficient dag_node blocks: At least 1 "dag_node" blocks are required.

--- FAIL: TestAccDataSourceAWSGlueScript_Language_Scala (0.58s)
    testing.go:568: Step 0 error: config is invalid: 4 problems:

        - Unsupported argument: An argument named "dag_edge" is not expected here. Did you mean to define a block of type "dag_edge"?
        - Unsupported argument: An argument named "dag_node" is not expected here. Did you mean to define a block of type "dag_node"?
        - Insufficient dag_edge blocks: At least 1 "dag_edge" blocks are required.
        - Insufficient dag_node blocks: At least 1 "dag_node" blocks are required.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccDataSourceAWSGlueScript_Language_Scala (11.56s)
--- PASS: TestAccDataSourceAWSGlueScript_Language_Python (11.68s)
```