tests/service/ec2: Blacklist usw2-az4 zone ID for EC2 Transit Gateway acceptance testing
AWS recently added a fourth Availability Zone to the US West (Oregon) Region, which does not yet support EC2 Transit Gateway. This new AZ has the zone ID of `usw2-az4` and here we blacklist it to prevent random acceptance testing failures due to random AZ selection for VPC subnets.

Previous output from acceptance testing (due to randomized AZ selection potentially including usw2-az4):

```
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_DnsSupport
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_Ipv6Support
=== CONT  TestAccAWSRoute_TransitGatewayID_DestinationCidrBlock
--- PASS: TestAccAWSRoute_TransitGatewayID_DestinationCidrBlock (335.39s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTablePropagation
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_DnsSupport (338.24s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_Tags
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter (343.74s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_SubnetIds
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_Ipv6Support (373.39s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociation
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociation (138.80s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating EC2 Transit Gateway VPC Attachment: IncorrectState: Transit Gateway is not available in availability zone us-west-2d (subnet subnet-02fadf209fbcea990).
          status code: 400, request id: d3dab975-9fd1-498f-96b5-4a25c35e766e

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test833613409/main.tf line 21:
          (source code not available)

=== CONT  TestAccAWSEc2TransitGatewayRoute_disappears_TransitGatewayAttachment
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_Tags (354.65s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_disappears
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTablePropagation (361.32s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociationAndPropagationDisabled
--- PASS: TestAccAWSEc2TransitGatewayRoute_disappears_TransitGatewayAttachment (300.08s)
=== CONT  TestAccAWSEc2TransitGatewayRoute_basic
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_SubnetIds (472.20s)
=== CONT  TestAccAWSEc2TransitGatewayRoute_disappears
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachment_disappears (159.14s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating EC2 Transit Gateway VPC Attachment: IncorrectState: Transit Gateway is not available in availability zone us-west-2d (subnet subnet-0e42651c64da6948d).
          status code: 400, request id: 01a3bd02-49a9-4e51-9209-29c4ea3bda57

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test261015898/main.tf line 21:
          (source code not available)

=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_basic
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociationAndPropagationDisabled (244.74s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_ID
--- FAIL: TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_ID (162.97s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating EC2 Transit Gateway VPC Attachment: IncorrectState: Transit Gateway is not available in availability zone us-west-2d (subnet subnet-0696ec949e8fc2f35).
          status code: 400, request id: 6ebf453e-341d-4305-b6ed-fb9a6e9df73e

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test789981369/main.tf line 21:
          (source code not available)

--- PASS: TestAccAWSEc2TransitGatewayRoute_basic (305.49s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_basic (321.71s)
--- PASS: TestAccAWSEc2TransitGatewayRoute_disappears (360.25s)
```

Output from acceptance testing:

```
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_Ipv6Support
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_DnsSupport
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_disappears
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_disappears (339.47s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_basic
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_DnsSupport (358.09s)
=== CONT  TestAccAWSEc2TransitGatewayRoute_disappears_TransitGatewayAttachment
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_Ipv6Support (365.36s)
=== CONT  TestAccAWSEc2TransitGatewayRoute_disappears
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter (366.51s)
=== CONT  TestAccAWSEc2TransitGatewayRoute_basic
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_basic (315.36s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_ID
--- PASS: TestAccAWSEc2TransitGatewayRoute_disappears (293.49s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociation
--- PASS: TestAccAWSEc2TransitGatewayRoute_disappears_TransitGatewayAttachment (341.21s)
=== CONT  TestAccAWSRoute_TransitGatewayID_DestinationCidrBlock
--- PASS: TestAccAWSEc2TransitGatewayRoute_basic (354.87s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTablePropagation
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_ID (303.98s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_Tags
--- PASS: TestAccAWSRoute_TransitGatewayID_DestinationCidrBlock (324.51s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociationAndPropagationDisabled
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociation (417.19s)
=== CONT  TestAccAWSEc2TransitGatewayVpcAttachment_SubnetIds
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTablePropagation (354.84s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociationAndPropagationDisabled (271.61s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_Tags (360.89s)
--- PASS: TestAccAWSEc2TransitGatewayVpcAttachment_SubnetIds (488.30s)
```