tests/resource/aws_lb_listener_rule: Various Terraform 0.12 syntax and test fixes
These changes are backwards compatible with Terraform 0.11.

Changes:
* tests/resource/aws_lb_listener_rule: Ensure authentication_request_extra_params configurations use equals
* tests/resource/aws_lb_listener_rule: Temporarily use expanded subnets references
* tests/resource/aws_lb_listener_rule: Fix resource name typo in TestAccAWSLBListenerRuleBackwardsCompatibility TestCheck (unrelated to syntax fixes but previously failing)
* tests/resource/aws_lb_listener_rule: Fix resource naming in TestAccAWSLBListenerRule_priority configurations

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSLBListenerRuleBackwardsCompatibility (208.64s)
    testing.go:568: Step 0 error: Check failed: 1 error occurred:
          * Check 6/14 error: Not found: aws_lb_listener_rule.static in [root]

--- FAIL: TestAccAWSLBListenerRule_priority (323.18s)
    testing.go:568: Step 5 error: /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test460870076/main.tf:95,33-40: Invalid resource name; A name must start with a letter and may contain only letters, digits, underscores, and dashes.

--- FAIL: TestAccAWSLBListenerRule_basic (3.94s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test013185120/main.tf line 31:
          (source code not available)

        Inappropriate value for attribute "subnets": element 0: string required.

--- FAIL: TestAccAWSLBListenerRule_cognito (0.94s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "authentication_request_extra_params" are not expected here. Did you mean to define argument "authentication_request_extra_params"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSLBListenerRule_Action_Order (240.96s)
--- PASS: TestAccAWSLBListenerRule_Action_Order_Recreates (234.45s)
--- PASS: TestAccAWSLBListenerRule_basic (237.02s)
--- PASS: TestAccAWSLBListenerRule_changeListenerRuleArnForcesNew (250.64s)
--- PASS: TestAccAWSLBListenerRule_cognito (240.74s)
--- PASS: TestAccAWSLBListenerRule_fixedResponse (185.82s)
--- PASS: TestAccAWSLBListenerRule_multipleConditionThrowsError (2.06s)
--- PASS: TestAccAWSLBListenerRule_oidc (235.37s)
--- PASS: TestAccAWSLBListenerRule_priority (380.15s)
--- PASS: TestAccAWSLBListenerRule_redirect (258.12s)
--- PASS: TestAccAWSLBListenerRule_updateRulePriority (250.87s)
--- PASS: TestAccAWSLBListenerRuleBackwardsCompatibility (216.63s)
```