tests/resource/aws_eks_node_group: Fix version test to use version from aws_eks_cluster reference
The EKS Cluster would spin up with the latest Kubernetes version while the Node Group could be hardcoded multiple behind. The EKS API unfortunately does not provide a lookup API for versioning yet.

Previously:

```
Error: error creating EKS Node Group (tf-acc-test-1420558841397012520:tf-acc-test-1420558841397012520): InvalidParameterException: Nodegroup Kubernetes version should be equal to Cluster kubernetes version 1.16 or be behind be 1
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEksNodeGroup_Version (1630.32s)
```