tests/service/mediastore: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSMediaStoreContainer_basic (1.48s)
    testing.go:568: Step 0 error: errors during apply:

        Error: RequestError: send request failed
        caused by: Post https://mediastore.us-gov-west-1.amazonaws.com/: dial tcp: lookup mediastore.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSMediaStoreContainerPolicy_import (2.40s)
    resource_aws_media_store_container_test.go:104: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://mediastore.us-gov-west-1.amazonaws.com/: dial tcp: lookup mediastore.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMediaStoreContainer_import (2.40s)
    resource_aws_media_store_container_test.go:104: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://mediastore.us-gov-west-1.amazonaws.com/: dial tcp: lookup mediastore.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMediaStoreContainer_basic (2.40s)
    resource_aws_media_store_container_test.go:104: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://mediastore.us-gov-west-1.amazonaws.com/: dial tcp: lookup mediastore.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSMediaStoreContainerPolicy_basic (2.40s)
    resource_aws_media_store_container_test.go:104: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://mediastore.us-gov-west-1.amazonaws.com/: dial tcp: lookup mediastore.us-gov-west-1.amazonaws.com: no such host
```