r/aws_swf_domain: Switch to 'WithoutTimeout' CRUD handlers (#15090).
Acceptance test output:

% SWF_DOMAIN_TESTING_ENABLED=1 make testacc TESTARGS='-run=TestAccSWFDomain_' PKG=swf ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/swf/... -v -count 1 -parallel 3  -run=TestAccSWFDomain_ -timeout 180m
=== RUN   TestAccSWFDomain_basic
=== PAUSE TestAccSWFDomain_basic
=== RUN   TestAccSWFDomain_nameGenerated
=== PAUSE TestAccSWFDomain_nameGenerated
=== RUN   TestAccSWFDomain_namePrefix
=== PAUSE TestAccSWFDomain_namePrefix
=== RUN   TestAccSWFDomain_tags
=== PAUSE TestAccSWFDomain_tags
=== RUN   TestAccSWFDomain_description
=== PAUSE TestAccSWFDomain_description
=== CONT  TestAccSWFDomain_basic
=== CONT  TestAccSWFDomain_tags
=== CONT  TestAccSWFDomain_description
=== CONT  TestAccSWFDomain_basic
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: SWF Domain still exists: tf-acc-test-1774128667268811585
--- FAIL: TestAccSWFDomain_basic (20.57s)
=== CONT  TestAccSWFDomain_namePrefix
--- PASS: TestAccSWFDomain_description (20.60s)
=== CONT  TestAccSWFDomain_nameGenerated
--- PASS: TestAccSWFDomain_namePrefix (18.67s)
=== CONT  TestAccSWFDomain_nameGenerated
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: SWF Domain still exists: terraform-20221025211814901400000002
--- FAIL: TestAccSWFDomain_nameGenerated (18.78s)
=== CONT  TestAccSWFDomain_tags
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: SWF Domain still exists: tf-acc-test-3544784691361893861
--- FAIL: TestAccSWFDomain_tags (44.95s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/swf	48.975s
FAIL
make: *** [testacc] Error 1