Acceptance test output:
% make testacc TESTARGS='-run=TestAccS3BucketLifecycleConfiguration_' PKG=s3 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 2  -run=TestAccS3BucketLifecycleConfiguration_ -timeout 360m
=== RUN   TestAccS3BucketLifecycleConfiguration_basic
=== PAUSE TestAccS3BucketLifecycleConfiguration_basic
=== RUN   TestAccS3BucketLifecycleConfiguration_disappears
=== PAUSE TestAccS3BucketLifecycleConfiguration_disappears
=== RUN   TestAccS3BucketLifecycleConfiguration_filterWithPrefix
=== PAUSE TestAccS3BucketLifecycleConfiguration_filterWithPrefix
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThan
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThan
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThanZero
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThanZero
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeLessThan
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeLessThan
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRange
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRange
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix
=== RUN   TestAccS3BucketLifecycleConfiguration_disableRule
=== PAUSE TestAccS3BucketLifecycleConfiguration_disableRule
=== RUN   TestAccS3BucketLifecycleConfiguration_multipleRules
=== PAUSE TestAccS3BucketLifecycleConfiguration_multipleRules
=== RUN   TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix
=== PAUSE TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix
=== RUN   TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration
=== PAUSE TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration
=== RUN   TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition
=== PAUSE TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition
=== RUN   TestAccS3BucketLifecycleConfiguration_prefix
=== PAUSE TestAccS3BucketLifecycleConfiguration_prefix
=== RUN   TestAccS3BucketLifecycleConfiguration_Filter_Tag
=== PAUSE TestAccS3BucketLifecycleConfiguration_Filter_Tag
=== RUN   TestAccS3BucketLifecycleConfiguration_RuleExpiration_expireMarkerOnly
=== PAUSE TestAccS3BucketLifecycleConfiguration_RuleExpiration_expireMarkerOnly
=== RUN   TestAccS3BucketLifecycleConfiguration_RuleExpiration_emptyBlock
=== PAUSE TestAccS3BucketLifecycleConfiguration_RuleExpiration_emptyBlock
=== RUN   TestAccS3BucketLifecycleConfiguration_ruleAbortIncompleteMultipartUpload
=== PAUSE TestAccS3BucketLifecycleConfiguration_ruleAbortIncompleteMultipartUpload
=== RUN   TestAccS3BucketLifecycleConfiguration_TransitionDate_standardIa
=== PAUSE TestAccS3BucketLifecycleConfiguration_TransitionDate_standardIa
=== RUN   TestAccS3BucketLifecycleConfiguration_TransitionDate_intelligentTiering
=== PAUSE TestAccS3BucketLifecycleConfiguration_TransitionDate_intelligentTiering
=== RUN   TestAccS3BucketLifecycleConfiguration_TransitionStorageClassOnly_intelligentTiering
=== PAUSE TestAccS3BucketLifecycleConfiguration_TransitionStorageClassOnly_intelligentTiering
=== RUN   TestAccS3BucketLifecycleConfiguration_TransitionZeroDays_intelligentTiering
=== PAUSE TestAccS3BucketLifecycleConfiguration_TransitionZeroDays_intelligentTiering
=== RUN   TestAccS3BucketLifecycleConfiguration_TransitionUpdateBetweenDaysAndDate_intelligentTiering
=== PAUSE TestAccS3BucketLifecycleConfiguration_TransitionUpdateBetweenDaysAndDate_intelligentTiering
=== RUN   TestAccS3BucketLifecycleConfiguration_EmptyFilter_NonCurrentVersions
=== PAUSE TestAccS3BucketLifecycleConfiguration_EmptyFilter_NonCurrentVersions
=== RUN   TestAccS3BucketLifecycleConfiguration_migrate_noChange
=== PAUSE TestAccS3BucketLifecycleConfiguration_migrate_noChange
=== RUN   TestAccS3BucketLifecycleConfiguration_migrate_withChange
=== PAUSE TestAccS3BucketLifecycleConfiguration_migrate_withChange
=== RUN   TestAccS3BucketLifecycleConfiguration_Update_filterWithAndToFilterWithPrefix
=== PAUSE TestAccS3BucketLifecycleConfiguration_Update_filterWithAndToFilterWithPrefix
=== CONT  TestAccS3BucketLifecycleConfiguration_basic
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_Tag
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_Tag (100.06s)
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix
--- PASS: TestAccS3BucketLifecycleConfiguration_basic (100.09s)
=== CONT  TestAccS3BucketLifecycleConfiguration_prefix
--- PASS: TestAccS3BucketLifecycleConfiguration_prefix (100.43s)
=== CONT  TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRangeAndPrefix (100.49s)
=== CONT  TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration
    bucket_lifecycle_configuration_test.go:460: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_s3_bucket_lifecycle_configuration.test will be updated in-place
          ~ resource "aws_s3_bucket_lifecycle_configuration" "test" {
                id     = "tf-acc-test-4965495481173498595"
                # (1 unchanged attribute hidden)

              ~ rule {
                    id     = "tf-acc-test-4965495481173498595"
                    # (1 unchanged attribute hidden)

                  ~ noncurrent_version_expiration {
                      - newer_noncurrent_versions = "0" -> null
                        # (1 unchanged attribute hidden)
                    }
                    # (1 unchanged block hidden)
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
=== NAME  TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition
    bucket_lifecycle_configuration_test.go:490: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_s3_bucket_lifecycle_configuration.test will be updated in-place
          ~ resource "aws_s3_bucket_lifecycle_configuration" "test" {
                id     = "tf-acc-test-7612092602594875830"
                # (1 unchanged attribute hidden)

              ~ rule {
                    id     = "tf-acc-test-7612092602594875830"
                    # (1 unchanged attribute hidden)

                  + noncurrent_version_transition {
                      + noncurrent_days = 30
                      + storage_class   = "STANDARD_IA"
                    }
                  + noncurrent_version_transition {
                      + noncurrent_days = 60
                      + storage_class   = "GLACIER"
                    }
                  - noncurrent_version_transition {
                      - newer_noncurrent_versions = "0" -> null
                      - noncurrent_days           = 30 -> null
                      - storage_class             = "STANDARD_IA" -> null
                    }
                  - noncurrent_version_transition {
                      - newer_noncurrent_versions = "0" -> null
                      - noncurrent_days           = 60 -> null
                      - storage_class             = "GLACIER" -> null
                    }
                    # (1 unchanged block hidden)
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionExpiration (68.85s)
=== CONT  TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix
--- FAIL: TestAccS3BucketLifecycleConfiguration_nonCurrentVersionTransition (85.58s)
=== CONT  TestAccS3BucketLifecycleConfiguration_multipleRules
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules_noFilterOrPrefix (98.30s)
=== CONT  TestAccS3BucketLifecycleConfiguration_disableRule
--- PASS: TestAccS3BucketLifecycleConfiguration_multipleRules (100.67s)
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThanZero
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThanZero (99.58s)
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRange
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeRange (96.73s)
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeLessThan
--- PASS: TestAccS3BucketLifecycleConfiguration_disableRule (244.66s)
=== CONT  TestAccS3BucketLifecycleConfiguration_filterWithPrefix
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeLessThan (97.78s)
=== CONT  TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThan
--- PASS: TestAccS3BucketLifecycleConfiguration_Filter_ObjectSizeGreaterThan (97.88s)
=== CONT  TestAccS3BucketLifecycleConfiguration_TransitionZeroDays_intelligentTiering
    bucket_lifecycle_configuration_test.go:819: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-9165865021835932531) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: X4W0GXTB0QZ2JGBV, HostID: FNDkzhR6T7YNf/seXN6vdz3W96dhZ2bePRKJMpEy1iwnhkVYVxzoCguiVpjsDy6MBA9v7QxKX+c=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_TransitionZeroDays_intelligentTiering (13.94s)
=== CONT  TestAccS3BucketLifecycleConfiguration_Update_filterWithAndToFilterWithPrefix
--- PASS: TestAccS3BucketLifecycleConfiguration_filterWithPrefix (183.31s)
=== CONT  TestAccS3BucketLifecycleConfiguration_migrate_withChange
    bucket_lifecycle_configuration_test.go:957: Step 2/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-1503829699562242896) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: FEM32EGQPX41QXAZ, HostID: 18nLnu4lVjrdYeyV4SXwVytgcMSP6zEhPBoZFGMdHdm2FgmDj61OcCnTwkWSrct1g3w54K6SPe8=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_migrate_withChange (32.60s)
=== CONT  TestAccS3BucketLifecycleConfiguration_migrate_noChange
--- PASS: TestAccS3BucketLifecycleConfiguration_migrate_noChange (112.77s)
=== CONT  TestAccS3BucketLifecycleConfiguration_EmptyFilter_NonCurrentVersions
--- PASS: TestAccS3BucketLifecycleConfiguration_Update_filterWithAndToFilterWithPrefix (156.42s)
=== CONT  TestAccS3BucketLifecycleConfiguration_TransitionUpdateBetweenDaysAndDate_intelligentTiering
    bucket_lifecycle_configuration_test.go:848: Step 1/4 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-3796608410946237470) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: 3G0VMQB8E5Q70AC6, HostID: JBa9uAldw2aGG7GCD+KylH0wnUFS62ooIOaDgXFUOYS8v/M+7VwMS4lPLFi5+MWyBfL9QSuwksgDhrI0FojW0w==, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_TransitionUpdateBetweenDaysAndDate_intelligentTiering (13.43s)
=== CONT  TestAccS3BucketLifecycleConfiguration_TransitionDate_standardIa
    bucket_lifecycle_configuration_test.go:728: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-4522327737322788276) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: 7V8BDM0GS79AR1MD, HostID: HH01lNRsJIzXBv4JyRGMp8mA+YBHII47GySEATuwrFZs2XWP7GIZvDr9XELtXD6bYxO11LNewCQ=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_TransitionDate_standardIa (13.61s)
=== CONT  TestAccS3BucketLifecycleConfiguration_TransitionStorageClassOnly_intelligentTiering
    bucket_lifecycle_configuration_test.go:787: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-604965627273996451) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: Z9XEFM60Y6ED1VJC, HostID: VotFmMObL5z9ntbHQgaWC3hO+typgzQZifF8opH8JvQMf3h478vhIqGXZzNIxu/m7PG4+Atp414=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_TransitionStorageClassOnly_intelligentTiering (13.58s)
=== CONT  TestAccS3BucketLifecycleConfiguration_TransitionDate_intelligentTiering
    bucket_lifecycle_configuration_test.go:760: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-8049303294792731938) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: JCMDC3G363BTMHCZ, HostID: f6vqLv6kadiNkCgtpNiPIW/aAN+T/AZnyphnFNp/lSAvthY32ul4j/qzvCNYQi+GLmYUE83gnTs=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_TransitionDate_intelligentTiering (14.12s)
=== CONT  TestAccS3BucketLifecycleConfiguration_disappears
=== NAME  TestAccS3BucketLifecycleConfiguration_EmptyFilter_NonCurrentVersions
    bucket_lifecycle_configuration_test.go:887: Step 1/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_s3_bucket_lifecycle_configuration.test will be updated in-place
          ~ resource "aws_s3_bucket_lifecycle_configuration" "test" {
                id     = "tf-acc-test-8905089461801610559"
                # (1 unchanged attribute hidden)

              ~ rule {
                    id     = "tf-acc-test-8905089461801610559"
                    # (1 unchanged attribute hidden)

                  + noncurrent_version_transition {
                      + noncurrent_days = 30
                      + storage_class   = "STANDARD_IA"
                    }
                  - noncurrent_version_transition {
                      - newer_noncurrent_versions = "0" -> null
                      - noncurrent_days           = 30 -> null
                      - storage_class             = "STANDARD_IA" -> null
                    }
                    # (2 unchanged blocks hidden)
                }
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccS3BucketLifecycleConfiguration_EmptyFilter_NonCurrentVersions (84.66s)
=== CONT  TestAccS3BucketLifecycleConfiguration_RuleExpiration_expireMarkerOnly
--- PASS: TestAccS3BucketLifecycleConfiguration_disappears (62.39s)
=== CONT  TestAccS3BucketLifecycleConfiguration_ruleAbortIncompleteMultipartUpload
=== NAME  TestAccS3BucketLifecycleConfiguration_RuleExpiration_expireMarkerOnly
    bucket_lifecycle_configuration_test.go:601: Step 3/4 error: Error running apply: exit status 1

        Error: updating S3 Bucket Lifecycle Configuration (tf-acc-test-3672198306359129321): operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: WRW19PQPFKEA5HKY, HostID: pKgn4AcZu94i57OSNHIUnZobvkYXLuetnE9iHkNe8GeIdfZVKdp5PpNxtwR16Ora0KUi0IQ+yiQ=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_RuleExpiration_expireMarkerOnly (127.12s)
=== CONT  TestAccS3BucketLifecycleConfiguration_RuleExpiration_emptyBlock
    bucket_lifecycle_configuration_test.go:647: Step 1/2 error: Error running apply: exit status 1

        Error: creating S3 Bucket (tf-acc-test-7707591423620802902) Lifecycle Configuration: operation error S3: PutBucketLifecycleConfiguration, https response error StatusCode: 400, RequestID: B4SYGC7V5510ZKN8, HostID: 0ZXCV+bx42todcgtK+FbRE3Jz+/KnTZaz8vr9Ix0c/3ZGdwIoCbkTRRInKAjTZ1PWCvP4iP/XEw=, api error MalformedXML: The XML you provided was not well-formed or did not validate against our published schema

          with aws_s3_bucket_lifecycle_configuration.test,
          on terraform_plugin_test.tf line 6, in resource "aws_s3_bucket_lifecycle_configuration" "test":
           6: resource "aws_s3_bucket_lifecycle_configuration" "test" {

--- FAIL: TestAccS3BucketLifecycleConfiguration_RuleExpiration_emptyBlock (14.09s)
--- PASS: TestAccS3BucketLifecycleConfiguration_ruleAbortIncompleteMultipartUpload (195.58s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/s3	1267.378s
FAIL
make: *** [testacc] Error 1