Integer port number
This should allow the following in Python CDKTF:
```python
LbListener(
    stack,
    'http',
    default_action=[
        LbListenerDefaultAction(
            type='redirect',
            redirect=LbListenerDefaultActionRedirect(
                port=443, protocol='HTTPS', status_code='HTTP_301'
            ),
        ),
    ],
    load_balancer=load_balancer.arn,
    port=80,
    protocol='HTTP',
```

Previously `port='443'` was required to avoid
```
TypeError: type of argument port must be one of (str, NoneType); got int instead
```