tests/provider: Remove all aws_region current = true configurations
This argument was recently removed.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSCloudwatchLogDestinationPolicy_basic (1.75s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSCloudwatchLogDestinationPolicy_importBasic (1.75s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSCloudwatchLogDestination_importBasic (1.75s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSCloudwatchLogDestination_basic (1.75s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSDynamoDbGlobalTable_import (0.72s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSDynamoDbGlobalTable_basic (0.85s)
    testing.go:538: Step 3 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSIoTTopicRule_elasticsearch (1.84s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSSfnStateMachine_createUpdate (1.52s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
--- FAIL: TestAccAWSSfnStateMachine_Tags (1.52s)
    testing.go:538: Step 0 error: config is invalid: data.aws_region.current: "current": [REMOVED] Defaults to current provider region if no other filtering is enabled
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudwatchLogDestinationPolicy_importBasic (109.96s)
--- PASS: TestAccAWSCloudwatchLogDestinationPolicy_basic (110.55s)
--- PASS: TestAccAWSCloudwatchLogDestination_importBasic (97.04s)
--- PASS: TestAccAWSCloudwatchLogDestination_basic (98.22s)
--- PASS: TestAccAWSDynamoDbGlobalTable_import (283.25s)
--- PASS: TestAccAWSDynamoDbGlobalTable_basic (285.12s)
--- PASS: TestAccAWSIoTTopicRule_elasticsearch (11.31s)
--- PASS: TestAccAWSSfnStateMachine_Tags (55.71s)
```