Update docs on aws_cloudwatch_event_target's ecs_target.task_count to say it is required
The docs previously said it defaulted to 1 and was optional, but actually omitting the value produced an AWS error:

Error: Creating CloudWatch Event Target failed: InvalidParameter: 1 validation error(s) found.
- minimum field value of 1, PutTargetsInput.Targets[0].EcsParameters.TaskCount.