Remove MaxItems for credentials_map because of error
--- FAIL: TestProvider (0.16s)
    provider_test.go:22: err: 1 error occurred:
        	* resource aws_appflow_connector_profile: credentials_map: MaxItems and MinItems are only supported on lists or sets