tests/resource/aws_spot_datafeed_subscription: Add missing S3 grants to configuration and minor refactoring
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/15953

Previously in AWS Commercial:

```
TestAccAWSSpotDatafeedSubscription_serial/basic: resource_aws_spot_datafeed_subscription_test.go:55: Step 1/1 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# aws_s3_bucket.default will be updated in-place
~ resource "aws_s3_bucket" "default" {
id                          = "tf-spot-datafeed-6406181564871998861"
tags                        = {}
# (9 unchanged attributes hidden)
- grant {
- id          = "--OMITTED--" -> null
- permissions = [
- "FULL_CONTROL",
] -> null
- type        = "CanonicalUser" -> null
}
- grant {
- id          = "--OMITTED--" -> null
- permissions = [
- "FULL_CONTROL",
] -> null
- type        = "CanonicalUser" -> null
}
# (1 unchanged block hidden)
}
Plan: 0 to add, 1 to change, 0 to destroy.
```

Previously in AWS GovCloud (US):

```
TestAccAWSSpotDatafeedSubscription_serial/basic: resource_aws_spot_datafeed_subscription_test.go:55: Step 1/1 error: Error running apply: 2020/10/30 16:59:42 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Error Creating Spot Datafeed Subscription: UnsupportedOperation: The functionality you requested is not available in this region.
  status code: 400, request id: d8186507-bcbe-4424-b4a9-dd593eab637a
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSSpotDatafeedSubscription_serial (57.83s)
    --- PASS: TestAccAWSSpotDatafeedSubscription_serial/basic (30.21s)
    --- PASS: TestAccAWSSpotDatafeedSubscription_serial/disappears (27.61s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSSpotDatafeedSubscription_serial (3.10s)
    --- SKIP: TestAccAWSSpotDatafeedSubscription_serial/basic (1.64s)
    --- SKIP: TestAccAWSSpotDatafeedSubscription_serial/disappears (1.45s)
```