r/aws_s3_bucket: enable in-place modification of `object_lock_enabled`
```console
% make t K=s3 T=TestAccS3Bucket_
make: Verifying source code with gofmt...
make: Running acceptance tests on branch: 🌿 reed/s3-object-lock-enable-replacement 🌿...
TF_ACC=1 go1.26.6 test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_'  -timeout 360m -vet=off -buildvcs=false
2026/09/01 11:31:46 Creating Terraform AWS Provider (SDKv2-style)...
2026/09/01 11:31:46 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock (60.86s)
=== CONT  TestAccS3Bucket_Manage_lifecycleBasic
--- PASS: TestAccS3Bucket_Manage_versioningDisabled (76.16s)
=== CONT  TestAccS3Bucket_tags_skipCredentialsValidationAndRequestingAccountID
--- PASS: TestAccS3Bucket_Manage_versioningAndMFADeleteDisabled (76.47s)
=== CONT  TestAccS3Bucket_tags_fallbackS3API
    bucket_test.go:898: skipping test; environment variable TF_ACC_ASSUME_ROLE_ARN must be set. Usage: Amazon Resource Name (ARN) of existing IAM Role to assume for testing restricted permissions
--- SKIP: TestAccS3Bucket_tags_fallbackS3API (0.00s)
=== CONT  TestAccS3Bucket_Tags_EmptyTag_OnUpdate_add
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration (76.80s)
=== CONT  TestAccS3Bucket_Tags_ComputedTag_onCreate
--- PASS: TestAccS3Bucket_Namespace_AccountRegional_namePrefix (80.50s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_nullNonOverlappingResourceTag
--- PASS: TestAccS3Bucket_Manage_MFADeleteDisabled (80.68s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_nullOverlappingResourceTag
--- PASS: TestAccS3Bucket_Manage_objectLockWithVersioning_deprecatedEnabled (80.80s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccS3Bucket_Manage_objectLockWithVersioning (81.06s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_emptyResourceTag
--- PASS: TestAccS3Bucket_tags_ignoreTags (113.41s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly (119.15s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccS3Bucket_Manage_objectLockWithVersioning_enableDeprecatedOnExisting (122.97s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_overlapping
--- PASS: TestAccS3Bucket_Manage_objectLockWithVersioning_enableOnExisting (123.22s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_nonOverlapping
--- PASS: TestAccS3Bucket_Identity_basic (127.00s)
=== CONT  TestAccS3Bucket_Tags_DefaultTags_providerOnly
--- PASS: TestAccS3Bucket_Replication_twoDestination (138.00s)
=== CONT  TestAccS3Bucket_Tags_EmptyTag_OnUpdate_replace
--- PASS: TestAccS3Bucket_Replication_multipleDestinationsEmptyFilter (138.53s)
=== CONT  TestAccS3Bucket_Replication_basic
--- PASS: TestAccS3Bucket_Replication_multipleDestinationsNonEmptyFilter (138.68s)
=== CONT  TestAccS3Bucket_Manage_objectLock_deprecatedEnabled
--- PASS: TestAccS3Bucket_Tags_ComputedTag_OnUpdate_add (145.15s)
=== CONT  TestAccS3Bucket_Manage_objectLock_migrate
--- PASS: TestAccS3Bucket_Manage_versioning (149.76s)
=== CONT  TestAccS3Bucket_Basic_forceDestroyWithObjectVersionsUnusualKeyBytes
--- PASS: TestAccS3Bucket_Tags_ComputedTag_onCreate (94.69s)
=== CONT  TestAccS3Bucket_tags_withSystemTags
--- PASS: TestAccS3Bucket_Tags_DefaultTags_nullNonOverlappingResourceTag (91.20s)
=== CONT  TestAccS3Bucket_List_regionOverride
--- PASS: TestAccS3Bucket_Tags_DefaultTags_emptyResourceTag (90.78s)
=== CONT  TestAccS3Bucket_Duplicate_UsEast1AltAccount
    bucket_test.go:631: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccS3Bucket_Duplicate_UsEast1AltAccount (0.00s)
=== CONT  TestAccS3Bucket_Tags_EmptyTag_onCreate
--- PASS: TestAccS3Bucket_Tags_DefaultTags_emptyProviderOnlyTag (91.24s)
=== CONT  TestAccS3Bucket_Duplicate_UsEast1
--- PASS: TestAccS3Bucket_Tags_DefaultTags_nullOverlappingResourceTag (91.37s)
=== CONT  TestAccS3Bucket_Tags_addOnUpdate
--- PASS: TestAccS3Bucket_Manage_lifecycleBasic (115.65s)
=== CONT  TestAccS3Bucket_Duplicate_basic
--- PASS: TestAccS3Bucket_Duplicate_UsEast1 (30.02s)
=== CONT  TestAccS3Bucket_Tags_null
--- PASS: TestAccS3Bucket_Duplicate_basic (30.21s)
=== CONT  TestAccS3Bucket_Tags_emptyMap
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithObjectVersionsUnusualKeyBytes (63.39s)
=== CONT  TestAccS3Bucket_tags
--- PASS: TestAccS3Bucket_Manage_objectLock_deprecatedEnabled (77.35s)
=== CONT  TestAccS3Bucket_disappears
--- PASS: TestAccS3Bucket_Replication_ruleDestinationAddAccessControlTranslation (218.88s)
=== CONT  TestAccS3Bucket_Identity_ExistingResource_noRefreshNoChange
--- PASS: TestAccS3Bucket_Replication_ruleDestinationAccessControlTranslation (228.35s)
=== CONT  TestAccS3Bucket_Basic_upgradeFromV5
--- PASS: TestAccS3Bucket_tags_skipCredentialsValidationAndRequestingAccountID (156.47s)
=== CONT  TestAccS3Bucket_List_includeResource
--- PASS: TestAccS3Bucket_List_regionOverride (65.48s)
=== CONT  TestAccS3Bucket_Basic_requestPayer
--- PASS: TestAccS3Bucket_Manage_objectLock_migrate (101.07s)
=== CONT  TestAccS3Bucket_List_basic
--- PASS: TestAccS3Bucket_Tags_DefaultTags_updateToResourceOnly (140.92s)
=== CONT  TestAccS3Bucket_Manage_objectLock
--- PASS: TestAccS3Bucket_Tags_DefaultTags_updateToProviderOnly (141.66s)
=== CONT  TestAccS3Bucket_Basic_keyEnabled
--- PASS: TestAccS3Bucket_disappears (62.51s)
=== CONT  TestAccS3Bucket_Manage_lifecycleRemove
--- PASS: TestAccS3Bucket_Tags_EmptyTag_OnUpdate_replace (145.14s)
=== CONT  TestAccS3Bucket_Basic_forceDestroyWithEmptyPrefixes
--- PASS: TestAccS3Bucket_Tags_EmptyTag_OnUpdate_add (223.74s)
=== CONT  TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled
--- PASS: TestAccS3Bucket_Tags_addOnUpdate (141.15s)
=== CONT  TestAccS3Bucket_Security_corsSingleMethodAndEmptyOrigin
--- PASS: TestAccS3Bucket_Identity_ExistingResource_noRefreshNoChange (98.58s)
=== CONT  TestAccS3Bucket_Basic_acceleration
--- PASS: TestAccS3Bucket_Tags_null (122.39s)
=== CONT  TestAccS3Bucket_Basic_nameGenerated
=== NAME  TestAccS3Bucket_List_includeResource
    bucket_list_test.go:95: Step 2/2 error running query checks: running terraform query command returned diagnostics: [{baseLogMessage:{Lvl:error Msg:Error: Error Listing Tags Time:2026-09-01 11:37:14.729581 -0400 EDT} Diagnostic:{Severity:error Address:list.aws_s3_bucket.test Summary:Error Listing Tags Detail:An error occurred while listing tags for s3: operation error S3 Control: ListTagsForResource, https response error StatusCode: 404, RequestID: YWAMW3WW0NX5W0NG, HostID: uXTZD0kRBR5nGCvvKmD2/ZkD+lwbbU7ydUlf2mscASkdzJoE31F4j52HxZH/b8zI0edZj9t3kyd6uzOXt6yBbqqcgEn28/pj, api error NoSuchResource: The specified resource doesn't exist. Range:0x5774318b4b00 Snippet:0x577462d802d0}}]
--- PASS: TestAccS3Bucket_Tags_EmptyTag_onCreate (156.62s)
=== CONT  TestAccS3Bucket_Namespace_AccountRegional_nameGenerated
--- PASS: TestAccS3Bucket_Tags_emptyMap (121.96s)
=== CONT  TestAccS3Bucket_Web_simple
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithEmptyPrefixes (55.27s)
=== CONT  TestAccS3Bucket_Basic_forceDestroyWithObjectVersions
--- FAIL: TestAccS3Bucket_List_includeResource (109.65s)
=== CONT  TestAccS3Bucket_Namespace_AccountRegional_basic
--- PASS: TestAccS3Bucket_Basic_keyEnabled (82.00s)
=== CONT  TestAccS3Bucket_Security_disableDefaultEncryptionWhenDefaultEncryptionIsEnabled
--- PASS: TestAccS3Bucket_Basic_upgradeFromV5 (119.00s)
=== CONT  TestAccS3Bucket_Security_enableDefaultEncryptionWhenAES256IsUsed
--- PASS: TestAccS3Bucket_List_basic (105.50s)
=== CONT  TestAccS3Bucket_Basic_forceDestroyWithUnusualKeyBytes
--- PASS: TestAccS3Bucket_Tags_DefaultTags_nonOverlapping (231.97s)
=== CONT  TestAccS3Bucket_Namespace_global
--- PASS: TestAccS3Bucket_Tags_DefaultTags_overlapping (232.79s)
=== CONT  TestAccS3Bucket_Security_enableDefaultEncryptionWhenTypical
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled (62.00s)
=== CONT  TestAccS3Bucket_Basic_forceDestroy
--- PASS: TestAccS3Bucket_Basic_requestPayer (126.60s)
=== CONT  TestAccS3Bucket_Web_routingRules
--- PASS: TestAccS3Bucket_Manage_lifecycleRemove (95.34s)
=== CONT  TestAccS3Bucket_Security_logging
--- PASS: TestAccS3Bucket_Manage_objectLock (123.94s)
=== CONT  TestAccS3Bucket_Basic_skipCredentialsValidationAndRequestingAccountID
--- PASS: TestAccS3Bucket_Security_corsSingleMethodAndEmptyOrigin (72.81s)
=== CONT  TestAccS3Bucket_Web_redirect
--- PASS: TestAccS3Bucket_Basic_nameGenerated (75.69s)
=== CONT  TestAccS3Bucket_Identity_ExistingResource_basic
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithObjectVersions (68.53s)
=== CONT  TestAccS3Bucket_Basic_namePrefix
--- PASS: TestAccS3Bucket_Namespace_AccountRegional_nameGenerated (81.86s)
=== CONT  TestAccS3Bucket_Replication_RTC_valid
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithUnusualKeyBytes (59.30s)
=== CONT  TestAccS3Bucket_Replication_withoutPrefix
--- PASS: TestAccS3Bucket_Security_enableDefaultEncryptionWhenAES256IsUsed (75.17s)
=== CONT  TestAccS3Bucket_Security_corsEmptyOrigin
--- PASS: TestAccS3Bucket_Basic_forceDestroy (61.09s)
=== CONT  TestAccS3Bucket_Replication_schemaV2SameRegion
--- PASS: TestAccS3Bucket_Replication_basic (286.16s)
=== CONT  TestAccS3Bucket_Security_corsDelete
--- PASS: TestAccS3Bucket_Namespace_AccountRegional_basic (89.02s)
=== CONT  TestAccS3Bucket_Replication_schemaV2
--- PASS: TestAccS3Bucket_tags_withSystemTags (262.72s)
=== CONT  TestAccS3Bucket_Security_corsUpdate
--- PASS: TestAccS3Bucket_Basic_acceleration (124.03s)
=== CONT  TestAccS3Bucket_Replication_inline
--- PASS: TestAccS3Bucket_Namespace_global (86.50s)
=== CONT  TestAccS3Bucket_Replication_withReplicaModifications
--- PASS: TestAccS3Bucket_Tags_DefaultTags_providerOnly (314.78s)
=== CONT  TestAccS3Bucket_Replication_withoutStorageClass
--- PASS: TestAccS3Bucket_Security_enableDefaultEncryptionWhenTypical (92.09s)
=== CONT  TestAccS3Bucket_Identity_regionOverride
--- PASS: TestAccS3Bucket_Basic_skipCredentialsValidationAndRequestingAccountID (74.72s)
=== CONT  TestAccS3Bucket_Tags_IgnoreTags_Overlap_resourceTag
--- PASS: TestAccS3Bucket_Security_disableDefaultEncryptionWhenDefaultEncryptionIsEnabled (116.61s)
=== CONT  TestAccS3Bucket_Basic_emptyString
--- PASS: TestAccS3Bucket_Security_logging (86.77s)
=== CONT  TestAccS3Bucket_Basic_basic
--- PASS: TestAccS3Bucket_Web_routingRules (120.99s)
=== CONT  TestAccS3Bucket_Tags_IgnoreTags_Overlap_defaultTag
--- PASS: TestAccS3Bucket_Basic_namePrefix (78.27s)
=== CONT  TestAccS3Bucket_Tags_ComputedTag_OnUpdate_replace
--- PASS: TestAccS3Bucket_Security_corsDelete (64.96s)
=== CONT  TestAccS3Bucket_Replication_expectVersioningValidationError
--- PASS: TestAccS3Bucket_Web_simple (165.64s)
--- PASS: TestAccS3Bucket_Security_corsEmptyOrigin (80.32s)
--- PASS: TestAccS3Bucket_Replication_schemaV2SameRegion (88.43s)
--- PASS: TestAccS3Bucket_tags (304.25s)
--- PASS: TestAccS3Bucket_Basic_emptyString (72.64s)
--- PASS: TestAccS3Bucket_Basic_basic (71.53s)
--- PASS: TestAccS3Bucket_Replication_expectVersioningValidationError (50.03s)
--- PASS: TestAccS3Bucket_Replication_withoutPrefix (129.25s)
--- PASS: TestAccS3Bucket_Web_redirect (158.52s)
--- PASS: TestAccS3Bucket_Identity_regionOverride (101.01s)
--- PASS: TestAccS3Bucket_Security_corsUpdate (116.59s)
--- PASS: TestAccS3Bucket_Identity_ExistingResource_basic (151.19s)
--- PASS: TestAccS3Bucket_Replication_withReplicaModifications (112.09s)
--- PASS: TestAccS3Bucket_Replication_withoutStorageClass (115.21s)
--- PASS: TestAccS3Bucket_Replication_inline (135.43s)
--- PASS: TestAccS3Bucket_Tags_ComputedTag_OnUpdate_replace (94.67s)
--- PASS: TestAccS3Bucket_Tags_IgnoreTags_Overlap_defaultTag (103.17s)
--- PASS: TestAccS3Bucket_Tags_IgnoreTags_Overlap_resourceTag (135.79s)
--- PASS: TestAccS3Bucket_Replication_RTC_valid (209.43s)
--- PASS: TestAccS3Bucket_Replication_schemaV2 (230.43s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/s3 670.506s
```