tests/service/docdb: Temporarily use expanded references
These were from recently merged pull requests and have syntax that is incompatible with Terraform 0.12. This change is both backwards (0.11) and forwards (0.12) compatible to allow the configuration on both versions. Eventually the temporary workaround will be removed when we switch the provider test configurations to 0.12-only syntax.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSDocDBClusterInstance_az (2.04s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test482154120/main.tf line 6:
          (source code not available)

        Inappropriate value for attribute "availability_zones": element 0: string
        required.

--- FAIL: TestAccAWSDocDBClusterSnapshot_basic (2.01s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test699729194/main.tf line 26:
          (source code not available)

        Inappropriate value for attribute "subnet_ids": element 0: string required.

--- FAIL: TestAccAWSDocDBCluster_Port (2.15s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test810236062/main.tf line 5:
          (source code not available)

        Inappropriate value for attribute "availability_zones": element 0: string
        required.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSDocDBClusterSnapshot_basic (221.32s)
--- PASS: TestAccAWSDocDBCluster_Port (236.08s)
--- PASS: TestAccAWSDocDBClusterInstance_az (700.93s)
```