service/sfn: Fixes for tfproviderlint R006
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/11864

`RetryFunc` should only be used when logic has a retryable condition. In the case of working with the AWS Go SDK, it also arbitrarily restricts the automatic retrying logic of API calls to the timeout, which is generally undesired.

Previously:

```
aws/resource_aws_sfn_activity.go:117:39: R006: RetryFunc should include RetryableError() handling or be removed
aws/resource_aws_sfn_state_machine.go:181:39: R006: RetryFunc should include RetryableError() handling or be removed
```

Output from acceptance testing (unrelated failure present on master due to SFN eventual consistency):

```
--- PASS: TestAccAWSSfnActivity_basic (18.37s)
--- PASS: TestAccAWSSfnActivity_Tags (43.33s)

--- FAIL: TestAccAWSSfnStateMachine_createUpdate (55.52s)
    testing.go:640: Step 1 error: Check failed: Check 5/6 error: aws_sfn_state_machine.foo: Attribute 'definition' didn't match ".*\\\"MaxAttempts\\\": 10.*", got "{\n  \"Comment\": \"A Hello World example of the Amazon States Language using an AWS Lambda Function\",\n  \"StartAt\": \"HelloWorld\",\n  \"States\": {\n    \"HelloWorld\": {\n      \"Type\": \"Task\",\n      \"Resource\": \"arn:aws:lambda:us-west-2:187416307283:function:sfn-uzt6w9nxeb\",\n      \"Retry\": [\n        {\n          \"ErrorEquals\": [\"States.ALL\"],\n          \"IntervalSeconds\": 5,\n          \"MaxAttempts\": 5,\n          \"BackoffRate\": 8.0\n        }\n      ],\n      \"End\": true\n    }\n  }\n}\n"
--- PASS: TestAccAWSSfnStateMachine_Tags (73.52s)
```