tests/data-source/aws_pricing_product: Adjust redshift query precision
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16720

Previously:

```
=== CONT  TestAccDataSourceAwsPricingProduct_redshift
TestAccDataSourceAwsPricingProduct_redshift: data_source_aws_pricing_product_test.go:29: Step 1/1 error: Error running pre-apply refresh:
Error: Pricing product query not precise enough. Returned more than one element: ....
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccDataSourceAwsPricingProduct_redshift (8.55s)
```

Output from acceptance testing in AWS GovCloud (US):

```
=== CONT  TestAccDataSourceAwsPricingProduct_redshift
    provider_test.go:697: skipping tests; partition aws-us-gov does not support api.pricing service
--- SKIP: TestAccDataSourceAwsPricingProduct_redshift (1.38s)
```