tests/resource/aws_elasticache_replication_group: Fix node size for VPC test with snapshotting
Previously:

```
--- FAIL: TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2 (6.13s)
    testing.go:527: Step 0 error: Error applying: 1 error occurred:
        	* aws_elasticache_replication_group.bar: 1 error occurred:
        	* aws_elasticache_replication_group.bar: Error creating Elasticache Replication Group: InvalidParameterCombination: The requested configuration does not support snapshotting. Snapshot window parameter should not be specified.
```