r/aws_eks_capability(test): switch to `AWS_IDENTITY_STORE_GROUP_ID` env var
Test still failing, but no longer due to server side validation of the IDC group identifier.

```console
% WS_IDENTITY_STORE_USER_ID=c4b86468-0061-702e-f540-d17f8b3bc6f1 AWS_IDENTITY_STORE_GROUP_NAME=f48884f8-30e1-7057-0c44-848c0aca4ed2 make t K=eks T=TestAccEKSCapability_ArgoCD_rbac
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-aws_eks_capability 🌿...
TF_ACC=1 go1.24.10 test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSCapability_ArgoCD_rbac'  -timeout 360m -vet=off
2025/12/02 13:47:51 Creating Terraform AWS Provider (SDKv2-style)...
2025/12/02 13:47:51 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccEKSCapability_ArgoCD_rbac
=== PAUSE TestAccEKSCapability_ArgoCD_rbac
=== CONT  TestAccEKSCapability_ArgoCD_rbac
    capability_test.go:217: Step 3/3 error: Error running apply: exit status 1

        Error: Invalid list/set

          with aws_eks_capability.test,
          on terraform_plugin_test.tf line 119, in resource "aws_eks_capability" "test":
         119: resource "aws_eks_capability" "test" {

        too many elements: want 1, got 2
--- FAIL: TestAccEKSCapability_ArgoCD_rbac (1104.26s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/eks        1110.774s
```