r/aws_iot_topic_rule: Tidy up 'TestAccIoTTopicRule_kafka'.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccIoTTopicRule_kafka' PKG=iot
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTTopicRule_kafka -timeout 180m
=== RUN   TestAccIoTTopicRule_kafka
=== PAUSE TestAccIoTTopicRule_kafka
=== CONT  TestAccIoTTopicRule_kafka
    topic_rule_test.go:660: Step 1/2 error: Error running apply: exit status 1

        Error: creating IoT Topic Rule (tf_acc_test_1bnm6szi43rc3u28f6qd): InvalidRequestException: Invalid destination arn 'arn:aws:kafka:us-west-2:123456789012:topic/test'.

          with aws_iot_topic_rule.rule,
          on terraform_plugin_test.tf line 50, in resource "aws_iot_topic_rule" "rule":
          50: resource "aws_iot_topic_rule" "rule" {

--- FAIL: TestAccIoTTopicRule_kafka (17.32s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/iot	20.920s
FAIL
make: *** [testacc] Error 1

Requires new 'aws_topic_rule_destination' resource.