resource/aws_launch_configuration: Prevent ResourceInUse errors caused by eventual consistency during deletion
References:
* https://github.com/terraform-providers/terraform-provider-aws/issues/502
* https://github.com/terraform-providers/terraform-provider-aws/issues/646

Also discovered during acceptance testing, which was no longer present after this change:

```
--- FAIL: TestAccAWSAutoScalingGroup_basic (233.37s)
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Error applying: 1 error occurred:
          * aws_launch_configuration.foobar (destroy): 1 error occurred:
          * aws_launch_configuration.foobar: ResourceInUse: Cannot delete launch configuration terraform-20190305190002502900000001 because it is attached to AutoScalingGroup terraform-test-xkagj2tcwm
```

It appears the Autoscaling service can display an eventual consistency delay between when an Autoscaling Group requiring a Launch Configuration is deleted and deleting the Launch Configuration immediately after.

Output from acceptance testing:

```
--- PASS: TestAccAWSLaunchConfiguration_importBasic (14.18s)
--- PASS: TestAccAWSLaunchConfiguration_withSpotPrice (15.10s)
--- PASS: TestAccAWSLaunchConfiguration_ebs_noDevice (16.20s)
--- PASS: TestAccAWSLaunchConfiguration_withBlockDevices (17.60s)
--- PASS: TestAccAWSLaunchConfiguration_withEncryption (19.82s)
--- PASS: TestAccAWSLaunchConfiguration_userData (26.26s)
--- PASS: TestAccAWSLaunchConfiguration_basic (28.43s)
--- PASS: TestAccAWSLaunchConfiguration_updateEbsBlockDevices (30.24s)
--- PASS: TestAccAWSLaunchConfiguration_updateRootBlockDevice (31.82s)
--- PASS: TestAccAWSLaunchConfiguration_withIAMProfile (35.39s)
--- PASS: TestAccAWSLaunchConfiguration_withVpcClassicLink (37.53s)
```