resource/aws_rds_cluster_parameter_group: Prevent missing DBClusterParameterGroupName error on creation with generated names and name_prefix
References:
* https://github.com/terraform-providers/terraform-provider-aws/issues/1739
* https://github.com/terraform-providers/terraform-provider-aws/issues/7264

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSDBClusterParameterGroup_generatedName_Parameter (8.30s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_rds_cluster_parameter_group.test: 1 error occurred:
        	* aws_rds_cluster_parameter_group.test: Error modifying DB Cluster Parameter Group: InvalidParameterValue: The parameter DBClusterParameterGroupName must be provided and must not be blank.
        	status code: 400, request id: e2a07ba0-ba60-4d24-a8ee-3d7a86cf1793

--- FAIL: TestAccAWSDBClusterParameterGroup_namePrefix_Parameter (8.43s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_rds_cluster_parameter_group.test: 1 error occurred:
        	* aws_rds_cluster_parameter_group.test: Error modifying DB Cluster Parameter Group: InvalidParameterValue: The parameter DBClusterParameterGroupName must be provided and must not be blank.
        	status code: 400, request id: 895b9f34-c88e-46ec-8006-0ee61096cff1
```

Output from acceptance testing:

```
--- PASS: TestAccAWSDBClusterParameterGroup_disappears (10.98s)
--- PASS: TestAccAWSDBClusterParameterGroup_namePrefix (12.80s)
--- PASS: TestAccAWSDBClusterParameterGroup_generatedName (12.99s)
--- PASS: TestAccAWSDBClusterParameterGroup_namePrefix_Parameter (13.53s)
--- PASS: TestAccAWSDBClusterParameterGroup_generatedName_Parameter (13.60s)
--- PASS: TestAccAWSDBClusterParameterGroup_withApplyMethod (14.34s)
--- PASS: TestAccAWSDBClusterParameterGroup_importBasic (15.56s)
--- PASS: TestAccAWSDBClusterParameterGroup_basic (24.07s)
```