tests/service/lightsail: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSLightsailInstance_basic (1.16s)
    testing.go:568: Step 0 error: errors during plan:

        Error: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSLightsailStaticIp_basic (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailStaticIpAttachment_disappears (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailKeyPair_encrypted (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailDomain_basic (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailKeyPair_imported (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailInstance_disapear (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailKeyPair_nameprefix (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailKeyPair_basic (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailInstance_euRegion (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailDomain_disappears (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailStaticIpAttachment_basic (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailStaticIp_disappears (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSLightsailInstance_basic (1.89s)
    resource_aws_lightsail_instance_test.go:171: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://lightsail.us-gov-west-1.amazonaws.com/: dial tcp: lookup lightsail.us-gov-west-1.amazonaws.com: no such host
```