resource/aws_db_instance: Redact MasterUserPassword when displaying InvalidParameterValue error with CreateDBInstance
It was previously requested that the aws_db_instance Terraform resource show the given CreateDBInstance input configuration when receiving an `InvalidParameterValue` error. This would previously show the `MasterUserPassword` field of the input in the UI.

Previously before code update:

```
--- FAIL: TestAccAWSDBInstance_Password (5.84s)
    testing.go:561: Step 0, expected error:

        errors during apply: Error creating DB Instance: InvalidParameterValue: The parameter MasterUserPassword is not a valid password because it is shorter than 8 characters.
        	status code: 400, request id: 795895e7-8110-4460-9bf7-5211729522d9, {
          AllocatedStorage: 5,
          AutoMinorVersionUpgrade: true,
          BackupRetentionPeriod: 0,
          CopyTagsToSnapshot: false,
          DBInstanceClass: "db.t2.micro",
          DBInstanceIdentifier: "tf-acc-test-796357036994784624",
          DBName: "",
          DeletionProtection: false,
          Engine: "mysql",
          EngineVersion: "",
          MasterUserPassword: "invalid",
          MasterUsername: "tfacctest",
          PubliclyAccessible: false,
          StorageEncrypted: false,
          Tags: []
        }

        To match:

        MasterUserPassword: "\*{8}",
```

Output from acceptance testing after code update:

```
--- PASS: TestAccAWSDBInstance_Password (401.36s)
```