tests/service/gamelift: Add PreCheck for service availability and skip undefined sample game regions
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSGameliftAlias_basic (0.99s)
    testing.go:568: Step 0 error: errors during apply:

        Error: RequestError: send request failed
        caused by: Post https://gamelift.us-gov-west-1.amazonaws.com/: dial tcp: lookup gamelift.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host

--- FAIL: TestAccAWSGameliftBuild_basic (0.00s)
    resource_aws_gamelift_build_test.go:72: Account ID not found for region "us-gov-west-1"
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSGameliftAlias_fleetRouting (0.00s)
    resource_aws_gamelift_alias_test.go:163: GameLift Account ID not found for region "us-gov-west-1"
--- SKIP: TestAccAWSGameliftBuild_basic (0.00s)
    resource_aws_gamelift_build_test.go:73: GameLift Account ID not found for region "us-gov-west-1"
--- SKIP: TestAccAWSGameliftFleet_basic (0.00s)
    resource_aws_gamelift_fleet_test.go:251: GameLift Account ID not found for region "us-gov-west-1"
--- SKIP: TestAccAWSGameliftFleet_allFields (0.00s)
    resource_aws_gamelift_fleet_test.go:330: GameLift Account ID not found for region "us-gov-west-1"
--- SKIP: TestAccAWSGameliftGameSessionQueue_basic (1.95s)
    resource_aws_gamelift_build_test.go:186: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://gamelift.us-gov-west-1.amazonaws.com/: dial tcp: lookup gamelift.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSGameliftAlias_importBasic (1.23s)
    resource_aws_gamelift_build_test.go:186: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://gamelift.us-gov-west-1.amazonaws.com/: dial tcp: lookup gamelift.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSGameliftAlias_basic (1.23s)
    resource_aws_gamelift_build_test.go:186: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://gamelift.us-gov-west-1.amazonaws.com/: dial tcp: lookup gamelift.us-gov-west-1.amazonaws.com: no such host
```