data-source/aws_iam_policy_document: Ensure principals configurations in testing and documentation omit equals
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAppautoscalingScheduledAction_EMR (0.59s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "principals" is not expected here. Did you mean to define a block of type "principals"?
```

Output from Terraform 0.12 acceptance testing (other tests will require additional updates to pass):

```
--- PASS: TestAccAWSCloudwatchLogDestinationPolicy_importBasic (102.32s)
--- PASS: TestAccAWSCloudwatchLogDestination_basic (102.32s)
--- PASS: TestAccAWSCloudwatchLogDestination_importBasic (94.94s)
--- PASS: TestAccAWSCloudwatchLogDestinationPolicy_basic (101.92s)
--- PASS: TestAccAWSAppautoscalingScheduledAction_EMR (514.02s)
--- PASS: TestAccAWSAppautoScalingTarget_emrCluster (544.24s)
```