resource/aws_db_instance: Prevent error when using snapshot_identifier with multi_az enabled and sqlserver engine
When calling `RestoreDBInstanceFromDBSnapshot` and attempting to enable `MultiAZ` with `Engine` set to SQL server, it first must be set to disabled since the API requires `BackupRetentionPeriod`, but that parameter is not available for the initial API call.

* When using `multi_az` with `snapshot_identifier` and `engine` set to `sqlserver*`, remove parameter or catch specific error and require `ModifyDBInstance` API call afterwards
* When `ModifyDBInstance` is being called during resource creation, always set `ApplyImmediately` to `true` to prevent need for double apply.

Previously:

```
--- FAIL: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (1101.33s)
	testing.go:527: Step 0 error: Error applying: 1 error occurred:
			* aws_db_instance.test: 1 error occurred:
			* aws_db_instance.test: Error creating DB Instance: InvalidParameterValue: Mirroring cannot be applied to instances with backup retention set to zero.
```

Now:

```
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (4031.24s)
```