tests/service/backup: Add PreCheck for service availability
Previously in AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAwsBackupVault_basic (6.91s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Backup Vault (): RequestError: send request failed
        caused by: Put https://backup.us-gov-west-1.amazonaws.com/backup-vaults/tf_acc_test_backup_vault_5570772252950055746: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
```

Output from AWS Standard acceptance testing:

```
--- PASS: TestAccAwsBackupVault_basic (13.66s)
--- PASS: TestAccAwsBackupPlan_disappears (15.83s)
--- PASS: TestAccAwsBackupPlan_withRules (17.25s)
--- PASS: TestAccAwsBackupPlan_basic (17.54s)
--- PASS: TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly (17.64s)
--- PASS: TestAccAwsBackupPlan_withLifecycle (17.76s)
--- PASS: TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly (17.76s)
--- PASS: TestAccAwsBackupSelection_disappears (19.88s)
--- PASS: TestAccAwsBackupSelection_withTags (21.30s)
--- PASS: TestAccAwsBackupSelection_basic (21.36s)
--- PASS: TestAccAwsBackupSelection_withResources (21.46s)
--- PASS: TestAccAwsBackupPlan_withRuleAdd (28.56s)
--- PASS: TestAccAwsBackupPlan_withRuleRemove (29.33s)
--- PASS: TestAccAwsBackupVault_withTags (31.91s)
--- PASS: TestAccAwsBackupSelection_updateTag (33.08s)
--- PASS: TestAccAwsBackupPlan_withTags (40.05s)
--- PASS: TestAccAwsBackupVault_withKmsKey (44.04s)
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAwsBackupSelection_disappears (2.20s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withLifecycleDeleteAfterOnly (2.20s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withRuleRemove (2.20s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupSelection_updateTag (2.20s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupVault_withTags (2.20s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withTags (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_basic (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupSelection_basic (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withRules (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withRuleAdd (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withLifecycleColdStorageAfterOnly (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_disappears (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupVault_basic (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupSelection_withTags (2.21s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupSelection_withResources (2.22s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupPlan_withLifecycle (2.23s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsBackupVault_withKmsKey (2.23s)
    resource_aws_backup_vault_test.go:148: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://backup.us-gov-west-1.amazonaws.com/backup-vaults/: dial tcp: lookup backup.us-gov-west-1.amazonaws.com: no such host
```