tests/resource/aws_vpc_peering_connection: Remove ID-only refresh configuration (#18349)
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/18348

Identifier only refresh testing is generally a legacy testing practice before full import testing was the normal convention. Certain functionality of `IDRefreshName` testing, such as alternate providers defined by the test configuration and `ProviderFactories`, is not compatible since there is no method to pass in the original configuration to prevent Terraform CLI errors such as:

```
=== CONT  TestAccAWSVPCPeeringConnection_region
    testing_new.go:214: Error running terraform refresh: exit status 1

        Error: Provider configuration not present

        To work with aws_vpc.peer (orphan) its original provider configuration at
        provider["registry.terraform.io/hashicorp/awsalternate"] is required, but it
        has been removed. This occurs when a provider configuration is removed while
        objects created by that provider still exist in the state. Re-add the provider
        configuration to destroy aws_vpc.peer (orphan), after which you can remove the
        provider configuration again.

--- FAIL: TestAccAWSVPCPeeringConnection_region (24.38s)
```

Import testing accepts a `Config`, which is how it does not have a similar issue. Will submit followup issue to fix the Go documentation in the Terraform Plugin SDK as this testing is not run by default and note this limitation. Will also submit followup issue to remove `IDRefreshIgnore` and `IDRefreshName` from all testing.

Output from acceptance testing:

```
--- PASS: TestAccAWSVPCPeeringConnection_peerRegionAutoAccept (13.29s)
--- PASS: TestAccAWSVPCPeeringConnection_failedState (14.70s)
--- PASS: TestAccAWSVPCPeeringConnection_plan (24.21s)
--- PASS: TestAccAWSVPCPeeringConnection_optionsNoAutoAccept (25.87s)
--- PASS: TestAccAWSVPCPeeringConnection_basic (27.94s)
--- PASS: TestAccAWSVPCPeeringConnection_region (30.92s)
--- PASS: TestAccAWSVPCPeeringConnection_options (60.28s)
--- PASS: TestAccAWSVPCPeeringConnection_accept (61.32s)
--- PASS: TestAccAWSVPCPeeringConnection_tags (62.79s)
```