tests/resource/aws_guardduty_detector: Add sweeper (#11722)
Previously in the acceptance testing:

```
--- FAIL: TestAccAWSGuardDuty (35.95s)
    --- FAIL: TestAccAWSGuardDuty/Detector (6.32s)
        --- FAIL: TestAccAWSGuardDuty/Detector/basic (3.60s)
            testing.go:640: Step 0 error: errors during apply:

                Error: Creating GuardDuty Detector failed: BadRequestException: The request is rejected because a detector already exists for the current account.
                {
                  Message_: "The request is rejected because a detector already exists for the current account.",
                  Type: "InvalidInputException"
                }
```

As a first mitigation against testing accounts that may already have a GuardDuty Detector (e.g. dangling from previous test failures), we introduce a sweeper to clean them. Other mitigations are also possible in the future like adding a `PreCheck` function that will skip testing if there is still a GuardDuty Detector present at test run time, but this should be a good start.

Output from sweeper:

```console
$ go test ./aws -v -timeout=10h -sweep=us-west-2 -sweep-run=aws_guardduty_detector -sweep-allow-failures
2020/01/22 16:15:43 [DEBUG] Running Sweepers for region (us-west-2):
2020/01/22 16:15:43 [DEBUG] Running Sweeper (aws_guardduty_detector) in region (us-west-2)
...
2020/01/22 16:15:46 [INFO] Deleting GuardDuty Detector: aeb7be04e91fee02468976b298d45013
2020/01/22 16:15:47 Sweeper Tests ran successfully:
	- aws_guardduty_detector
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.534s
```