tests/resource/aws_db_proxy_default_target_group: Check disappearance with DB Proxy removal since default Target Group cannot be removed (#15546)
Previously:

```
=== CONT  TestAccAWSDBProxyDefaultTargetGroup_disappears
TestAccAWSDBProxyDefaultTargetGroup_disappears: resource_aws_db_proxy_default_target_group_test.go:221: Step 1/1 error: Expected a non-empty plan, but got an empty plan!
--- FAIL: TestAccAWSDBProxyDefaultTargetGroup_disappears (597.58s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSDBProxyDefaultTargetGroup_disappears (682.08s)
```