r/aws_route53_resolver_rule: Switch to 'WithoutTimeout' CRUD handlers (#15090).
Acceptance test output:

% make testacc TESTARGS='-run=TestAccRoute53ResolverRule_\|TestAccRoute53ResolverRuleDataSource_\|TestAccRoute53ResolverRulesDataSource_' PKG=route53resolver ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53resolver/... -v -count 1 -parallel 3  -run=TestAccRoute53ResolverRule_\|TestAccRoute53ResolverRuleDataSource_\|TestAccRoute53ResolverRulesDataSource_ -timeout 180m
=== RUN   TestAccRoute53ResolverRuleDataSource_basic
=== PAUSE TestAccRoute53ResolverRuleDataSource_basic
=== RUN   TestAccRoute53ResolverRuleDataSource_resolverEndpointIdWithTags
=== PAUSE TestAccRoute53ResolverRuleDataSource_resolverEndpointIdWithTags
=== RUN   TestAccRoute53ResolverRuleDataSource_sharedByMe
=== PAUSE TestAccRoute53ResolverRuleDataSource_sharedByMe
=== RUN   TestAccRoute53ResolverRuleDataSource_sharedWithMe
=== PAUSE TestAccRoute53ResolverRuleDataSource_sharedWithMe
=== RUN   TestAccRoute53ResolverRule_basic
=== PAUSE TestAccRoute53ResolverRule_basic
=== RUN   TestAccRoute53ResolverRule_disappears
=== PAUSE TestAccRoute53ResolverRule_disappears
=== RUN   TestAccRoute53ResolverRule_tags
=== PAUSE TestAccRoute53ResolverRule_tags
=== RUN   TestAccRoute53ResolverRule_justDotDomainName
=== PAUSE TestAccRoute53ResolverRule_justDotDomainName
=== RUN   TestAccRoute53ResolverRule_trailingDotDomainName
=== PAUSE TestAccRoute53ResolverRule_trailingDotDomainName
=== RUN   TestAccRoute53ResolverRule_updateName
=== PAUSE TestAccRoute53ResolverRule_updateName
=== RUN   TestAccRoute53ResolverRule_forward
=== PAUSE TestAccRoute53ResolverRule_forward
=== RUN   TestAccRoute53ResolverRule_forwardEndpointRecreate
=== PAUSE TestAccRoute53ResolverRule_forwardEndpointRecreate
=== RUN   TestAccRoute53ResolverRulesDataSource_basic
=== PAUSE TestAccRoute53ResolverRulesDataSource_basic
=== RUN   TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== PAUSE TestAccRoute53ResolverRulesDataSource_resolverEndpointID
=== RUN   TestAccRoute53ResolverRulesDataSource_nameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nameRegex
=== RUN   TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== PAUSE TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
=== CONT  TestAccRoute53ResolverRuleDataSource_basic
=== CONT  TestAccRoute53ResolverRule_trailingDotDomainName
=== CONT  TestAccRoute53ResolverRule_basic
--- PASS: TestAccRoute53ResolverRuleDataSource_basic (19.94s)
=== CONT  TestAccRoute53ResolverRule_justDotDomainName
--- PASS: TestAccRoute53ResolverRule_trailingDotDomainName (21.44s)
=== CONT  TestAccRoute53ResolverRule_tags
--- PASS: TestAccRoute53ResolverRule_basic (22.70s)
=== CONT  TestAccRoute53ResolverRule_disappears
--- PASS: TestAccRoute53ResolverRule_disappears (13.78s)
=== CONT  TestAccRoute53ResolverRulesDataSource_basic
--- PASS: TestAccRoute53ResolverRule_justDotDomainName (18.80s)
=== CONT  TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex
--- PASS: TestAccRoute53ResolverRulesDataSource_basic (14.40s)
=== CONT  TestAccRoute53ResolverRulesDataSource_nameRegex
--- PASS: TestAccRoute53ResolverRulesDataSource_nonExistentNameRegex (14.29s)
=== CONT  TestAccRoute53ResolverRulesDataSource_resolverEndpointID
--- PASS: TestAccRoute53ResolverRule_tags (45.74s)
=== CONT  TestAccRoute53ResolverRule_forward
--- PASS: TestAccRoute53ResolverRulesDataSource_nameRegex (16.69s)
=== CONT  TestAccRoute53ResolverRuleDataSource_sharedByMe
    acctest.go:645: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccRoute53ResolverRuleDataSource_sharedByMe (0.00s)
=== CONT  TestAccRoute53ResolverRuleDataSource_sharedWithMe
    acctest.go:645: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccRoute53ResolverRuleDataSource_sharedWithMe (0.00s)
=== CONT  TestAccRoute53ResolverRule_forwardEndpointRecreate
=== CONT  TestAccRoute53ResolverRulesDataSource_resolverEndpointID
    rules_data_source_test.go:42: Step 1/1 error: Error running apply: exit status 1

        Error: creating Route53 Resolver Rule: InvalidRequestException: [RSLVR-00718] Cannot create a rule with type RECURSIVE

          with aws_route53_resolver_rule.recursive,
          on terraform_plugin_test.tf line 73, in resource "aws_route53_resolver_rule" "recursive":
          73: resource "aws_route53_resolver_rule" "recursive" {

--- FAIL: TestAccRoute53ResolverRulesDataSource_resolverEndpointID (229.59s)
=== CONT  TestAccRoute53ResolverRule_updateName
--- PASS: TestAccRoute53ResolverRule_updateName (29.13s)
=== CONT  TestAccRoute53ResolverRuleDataSource_resolverEndpointIdWithTags
--- PASS: TestAccRoute53ResolverRule_forward (275.42s)
--- PASS: TestAccRoute53ResolverRule_forwardEndpointRecreate (470.91s)
--- PASS: TestAccRoute53ResolverRuleDataSource_resolverEndpointIdWithTags (240.73s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver	556.632s
FAIL
make: *** [testacc] Error 1