resource/aws_sfn_state_machine: Handle IAM role eventual consistency on creation + wait for delete + add `arn` attribute (#12005)
Output from acceptance testing (unrelated consistent test failure due to #12506):

```
--- PASS: TestAccAWSSfnStateMachine_tags (55.38s)
--- FAIL: TestAccAWSSfnStateMachine_createUpdate (61.93s)
--- PASS: TestAccAWSSfnStateMachine_disappears (67.31s)
```