tests/resource/aws_ec2_capacity_reservation: Implement PreCheck for EC2 Capacity Reservation support
EC2 Capacity Reservation is a newer resource type that is not supported in all AWS regions and partitions. Here we implement a PreCheck function to skip their acceptance tests until they are supported instead of failing.

Previous output from acceptance testing (AWS GovCloud (US)):

```
--- FAIL: TestAccAWSEc2CapacityReservation_basic (0.54s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_ec2_capacity_reservation.test: 1 error occurred:
        	* aws_ec2_capacity_reservation.test: Error creating EC2 Capacity Reservation: UnsupportedOperation: The functionality you requested is not available in this region.
```

Output from acceptance testing (AWS GovCloud (US)):

```
--- SKIP: TestAccAWSEc2CapacityReservation_basic (1.74s)
--- SKIP: TestAccAWSEc2CapacityReservation_ebsOptimized (1.71s)
--- SKIP: TestAccAWSEc2CapacityReservation_endDate (1.71s)
--- SKIP: TestAccAWSEc2CapacityReservation_endDateType (1.77s)
--- SKIP: TestAccAWSEc2CapacityReservation_ephemeralStorage (1.77s)
--- SKIP: TestAccAWSEc2CapacityReservation_instanceCount (1.74s)
--- SKIP: TestAccAWSEc2CapacityReservation_instanceMatchCriteria (1.74s)
--- SKIP: TestAccAWSEc2CapacityReservation_instanceType (1.78s)
--- SKIP: TestAccAWSEc2CapacityReservation_tags (1.74s)

PASS
ok    github.com/terraform-providers/terraform-provider-aws/aws 3.838s
```

Output from acceptance testing (AWS Standard):

```
--- PASS: TestAccAWSEc2CapacityReservation_basic (14.43s)
```