tests/service/xray: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSXraySamplingRule_basic (0.76s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating XRay Sampling Rule: RequestError: send request failed
        caused by: Post https://xray.us-gov-west-1.amazonaws.com/CreateSamplingRule: dial tcp: lookup xray.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSXraySamplingRule_update (7.17s)
    resource_aws_xray_sampling_rule_test.go:163: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://xray.us-gov-west-1.amazonaws.com/GetSamplingRules: dial tcp: lookup xray.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSXraySamplingRule_basic (7.17s)
    resource_aws_xray_sampling_rule_test.go:163: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://xray.us-gov-west-1.amazonaws.com/GetSamplingRules: dial tcp: lookup xray.us-gov-west-1.amazonaws.com: no such host
```