tests/resource/aws_datasync_location_smb: Simplify and update base configuration (#15951)
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/15950

DataSync SMB Locations do not need a valid SMB endpoint to be created, so we remove the extra configuration which was problematic due to Storage Gateway.

Previously:

```
=== CONT  TestAccAWSDataSyncLocationSmb_basic
TestAccAWSDataSyncLocationSmb_basic: resource_aws_datasync_location_smb_test.go:87: Step 1/2 error: Error running apply: 2020/10/30 21:12:22 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: error retrieving activation key from IP Address (52.43.34.79): error making HTTP request: Get "http://52.43.34.79/?activationRegion=us-west-2": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
--- FAIL: TestAccAWSDataSyncLocationSmb_basic (698.97s)

=== CONT  TestAccAWSDataSyncLocationSmb_disappears
TestAccAWSDataSyncLocationSmb_disappears: resource_aws_datasync_location_smb_test.go:120: Step 1/1 error: Error running apply: 2020/10/30 21:13:15 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: error retrieving activation key from IP Address (52.12.135.60): error making HTTP request: Get "http://52.12.135.60/?activationRegion=us-west-2": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
--- FAIL: TestAccAWSDataSyncLocationSmb_disappears (696.98s)

=== CONT  TestAccAWSDataSyncLocationSmb_Tags
TestAccAWSDataSyncLocationSmb_Tags: resource_aws_datasync_location_smb_test.go:141: Step 1/4 error: Error running apply: 2020/10/30 21:13:23 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: error retrieving activation key from IP Address (52.41.144.141): error making HTTP request: Get "http://52.41.144.141/?activationRegion=us-west-2": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
--- FAIL: TestAccAWSDataSyncLocationSmb_Tags (697.96s)

=== CONT  TestAccAWSDataSyncLocationSmb_Tags
TestAccAWSDataSyncLocationSmb_Tags: resource_aws_datasync_location_smb_test.go:141: Step 1/4 error: Error running apply:
Error: expected HTTP status code 302, received: 500
--- FAIL: TestAccAWSDataSyncLocationSmb_Tags (330.19s)

=== CONT  TestAccAWSDataSyncLocationSmb_basic
TestAccAWSDataSyncLocationSmb_basic: resource_aws_datasync_location_smb_test.go:87: Step 1/2 error: Error running apply:
Error: expected HTTP status code 302, received: 500
--- FAIL: TestAccAWSDataSyncLocationSmb_basic (522.60s)

=== CONT  TestAccAWSDataSyncLocationSmb_disappears
TestAccAWSDataSyncLocationSmb_disappears: resource_aws_datasync_location_smb_test.go:120: Step 1/1 error: Error running apply:
Error: expected HTTP status code 302, received: 500
--- FAIL: TestAccAWSDataSyncLocationSmb_disappears (513.09s)
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSDataSyncLocationSmb_basic (166.60s)
--- PASS: TestAccAWSDataSyncLocationSmb_disappears (187.80s)
--- PASS: TestAccAWSDataSyncLocationSmb_Tags (211.25s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSDataSyncLocationSmb_disappears (162.12s)
--- PASS: TestAccAWSDataSyncLocationSmb_basic (184.29s)
--- PASS: TestAccAWSDataSyncLocationSmb_Tags (235.60s)
```