r/aws_opensearch_domain: handle unset auto_tune_options.rollback_on_disable
Previously omitting this optional argument resulted in a failure when creating or updating the domain:

```
Error: modifying config for OpenSearch Domain: ValidationException: 1 validation error detected: Value '' at 'autoTuneOptions.rollbackOnDisable' failed to satisfy constraint: Member must satisfy enum value set: [DEFAULT_ROLLBACK, NO_ROLLBACK]
```

The `auto_tune_options` expander logic has been updated to properly handle cases where `rollback_on_disable` is unset.

```console
% make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_autoTuneOptions
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/opensearch/... -v -count 1 -parallel 20 -run='TestAccOpenSearchDomain_autoTuneOptions'  -timeout 360m

--- PASS: TestAccOpenSearchDomain_autoTuneOptions (1915.20s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearch 1920.265s
```