tests/resource/aws_db_instance: Use Terraform 0.11.12 and later compatible file hashing function
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSDBInstance_S3Import (1.82s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of ../files/mysql-5-6-xtrabackup.tar.gz are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
```

Output from Terraform 0.11.12 acceptance testing (same test failure as previously):

```
--- FAIL: TestAccAWSDBInstance_S3Import (709.69s)
    testing.go:568: Step 0 error: errors during apply:

        Error: unexpected state 'incompatible-restore', wanted target 'available, storage-optimization'. last error: %!s(<nil>)
```

Output from Terraform 0.12 acceptance testing (same test failure as previously):

```
--- FAIL: TestAccAWSDBInstance_S3Import (708.87s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_db_instance.s3: 1 error occurred:
        	* aws_db_instance.s3: unexpected state 'incompatible-restore', wanted target 'available, storage-optimization'. last error: %!s(<nil>)
```