tests/resource/aws_db_parameter_group: Update TestAccAWSDBParameterGroup_limit syntax for 0.12
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSDBParameterGroup_limit (0.46s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test375589049/main.tf:7,62-67: Invalid single-argument block definition; A single-line block definition must end with a closing brace immediately after its single argument definition.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- FAIL: TestAccAWSDBParameterGroup_limit (15.12s)
    testing.go:568: Step 0 error: Check failed: Check 57/87 error: aws_db_parameter_group.large: Attribute 'parameter.1937131004.value' expected "on", got "ON"
```