r/aws_vpc_peering_connection_accepter: Tidy up. r/aws_vpc_peering_connection_options: Tidy up.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccEC2VPCPeeringConnection_\|TestAccEC2VPCPeeringConnectionOptions_\|TestAccEC2VPCPeeringConnectionAccepter_' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2VPCPeeringConnection_\|TestAccEC2VPCPeeringConnectionOptions_\|TestAccEC2VPCPeeringConnectionAccepter_ -timeout 180m
=== RUN   TestAccEC2VPCPeeringConnectionAccepter_sameRegionSameAccount
=== PAUSE TestAccEC2VPCPeeringConnectionAccepter_sameRegionSameAccount
=== RUN   TestAccEC2VPCPeeringConnectionAccepter_differentRegionSameAccount
=== PAUSE TestAccEC2VPCPeeringConnectionAccepter_differentRegionSameAccount
=== RUN   TestAccEC2VPCPeeringConnectionAccepter_sameRegionDifferentAccount
=== PAUSE TestAccEC2VPCPeeringConnectionAccepter_sameRegionDifferentAccount
=== RUN   TestAccEC2VPCPeeringConnectionAccepter_differentRegionDifferentAccount
=== PAUSE TestAccEC2VPCPeeringConnectionAccepter_differentRegionDifferentAccount
=== RUN   TestAccEC2VPCPeeringConnectionOptions_basic
=== PAUSE TestAccEC2VPCPeeringConnectionOptions_basic
=== RUN   TestAccEC2VPCPeeringConnectionOptions_differentRegionSameAccount
=== PAUSE TestAccEC2VPCPeeringConnectionOptions_differentRegionSameAccount
=== RUN   TestAccEC2VPCPeeringConnectionOptions_sameRegionDifferentAccount
=== PAUSE TestAccEC2VPCPeeringConnectionOptions_sameRegionDifferentAccount
=== RUN   TestAccEC2VPCPeeringConnection_basic
=== PAUSE TestAccEC2VPCPeeringConnection_basic
=== RUN   TestAccEC2VPCPeeringConnection_disappears
=== PAUSE TestAccEC2VPCPeeringConnection_disappears
=== RUN   TestAccEC2VPCPeeringConnection_tags
=== PAUSE TestAccEC2VPCPeeringConnection_tags
=== RUN   TestAccEC2VPCPeeringConnection_options
=== PAUSE TestAccEC2VPCPeeringConnection_options
=== RUN   TestAccEC2VPCPeeringConnection_failedState
=== PAUSE TestAccEC2VPCPeeringConnection_failedState
=== RUN   TestAccEC2VPCPeeringConnection_peerRegionAutoAccept
=== PAUSE TestAccEC2VPCPeeringConnection_peerRegionAutoAccept
=== RUN   TestAccEC2VPCPeeringConnection_region
=== PAUSE TestAccEC2VPCPeeringConnection_region
=== RUN   TestAccEC2VPCPeeringConnection_accept
=== PAUSE TestAccEC2VPCPeeringConnection_accept
=== RUN   TestAccEC2VPCPeeringConnection_optionsNoAutoAccept
=== PAUSE TestAccEC2VPCPeeringConnection_optionsNoAutoAccept
=== CONT  TestAccEC2VPCPeeringConnectionAccepter_sameRegionSameAccount
=== CONT  TestAccEC2VPCPeeringConnection_disappears
=== CONT  TestAccEC2VPCPeeringConnectionOptions_basic
--- PASS: TestAccEC2VPCPeeringConnection_disappears (30.57s)
=== CONT  TestAccEC2VPCPeeringConnectionAccepter_sameRegionDifferentAccount
    acctest.go:599: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccEC2VPCPeeringConnectionAccepter_sameRegionDifferentAccount (0.05s)
=== CONT  TestAccEC2VPCPeeringConnectionAccepter_differentRegionDifferentAccount
    acctest.go:599: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccEC2VPCPeeringConnectionAccepter_differentRegionDifferentAccount (0.05s)
=== CONT  TestAccEC2VPCPeeringConnection_basic
--- PASS: TestAccEC2VPCPeeringConnectionAccepter_sameRegionSameAccount (35.20s)
=== CONT  TestAccEC2VPCPeeringConnectionOptions_sameRegionDifferentAccount
    acctest.go:599: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccEC2VPCPeeringConnectionOptions_sameRegionDifferentAccount (0.05s)
=== CONT  TestAccEC2VPCPeeringConnectionAccepter_differentRegionSameAccount
--- PASS: TestAccEC2VPCPeeringConnection_basic (33.82s)
=== CONT  TestAccEC2VPCPeeringConnectionOptions_differentRegionSameAccount
--- PASS: TestAccEC2VPCPeeringConnectionOptions_basic (73.77s)
=== CONT  TestAccEC2VPCPeeringConnection_options
--- PASS: TestAccEC2VPCPeeringConnectionAccepter_differentRegionSameAccount (41.45s)
=== CONT  TestAccEC2VPCPeeringConnection_peerRegionAutoAccept
--- PASS: TestAccEC2VPCPeeringConnection_peerRegionAutoAccept (14.34s)
=== CONT  TestAccEC2VPCPeeringConnection_failedState
--- PASS: TestAccEC2VPCPeeringConnection_failedState (16.04s)
=== CONT  TestAccEC2VPCPeeringConnection_optionsNoAutoAccept
--- PASS: TestAccEC2VPCPeeringConnection_optionsNoAutoAccept (29.37s)
=== CONT  TestAccEC2VPCPeeringConnection_region
--- PASS: TestAccEC2VPCPeeringConnection_options (68.49s)
=== CONT  TestAccEC2VPCPeeringConnection_tags
--- PASS: TestAccEC2VPCPeeringConnectionOptions_differentRegionSameAccount (80.40s)
=== CONT  TestAccEC2VPCPeeringConnection_accept
--- PASS: TestAccEC2VPCPeeringConnection_region (37.49s)
=== CONT  TestAccEC2VPCPeeringConnection_accept
    vpc_peering_connection_test.go:341: Step 2/4 error: Check failed: Check 2/2 error: aws_vpc_peering_connection.test: Attribute 'accept_status' expected "active", got "pending-acceptance"
--- FAIL: TestAccEC2VPCPeeringConnection_accept (42.74s)
--- PASS: TestAccEC2VPCPeeringConnection_tags (77.39s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	223.670s
FAIL
make: *** [testacc] Error 1