tests/data-source/aws_cloudformation_stack: Fix outputs.VPCId handling for longer VPC IDs
AWS switched to longer IDs at some point and we don't particularly care how long they are.

Previously:

```
--- FAIL: TestAccAWSCloudFormationStack_dataSource_basic (64.08s)
    testing.go:527: Step 0 error: Check failed: Check 2/11 error: data.aws_cloudformation_stack.network: Attribute 'outputs.VPCId' didn't match "^vpc-[a-z0-9]{8}$", got "vpc-06a0f633be3839442"
--- FAIL: TestAccAWSCloudFormationStack_dataSource_yaml (54.21s)
    testing.go:527: Step 0 error: Check failed: Check 2/11 error: data.aws_cloudformation_stack.yaml: Attribute 'outputs.VPCId' didn't match "^vpc-[a-z0-9]{8}$", got "vpc-05022ffdfe3c092f8"
```

Now:

```
--- PASS: TestAccAWSCloudFormationStack_dataSource_basic (72.94s)
--- PASS: TestAccAWSCloudFormationStack_dataSource_yaml (72.08s)
```