tests/resource/aws_dms_replication_instance: Generate TestAccAWSDmsReplicationInstance_EngineVersion Steps
This acceptance test is designed to test engine version upgrades. Over time, DMS replication instance engine versions are deprecated so they will eventually error on resource creation, e.g.

```
InvalidParameterValueException: No replication engine found with version: 2.4.2
```

During the `PreCheck`, we will find two candidate engine versions from the orderable replication instances and generate the relevant `resource.TestStep`. We prefer this method over creating a plural data source that seems impractical for real world usage.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSDmsReplicationInstance_EngineVersion (1.75s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_dms_replication_instance.test: 1 error occurred:
        	* aws_dms_replication_instance.test: error creating DMS Replication Instance: InvalidParameterValueException: No replication engine found with version: 2.4.2
        	status code: 400, request id: fd8e5b9a-fd56-11e8-acad-e361fb652d8c
```

New output from acceptance testing:

```
--- PASS: TestAccAWSDmsReplicationInstance_EngineVersion (554.18s)
```