r/aws_vpc_security_group_ingress_rule: Add 'TestAccVPCSecurityGroupIngressRule_tags'.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccVPCSecurityGroupIngressRule_tags' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCSecurityGroupIngressRule_tags -timeout 180m
=== RUN   TestAccVPCSecurityGroupIngressRule_tags
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags
=== CONT  TestAccVPCSecurityGroupIngressRule_tags
    vpc_security_group_ingress_rule_test.go:82: Step 3/4 error: Error running apply: exit status 1

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_vpc_security_group_ingress_rule.test.tags_all. All values must be known
        after apply, so this is always a bug in the provider and should be reported
        in the provider's own repository. Terraform will still save the other known
        object values in the state.
--- FAIL: TestAccVPCSecurityGroupIngressRule_tags (31.14s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	35.800s
FAIL
make: *** [testacc] Error 1