tests/service/dlm: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSDlmLifecyclePolicy_Basic (1.40s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating DLM Lifecycle Policy: RequestError: send request failed
        caused by: Post https://dlm.us-gov-west-1.amazonaws.com/policies: dial tcp: lookup dlm.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSDlmLifecyclePolicy_Basic (1.97s)
    resource_aws_dlm_lifecycle_policy_test.go:158: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://dlm.us-gov-west-1.amazonaws.com/policies: dial tcp: lookup dlm.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSDlmLifecyclePolicy_Full (1.97s)
    resource_aws_dlm_lifecycle_policy_test.go:158: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://dlm.us-gov-west-1.amazonaws.com/policies: dial tcp: lookup dlm.us-gov-west-1.amazonaws.com: no such host
```