tests/resource/aws_ses_active_receipt_rule_set: Serialize testing
Since there can only be one active Receipt Rule Set, previously received these types of errors when ran in parallel:

```
=== CONT  TestAccAWSSESActiveReceiptRuleSet_basic
TestAccAWSSESActiveReceiptRuleSet_basic: resource_aws_ses_active_receipt_rule_set_test.go:18: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
# aws_ses_active_receipt_rule_set.test will be updated in-place
~ resource "aws_ses_active_receipt_rule_set" "test" {
id            = "tf-acc-test-200923444865777778"
~ rule_set_name = "tf-acc-test-3328795909966366230" -> "tf-acc-test-200923444865777778"
}
Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAWSSESActiveReceiptRuleSet_basic (28.83s)

=== CONT  TestAccAWSSESActiveReceiptRuleSet_basic
TestAccAWSSESActiveReceiptRuleSet_basic: resource_aws_ses_active_receipt_rule_set_test.go:18: After applying this test step and performing a `terraform refresh`, the plan was not empty.
stdout
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
# aws_ses_active_receipt_rule_set.test will be created
+ resource "aws_ses_active_receipt_rule_set" "test" {
+ id            = (known after apply)
+ rule_set_name = "tf-acc-test-4001499284644559282"
}
Plan: 1 to add, 0 to change, 0 to destroy.
--- FAIL: TestAccAWSSESActiveReceiptRuleSet_basic (34.83s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSSESActiveReceiptRuleSet_serial (27.75s)
    --- PASS: TestAccAWSSESActiveReceiptRuleSet_serial/basic (14.81s)
    --- PASS: TestAccAWSSESActiveReceiptRuleSet_serial/disappears (12.94s)
```