tests/service/secretsmanager: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAwsSecretsManagerSecret_Basic (0.57s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Secrets Manager Secret: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAwsSecretsManagerSecret_Basic (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecretVersion_VersionStages (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecretVersion_Base64Binary (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecret_Name (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_withNamePrefix (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecretVersion_Basic (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_RotationRules (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_KmsKeyID (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_RecoveryWindowInDays_Recreate (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_Tags (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecretVersion_VersionStage (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_policy (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecretVersion_VersionID (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecret_Policy (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecret_ARN (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecretVersion_BasicString (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_Description (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsSecretsManagerSecret_Basic (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsSecretsManagerSecret_RotationLambdaARN (2.56s)
    resource_aws_secretsmanager_secret_test.go:513: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://secretsmanager.us-gov-west-1.amazonaws.com/: dial tcp: lookup secretsmanager.us-gov-west-1.amazonaws.com: no such host
```