tests/provider: Use SDK v2 compliant ExpectError conditions (#14434)
The `config is invalid:` prefix is no longer present in Terraform Plugin SDK v2. e.g.

```
TestAccAWSAcmCertificate_root_TrailingPeriod: resource_aws_acm_certificate_test.go:258: Expected an error with pattern, no match on: terraform failed: exit status 1
stderr:
Error: invalid value for domain_name (cannot end with a period)
on config733606703/terraform_plugin_test.tf line 3, in resource "aws_acm_certificate" "cert":
3:   domain_name       = "--OMITTED--"
--- FAIL: TestAccAWSAcmCertificate_root_TrailingPeriod (4.02s)
```

Output from acceptance testing (V1):

```
--- PASS: TestAccAWSAcmCertificate_root_TrailingPeriod (0.85s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithFilter_Empty (0.85s)
--- PASS: TestAccAWSS3BucketAnalyticsConfiguration_WithStorageClassAnalysis_Empty (0.94s)
--- PASS: TestAccAWSSESDomainIdentity_trailingPeriod (1.17s)
```