provider: Convert and enforce most data sources to AWS Go SDK pointer conversion functions during assignment (#17749)
* provider: Convert and enforce most data sources to AWS Go SDK pointer conversion functions during assignment

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/12992

This work is being done in chunks to reduce review burden. Avoiding `aws_route_table` data source due to large pull request pending review.

Previously:

```
aws/data_source_aws_cloudfront_origin_request_policy.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
131:		originRequestPolicy := *resp.OriginRequestPolicy.OriginRequestPolicyConfig

aws/data_source_aws_db_instance.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
240:	dbInstance := *resp.DBInstances[0]

aws/data_source_aws_ebs_volume.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
125:	itime := *a[i].CreateTime
--------------------------------------------------------------------------------
126:	jtime := *a[j].CreateTime

aws/data_source_aws_ec2_managed_prefix_list.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
104:	pl := *out.PrefixLists[0]

aws/data_source_aws_ecs_container_definition.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
78:	taskDefinition := *desc.TaskDefinition

aws/data_source_aws_ecs_task_definition.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
59:	taskDefinition := *desc.TaskDefinition

aws/data_source_aws_eip.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
139:	region := *conn.Config.Region

aws/data_source_aws_instance.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
505:		monitoringState := *instance.Monitoring.State

aws/data_source_aws_mq_broker.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
214:			nextToken = *out.NextToken

aws/data_source_aws_prefix_list.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
71:		cidrs[i] = *v

aws/data_source_aws_redshift_cluster.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
192:	rsc := *resp.Clusters[0]

aws/data_source_aws_route53_resolver_rule.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
123:	arn := *rule.Arn

aws/data_source_aws_s3_bucket_object.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
219:			contentType = *out.ContentType

aws/data_source_aws_ssm_patch_baseline.go
severity:warning rule:prefer-aws-go-sdk-pointer-conversion-assignment: Prefer AWS Go SDK pointer conversion functions for dereferencing during assignment, e.g. aws.StringValue()
108:	baseline := *filteredBaselines[0]
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudFrontDataSourceOriginRequestPolicy_basic (14.90s)

--- PASS: TestAccAWSDataSourceRedshiftCluster_basic (338.01s)
--- PASS: TestAccAWSDataSourceRedshiftCluster_logging (461.02s)
--- PASS: TestAccAWSDataSourceRedshiftCluster_vpc (1007.17s)

--- PASS: TestAccAWSDbInstanceDataSource_basic (541.75s)
--- PASS: TestAccAWSDbInstanceDataSource_ec2Classic (428.74s)

--- PASS: TestAccAWSEbsVolumeDataSource_basic (26.76s)
--- PASS: TestAccAWSEbsVolumeDataSource_multipleFilters (28.34s)

--- PASS: TestAccAWSEcsDataSource_ecsCluster (25.22s)
--- PASS: TestAccAWSEcsDataSource_ecsClusterContainerInsights (27.43s)
--- PASS: TestAccAWSEcsDataSource_ecsContainerDefinition (85.07s)
--- PASS: TestAccAWSEcsDataSource_ecsTaskDefinition (14.90s)

--- PASS: TestAccAWSInstanceDataSource_AzUserData (87.68s)
--- PASS: TestAccAWSInstanceDataSource_basic (107.50s)
--- PASS: TestAccAWSInstanceDataSource_blockDevices (117.28s)
--- PASS: TestAccAWSInstanceDataSource_blockDeviceTags (72.21s)
--- PASS: TestAccAWSInstanceDataSource_creditSpecification (99.16s)
--- PASS: TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId (109.93s)
--- PASS: TestAccAWSInstanceDataSource_enclaveOptions (129.58s)
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_falseToTrue (174.55s)
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_trueToFalse (207.17s)
--- PASS: TestAccAWSInstanceDataSource_GetUserData (176.78s)
--- PASS: TestAccAWSInstanceDataSource_GetUserData_NoUserData (188.74s)
--- PASS: TestAccAWSInstanceDataSource_gp2IopsDevice (116.35s)
--- PASS: TestAccAWSInstanceDataSource_gp3ThroughputDevice (138.11s)
--- PASS: TestAccAWSInstanceDataSource_keyPair (95.12s)
--- PASS: TestAccAWSInstanceDataSource_metadataOptions (126.18s)
--- PASS: TestAccAWSInstanceDataSource_PlacementGroup (106.32s)
--- PASS: TestAccAWSInstanceDataSource_privateIP (105.60s)
--- PASS: TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId (99.53s)
--- PASS: TestAccAWSInstanceDataSource_rootInstanceStore (116.08s)
--- PASS: TestAccAWSInstanceDataSource_secondaryPrivateIPs (97.97s)
--- PASS: TestAccAWSInstanceDataSource_SecurityGroups (100.32s)
--- PASS: TestAccAWSInstanceDataSource_tags (104.63s)
--- PASS: TestAccAWSInstanceDataSource_VPC (128.18s)
--- PASS: TestAccAWSInstanceDataSource_VPCSecurityGroups (104.24s)

--- FAIL: TestAccAWSRoute53ResolverRuleDataSource_SharedByMe (245.06s) # https://github.com/hashicorp/terraform-provider-aws/issues/17748
--- FAIL: TestAccAWSRoute53ResolverRuleDataSource_SharedWithMe (244.80s) # https://github.com/hashicorp/terraform-provider-aws/issues/17748
--- PASS: TestAccAWSRoute53ResolverRuleDataSource_basic (39.01s)
--- PASS: TestAccAWSRoute53ResolverRuleDataSource_ResolverEndpointIdWithTags (245.76s)

--- PASS: TestAccAWSSsmPatchBaselineDataSource_existingBaseline (12.32s)
--- PASS: TestAccAWSSsmPatchBaselineDataSource_newBaseline (13.36s)

--- PASS: TestAccDataSourceAwsEc2ManagedPrefixList_basic (21.32s)
--- PASS: TestAccDataSourceAwsEc2ManagedPrefixList_filter (21.14s)
--- PASS: TestAccDataSourceAwsEc2ManagedPrefixList_matchesTooMany (2.87s)

--- PASS: TestAccDataSourceAWSEIP_CarrierIP (23.38s)
--- PASS: TestAccDataSourceAWSEIP_Filter (15.90s)
--- PASS: TestAccDataSourceAWSEIP_Id (15.69s)
--- PASS: TestAccDataSourceAWSEIP_Instance (136.26s)
--- PASS: TestAccDataSourceAWSEIP_NetworkInterface (75.80s)
--- PASS: TestAccDataSourceAWSEIP_PublicIP_EC2Classic (8.65s)
--- PASS: TestAccDataSourceAWSEIP_PublicIP_VPC (13.56s)
--- PASS: TestAccDataSourceAWSEIP_Tags (18.22s)
--- SKIP: TestAccDataSourceAWSEIP_CustomerOwnedIpv4Pool (1.43s)

--- PASS: TestAccDataSourceAWSMqBroker_basic (1171.78s)

--- PASS: TestAccDataSourceAwsPrefixList_basic (15.86s)
--- PASS: TestAccDataSourceAwsPrefixList_filter (15.64s)
--- PASS: TestAccDataSourceAwsPrefixList_nameDoesNotOverrideFilter (2.38s)

--- PASS: TestAccDataSourceAWSS3BucketObject_allParams (31.42s)
--- PASS: TestAccDataSourceAWSS3BucketObject_basic (30.11s)
--- PASS: TestAccDataSourceAWSS3BucketObject_basicViaAccessPoint (31.43s)
--- PASS: TestAccDataSourceAWSS3BucketObject_kmsEncrypted (31.19s)
--- PASS: TestAccDataSourceAWSS3BucketObject_LeadingSlash (53.90s)
--- PASS: TestAccDataSourceAWSS3BucketObject_MultipleSlashes (52.83s)
--- PASS: TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOff (31.63s)
--- PASS: TestAccDataSourceAWSS3BucketObject_ObjectLockLegalHoldOn (33.57s)
--- PASS: TestAccDataSourceAWSS3BucketObject_readableBody (31.01s)
--- PASS: TestAccDataSourceAWSS3BucketObject_SingleSlashAsKey (28.06s)
```

* data-source/aws_cloudfront_origin_request_policy: Fix staticcheck report

Previously:

```
aws/data_source_aws_cloudfront_origin_request_policy.go:129:38: SA5011: possible nil pointer dereference (staticcheck)
		d.Set("etag", aws.StringValue(resp.ETag))
		                                   ^
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudFrontDataSourceOriginRequestPolicy_basic (10.93s)
```