tests/service/elastictranscoder: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSElasticTranscoderPreset_basic (0.66s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Elastic Transcoder Preset: RequestError: send request failed
        caused by: Post https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/presets: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSElasticTranscoderPreset_basic (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticTranscoderPipeline_withContentConfig (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticTranscoderPipeline_notifications (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticTranscoderPipeline_kmsKey (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticTranscoderPreset_import (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticTranscoderPipeline_basic (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSElasticTranscoderPipeline_withPermissions (2.40s)
    resource_aws_elastic_transcoder_pipeline_test.go:247: skipping acceptance testing: RequestError: send request failed
        caused by: Get https://elastictranscoder.us-gov-west-1.amazonaws.com/2012-09-25/pipelines: dial tcp: lookup elastictranscoder.us-gov-west-1.amazonaws.com: no such host
```