tests/service/budgets: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSBudgetsBudget_basic (0.61s)
    testing.go:568: Step 0 error: errors during apply:

        Error: create budget failed: RequestError: send request failed
        caused by: Post https://budgets.us-gov-west-1.amazonaws.com/: dial tcp: lookup budgets.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSBudgetsBudget_prefix (2.40s)
    resource_aws_budgets_budget_test.go:349: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://budgets.us-gov-west-1.amazonaws.com/: dial tcp: lookup budgets.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBudgetsBudget_notification (2.40s)
    resource_aws_budgets_budget_test.go:349: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://budgets.us-gov-west-1.amazonaws.com/: dial tcp: lookup budgets.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSBudgetsBudget_basic (2.40s)
    resource_aws_budgets_budget_test.go:349: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://budgets.us-gov-west-1.amazonaws.com/: dial tcp: lookup budgets.us-gov-west-1.amazonaws.com: no such host
```