tests/provider: Temporarily use expanded data.aws_availability_zones.available.names references
As well as remove extraneous references in RDS Cluster testing where possible. This change is backwards (0.11) and forwards (0.12) compatible. Its not pretty, but is a workaround for a lack of a simple cross-compatible unknown TypeList to TypeList reference until the provider test configurations are eventually migrated to 0.12 only syntax.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAutoscalingPolicy_basic (2.89s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test226640772/main.tf line 21:
          (source code not available)

        Inappropriate value for attribute "availability_zones": element 0: string
        required.
```

Output from Terraform 0.11 acceptance testing:

```
--- PASS: TestAccAWSAutoscalingPolicy_basic (42.40s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAwsAutoScalingGroupDataSource_basic (50.28s)
--- PASS: TestAccAWSAutoscalingPolicy_disappears (44.22s)
--- PASS: TestAccAWSAutoscalingPolicy_SimpleScalingStepAdjustment (48.61s)
--- PASS: TestAccAWSAutoscalingPolicy_upgrade (48.66s)
--- PASS: TestAccAWSAutoscalingPolicy_TargetTrack_Custom (56.13s)
--- PASS: TestAccAWSAutoscalingPolicy_zerovalue (74.47s)
--- PASS: TestAccAWSAutoscalingPolicy_basic (81.88s)
--- PASS: TestAccAWSAutoscalingPolicy_TargetTrack_Predefined (84.55s)
--- PASS: TestAccAWSNeptuneClusterInstance_withaz (816.01s)
--- PASS: TestAccAWSRDSCluster_EngineVersion (67.60s)
--- PASS: TestAccAWSRDSCluster_Port (251.66s)
--- PASS: TestAccAWSRDSClusterInstance_az (817.02s)
--- PASS: TestAccAWSRDSCluster_EngineVersionWithPrimaryInstance (1207.86s)
```