r/aws_vpc_security_group_ingress_rule: Add 'TestAccVPCSecurityGroupIngressRule_cidrIPv6'.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccVPCSecurityGroupIngressRule_cidrIPv6' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCSecurityGroupIngressRule_cidrIPv6 -timeout 180m
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv6
    vpc_security_group_ingress_rule_test.go:247: Step 3/3 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_vpc_security_group_ingress_rule.test will be updated in-place
          ~ resource "aws_vpc_security_group_ingress_rule" "test" {
              - from_port              = -1 -> null
                id                     = "sgr-079d32952e988e709"
              - to_port                = -1 -> null
                # (6 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccVPCSecurityGroupIngressRule_cidrIPv6 (61.00s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	71.852s
FAIL
make: *** [testacc] Error 1