tests/resource/aws_lb_listener_certificate: Use TLS provider instead of hardcoded certificates
Previous output from acceptance testing (starting December 18, 2018):

```
--- FAIL: TestAccAwsLbListenerCertificate_basic (186.13s)
    testing.go:538: Step 0 error: Error applying: 4 errors occurred:
        	* aws_iam_server_certificate.additional_2: 1 error occurred:
        	* aws_iam_server_certificate.additional_2: Error uploading server certificate, error: MalformedCertificate: Certificate is no longer valid. The 'Not After' date restriction on the certificate has passed.

        	* aws_iam_server_certificate.additional_1: 1 error occurred:
        	* aws_iam_server_certificate.additional_1: Error uploading server certificate, error: MalformedCertificate: Certificate is no longer valid. The 'Not After' date restriction on the certificate has passed.

        	* aws_iam_server_certificate.additional_3: 1 error occurred:
        	* aws_iam_server_certificate.additional_3: Error uploading server certificate, error: MalformedCertificate: Certificate is no longer valid. The 'Not After' date restriction on the certificate has passed.

        	* aws_iam_server_certificate.default: 1 error occurred:
        	* aws_iam_server_certificate.default: Error uploading server certificate, error: MalformedCertificate: Certificate is no longer valid. The 'Not After' date restriction on the certificate has passed.
```

Output from acceptance testing:

```
--- PASS: TestAccAwsLbListenerCertificate_basic (189.06s)
--- PASS: TestAccAwsLbListenerCertificate_cycle (236.43s)
```