tests/resource/aws_rds_cluster: Terraform 0.12 compatible fixes for TestAccAWSRDSCluster_EncryptedCrossRegionReplication
Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSRDSCluster_EncryptedCrossRegionReplication (0.74s)
    testing.go:568: Step 0 error: config is invalid: Incorrect attribute value type: Inappropriate value for attribute "availability_zones": element 0: string required.

--- FAIL: TestAccAWSRDSCluster_EncryptedCrossRegionReplication (4.69s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test744740497/main.tf line 93:
          (source code not available)

        Inappropriate value for attribute "subnet_ids": element 0: string required.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSRDSCluster_EncryptedCrossRegionReplication (1570.28s)
```