tests/resource/aws_backup_plan: Add missing equals sign for tags configuration
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 Provider SDK acceptance testing:

```
--- FAIL: TestAccAwsBackupPlan_withTags (1.08s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "tags" are not expected here. Did you mean to define argument "tags"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 Provider SDK acceptance testing:

```
--- PASS: TestAccAwsBackupPlan_withTags (40.92s)
```