tests/service/cognitoidentity: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSCognitoIdentityPool_basic (1.11s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Cognito Identity Pool: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSCognitoIdentityPoolRolesAttachment_basic (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPool_supportedLoginProviders (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPool_samlProviderArns (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPool_openidConnectProviderArns (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithRulesTypeError (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPool_basic (2.25s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPool_importBasic (2.25s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithTokenTypeError (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPool_cognitoIdentityProviders (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithAmbiguousRoleResolutionError (2.24s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappings (2.25s)
    resource_aws_cognito_identity_pool_test.go:272: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://cognito-identity.us-gov-west-1.amazonaws.com/: dial tcp: lookup cognito-identity.us-gov-west-1.amazonaws.com: no such host
```