r/aws_bedrock_inference_profile(test): replace hardcoded foundation model
Now uses the foundation model data source rather than a hardcoded ARN,
which was causing all acceptance tests for this resource to fail with an
error like the following.

```console
=== CONT  TestAccBedrockInferenceProfile_tags
    inference_profile_tags_gen_test.go:30: Step 1/8 error: Error running apply: exit status 1

        Error: creating Amazon Bedrock Inference Profile ("tf-acc-test-8528140228953212908"): operation error Bedrock: CreateInferenceProfile, https response error StatusCode: 403, RequestID: c1455bb3-d32e-4ffe-956f-93411b8c0eed, AccessDeniedException: The provided model identifier is invalid.

          with aws_bedrock_inference_profile.test,
          on main_gen.tf line 4, in resource "aws_bedrock_inference_profile" "test":
           4: resource "aws_bedrock_inference_profile" "test" {

        operation error Bedrock: CreateInferenceProfile, https response error
        StatusCode: 403, RequestID: c1455bb3-d32e-4ffe-956f-93411b8c0eed,
        AccessDeniedException: The provided model identifier is invalid.
--- FAIL: TestAccBedrockInferenceProfile_tags (54.32s)
```