resource/aws_opsworks_application: Ensure app_source, environment, and ssl_configuration configurations omit equals in testing and documentation
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSOpsworksApplication (0.44s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test607820899/main.tf:103,31-36: Missing attribute separator; Expected a newline or comma to mark the beginning of the next attribute.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- FAIL: TestAccAWSOpsworksApplication (44.96s)
    testing.go:568: Step 1 error: Check failed: Check 2/24 error: Unnexpected environment: [{
          Key: "key2",
          Secure: true,
          Value: "*****FILTERED*****"
        }]
```