resource/aws_network_acl: Use schema.ImportStatePassthrough (#13419)
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13408

While this resource was not actually performing multiple resource import, the commented code was showing up in searches for it (via `.SetType()`). As an added bonus to the dramatically simpler code (since Terraform automatic refresh during import), this removes the legacy `import_` file. Yay!

Output from acceptance testing (see #13382 for fixes to _SubnetsChange and _SubnetsDelete tests):

```
--- PASS: TestAccAWSNetworkAcl_espProtocol (34.51s)
--- PASS: TestAccAWSNetworkAcl_basic (35.15s)
--- PASS: TestAccAWSNetworkAcl_ipv6ICMPRules (36.21s)
--- PASS: TestAccAWSNetworkAcl_OnlyEgressRules (37.51s)
--- PASS: TestAccAWSNetworkAcl_disappears (37.95s)
--- PASS: TestAccAWSNetworkAcl_EgressAndIngressRules (38.20s)
--- PASS: TestAccAWSNetworkAcl_ipv6VpcRules (38.68s)
--- PASS: TestAccAWSNetworkAcl_ipv6Rules (44.12s)
--- PASS: TestAccAWSNetworkAcl_OnlyIngressRules_basic (44.86s)
--- PASS: TestAccAWSNetworkAcl_CaseSensitivityNoChanges (45.01s)
--- FAIL: TestAccAWSNetworkAcl_SubnetsDelete (55.50s)
--- PASS: TestAccAWSNetworkAcl_OnlyIngressRules_update (65.91s)
--- PASS: TestAccAWSNetworkAcl_SubnetChange (66.79s)
--- PASS: TestAccAWSNetworkAcl_Egress_ConfigMode (74.44s)
--- PASS: TestAccAWSNetworkAcl_Subnets (75.89s)
--- PASS: TestAccAWSNetworkAcl_Ingress_ConfigMode (76.75s)
```