resource/aws_gamelift_fleet: Increase default deletion timeout to 20 minutes, add missing timeouts documentation
Reference: https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-editing.html

Our daily acceptance testing is often failing due to the current default deletion timeout of 5 minutes:

```
--- FAIL: TestAccAWSGameliftFleet_basic (1350.58s)
    testing.go:630: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during apply: timeout while waiting for resource to be gone (last state: 'DELETING', timeout: 5m0s)
```

The GameLift documentation does not provide too much guidance on the expected deletion time, but increasing this to 20 minutes to match typical EC2 instance deletion maximums should help.

Output from acceptance testing:

```
--- PASS: TestAccAWSGameliftFleet_basic (1494.07s)
--- PASS: TestAccAWSGameliftFleet_allFields (1535.56s)
```