tests/resource/aws_rds_cluster: Remove aws_s3_bucket region argument from TestAccAWSRDSCluster_s3Restore (#14272)
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/14127

Missed during test configuration cleanup after the referenced argument removal. Fixes the initial configuration issue, but does not fix the (still) broken test which is presumably something to do with the backup file or engine version.

Previously:

```
--- FAIL: TestAccAWSRDSCluster_s3Restore (0.99s)
testing.go:684: Step 0 error: config is invalid: "region": this field cannot be set
```

Output from acceptance testing:

```
=== CONT  TestAccAWSRDSCluster_s3Restore
    TestAccAWSRDSCluster_s3Restore: testing.go:684: Step 0 error: errors during apply:

        Error: Error waiting for RDS Cluster state to be "available": unexpected state 'migration-failed', wanted target 'available'. last error: %!s(<nil>)
```