service/cognito: Various Terraform 0.12 syntax fixes
These changes are backwards compatible with Terraform 0.11.

Changes:
* resource/aws_cognito_identity_pool: Ensure supported_login_providers configuration include equals in testing and documentation
* resource/aws_cognito_identity_provider: Ensure attribute_mapping and provider_details configurations include equals in testing and documentation
* resource/aws_cognito_resource_server: Omit scope configuration equals in testing and documentation

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSCognitoIdentityProvider_basic (1.58s)
    testing.go:568: Step 0 error: config is invalid: 3 problems:

        - Missing required argument: The argument "provider_details" is required, but no definition was found.
        - Unsupported block type: Blocks of type "provider_details" are not expected here. Did you mean to define argument "provider_details"? If so, use the equals sign to assign it a value.
        - Unsupported block type: Blocks of type "attribute_mapping" are not expected here. Did you mean to define argument "attribute_mapping"? If so, use the equals sign to assign it a value.

--- FAIL: TestAccAWSCognitoIdentityPool_supportedLoginProviders (0.50s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test903661443/main.tf:7,5-6: Invalid argument name; Argument names must not be quoted.

--- FAIL: TestAccAWSCognitoResourceServer_scope (0.64s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test540721977/main.tf:11,3-8: Attribute redefined; The argument "scope" was already set at /opt/teamcity-agent/temp/buildTmp/tf-test540721977/main.tf:6,3-8. Each argument may be set only once.
```

Output from Terraform 0.12 acceptance testing (additional Terraform Provider SDK fixes required):

```
--- PASS: TestAccAWSCognitoIdentityPool_supportedLoginProviders (25.17s)
--- PASS: TestAccAWSCognitoIdentityProvider_basic (14.50s)
--- FAIL: TestAccAWSCognitoResourceServer_scope (29.79s)
    testing.go:568: Step 3 error: Check failed: 1 error occurred:
        	* Check 3/3 error: aws_cognito_resource_server.main: Attribute 'scope_identifiers.#' expected "0", got "1"
```