interpolated tags - correct syntax tf 0.12.12
Error: Incorrect attribute value type

  on terraform-aws-bastion/main.tf line 265, in resource "aws_autoscaling_group" "bastion_auto_scaling_group":
 265:   tags = ["${concat(

Inappropriate value for attribute "tags": element 0: map ofstring required.