tests/service/elasticsearchservice: Add IAM Service Linked Role PreCheck
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/10035#pullrequestreview-285218537

Without the IAM SLR:

```
--- FAIL: TestAccAWSElasticSearchDomain_basic (1.41s)
    resource_aws_elasticsearch_domain_test.go:827: missing IAM Service Linked Role (es.amazonaws.com), please create it in the AWS account and retry
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSElasticSearchDomain_basic (841.35s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSElasticSearchDomain_basic (605.90s)
```