service/ec2: Additional EC2 Transit Gateway test configuration blacklisting for usw2-az4
Followup to 9babb9ca88a6d0a5324911d41b0530fb76a15c37

AWS recently added a fourth Availability Zone to the US West (Oregon) Region, which does not yet support EC2 Transit Gateway. This new AZ has the zone ID of `usw2-az4` and here we blacklist it to prevent random acceptance testing failures due to random AZ selection for VPC subnets.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSRouteDataSource_TransitGatewayID (70.80s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating EC2 Transit Gateway VPC Attachment: IncorrectState: Transit Gateway is not available in availability zone us-west-2d (subnet subnet-022d8187b0a3f3bd7).

--- FAIL: TestAccAWSRouteTable_Route_TransitGatewayID (154.66s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating EC2 Transit Gateway VPC Attachment: IncorrectState: Transit Gateway is not available in availability zone us-west-2d (subnet subnet-0081b6f66536f80b4).
```

Output from acceptance testing:

```
--- PASS: TestAccAWSRouteTable_Route_TransitGatewayID (310.00s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (312.35s)
```