tests/resource/aws_key_pair: Testing to cover missing fingerprint attribute in Terraform state and refactoring for best practices
Previously:

```
--- FAIL: TestAccAWSKeyPair_basic (7.40s)
    testing.go:527: Step 0 error: Check failed: Check 3/4 error: aws_key_pair.a_key_pair: Attribute 'fingerprint' not found
--- PASS: TestAccAWSKeyPair_generatedName (9.86s)
--- PASS: TestAccAWSKeyPair_namePrefix (10.50s)
```

Now:

```
--- PASS: TestAccAWSKeyPair_basic (11.71s)
--- PASS: TestAccAWSKeyPair_generatedName (11.92s)
--- PASS: TestAccAWSKeyPair_namePrefix (11.41s)
```