tests/resource/aws_emr_cluster: Refactor testing configurations to use single base VPC configuration, blacklist usw2-az4
Many instance types are not available in us2w-az4 (us-west-2d), e.g.

```
--- FAIL: TestAccAWSEMRCluster_basic (97.00s)
    testing.go:635: Step 0 error: errors during apply:

        Error: Error waiting for EMR Cluster state to be "WAITING" or "RUNNING": TERMINATING: VALIDATION_ERROR: The requested instance type c4.large is not supported in the requested availability zone. Learn more at https://docs.aws.amazon.com/console/elasticmapreduce/ERROR_noinstancetype
```

We use our common approach of blacklisting the Availability Zone for now to workaround this limitation. Further refactoring of this testing, such as removing and consolidating IAM handling, can be performed in later changes.

Output from acceptance testing (single run!):

```
--- PASS: TestAccAWSEMRCluster_instance_group_names (425.87s)
--- PASS: TestAccAWSEMRCluster_configurationsJson (456.46s)
--- PASS: TestAccAWSEMRCluster_basic (489.35s)
--- PASS: TestAccAWSEMRCluster_instance_group_update (510.54s)
--- PASS: TestAccAWSEMRCluster_Kerberos_ClusterDedicatedKdc (528.88s)
--- PASS: TestAccAWSEMRCluster_updateAutoScalingPolicy (539.07s)
--- PASS: TestAccAWSEMRCluster_additionalInfo (548.10s)
--- PASS: TestAccAWSEMRCluster_instance_group_EBSVolumeType_st1 (571.28s)
--- PASS: TestAccAWSEMRCluster_instance_group (608.37s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_AutoscalingPolicy (613.51s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Migration_CoreInstanceType (746.51s)
--- PASS: TestAccAWSEMRCluster_disappears (758.07s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_Migration_InstanceGroup (429.42s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceType (890.39s)
--- PASS: TestAccAWSEMRCluster_security_config (418.18s)
--- PASS: TestAccAWSEMRCluster_Step_Basic (400.23s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_Migration_MasterInstanceType (518.87s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Name (984.85s)
--- PASS: TestAccAWSEMRCluster_bootstrap_ordering (451.43s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_BidPrice (1060.09s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceType (1067.40s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_BidPrice (1088.00s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_InstanceCount (1126.34s)
--- PASS: TestAccAWSEMRCluster_Step_Multiple (622.48s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_InstanceCount (1182.24s)
--- PASS: TestAccAWSEMRCluster_keepJob (575.52s)
--- PASS: TestAccAWSEMRCluster_terminationProtected (623.66s)
--- PASS: TestAccAWSEMRCluster_s3Logging (595.31s)
--- PASS: TestAccAWSEMRCluster_Step_ConfigMode (857.56s)
--- PASS: TestAccAWSEMRCluster_CoreInstanceGroup_Migration_InstanceGroup (1403.31s)
--- PASS: TestAccAWSEMRCluster_custom_ami_id (546.91s)
--- PASS: TestAccAWSEMRCluster_MasterInstanceGroup_Name (1009.97s)
--- PASS: TestAccAWSEMRCluster_visibleToAllUsers (804.95s)
--- PASS: TestAccAWSEMRCluster_tags (738.75s)
--- PASS: TestAccAWSEMRCluster_root_volume_size (781.34s)
```