service/rds: Refactor to use keyvaluetags package
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10688

Output from acceptance testing (test failures present on master):

```
--- PASS: TestAccAWSDBClusterSnapshot_basic (145.21s)
--- PASS: TestAccAWSDBClusterSnapshot_Tags (167.89s)

--- PASS: TestAccAWSDbClusterSnapshotDataSource_DbClusterIdentifier (134.49s)
--- PASS: TestAccAWSDbClusterSnapshotDataSource_DbClusterSnapshotIdentifier (175.55s)
--- PASS: TestAccAWSDbClusterSnapshotDataSource_MostRecent (170.03s)

--- PASS: TestAccAWSDBEventSubscription_basicUpdate (109.85s)
--- PASS: TestAccAWSDBEventSubscription_categoryUpdate (109.93s)
--- PASS: TestAccAWSDBEventSubscription_disappears (73.12s)
--- PASS: TestAccAWSDBEventSubscription_withPrefix (72.51s)
--- PASS: TestAccAWSDBEventSubscription_withSourceIds (79.37s)

--- PASS: TestAccAWSDBInstance_AllowMajorVersionUpgrade (622.45s)
--- PASS: TestAccAWSDBInstance_basic (437.80s)
--- PASS: TestAccAWSDBInstance_CACertificateIdentifier (558.71s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (577.71s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfigurationUpdate (801.15s)
--- PASS: TestAccAWSDBInstance_DeletionProtection (612.92s)
--- PASS: TestAccAWSDBInstance_ec2Classic (479.20s)
--- FAIL: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (2.88s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (519.28s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (846.65s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (866.07s)
--- PASS: TestAccAWSDBInstance_generatedName (508.16s)
--- PASS: TestAccAWSDBInstance_iamAuth (628.98s)
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (553.98s)
--- PASS: TestAccAWSDBInstance_kmsKey (455.16s)
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (619.67s)
--- PASS: TestAccAWSDBInstance_MinorVersion (422.63s)
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1073.44s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (727.35s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (763.44s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (601.73s)
--- PASS: TestAccAWSDBInstance_MSSQL_Domain (3112.62s)
--- PASS: TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore (3000.13s)
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (1443.14s)
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (1939.69s)
--- PASS: TestAccAWSDBInstance_namePrefix (448.21s)
--- FAIL: TestAccAWSDBInstance_optionGroup (10.65s)
--- PASS: TestAccAWSDBInstance_Password (515.57s)
--- PASS: TestAccAWSDBInstance_portUpdate (517.92s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1614.83s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1655.29s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade (1341.52s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1705.39s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1646.29s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (1979.15s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1664.98s)
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection (0.00s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1660.09s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1675.43s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage (1415.38s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1526.31s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (1957.97s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1402.12s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled (1687.20s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1646.21s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1475.53s)
--- FAIL: TestAccAWSDBInstance_S3Import (812.70s)
--- PASS: TestAccAWSDBInstance_separate_iops_update (742.36s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (1220.05s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1814.70s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade (2191.21s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1200.33s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (1333.15s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1452.61s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1603.77s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1253.51s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1337.59s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1472.50s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1684.81s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1330.32s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage (1311.72s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1325.95s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (1920.10s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (4366.30s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1301.06s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled (1574.36s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1150.01s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1300.72s)
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset (0.00s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1284.07s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1414.07s)
--- PASS: TestAccAWSDBInstance_subnetGroup (1157.60s)

--- PASS: TestAccAWSDbInstanceDataSource_basic (631.27s)
--- PASS: TestAccAWSDbInstanceDataSource_ec2Classic (446.53s)

--- PASS: TestAccAWSDBOptionGroup_basic (7.60s)
--- PASS: TestAccAWSDBOptionGroup_basicDestroyWithInstance (524.56s)
--- PASS: TestAccAWSDBOptionGroup_generatedName (7.45s)
--- PASS: TestAccAWSDBOptionGroup_multipleOptions (7.75s)
--- PASS: TestAccAWSDBOptionGroup_namePrefix (7.60s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings (13.80s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_IAMRole (26.61s)
--- PASS: TestAccAWSDBOptionGroup_Option_OptionSettings_MultipleNonDefault (13.35s)
--- PASS: TestAccAWSDBOptionGroup_OracleOptionsUpdate (14.46s)
--- PASS: TestAccAWSDBOptionGroup_sqlServerOptionsUpdate (13.06s)
--- PASS: TestAccAWSDBOptionGroup_Tags (17.70s)
--- PASS: TestAccAWSDBOptionGroup_Tags_WithOptions (18.13s)
--- PASS: TestAccAWSDBOptionGroup_timeoutBlock (7.67s)

--- PASS: TestAccAWSDBParameterGroup_basic (15.85s)
--- PASS: TestAccAWSDBParameterGroup_Disappears (6.81s)
--- PASS: TestAccAWSDBParameterGroup_generatedName (15.17s)
--- PASS: TestAccAWSDBParameterGroup_limit (44.08s)
--- PASS: TestAccAWSDBParameterGroup_MatchDefault (8.51s)
--- PASS: TestAccAWSDBParameterGroup_namePrefix (23.95s)
--- PASS: TestAccAWSDBParameterGroup_Only (9.13s)
--- PASS: TestAccAWSDBParameterGroup_withApplyMethod (12.54s)

--- PASS: TestAccAWSDBSecurityGroup_basic (29.86s)

--- PASS: TestAccAWSDBSnapshot_basic (683.27s)
--- PASS: TestAccAWSDBSnapshot_disappears (753.38s)
--- PASS: TestAccAWSDBSnapshot_tags (709.04s)

--- PASS: TestAccAWSDBSubnetGroup_basic (11.68s)
--- PASS: TestAccAWSDBSubnetGroup_generatedName (11.34s)
--- PASS: TestAccAWSDBSubnetGroup_namePrefix (11.54s)
--- PASS: TestAccAWSDBSubnetGroup_updateDescription (18.54s)
--- PASS: TestAccAWSDBSubnetGroup_withUndocumentedCharacters (11.60s)
```