tests/service/route53resolver: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAwsRoute53ResolverEndpoint_basicInbound (5.14s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating Route53 Resolver endpoint: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAwsRoute53ResolverRule_forwardEndpointRecreate (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverEndpoint_updateOutbound (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverEndpoint_basicInbound (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverRuleAssociation_basic (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverRule_forward (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverRule_basic (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverRule_tags (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAwsRoute53ResolverRule_updateName (2.60s)
    resource_aws_route53_resolver_endpoint_test.go:198: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://route53resolver.us-gov-west-1.amazonaws.com/: dial tcp: lookup route53resolver.us-gov-west-1.amazonaws.com: no such host
```