tests/service/kafka: Update removed Kafka version
There is no API for fetching available versions, so manually updating the test configurations. This API removal was not included in the [2.2.1 announcement](https://aws.amazon.com/about-aws/whats-new/2019/07/amazon-msk-adds-support-apache-kafka-version-221-expands-availability-stockholm-mumbai-seoul/).

Previously:

```
--- FAIL: TestAccAWSMskCluster_basic (8.39s)
    testing.go:569: Step 0 error: errors during apply:

        Error: error creating MSK cluster: BadRequestException: Unsupported KafkaVersion [2.1.0]. Valid values: [1.1.1, 2.2.1]
```

Output from acceptance testing in AWS Commercial (in an account that hasn't reached the MSK Configuration quota and now correctly shows failures relating to the default encryption changing from client broker TLS_PLAINTEXT to TLS after launch):

```
--- FAIL: TestAccAWSMskCluster_basic (756.44s)
    testing.go:569: Step 0 error: Check failed: Check 3/27 error: aws_msk_cluster.test: Attribute 'bootstrap_brokers' didn't match "^(([-\\w]+\\.){1,}[\\w]+:\\d+,){2,}([-\\w]+\\.){1,}[\\w]+:\\d+$", got ""
```