tests/service/servicediscovery: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic (8.28s)
    testing.go:568: Step 0 error: errors during apply:

        Error: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccAWSServiceDiscoveryPublicDnsNamespace_basic (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryHttpNamespace_basic (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryHttpNamespace_Description (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryPublicDnsNamespace_longname (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryService_import (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryService_public (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_longname (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryService_private (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic (2.41s)
    resource_aws_service_discovery_private_dns_namespace_test.go:117: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://servicediscovery.us-gov-west-1.amazonaws.com/: dial tcp: lookup servicediscovery.us-gov-west-1.amazonaws.com: no such host
```