tests/service/directconnect: Implement aws_dx_connection and aws_dx_lag sweepers (#17437)
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17391

The acceptance testing can leave lingering resources on failed runs (e.g. via coding issues during development or panics). These lingering resources can cause quota limits to be reached, extraneous money to be spent, or in some worst cases leave open security risks in the testing account.

We do not require sweeper implementation during initial resource implementation at this time, but this may change in the future when the process can be simplified and documented better.

Currently testing is failing in the main testing account due to hitting the service limit:

```
=== CONT  TestAccAWSDxConnectionAssociation_multiConns
resource_aws_dx_connection_association_test.go:31: Step 1/1 error: Error running apply:
Error: error creating Direct Connect LAG: DirectConnectClientException: Maximum number of lags per location is limited to 10.
--- FAIL: TestAccAWSDxConnectionAssociation_multiConns (18.50s)
```

Output from sweeper in AWS Commercial:

```
 aws directconnect describe-lags --query 'lags[?lagState != `deleted`]' | jq '. | length'
9

2021/02/03 15:19:17 [DEBUG] Running Sweepers for region (us-west-2):
2021/02/03 15:19:17 [DEBUG] Running Sweeper (aws_dx_lag) in region (us-west-2)
2021/02/03 15:19:19 [DEBUG] Deleting Direct Connect LAG: dxlag-fg5q24hc
2021/02/03 15:19:30 [DEBUG] Deleting Direct Connect LAG: dxlag-fg6dvyxq
2021/02/03 15:19:41 [DEBUG] Deleting Direct Connect LAG: dxlag-fgm4id4e
2021/02/03 15:19:52 [DEBUG] Deleting Direct Connect LAG: dxlag-fghic82e
2021/02/03 15:20:02 [DEBUG] Deleting Direct Connect LAG: dxlag-fgyvj65j
2021/02/03 15:20:13 [DEBUG] Deleting Direct Connect LAG: dxlag-fg5t8zzy
2021/02/03 15:20:24 [DEBUG] Deleting Direct Connect LAG: dxlag-fh1j9cs9
2021/02/03 15:20:35 [DEBUG] Deleting Direct Connect LAG: dxlag-fg2s4p4t
2021/02/03 15:20:46 [DEBUG] Deleting Direct Connect LAG: dxlag-ffp801di
2021/02/03 15:20:47 [ERROR] error deleting Direct Connect LAG (dxlag-ffp801di): DirectConnectClientException: Lag dxlag-ffp801di cannot be deleted until its bundled Connections are disassociated or deleted.
2021/02/03 15:20:47 [ERROR] Error running Sweeper (aws_dx_lag) in region (us-west-2): 1 error occurred:
	* error deleting Direct Connect LAG (dxlag-ffp801di): DirectConnectClientException: Lag dxlag-ffp801di cannot be deleted until its bundled Connections are disassociated or deleted.

2021/02/03 15:20:47 Sweeper Tests ran successfully:
2021/02/03 15:20:47 Sweeper Tests ran unsuccessfully:
	- aws_dx_lag: 1 error occurred:
	* error deleting Direct Connect LAG (dxlag-ffp801di): DirectConnectClientException: Lag dxlag-ffp801di cannot be deleted until its bundled Connections are disassociated or deleted.

2021/02/03 15:20:47 [DEBUG] Running Sweepers for region (us-east-1):
2021/02/03 15:20:47 [DEBUG] Running Sweeper (aws_dx_lag) in region (us-east-1)
2021/02/03 15:20:48 Sweeper Tests ran successfully:
	- aws_dx_lag
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	94.111s
FAIL

 aws directconnect describe-lags --query 'lags[?lagState != `deleted`]' | jq '. | length'
 1
```

After creating `aws_dx_connection` sweeper:

```
aws directconnect describe-connections | jq '.connections | length'
2
 aws directconnect describe-lags --query 'lags[?lagState != `deleted`]' | jq '. | length'
1

2021/02/03 15:33:20 [DEBUG] Running Sweepers for region (us-west-2):
2021/02/03 15:33:20 [DEBUG] Running Sweeper (aws_dx_connection) in region (us-west-2)
2021/02/03 15:33:22 [DEBUG] Deleting Direct Connect connection: dxcon-fguq32vy
2021/02/03 15:33:33 [DEBUG] Deleting Direct Connect connection: dxcon-fgouobks
2021/02/03 15:33:44 [DEBUG] Running Sweeper (aws_dx_lag) in region (us-west-2)
2021/02/03 15:33:44 [DEBUG] Deleting Direct Connect LAG: dxlag-ffp801di
2021/02/03 15:33:55 [DEBUG] Deleting Direct Connect LAG: dxlag-fg5q24hc
2021/02/03 15:34:06 [DEBUG] Deleting Direct Connect LAG: dxlag-fg6dvyxq
2021/02/03 15:34:17 [DEBUG] Deleting Direct Connect LAG: dxlag-fgm4id4e
2021/02/03 15:34:28 [DEBUG] Deleting Direct Connect LAG: dxlag-fghic82e
2021/02/03 15:34:39 [DEBUG] Deleting Direct Connect LAG: dxlag-fgyvj65j
2021/02/03 15:34:50 [DEBUG] Deleting Direct Connect LAG: dxlag-fg5t8zzy
2021/02/03 15:35:01 [DEBUG] Deleting Direct Connect LAG: dxlag-fh1j9cs9
2021/02/03 15:35:12 [DEBUG] Deleting Direct Connect LAG: dxlag-fg2s4p4t
2021/02/03 15:35:23 Sweeper Tests ran successfully:
	- aws_dx_connection
	- aws_dx_lag
2021/02/03 15:35:23 [DEBUG] Running Sweepers for region (us-east-1):
2021/02/03 15:35:23 [DEBUG] Running Sweeper (aws_dx_connection) in region (us-east-1)
2021/02/03 15:35:24 [DEBUG] Running Sweeper (aws_dx_lag) in region (us-east-1)
2021/02/03 15:35:24 Sweeper Tests ran successfully:
	- aws_dx_connection
	- aws_dx_lag
ok  	github.com/terraform-providers/terraform-provider-aws/aws	127.042s

aws directconnect describe-connections | jq '.connections | length'
0
aws directconnect describe-lags --query 'lags[?lagState != `deleted`]' | jq '. | length'
0
```

Output from sweeper in AWS GovCloud (US):

```
aws directconnect describe-connections | jq '.connections | length'
0
aws directconnect describe-lags --query 'lags[?lagState != `deleted`]' | jq '. | length'
0

2021/02/03 15:33:23 [DEBUG] Running Sweepers for region (us-gov-west-1):
2021/02/03 15:33:23 [DEBUG] Running Sweeper (aws_dx_connection) in region (us-gov-west-1)
2021/02/03 15:33:28 [DEBUG] Running Sweeper (aws_dx_lag) in region (us-gov-west-1)
2021/02/03 15:33:29 Sweeper Tests ran successfully:
	- aws_dx_connection
	- aws_dx_lag
ok  	github.com/terraform-providers/terraform-provider-aws/aws	8.491s

aws directconnect describe-connections | jq '.connections | length'
0
aws directconnect describe-lags --query 'lags[?lagState != `deleted`]' | jq '. | length'
0
```