r/aws_vpc_peering_connection: Fix 'TestAccAWSVPCPeeringConnection_peerRegionAutoAccept'.
Failing acceptance test output:

=== CONT  TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
    testing.go:677: Step 0, expected error:

        Error initializing context: 2 problems:

        - Could not satisfy plugin requirements:
        Plugin reinitialization required. Please run "terraform init".

        Plugins are external binaries that Terraform uses to access and manipulate
        resources. The configuration provided requires plugins which can't be located,
        don't satisfy the version constraints, or are otherwise incompatible.

        Terraform automatically discovers provider requirements from your
        configuration, including providers used in child modules. To see the
        requirements and constraints from each module, run "terraform providers".

        - provider "awsalternate" is not available

        To match:

        .*peer_region cannot be set whilst auto_accept is true when creating a vpc peering connection.*

--- FAIL: TestAccAWSVPCPeeringConnection_peerRegionAutoAccept (0.87s)

Successful acceptance test output:

$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSVPCPeeringConnection_peerRegionAutoAccept'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSVPCPeeringConnection_peerRegionAutoAccept -timeout 120m
=== RUN   TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
=== PAUSE TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
=== CONT  TestAccAWSVPCPeeringConnection_peerRegionAutoAccept
--- PASS: TestAccAWSVPCPeeringConnection_peerRegionAutoAccept (13.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	13.986s