resource/aws_datasync_agent: Update deletion error to match updated API deletion error
Starting around November 19, 2019 the DataSync API in AWS Commercial regions changed the error messaging for non-existent hosts from including "not found" to this new message:

```
--- FAIL: TestAccAWSDataSyncAgent_basic (158.82s)
    testing.go:696: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: InvalidRequestException: host-0c61c0944a13c5fda does not exist or has been deleted.

--- FAIL: TestAccAWSDataSyncAgent_disappears (116.35s)
    testing.go:635: Step 0 error: errors during follow-up refresh:

        Error: error reading DataSync Agent (arn:aws:datasync:us-west-2:*******:agent/agent-027e5766a4963f977): InvalidRequestException: host-027e5766a4963f977 does not exist or has been deleted.
```

It would be better if the API used a special error code instead so we did not need to rely on the contents of the generic InvalidRequestException error code message.

Output from acceptance testing:

```
--- PASS: TestAccAWSDataSyncAgent_basic (185.94s)
--- PASS: TestAccAWSDataSyncAgent_disappears (217.60s)
--- PASS: TestAccAWSDataSyncAgent_AgentName (234.13s)
--- PASS: TestAccAWSDataSyncAgent_Tags (286.51s)
```