fixup: add `testNotNull` annotation
Identity tests still failing as the configured `id` attribute is missing
the expected `_` separator. Additional investigation required.

```console
% make testacc PKG=vpc TESTS=TestAccVPCRoute_Identity_Basic
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.24.6 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCRoute_Identity_Basic'  -timeout 360m -vet=off
2025/08/26 16:59:57 Creating Terraform AWS Provider (SDKv2-style)...
2025/08/26 16:59:57 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPCRoute_Identity_Basic
=== PAUSE TestAccVPCRoute_Identity_Basic
=== CONT  TestAccVPCRoute_Identity_Basic
    vpc_route_identity_gen_test.go:30: Step 2/4 error running import: exit status 1

        Error: unexpected format of ID ("r-rtb-0e1c77d84ed2e0b022218071545"), expected ROUTETABLEID_DESTINATION

--- FAIL: TestAccVPCRoute_Identity_Basic (20.94s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        27.950s
FAIL
make: *** [testacc] Error 1
```