Acceptance test output:
% make testacc TESTARGS='-run=TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithAccount' PKG=networkmanager
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-aws_networkmanager_core_network_policy_document.account-id-regression 🌿...
TF_ACC=1 go1.25.5 test ./internal/service/networkmanager/... -v -count 1 -parallel 20  -run=TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithAccount -timeout 360m -vet=off
2026/01/02 09:10:35 Creating Terraform AWS Provider (SDKv2-style)...
2026/01/02 09:10:35 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithAccount
=== PAUSE TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithAccount
=== CONT  TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithAccount
    core_network_test.go:291: Step 1/1 error: Error running apply: exit status 1

        Error: creating Core Network: operation error NetworkManager: CreateCoreNetwork, https response error StatusCode: 400, RequestID: f4f10841-6699-48fe-a7cd-f61d98b24b45, CoreNetworkPolicyException: Incorrect policy.

          with aws_networkmanager_core_network.test,
          on terraform_plugin_test.tf line 47, in resource "aws_networkmanager_core_network" "test":
          47: resource "aws_networkmanager_core_network" "test" {

--- FAIL: TestAccNetworkManagerCoreNetwork_createBasePolicyDocumentWithAccount (9.28s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	14.527s
FAIL
make: *** [testacc] Error 1