tests/resource/aws_lb_listener: Various Terraform 0.12 syntax fixes
These changes are backwards compatible with Terraform 0.11.

Changes:
* tests/resource/aws_lb_listener: Ensure authentication_request_extra_params configurations use equals
* tests/resource/aws_lb_listener: Temporarily use expanded subnets references

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSLBListener_basic (4.25s)
    testing.go:568: Step 0 error: errors during plan:

        Error: Incorrect attribute value type

          on /opt/teamcity-agent/temp/buildTmp/tf-test145409224/main.tf line 16:
          (source code not available)

        Inappropriate value for attribute "subnets": element 0: string required.

--- FAIL: TestAccAWSLBListener_cognito (1.54s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "authentication_request_extra_params" are not expected here. Did you mean to define argument "authentication_request_extra_params"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSLBListener_BackwardsCompatibility (193.54s)
--- PASS: TestAccAWSLBListener_https (194.03s)
--- PASS: TestAccAWSLBListener_redirect (203.99s)
--- PASS: TestAccAWSLBListener_basic (214.76s)
--- PASS: TestAccAWSLBListener_fixedResponse (475.74s)
--- PASS: TestAccAWSLBListener_DefaultAction_Order_Recreates (213.00s)
--- PASS: TestAccAWSLBListener_DefaultAction_Order (214.66s)
--- PASS: TestAccAWSLBListener_cognito (255.30s)
--- PASS: TestAccAWSLBListener_oidc (308.55s)
```