Comment out self-registration of 'aws_vpc_security_group_ingress_rule' and 'aws_vpc_security_group_egress_rule'.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccVPCSecurityGroupIngressRule_basic\|TestAccVPCSecurityGroupEgressRule_basic' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCSecurityGroupIngressRule_basic\|TestAccVPCSecurityGroupEgressRule_basic -timeout 180m
=== RUN   TestAccVPCSecurityGroupEgressRule_basic
=== PAUSE TestAccVPCSecurityGroupEgressRule_basic
=== RUN   TestAccVPCSecurityGroupIngressRule_basic
=== PAUSE TestAccVPCSecurityGroupIngressRule_basic
=== CONT  TestAccVPCSecurityGroupEgressRule_basic
=== CONT  TestAccVPCSecurityGroupIngressRule_basic
=== CONT  TestAccVPCSecurityGroupEgressRule_basic
    vpc_security_group_egress_rule_test.go:23: Step 1/2 error: Error running pre-apply refresh: exit status 1

        Error: Invalid resource type

          on terraform_plugin_test.tf line 19, in resource "aws_vpc_security_group_egress_rule" "test":
          19: resource "aws_vpc_security_group_egress_rule" "test" {

        The provider hashicorp/aws does not support resource type
        "aws_vpc_security_group_egress_rule".
=== CONT  TestAccVPCSecurityGroupIngressRule_basic
    vpc_security_group_ingress_rule_test.go:87: Step 1/2 error: Error running pre-apply refresh: exit status 1

        Error: Invalid resource type

          on terraform_plugin_test.tf line 19, in resource "aws_vpc_security_group_ingress_rule" "test":
          19: resource "aws_vpc_security_group_ingress_rule" "test" {

        The provider hashicorp/aws does not support resource type
        "aws_vpc_security_group_ingress_rule".
--- FAIL: TestAccVPCSecurityGroupIngressRule_basic (5.47s)
--- FAIL: TestAccVPCSecurityGroupEgressRule_basic (5.49s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	13.577s
FAIL
make: *** [testacc] Error 1