r/aws_vpc: switch to `RetryUntilEqual` for VPC attribute modification
The return value from `findVPCAttributeByTwoPartKey` is a boolean, meaning that disabling a particular attribute would return a `false` zero value. The new waiter logic from the `retry` package treats zero values as "Not Found", so the previous approach of using the waiter/status function to poll for completion hangs and eventually fails when the attribute is disabled.

By switching to `tfresource.RetryUntilEqual`, the modification function returns as soon as the attribute value changes with no intermediary status parsing logic.

Before:

```console
=== NAME  TestAccVPC_disabledDNSSupport
    vpc_test.go:464: Step 1/2 error: Error running apply: exit status 1

        Error: creating EC2 VPC: modifying EnableDnsSupport: waiting for completion: couldn't find resource (21 retries)

          with aws_vpc.test,
          on terraform_plugin_test.tf line 12, in resource "aws_vpc" "test":
          12: resource "aws_vpc" "test" {
```

After:

```console
% make t K=vpc T=TestAccVPC_disabledDNSSupport
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 td-go-vcr-ec2 🌿...
TF_ACC=1 go1.25.7 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPC_disabledDNSSupport'  -timeout 360m -vet=off
2026/03/02 11:00:24 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/02 11:00:24 Initializing Terraform AWS Provider (SDKv2-style)...
=== RUN   TestAccVPC_disabledDNSSupport
=== PAUSE TestAccVPC_disabledDNSSupport
=== CONT  TestAccVPC_disabledDNSSupport
--- PASS: TestAccVPC_disabledDNSSupport (18.54s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        25.626s
```