tests/resource/aws_ec2_client_vpn_network_association: Blacklist usw2-az4 which does not support this functionality
Previously in the acceptance testing:

```
--- FAIL: TestAccAwsEc2ClientVpnNetworkAssociation_disappears (8.09s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating Client VPN network association: InvalidParameterValue: AZ us-west-2d is not currently supported. Please choose another az in this region
```

Output from acceptance testing:

```
--- PASS: TestAccAwsEc2ClientVpnNetworkAssociation_basic (521.82s)
--- PASS: TestAccAwsEc2ClientVpnNetworkAssociation_disappears (570.58s)
```