r/aws_bedrockagentcore_harness: Change `system_prompt` to Required. This is not considered a breaking change as previously, leaving this attribute unconfigured resulted in:
        Error: Provider produced inconsistent result after apply

        When applying changes to aws_bedrockagentcore_harness.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: .system_prompt: block count changed from 0 to 1.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.