resource/aws_s3_bucket: Skip MethodNotAllowed error for missing S3 Bucket Acceleration functionality (eu-north-1 support)
Previously (in eu-north-1 region):

```
--- FAIL: TestAccAWSS3Bucket_basic (12.73s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_s3_bucket.bucket: 1 error occurred:
        	* aws_s3_bucket.bucket: error getting S3 Bucket acceleration configuration: MethodNotAllowed: The specified method is not allowed against this resource.
        	status code: 405, request id: C4FF2A8370BED40B, host id: 7N8DyRUtrgpFbAJAzpbdG0DjGRVoESdOcy+T9Jf2yxiKlTDUUSydC1YpqxZXdqBlz6XaMgsUDA4=
```

Output from acceptance testing (in eu-north-1 region):

```
--- PASS: TestAccAWSS3Bucket_basic (29.97s)
```