Update rds_cluster_role_association.html.markdown
Updated example to use `.arn` attribute as expected.

When `.id` is used, the following error is thrown:
```
Error: "role_arn" (<role id>) is an invalid ARN: arn: invalid prefix
```