tests: Switch acceptance test configurations from removed nodejs4.3 Lambda runtime to nodejs8.10
The runtime has been EOL for a few months now, but support was actually turned off today in our main acceptance testing account. See also: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

Previously:

```
--- FAIL: TestAccAWSCloudwatchLogSubscriptionFilter_basic (8.09s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
          * aws_lambda_function.test_lambdafunction: 1 error occurred:
          * aws_lambda_function.test_lambdafunction: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.
          status code: 400, request id: 741dec0d-025e-11e9-9361-b14433c1c821
```

Output from acceptance testing:

```
--- PASS: TestAccAWSCloudTrail (80.44s)
    --- PASS: TestAccAWSCloudTrail/Trail (80.44s)
        --- PASS: TestAccAWSCloudTrail/Trail/eventSelector (80.44s)
--- PASS: TestAccAWSConfig (242.17s)
    --- PASS: TestAccAWSConfig/Config (242.17s)
        --- PASS: TestAccAWSConfig/Config/customlambda (115.58s)
        --- PASS: TestAccAWSConfig/Config/importLambda (126.59s)

--- PASS: TestAccAWSAPIGatewayAuthorizer_basic (60.64s)
--- PASS: TestAccAWSAPIGatewayMethod_customauthorizer (35.02s)
--- PASS: TestAccAWSCloudWatchEventTarget_input_transformer (22.43s)
--- PASS: TestAccAWSCloudwatchLogSubscriptionFilter_basic (28.00s)
--- PASS: TestAccAWSCloudwatchLogSubscriptionFilter_disappears (25.22s)
--- PASS: TestAccAWSCloudwatchLogSubscriptionFilter_disappears_LogGroup (26.85s)
--- PASS: TestAccAWSCognitoUserPool_withLambdaConfig (41.68s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (1236.04s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Deserializer_Update (136.39s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Enabled (132.66s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_HiveJsonSerDe_Empty (137.89s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_OpenXJsonSerDe_Empty (137.73s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_OrcSerDe_Empty (133.54s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_ParquetSerDe_Empty (148.69s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3_DataFormatConversionConfiguration_Serializer_Update (342.45s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (143.88s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (0.76s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (0.93s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (196.12s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (162.40s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_importBasic (123.72s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_missingProcessingConfiguration (111.77s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (892.83s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basic (92.16s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3basicWithTags (147.85s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3ConfigUpdates (212.48s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3KinesisStreamSource (114.95s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_s3WithCloudwatchLogging (103.34s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (337.09s)
--- PASS: TestAccAWSLambdaAlias_basic (32.55s)
--- PASS: TestAccAWSLambdaAlias_nameupdate (40.09s)
--- PASS: TestAccAWSLambdaAlias_routingconfig (43.06s)
--- PASS: TestAccAWSLambdaEventSourceMapping_changesInEnabledAreDetected (110.32s)
--- PASS: TestAccAWSLambdaEventSourceMapping_kinesis_basic (93.45s)
--- PASS: TestAccAWSLambdaEventSourceMapping_kinesis_disappears (85.50s)
--- PASS: TestAccAWSLambdaEventSourceMapping_kinesis_import (84.81s)
--- PASS: TestAccAWSLambdaEventSourceMapping_kinesis_removeBatchSize (91.32s)
--- PASS: TestAccAWSLambdaEventSourceMapping_sqs_basic (87.84s)
--- PASS: TestAccAWSLambdaEventSourceMapping_sqs_withFunctionName (30.70s)
--- PASS: TestAccAWSLambdaEventSourceMapping_sqsDisappears (108.43s)
--- PASS: TestAccAWSLambdaEventSourceMapping_StartingPositionTimestamp (78.94s)
--- PASS: TestAccAWSLambdaFunction_basic (38.11s)
--- PASS: TestAccAWSLambdaFunction_concurrency (48.19s)
--- PASS: TestAccAWSLambdaFunction_concurrencyCycle (59.80s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfig (47.10s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfigUpdated (47.08s)
--- PASS: TestAccAWSLambdaFunction_EmptyVpcConfig (33.52s)
--- PASS: TestAccAWSLambdaFunction_encryptedEnvVariables (68.81s)
--- PASS: TestAccAWSLambdaFunction_envVariables (74.63s)
--- PASS: TestAccAWSLambdaFunction_expectFilenameAndS3Attributes (21.29s)
--- PASS: TestAccAWSLambdaFunction_importLocalFile (32.44s)
--- PASS: TestAccAWSLambdaFunction_importLocalFile_VPC (38.30s)
--- PASS: TestAccAWSLambdaFunction_importS3 (34.38s)
--- PASS: TestAccAWSLambdaFunction_localUpdate (35.48s)
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (34.94s)
--- PASS: TestAccAWSLambdaFunction_nilDeadLetterConfig (29.84s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_java8 (31.38s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_NodeJs810 (38.78s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_noRuntime (1.23s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_provided (30.95s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_python27 (31.67s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_python36 (31.52s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_python37 (31.12s)
--- PASS: TestAccAWSLambdaFunction_runtimeValidation_ruby25 (30.73s)
--- PASS: TestAccAWSLambdaFunction_s3 (33.07s)
--- PASS: TestAccAWSLambdaFunction_s3Update_basic (52.97s)
--- PASS: TestAccAWSLambdaFunction_s3Update_unversioned (50.72s)
--- PASS: TestAccAWSLambdaFunction_tags (60.73s)
--- PASS: TestAccAWSLambdaFunction_tracingConfig (52.71s)
--- PASS: TestAccAWSLambdaFunction_updateRuntime (51.72s)
--- PASS: TestAccAWSLambdaFunction_versioned (30.58s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (50.35s)
--- PASS: TestAccAWSLambdaFunction_VPC (49.61s)
--- PASS: TestAccAWSLambdaFunction_VPC_withInvocation (51.38s)
--- PASS: TestAccAWSLambdaFunction_VPCRemoval (61.83s)
--- PASS: TestAccAWSLambdaFunction_VPCUpdate (69.99s)
--- PASS: TestAccAWSLambdaPermission_basic (23.44s)
--- PASS: TestAccAWSLambdaPermission_multiplePerms (37.87s)
--- PASS: TestAccAWSLambdaPermission_withIAMRole (31.24s)
--- PASS: TestAccAWSLambdaPermission_withQualifier (25.42s)
--- PASS: TestAccAWSLambdaPermission_withRawFunctionName (22.49s)
--- PASS: TestAccAWSLambdaPermission_withS3 (39.75s)
--- PASS: TestAccAWSLambdaPermission_withSNS (30.08s)
--- PASS: TestAccAWSLambdaPermission_withStatementIdPrefix (23.36s)
--- PASS: TestAccAwsSecretsManagerSecret_RotationLambdaARN (43.14s)
--- PASS: TestAccDataSourceAWSLambdaFunction_alias (31.84s)
--- PASS: TestAccDataSourceAWSLambdaFunction_basic (33.62s)
--- PASS: TestAccDataSourceAWSLambdaFunction_environment (31.38s)
--- PASS: TestAccDataSourceAWSLambdaFunction_version (28.52s)
--- PASS: TestAccDataSourceAWSLambdaFunction_vpc (37.59s)
```