Clarified WAF predicate documentation
predicate is a nested structure in terraform. Referenced predicate
documentation instead of referring to underlying WAF *Set objects.
Hopefully prevents user error of form:
> Error: aws_waf_rule.example: expected predicates.0.type to be one of
>  [ByteMatch GeoMatch IPMatch RegexMatch SizeConstraint SqlInjectionMatch XssMatch]