tests/data-source/aws_acmpca_certificate_authority: Add new permanent_deletion_time_in_days = 7 argument to test resources and handle additional error for non-existent testing
At a certain point, ACM-PCA started returning a `AccessDeniedException` instead of a `ResourceNotFoundException` when referencing a non-existing certificate authority, likely since the testing uses a fake ARN that is "another" AWS account. We cover both errors in case the error ever changes back.

Previous acceptance testing output:

```
--- FAIL: TestAccDataSourceAwsAcmpcaCertificateAuthority_Basic (3.45s)
    testing.go:531: Step 0, expected error:

        Error refreshing: 1 error occurred:
        	* data.aws_acmpca_certificate_authority.test: 1 error occurred:
        	* data.aws_acmpca_certificate_authority.test: data.aws_acmpca_certificate_authority.test: error reading ACMPCA Certificate Authority: AccessDeniedException: User: arn:aws:iam::123456789012:user/teamcity is not authorized to perform: acm-pca:DescribeCertificateAuthority on resource: arn:aws:acm-pca:us-east-1:123456789012:certificate-authority/tf-acc-test-does-not-exist
```

ACM-PCA defaults to 30 day deletion window, which is unnecessary in our acceptance testing. Add the new `permanent_deletion_time_in_days` argument from (https://github.com/terraform-providers/terraform-provider-aws/pull/7366) to help prevent `LimitExceededException` in our testing account. This is a virtual attribute so it is not valid to add to the `Check` functions.

Output from acceptance testing:

```
--- PASS: TestAccDataSourceAwsAcmpcaCertificateAuthority_Basic (19.09s)
```