r/aws_backup_plan: Add 'recovery_point_tags' acceptance test.
$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsBackupPlan_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsBackupPlan_ -timeout 120m
=== RUN   TestAccAwsBackupPlan_basic
=== PAUSE TestAccAwsBackupPlan_basic
=== RUN   TestAccAwsBackupPlan_withTags
=== PAUSE TestAccAwsBackupPlan_withTags
=== RUN   TestAccAwsBackupPlan_withRules
=== PAUSE TestAccAwsBackupPlan_withRules
=== RUN   TestAccAwsBackupPlan_withLifecycle
=== PAUSE TestAccAwsBackupPlan_withLifecycle
=== RUN   TestAccAwsBackupPlan_withRecoveryPointTags
=== PAUSE TestAccAwsBackupPlan_withRecoveryPointTags
=== RUN   TestAccAwsBackupPlan_disappears
=== PAUSE TestAccAwsBackupPlan_disappears
=== CONT  TestAccAwsBackupPlan_basic
=== CONT  TestAccAwsBackupPlan_withRecoveryPointTags
=== CONT  TestAccAwsBackupPlan_disappears
=== CONT  TestAccAwsBackupPlan_withRules
=== CONT  TestAccAwsBackupPlan_withLifecycle
=== CONT  TestAccAwsBackupPlan_withTags
--- PASS: TestAccAwsBackupPlan_disappears (19.33s)
--- PASS: TestAccAwsBackupPlan_basic (20.82s)
--- FAIL: TestAccAwsBackupPlan_withRecoveryPointTags (26.61s)
    testing.go:569: Step 1 error: errors during apply:

        Error: error updating Backup Plan (1104fa3b-5714-4c2e-9776-78660300ee6b): InvalidParameter: 2 validation error(s) found.
        - missing required field, UpdateBackupPlanInput.BackupPlan.Rules[0].RuleName.
        - missing required field, UpdateBackupPlanInput.BackupPlan.Rules[0].TargetBackupVaultName.

          on /tmp/tf-test417192270/main.tf line 6:
          (source code not available)

--- PASS: TestAccAwsBackupPlan_withRules (47.10s)
--- PASS: TestAccAwsBackupPlan_withTags (47.82s)
--- PASS: TestAccAwsBackupPlan_withLifecycle (60.07s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	60.128s
FAIL
GNUmakefile:24: recipe for target 'testacc' failed
make: *** [testacc] Error 1