resource/aws_flow_log: Add tags argument (#12273)
Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSFlowLog_LogDestinationType_S3_Invalid (8.49s)
--- PASS: TestAccAWSFlowLog_LogDestinationType_CloudWatchLogs (11.92s)
--- PASS: TestAccAWSFlowLog_disappears (12.09s)
--- PASS: TestAccAWSFlowLog_SubnetID (13.39s)
--- PASS: TestAccAWSFlowLog_LogDestinationType_S3 (13.66s)
--- PASS: TestAccAWSFlowLog_VPCID (18.86s)
--- PASS: TestAccAWSFlowLog_LogFormat (19.77s)
--- PASS: TestAccAWSFlowLog_tags (25.10s)
```

Output from acceptance testing in AWS GovCloud (US) (test failure unrelated due to hardcoded partition):

```
--- FAIL: TestAccAWSFlowLog_LogDestinationType_S3_Invalid (7.31s)
--- PASS: TestAccAWSFlowLog_disappears (9.71s)
--- PASS: TestAccAWSFlowLog_LogDestinationType_CloudWatchLogs (10.66s)
--- PASS: TestAccAWSFlowLog_LogDestinationType_S3 (11.05s)
--- PASS: TestAccAWSFlowLog_SubnetID (14.48s)
--- PASS: TestAccAWSFlowLog_VPCID (16.45s)
--- PASS: TestAccAWSFlowLog_LogFormat (17.23s)
--- PASS: TestAccAWSFlowLog_tags (19.83s)
```