tests/resource/aws_iot_policy: Remove TestAccAWSIoTPolicy_invalidJson test (#17408)
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/17397

During Terraform 0.12 syntax upgrades in the test configurations, the JSON policy was accidentally fixed so the API no longer threw the error the test was expecting:

```
=== CONT  TestAccAWSIoTPolicy_invalidJson
resource_aws_iot_policy_test.go:70: Step 1/1, expected an error but got none
--- FAIL: TestAccAWSIoTPolicy_invalidJson (16.73s)
```

Testing API errors is not a goal of our acceptance testing and this test should be removed rather than "broken" again.

Output from acceptance testing:

```
--- PASS: TestAccAWSIoTPolicy_disappears (12.15s)
--- PASS: TestAccAWSIoTPolicy_basic (16.11s)
```