resource/aws_dynamodb_table: Allow deletion retry of 5 minutes to handle global table deletions
When DynamoDB is deleting multiple regions of a global table, the deletion call can get stuck waiting for another deletion call to finish. This can be seen with the very consistently failing acceptance test:

--- FAIL: TestAccAWSDynamoDbGlobalTable_multipleRegions (284.43s)
	testing.go:579: Error destroying resource! WARNING: Dangling resources
		may exist. The full state and error is shown below.

		Error: Error applying: 2 errors occurred:
			* aws_dynamodb_table.us-east-1 (destroy): 1 error occurred:
			* aws_dynamodb_table.us-east-1: ResourceInUseException: Attempt to change a resource which is still in use: Table is being deleted: tf-acc-test-bavzb
			status code: 400, request id: 8UEJN22QSQF434KNQF9IJ63J1NVV4KQNSO5AEMVJF66Q9ASUAAJG

			* aws_dynamodb_table.us-west-2 (destroy): 1 error occurred:
			* aws_dynamodb_table.us-west-2: ResourceInUseException: Attempt to change a resource which is still in use: Table is being deleted: tf-acc-test-bavzb
			status code: 400, request id: T73SL4E6R3EUUE7E2012Q11DCJVV4KQNSO5AEMVJF66Q9ASUAAJG

Here we increase the retry threshold to allow DynamoDB to get around to deleting all other regions simultaneously.

make testacc TEST=./aws TESTARGS='-run=TestAccAWSDynamoDbGlobalTable_multipleRegions'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -run=TestAccAWSDynamoDbGlobalTable_multipleRegions -timeout 120m
=== RUN   TestAccAWSDynamoDbGlobalTable_multipleRegions
--- PASS: TestAccAWSDynamoDbGlobalTable_multipleRegions (301.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	302.214s