resource/aws_cognito_identity_pool: Refactor to use keyvaluetags package (#11263)
Output from acceptance testing (test failure present on master and unrelated):

```
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithTokenTypeError (10.53s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithRulesTypeError (11.95s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithAmbiguousRoleResolutionError (12.49s)
--- FAIL: TestAccAWSCognitoIdentityPool_openidConnectProviderArns (16.97s)
--- PASS: TestAccAWSCognitoIdentityPool_basic (19.04s)
--- PASS: TestAccAWSCognitoIdentityPool_cognitoIdentityProviders (22.59s)
--- PASS: TestAccAWSCognitoIdentityPool_tags (23.26s)
--- PASS: TestAccAWSCognitoIdentityPool_supportedLoginProviders (23.99s)
--- PASS: TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider (24.44s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_basic (24.71s)
--- PASS: TestAccAWSCognitoIdentityPool_samlProviderArns (26.86s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappings (34.97s)
```