tests/resource/aws_elasticsearch_domain: Add missing ImportStateVerifyIgnore to TestAccAWSElasticSearchDomain_LogPublishingOptions_AuditLogs
Applies the fix given to other tests with the `advanced_security_options` configuration, given the `DescribeElasticsearchDomainConfig` API does not return this information so it cannot be imported.

Previously:

```
=== CONT  TestAccAWSElasticSearchDomain_LogPublishingOptions_AuditLogs
TestAccAWSElasticSearchDomain_LogPublishingOptions_AuditLogs: resource_aws_elasticsearch_domain_test.go:673: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=5) {
(string) (len=49) "advanced_security_options.0.master_user_options.#": (string) (len=1) "1",
(string) (len=51) "advanced_security_options.0.master_user_options.0.%": (string) (len=1) "3",
(string) (len=65) "advanced_security_options.0.master_user_options.0.master_user_arn": (string) "",
(string) (len=66) "advanced_security_options.0.master_user_options.0.master_user_name": (string) (len=14) "testmasteruser",
(string) (len=70) "advanced_security_options.0.master_user_options.0.master_user_password": (string) (len=14) "Barbarbarbar1!"
}
--- FAIL: TestAccAWSElasticSearchDomain_LogPublishingOptions_AuditLogs (1821.76s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSElasticSearchDomain_LogPublishingOptions_AuditLogs (932.09s)
```