deps: Remove direct dependencies on github.com/hashicorp/vault and github.com/hashicorp/errwrap (#14612)
* deps: Remove direct dependencies on github.com/hashicorp/vault and github.com/hashicorp/errwrap

Some additional Terraform Plugin SDK v1 dependencies cleanup.

Output from acceptance testing:

```
--- PASS: TestAccAWSAccessKey_basic (11.62s)
--- PASS: TestAccAWSAccessKey_encrypted (12.81s)
--- PASS: TestAccAWSAccessKey_inactive (19.14s)

--- PASS: TestAccAWSLightsailKeyPair_basic (26.78s)
--- PASS: TestAccAWSLightsailKeyPair_encrypted (25.45s)
--- PASS: TestAccAWSLightsailKeyPair_nameprefix (26.51s)
--- PASS: TestAccAWSLightsailKeyPair_publicKey (25.57s)

--- PASS: TestAccAWSUserLoginProfile_basic (29.80s)
--- PASS: TestAccAWSUserLoginProfile_keybase (14.88s)
--- PASS: TestAccAWSUserLoginProfile_keybaseDoesntExist (8.42s)
--- PASS: TestAccAWSUserLoginProfile_notAKey (8.36s)
--- PASS: TestAccAWSUserLoginProfile_PasswordLength (14.74s)
```

* internal/vault/helper/pgpkeys: Add missing error checking for new internalized code

Previously reported linter error:

```
aws/internal/vault/helper/pgpkeys/encrypt_decrypt.go:114:16: Error return value of `ptBuf.ReadFrom` is not checked (errcheck)
	ptBuf.ReadFrom(md.UnverifiedBody)
	              ^
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAccessKey_basic (10.83s)
--- PASS: TestAccAWSAccessKey_encrypted (10.89s)
--- PASS: TestAccAWSAccessKey_inactive (18.69s)

--- PASS: TestAccAWSLightsailKeyPair_basic (25.49s)
--- PASS: TestAccAWSLightsailKeyPair_encrypted (24.46s)
--- PASS: TestAccAWSLightsailKeyPair_nameprefix (25.67s)
--- PASS: TestAccAWSLightsailKeyPair_publicKey (24.93s)

--- PASS: TestAccAWSUserLoginProfile_basic (21.19s)
--- PASS: TestAccAWSUserLoginProfile_keybase (12.62s)
--- PASS: TestAccAWSUserLoginProfile_keybaseDoesntExist (7.63s)
--- PASS: TestAccAWSUserLoginProfile_notAKey (7.41s)
--- PASS: TestAccAWSUserLoginProfile_PasswordLength (14.54s)
```