tests/resource/aws_storagegateway_cache: Use DiskNode for Local Disk lookup, refactor ARN checks to Pair instead of regexp
Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/12247

Using DiskNode is stable across M4 and M5 instance classes. Also adds missing disk_id acceptance testing workaround that is applied to other aws_storagegateway_cache test configurations.

Previously:

```
--- FAIL: TestAccAWSStorageGatewayCache_FileGateway (259.42s)
    testing.go:669: Step 0 error: errors during apply:

        Error: no results found for query, try adjusting your search criteria

--- FAIL: TestAccAWSStorageGatewayCache_TapeAndVolumeGateway (217.42s)
    testing.go:669: Step 0 error: errors during apply:

        Error: no results found for query, try adjusting your search criteria
```

Output from acceptance testing:

```
--- PASS: TestAccAWSStorageGatewayCache_FileGateway (281.21s)
--- PASS: TestAccAWSStorageGatewayCache_TapeAndVolumeGateway (326.66s)
```