account: enable `go-vcr` support (#44700)
* account: enable `go-vcr` support

Enables `go-vcr` for the `account` service.

```console
% make testacc PKG=account VCR_MODE=RECORD_ONLY VCR_PATH=/tmp/account-vcr-testdata/
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-go-vcr-account 🌿...
TF_ACC=1 go1.24.8 test ./internal/service/account/... -v -count 1 -parallel 20   -timeout 360m -vet=off
2025/10/17 16:23:38 Creating Terraform AWS Provider (SDKv2-style)...
2025/10/17 16:23:38 Initializing Terraform AWS Provider (SDKv2-style)...

=== RUN   TestAccAccount_serial/Region/AccountID
    region_test.go:69: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
    panic.go:636: provider meta not found for test TestAccAccount_serial/Region/AccountID
    panic.go:636: randomness source not found for test TestAccAccount_serial/Region/AccountID
=== RUN   TestAccAccount_serial/Region/basic
    region_test.go:24: Step 1/3 error: Error running apply: exit status 1

        Error: enabling Account Region (ap-southeast-3): operation error Account: EnableRegion, https response error StatusCode: 403, RequestID: 8bfd32c6-d078-49af-bb46-04238374fea1, AccessDeniedException: User: arn:aws:sts::<redacted>:assumed-role/<redacted> is not authorized to perform: account:EnableRegion on resource: arn:aws:account::<redacted>:account with an explicit deny in a service control policy

          with aws_account_region.test,
          on terraform_plugin_test.tf line 12, in resource "aws_account_region" "test":
          12: resource "aws_account_region" "test" {

    panic.go:636: randomness source not found for test TestAccAccount_serial/Region/basic
--- FAIL: TestAccAccount_serial (59.65s)
    --- PASS: TestAccAccount_serial/AlternateContact (29.70s)
        --- PASS: TestAccAccount_serial/AlternateContact/basic (19.58s)
        --- PASS: TestAccAccount_serial/AlternateContact/disappears (10.12s)
        --- SKIP: TestAccAccount_serial/AlternateContact/AccountID (0.00s)
    --- PASS: TestAccAccount_serial/PrimaryContact (26.36s)
        --- PASS: TestAccAccount_serial/PrimaryContact/basic (17.61s)
        --- PASS: TestAccAccount_serial/PrimaryContact/dataSourceBasic (8.75s)
        --- SKIP: TestAccAccount_serial/PrimaryContact/dataSourceAccountID (0.00s)
    --- FAIL: TestAccAccount_serial/Region (3.60s)
        --- SKIP: TestAccAccount_serial/Region/AccountID (0.00s)
        --- FAIL: TestAccAccount_serial/Region/basic (3.60s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/account	66.853s
```

* docs: tweak go-vcr agent guide