resource/aws_iot_thing: Ensure attributes configurations use equals
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSIotThing_full (0.60s)
    testing.go:568: Step 0 error: config is invalid: Unsupported block type: Blocks of type "attributes" are not expected here. Did you mean to define argument "attributes"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- FAIL: TestAccAWSIotThing_full (317.27s)
    testing.go:568: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_iot_thing_type.test
          arn:                      "arn:aws:iot:us-west-2:187416307283:thingtype/tf_acc_type_zaw92zkc" => "arn:aws:iot:us-west-2:187416307283:thingtype/tf_acc_type_zaw92zkc"
          deprecated:               "false" => "false"
          id:                       "tf_acc_type_zaw92zkc" => "tf_acc_type_zaw92zkc"
          name:                     "tf_acc_type_zaw92zkc" => "tf_acc_type_zaw92zkc"
          properties.#:             "1" => ""
          properties.0.description: "" => ""
```