resource/aws_glue_workflow: Ensure max_concurrent_runs attribute is saved during import
The Terraform Plugin SDK version 2.0.4 upgrade fixed something with `ImportStateVerify` testing, which now catches these arguments were not properly being set during `Read`.

Previously:

```
=== CONT  TestAccAWSGlueWorkflow_maxConcurrentRuns
TestAccAWSGlueWorkflow_maxConcurrentRuns: resource_aws_glue_workflow_test.go:82: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) {
}
(map[string]string) (len=1) {
(string) (len=19) "max_concurrent_runs": (string) (len=1) "1"
}
--- FAIL: TestAccAWSGlueWorkflow_maxConcurrentRuns (53.75s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSGlueWorkflow_basic (18.54s)
--- PASS: TestAccAWSGlueWorkflow_DefaultRunProperties (18.56s)
--- PASS: TestAccAWSGlueWorkflow_Description (33.03s)
--- PASS: TestAccAWSGlueWorkflow_disappears (14.56s)
--- PASS: TestAccAWSGlueWorkflow_maxConcurrentRuns (50.47s)
--- PASS: TestAccAWSGlueWorkflow_Tags (48.23s)
```