tests/resource/aws_rds_cluster: Remove enabled_cloudwatch_logs_exports and tags arguments from basic test configuration
This functionality is not required basic functionality for the resource and it is unavailable in certain regions.

Previous output from acceptance testing in AWS GovCloud (US):

```
--- FAIL: TestAccAWSRDSCluster_basic (7.73s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating RDS cluster: InvalidParameterCombination: You can’t use Cloudwatch Logs Export in this region

--- FAIL: TestAccAWSRDSCluster_updateCloudwatchLogsExports (7.92s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating RDS cluster: InvalidParameterCombination: You can’t use Cloudwatch Logs Export in this region

--- FAIL: TestAccAWSRDSCluster_updateTags (7.80s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating RDS cluster: InvalidParameterCombination: You can’t use Cloudwatch Logs Export in this region
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSRDSCluster_basic (159.73s)
--- PASS: TestAccAWSRDSCluster_Tags (206.62s)
--- PASS: TestAccAWSRDSCluster_EnabledCloudwatchLogsExports (227.41s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- FAIL: TestAccAWSRDSCluster_EnabledCloudwatchLogsExports (7.74s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating RDS cluster: InvalidParameterCombination: You can’t use Cloudwatch Logs Export in this region

--- PASS: TestAccAWSRDSCluster_basic (130.58s)
--- PASS: TestAccAWSRDSCluster_Tags (176.46s)
```