r/aws_vpc_default_route_table: convert to aws sdk v2
```console
%  make testacc PKG=ec2 TESTS="TestAccVPCDefaultRouteTable_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCDefaultRouteTable_'  -timeout 360m

--- PASS: TestAccVPCDefaultRouteTable_Disappears_vpc (15.78s)
--- PASS: TestAccVPCDefaultRouteTable_basic (23.28s)
--- PASS: TestAccVPCDefaultRouteTable_vpcEndpointAssociation (30.02s)
--- PASS: TestAccVPCDefaultRouteTable_tags (35.38s)
--- PASS: TestAccVPCDefaultRouteTable_prefixListToInternetGateway (37.40s)
--- PASS: TestAccVPCDefaultRouteTable_conditionalCIDRBlock (42.21s)
--- PASS: TestAccVPCDefaultRouteTable_Route_mode (48.90s)
--- PASS: TestAccVPCDefaultRouteTable_swap (57.83s)
--- PASS: TestAccVPCDefaultRouteTable_revokeExistingRules (111.44s)
=== NAME  TestAccVPCDefaultRouteTable_ipv4ToVPCEndpoint
    vpc_default_route_table_test.go:284: Step 1/3 error: Error running apply: exit status 1

        Error: modifying EC2 VPC Endpoint Service (vpce-svc-0182916f82dfce5bc) permissions: InvalidPrincipal: Invalid Principal: 'arn:aws:sts::727561393803:assumed-role/tf_aws_provider3_test-admin/jared.baker@hashicorp.com'
                status code: 400, request id: 124fc972-f18f-45fc-9cea-d1ba64a98108

          with aws_vpc_endpoint_service.test,
          on terraform_plugin_test.tf line 59, in resource "aws_vpc_endpoint_service" "test":
          59: resource "aws_vpc_endpoint_service" "test" {

--- FAIL: TestAccVPCDefaultRouteTable_ipv4ToVPCEndpoint (193.01s)
--- PASS: TestAccVPCDefaultRouteTable_ipv4ToTransitGateway (317.38s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        322.446s
```

Note: failing test is due to permissions on the test account user, and does not
fail in CI.