r/aws_lambda_event_source_mapping: add `use_resource_timeout_for_propagation` argument
```console
% make t K=lambda T=TestAccLambdaEventSourceMapping_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 b-lambda-iam-propagation-timeout 🌿...
TF_ACC=1 go1.26.4 test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaEventSourceMapping_'  -timeout 360m -vet=off
2026/07/08 10:19:51 Creating Terraform AWS Provider (SDKv2-style)...
2026/07/08 10:19:51 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig (73.34s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_parallelizationFactor
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_destination (109.01s)
=== CONT  TestAccLambdaEventSourceMapping_List_basic
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_startingPositionTimestamp (118.45s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_batchWindow
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_tumblingWindowInSeconds (122.83s)
=== CONT  TestAccLambdaEventSourceMapping_rabbitMQ
--- PASS: TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected (128.64s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_metricsConfig
--- PASS: TestAccLambdaEventSourceMapping_List_regionOverride (128.72s)
=== CONT  TestAccLambdaEventSourceMapping_documentDB
--- PASS: TestAccLambdaEventSourceMapping_SQS_batchWindow (131.80s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_scalingConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttempts (144.80s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_filterCriteria
--- PASS: TestAccLambdaEventSourceMapping_DynamoDB_functionResponseTypes (148.10s)
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithOnFailureDestination
--- PASS: TestAccLambdaEventSourceMapping_DynamoDB_streamAdded (163.86s)
=== CONT  TestAccLambdaEventSourceMapping_activeMQ
--- PASS: TestAccLambdaEventSourceMapping_Identity_ExistingResource_noRefreshNoChange (166.28s)
=== CONT  TestAccLambdaEventSourceMapping_mskWithEventSourceConfigSchemaRegistry
--- PASS: TestAccLambdaEventSourceMapping_List_includeResource (169.96s)
=== CONT  TestAccLambdaEventSourceMapping_mskWithOnFailureDestination
--- PASS: TestAccLambdaEventSourceMapping_DynamoDB_basic (171.06s)
=== CONT  TestAccLambdaEventSourceMapping_tags
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_bisectBatch (171.43s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_basic
=== NAME  TestAccLambdaEventSourceMapping_rabbitMQ
    event_source_mapping_test.go:1511: Step 1/2 error: Error running apply: exit status 1

        Error: creating MQ Broker (tf-acc-test-6032618144654602016): operation error mq: CreateBroker, https response error StatusCode: 400, RequestID: 255180cf-2c69-46a2-89d6-37cc2ef17f4b, BadRequestException: Broker engine type [RabbitMQ] does not support host instance type [mq.t3.micro].

          with aws_mq_broker.test,
          on terraform_plugin_test.tf line 66, in resource "aws_mq_broker" "test":
          66: resource "aws_mq_broker" "test" {

--- PASS: TestAccLambdaEventSourceMapping_Identity_ExistingResource_basic (181.48s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSeconds
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsZero (181.77s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSecondsNegativeOne
--- FAIL: TestAccLambdaEventSourceMapping_rabbitMQ (63.16s)
=== CONT  TestAccLambdaEventSourceMapping_Identity_regionOverride
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafka (191.00s)
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithProvisionedPollerConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_parallelizationFactor (126.75s)
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfigSchemaRegistry
--- PASS: TestAccLambdaEventSourceMapping_disappears (208.88s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsNegativeOne
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_batchWindow (98.28s)
=== CONT  TestAccLambdaEventSourceMapping_KMSKeyARN
--- PASS: TestAccLambdaEventSourceMapping_Identity_basic (217.10s)
=== CONT  TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithOnFailureDestination (82.96s)
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_basic
--- PASS: TestAccLambdaEventSourceMapping_List_basic (136.58s)
--- PASS: TestAccLambdaEventSourceMapping_tags (119.40s)
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSeconds (114.24s)
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRecordAgeInSecondsNegativeOne (120.75s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_metricsConfig (175.51s)
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfigSchemaRegistry (128.48s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_scalingConfig (200.66s)
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithProvisionedPollerConfig (141.63s)
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_maximumRetryAttemptsNegativeOne (134.85s)
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_basic (133.66s)
--- PASS: TestAccLambdaEventSourceMapping_KMSKeyARN (151.38s)
--- PASS: TestAccLambdaEventSourceMapping_Identity_regionOverride (189.42s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_basic (208.82s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_filterCriteria (252.69s)
=== NAME  TestAccLambdaEventSourceMapping_documentDB
    event_source_mapping_test.go:1696: Step 1/2 error: After applying this test step, the non-refresh plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement

        Terraform will perform the following actions:

          # aws_lambda_event_source_mapping.test must be replaced
        -/+ resource "aws_lambda_event_source_mapping" "test" {
              ~ arn                                = "arn:aws:lambda:us-west-2:<redacted>:event-source-mapping:06381220-d67c-4085-bc9a-c6866b2e66c1" -> (known after apply)
              - batch_size                         = 100 -> null
              - bisect_batch_on_function_error     = false -> null
              ~ function_arn                       = "arn:aws:lambda:us-west-2:<redacted>:function:tf-acc-test-8297617369699662093" -> (known after apply)
              ~ id                                 = "06381220-d67c-4085-bc9a-c6866b2e66c1" -> (known after apply)
              ~ last_modified                      = "2026-07-08T14:23:02Z" -> (known after apply)
              ~ last_processing_result             = "No records processed" -> (known after apply)
              - maximum_batching_window_in_seconds = 0 -> null
              ~ maximum_record_age_in_seconds      = 0 -> (known after apply)
              ~ maximum_retry_attempts             = 0 -> (known after apply)
              ~ parallelization_factor             = 0 -> (known after apply)
              - starting_position                  = "LATEST" -> null # forces replacement
              ~ state                              = "Enabled" -> (known after apply)
              ~ state_transition_reason            = "USER_INITIATED" -> (known after apply)
              ~ tags_all                           = {} -> (known after apply)
              - tumbling_window_in_seconds         = 0 -> null
              ~ uuid                               = "06381220-d67c-4085-bc9a-c6866b2e66c1" -> (known after apply)
                # (6 unchanged attributes hidden)

              ~ amazon_managed_kafka_event_source_config (known after apply)

              ~ self_managed_kafka_event_source_config (known after apply)

                # (2 unchanged blocks hidden)
            }

        Plan: 1 to add, 0 to change, 1 to destroy.
=== NAME  TestAccLambdaEventSourceMapping_activeMQ
    event_source_mapping_test.go:1456: Step 1/2 error: After applying this test step, the non-refresh plan was not empty.
        stdout:

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_mq_broker.test will be updated in-place
          ~ resource "aws_mq_broker" "test" {
                id                            = "b-49247417-5076-49d1-8d35-b7df591da5f8"
              + shared_resources              = (known after apply)
                # (18 unchanged attributes hidden)

                # (5 unchanged blocks hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccLambdaEventSourceMapping_activeMQ (1029.76s)
--- FAIL: TestAccLambdaEventSourceMapping_documentDB (1596.06s)
--- PASS: TestAccLambdaEventSourceMapping_mskWithOnFailureDestination (1823.80s)
--- PASS: TestAccLambdaEventSourceMapping_mskWithEventSourceConfigSchemaRegistry (1920.99s)
--- PASS: TestAccLambdaEventSourceMapping_mskWithEventSourceConfig (2945.68s)
--- PASS: TestAccLambdaEventSourceMapping_msk (3219.67s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/lambda     3227.999s
```

Failures are unrelated to this change.