tests/resource/aws_ssm_document: Add missing owners argument and fix deprecation in automation test
Previous output from acceptance testing:

```
--- FAIL: TestAccAWSSSMDocument_automation (0.83s)
    testing.go:538: Step 0 error: config is invalid: 2 problems:

        - aws_iam_instance_profile.ssm_profile: "roles": [DEPRECATED] Use `role` instead. Only a single role can be passed to an IAM Instance Profile
        - data.aws_ami.ssm_ami: "owners": required field is not set
```

Output from acceptance testing:

```
--- PASS: TestAccAWSSSMDocument_automation (20.54s)
```