r/aws_budgets_budget: Switch to 'WithoutTimeout' CRUD handlers (#15090).
Acceptance test output:

% make testacc TESTARGS='-run=TestAccBudgetsBudget_' PKG=budgets ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/budgets/... -v -count 1 -parallel 2  -run=TestAccBudgetsBudget_ -timeout 180m
=== RUN   TestAccBudgetsBudget_basic
=== PAUSE TestAccBudgetsBudget_basic
=== RUN   TestAccBudgetsBudget_Name_generated
=== PAUSE TestAccBudgetsBudget_Name_generated
=== RUN   TestAccBudgetsBudget_namePrefix
=== PAUSE TestAccBudgetsBudget_namePrefix
=== RUN   TestAccBudgetsBudget_disappears
=== PAUSE TestAccBudgetsBudget_disappears
=== RUN   TestAccBudgetsBudget_autoAdjustDataForecast
=== PAUSE TestAccBudgetsBudget_autoAdjustDataForecast
=== RUN   TestAccBudgetsBudget_autoAdjustDataHistorical
=== PAUSE TestAccBudgetsBudget_autoAdjustDataHistorical
=== RUN   TestAccBudgetsBudget_costTypes
=== PAUSE TestAccBudgetsBudget_costTypes
=== RUN   TestAccBudgetsBudget_notifications
=== PAUSE TestAccBudgetsBudget_notifications
=== CONT  TestAccBudgetsBudget_basic
=== CONT  TestAccBudgetsBudget_autoAdjustDataForecast
--- PASS: TestAccBudgetsBudget_autoAdjustDataForecast (19.37s)
=== CONT  TestAccBudgetsBudget_notifications
--- PASS: TestAccBudgetsBudget_basic (19.50s)
=== CONT  TestAccBudgetsBudget_costTypes
--- PASS: TestAccBudgetsBudget_costTypes (27.49s)
=== CONT  TestAccBudgetsBudget_autoAdjustDataHistorical
--- PASS: TestAccBudgetsBudget_notifications (31.83s)
=== CONT  TestAccBudgetsBudget_namePrefix
=== CONT  TestAccBudgetsBudget_autoAdjustDataHistorical
    budget_test.go:203: Step 1/3 error: Check failed: Check 5/12 error: aws_budgets_budget.test: Attribute 'auto_adjust_data.0.historical_options.0.lookback_available_periods' expected "2", got "0"
--- FAIL: TestAccBudgetsBudget_autoAdjustDataHistorical (8.55s)
=== CONT  TestAccBudgetsBudget_disappears
--- PASS: TestAccBudgetsBudget_disappears (11.86s)
=== CONT  TestAccBudgetsBudget_Name_generated
--- PASS: TestAccBudgetsBudget_namePrefix (16.41s)
--- PASS: TestAccBudgetsBudget_Name_generated (18.48s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/budgets	90.021s
FAIL
make: *** [testacc] Error 1