resource/aws_appsync_graphql_api: Adjust error messaging for context and proper formatter typing
Previously error messages during creation would use an incorrect format verb which was harder to read:

```
--- FAIL: TestAccAWSAppsyncGraphqlApi_basic (0.50s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating AppSync GraphQL API: &{%!d(string=RequestError) %!d(string=send request failed) [824649821952]}
```

Now error messages are properly formatted and consistently applied across Create/Read/Update/Delete functions.

```
--- FAIL: TestAccAWSAppsyncGraphqlApi_basic (6.36s)
    testing.go:568: Step 0 error: errors during apply:

        Error: error creating AppSync GraphQL API: RequestError: send request failed
        caused by: Post https://appsync.us-gov-west-1.amazonaws.com/v1/apis: dial tcp: lookup appsync.us-gov-west-1.amazonaws.com: no such host
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAppsyncGraphqlApi_disappears (12.98s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AWSIAM (13.22s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_APIKey (13.49s)
--- PASS: TestAccAWSAppsyncGraphqlApi_basic (13.94s)
--- PASS: TestAccAWSAppsyncGraphqlApi_LogConfig (15.25s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_OpenIDConnect (15.56s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType_AmazonCognitoUserPools (15.93s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_Issuer (19.66s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_ClientID (19.78s)
--- PASS: TestAccAWSAppsyncGraphqlApi_AuthenticationType (19.99s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_AuthTTL (21.15s)
--- PASS: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_DefaultAction (22.64s)
--- PASS: TestAccAWSAppsyncGraphqlApi_UserPoolConfig_AwsRegion (22.64s)
--- PASS: TestAccAWSAppsyncGraphqlApi_LogConfig_FieldLogLevel (27.56s)
--- PASS: TestAccAWSAppsyncGraphqlApi_OpenIDConnectConfig_IatTTL (29.54s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Name (29.79s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Schema (29.99s)
--- PASS: TestAccAWSAppsyncGraphqlApi_Tags (30.21s)
```