Updated indexing_configuration thing_indexing_configuration with filter
AWS updated the [Create|Get|Update]IndexingConfiguration requests with a new optional parameter: filter
This filter attribute IS required now, when named_shadow_indexing_mode is set to ON.
https://docs.aws.amazon.com/iot/latest/apireference/API_ThingIndexingConfiguration.html

If filter is missing in the described case above, then the following error message is returned:
Error: error updating IoT Indexing Configuration: InvalidRequestException: NamedShadowNames Filter must not be empty for enabling NamedShadowIndexingMode