tests/resource/aws_sns_topic_subscription: Use Terraform 0.11.12 and later compatible file hashing function
The updated file hashing function is forwards compatible with Terraform 0.12, which does not allow the use of the `file()` function with binary file content.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint (1.84s)
    testing.go:568: Step 0 error: config is invalid: Error in function call: Call to function "file" failed: contents of test-fixtures/lambda_confirm_sns.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
--- FAIL: TestAccAWSSNSTopicSubscription_autoConfirmingSecuredEndpoint (1.84s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Error in function call: Call to function "file" failed: contents of test-fixtures/lambda_confirm_sns.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
        - Error in function call: Call to function "file" failed: contents of test-fixtures/lambda_basic_authorizer.zip are not valid UTF-8; to read arbitrary bytes, use the filebase64 function instead.
```

Output from Terraform 0.11.12 acceptance testing:

```
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint (43.36s)
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingSecuredEndpoint (64.80s)
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint (43.75s)
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingSecuredEndpoint (80.95s)
```