tests/service/elasticache: Replace deprecated cache.m1 with cache.t3, refactor data source testing
Previously (since Feb 5, 2020):

```
--- FAIL: TestAccAWSElasticacheReplicationGroup_basic (11.22s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error creating Elasticache Replication Group: InvalidParameterValue: Invalid Cache Node Type: cache.m1.small
```