resource/aws_batch_compute_environment: Remove resource from Terraform state when not found instead of returning error
Reference: https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/running-and-writing-acceptance-tests.md#disappears-acceptance-tests
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12337
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13826

Previously:

```
=== CONT  TestAccAWSBatchComputeEnvironment_disappears
    TestAccAWSBatchComputeEnvironment_disappears: testing.go:684: Step 0 error: errors during follow-up refresh:

        Error: One compute environment is expected, but AWS return no compute environment

    TestAccAWSBatchComputeEnvironment_disappears: testing.go:745: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: errors during refresh: One compute environment is expected, but AWS return no compute environment

        State: <nil>
--- FAIL: TestAccAWSBatchComputeEnvironment_disappears (59.70s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources (35.53s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage (35.72s)
--- PASS: TestAccAWSBatchComputeEnvironment_createWithNamePrefix (64.40s)
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources (67.27s)
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanaged (67.28s)
--- PASS: TestAccAWSBatchComputeEnvironment_disappears (71.92s)
--- PASS: TestAccAWSBatchComputeEnvironment_launchTemplate (72.52s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot (72.67s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithAllocationStrategy (74.33s)
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2 (80.45s)
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithTags (81.01s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateState (93.78s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateInstanceType (105.25s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName (114.21s)
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate (114.41s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus (135.46s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_DesiredVcpus_Computed (171.29s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus (216.35s)
```