r/aws_elasticsearch_domain: handle unset auto_tune_options.rollback_on_disable
Previously omitting this optional argument resulted in a failure when creating or updating the domain:

```
Error: modifying config for OpenSearch Domain: ValidationException: 1 validation error detected: Value '' at 'autoTuneOptions.rollbackOnDisable' failed to satisfy constraint: Member must satisfy enum value set: [DEFAULT_ROLLBACK, NO_ROLLBACK]
```

The `auto_tune_options` expander logic has been updated to properly handle cases where `rollback_on_disable` is unset.

```console
% make testacc PKG=elasticsearch TESTS=TestAccElasticsearchDomain_AutoTuneOptions
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/elasticsearch/... -v -count 1 -parallel 20 -run='TestAccElasticsearchDomain_AutoTuneOptions'  -timeout 360m
=== RUN   TestAccElasticsearchDomain_AutoTuneOptions
=== PAUSE TestAccElasticsearchDomain_AutoTuneOptions
=== CONT  TestAccElasticsearchDomain_AutoTuneOptions
--- PASS: TestAccElasticsearchDomain_AutoTuneOptions (2287.79s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch      2292.708s
```