r/aws_grafana_workspace: Change 'authentication_providers' to ForceNew, otherwise:
% make testacc TESTS=TestAccGrafanaWorkspace_updateAuthenticationProvider PKG=grafana
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/grafana/... -v -count 1 -parallel 20 -run='TestAccGrafanaWorkspace_updateAuthenticationProvider'  -timeout 180m
=== RUN   TestAccGrafanaWorkspace_updateAuthenticationProvider
=== PAUSE TestAccGrafanaWorkspace_updateAuthenticationProvider
=== CONT  TestAccGrafanaWorkspace_updateAuthenticationProvider
    workspace_test.go:132: Step 3/3 error: Error running apply: exit status 1

        Error: error updating Grafana Workspace (g-c1118c98ae) authentication providers: ValidationException: To enable SAML you must provide the SAML configuration struct.
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "f65d4348-0f1d-4093-ac6a-ee61531eeea2"
          },
          Message_: "To enable SAML you must provide the SAML configuration struct."
        }

          with aws_grafana_workspace.test,
          on terraform_plugin_test.tf line 20, in resource "aws_grafana_workspace" "test":
          20: resource "aws_grafana_workspace" "test" {

--- FAIL: TestAccGrafanaWorkspace_updateAuthenticationProvider (158.85s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	164.194s
FAIL
make: *** [testacc] Error 1

Serialize acceptance tests.

Acceptance test output:

% make testacc TESTS=TestAccGrafana_serial PKG=grafana
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/grafana/... -v -count 1 -parallel 20 -run='TestAccGrafana_serial'  -timeout 180m
=== RUN   TestAccGrafana_serial
=== RUN   TestAccGrafana_serial/Workspace
=== RUN   TestAccGrafana_serial/Workspace/saml
=== RUN   TestAccGrafana_serial/Workspace/sso
    acctest.go:731: skipping tests: AccessDeniedException: User: arn:aws:sts::187416307283:assumed-role/terraform_team1_dev-developer/kewbank@hashicorp.com is not authorized to perform: sso:ListInstances
=== RUN   TestAccGrafana_serial/Workspace/disappears
=== RUN   TestAccGrafana_serial/Workspace/organization
    acctest.go:711: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccGrafana_serial/Workspace/dataSources
=== RUN   TestAccGrafana_serial/Workspace/permissionType
=== RUN   TestAccGrafana_serial/Workspace/notificationDestinations
--- PASS: TestAccGrafana_serial (993.54s)
    --- PASS: TestAccGrafana_serial/Workspace (993.54s)
        --- PASS: TestAccGrafana_serial/Workspace/saml (316.99s)
        --- SKIP: TestAccGrafana_serial/Workspace/sso (0.42s)
        --- PASS: TestAccGrafana_serial/Workspace/disappears (147.69s)
        --- SKIP: TestAccGrafana_serial/Workspace/organization (0.32s)
        --- PASS: TestAccGrafana_serial/Workspace/dataSources (160.39s)
        --- PASS: TestAccGrafana_serial/Workspace/permissionType (185.30s)
        --- PASS: TestAccGrafana_serial/Workspace/notificationDestinations (182.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	999.459s