service/ecs: Tagging support and aws_ecs_cluster refactoring
`aws_ecs_cluster` resource refactoring was due to it not performing `Read` after `Create`.

Changes:
* resource/aws_ecs_cluster: Add `tags` argument
* resource/aws_ecs_service: Add `tags` argument
* resource/aws_ecs_task_definition: Add `tags` argument
* resource/aws_ecs_cluster: Refactoring to call `Read` after `Create` to ensure proper creation
* tests/resource/aws_ecs_cluster: Add `_disappears` acceptance test
* tests/resource/aws_ecs_cluster: Ensure `testAccCheckAWSEcsClusterExists` actually checks existence in API

Without account setting update to newer ARNs (test failure expected):

```
--- PASS: TestAccAWSEcsCluster_basic (11.17s)
--- PASS: TestAccAWSEcsCluster_disappears (7.16s)
--- PASS: TestAccAWSEcsCluster_Tags (26.76s)
--- PASS: TestAccAWSEcsDataSource_ecsCluster (31.49s)
--- PASS: TestAccAWSEcsDataSource_ecsContainerDefinition (41.57s)
--- PASS: TestAccAWSEcsDataSource_ecsTaskDefinition (13.08s)
--- PASS: TestAccAWSEcsService_basicImport (26.50s)
--- PASS: TestAccAWSEcsService_disappears (34.44s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (348.42s)
--- PASS: TestAccAWSEcsService_withAlb (389.07s)
--- PASS: TestAccAWSEcsService_withARN (48.69s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (40.07s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (17.27s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (39.65s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (16.66s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (14.49s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (46.79s)
--- PASS: TestAccAWSEcsService_withIamRole (115.51s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (76.90s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (154.78s)
--- PASS: TestAccAWSEcsService_withLbChanges (220.54s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (41.21s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (29.47s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (78.79s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (56.19s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (40.89s)
--- PASS: TestAccAWSEcsService_withServiceRegistries (42.00s)
--- PASS: TestAccAWSEcsService_withServiceRegistries_container (50.34s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (30.06s)

--- FAIL: TestAccAWSEcsService_Tags (6.57s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
          * aws_ecs_service.test: 1 error occurred:
          * aws_ecs_service.test: InvalidParameterException: The new ARN and resource ID format must be enabled to add tags to the service. Opt in to the new format and try again.

--- PASS: TestAccAWSEcsServiceDataSource_basic (42.88s)
--- PASS: TestAccAWSEcsTaskDefinition_arrays (10.51s)
--- PASS: TestAccAWSEcsTaskDefinition_basic (16.31s)
--- PASS: TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource (17.57s)
--- PASS: TestAccAWSEcsTaskDefinition_constraint (10.68s)
--- PASS: TestAccAWSEcsTaskDefinition_ExecutionRole (10.89s)
--- PASS: TestAccAWSEcsTaskDefinition_Fargate (13.56s)
--- PASS: TestAccAWSEcsTaskDefinition_Inactive (17.45s)
--- PASS: TestAccAWSEcsTaskDefinition_Tags (24.18s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolume (10.60s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig (9.50s)
--- PASS: TestAccAWSEcsTaskDefinition_withEcsService (71.29s)
--- PASS: TestAccAWSEcsTaskDefinition_withNetworkMode (11.40s)
--- PASS: TestAccAWSEcsTaskDefinition_withScratchVolume (10.58s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskRoleArn (11.65s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume (9.24s)
```

With account settings update to newer ARNs:

```
--- PASS: TestAccAWSEcsCluster_basic (11.24s)
--- PASS: TestAccAWSEcsCluster_disappears (6.97s)
--- PASS: TestAccAWSEcsCluster_Tags (25.11s)
--- PASS: TestAccAWSEcsDataSource_ecsCluster (41.26s)
--- PASS: TestAccAWSEcsDataSource_ecsContainerDefinition (77.07s)
--- PASS: TestAccAWSEcsDataSource_ecsTaskDefinition (13.00s)
--- PASS: TestAccAWSEcsService_basicImport (33.62s)
--- PASS: TestAccAWSEcsService_disappears (20.62s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (260.87s)
--- PASS: TestAccAWSEcsService_Tags (40.60s)
--- PASS: TestAccAWSEcsService_withAlb (251.52s)
--- PASS: TestAccAWSEcsService_withARN (37.32s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (28.73s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (17.14s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (25.08s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (40.52s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (41.37s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (47.26s)
--- PASS: TestAccAWSEcsService_withIamRole (131.40s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (85.49s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (157.27s)
--- PASS: TestAccAWSEcsService_withLbChanges (220.89s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (40.17s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (75.42s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (100.87s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (57.42s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (40.44s)
--- PASS: TestAccAWSEcsService_withServiceRegistries (50.57s)
--- PASS: TestAccAWSEcsService_withServiceRegistries_container (54.97s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (19.74s)
--- PASS: TestAccAWSEcsServiceDataSource_basic (34.22s)
--- PASS: TestAccAWSEcsTaskDefinition_arrays (11.26s)
--- PASS: TestAccAWSEcsTaskDefinition_basic (33.55s)
--- PASS: TestAccAWSEcsTaskDefinition_changeVolumesForcesNewResource (24.14s)
--- PASS: TestAccAWSEcsTaskDefinition_constraint (9.49s)
--- PASS: TestAccAWSEcsTaskDefinition_ExecutionRole (10.83s)
--- PASS: TestAccAWSEcsTaskDefinition_Fargate (14.78s)
--- PASS: TestAccAWSEcsTaskDefinition_Inactive (17.59s)
--- PASS: TestAccAWSEcsTaskDefinition_Tags (24.01s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolume (22.39s)
--- PASS: TestAccAWSEcsTaskDefinition_withDockerVolumeMinimalConfig (9.48s)
--- PASS: TestAccAWSEcsTaskDefinition_withEcsService (70.93s)
--- PASS: TestAccAWSEcsTaskDefinition_withNetworkMode (10.23s)
--- PASS: TestAccAWSEcsTaskDefinition_withScratchVolume (13.30s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskRoleArn (10.80s)
--- PASS: TestAccAWSEcsTaskDefinition_withTaskScopedDockerVolume (14.35s)
```