resource/aws_network_acl: Set SchemaConfigModeAttr on egress and ingress configuration block attributes
References:

* https://github.com/hashicorp/terraform/issues/20505
* https://github.com/hashicorp/terraform/pull/20626

In Terraform 0.12, behaviors with configuration blocks are more explicit to allow configuration language improvements and remove ambiguities that required various undocumented workarounds in Terraform 0.11 and prior. As a consequence, configuration blocks that are marked `Optional: true` and `Computed: true` will no longer support explicitly zero-ing out the configuration without special implementation.

The `ConfigMode` schema parameter on the configuration block attribute allows the schema to override certain behaviors. In particular, setting `ConfigMode: schema.SchemaConfigModeAttr` will allow practitioners to continue setting the configuration block attribute to an empty list (in the semantic sense, e.g. `attr = []`), keeping this prior behavior in Terraform 0.12. This parameter does not have any effect with Terraform 0.11. This solution may be temporary or revisited in the future.

Previous output from Terraform 0.11:

```
--- PASS: TestAccAWSNetworkAcl_Egress_ConfigMode (53.47s)
--- PASS: TestAccAWSNetworkAcl_Ingress_ConfigMode (51.81s)
```

Previous output from Terraform 0.12:

```
--- FAIL: TestAccAWSNetworkAcl_Egress_ConfigMode (38.74s)
    testing.go:568: Step 4 error: config is invalid: Unsupported argument: An argument named "egress" is not expected here. Did you mean "ingress"?

--- FAIL: TestAccAWSNetworkAcl_Ingress_ConfigMode (38.89s)
    testing.go:568: Step 4 error: config is invalid: Unsupported argument: An argument named "ingress" is not expected here. Did you mean to define a block of type "ingress"?
```

Output from Terraform 0.11:

```
--- PASS: TestAccAWSNetworkAcl_Egress_ConfigMode (52.88s)
--- PASS: TestAccAWSNetworkAcl_Ingress_ConfigMode (52.70s)
```

Output from Terraform 0.12:

```
--- PASS: TestAccAWSNetworkAcl_Egress_ConfigMode (52.43s)
--- PASS: TestAccAWSNetworkAcl_Ingress_ConfigMode (53.60s)
```