data-source/aws_lb_listener: Add missing attributes from resource
Previously, the data source would silently fail setting "default_action" attributes.

```
--- FAIL: TestAccDataSourceAWSLBListener_basic (194.84s)
    testing.go:538: Step 0 error: Check failed: 6 errors occurred:
        	* Check 3/14 error: data.aws_lb_listener.front_end: Attribute 'default_action.0.target_group_arn' expected to be set
        	* Check 6/14 error: data.aws_lb_listener.front_end: Attribute 'default_action.#' not found
        	* Check 7/14 error: data.aws_lb_listener.front_end: Attribute 'default_action.0.type' not found
        	* Check 10/14 error: data.aws_lb_listener.from_lb_and_port: Attribute 'default_action.0.target_group_arn' expected to be set
        	* Check 13/14 error: data.aws_lb_listener.from_lb_and_port: Attribute 'default_action.#' not found
        	* Check 14/14 error: data.aws_lb_listener.from_lb_and_port: Attribute 'default_action.0.type' not found
```

With error handling enabled in the resource, we now receive proper errors to catch this problem:

```
--- FAIL: TestAccDataSourceAWSLBListener_basic (173.14s)
    testing.go:538: Step 0 error: Error applying: 2 errors occurred:
        	* data.aws_lb_listener.from_lb_and_port: data.aws_lb_listener.from_lb_and_port: error setting default_action: Invalid address to set: []string{"default_action", "0", "order"}
        	* data.aws_lb_listener.front_end: data.aws_lb_listener.front_end: error setting default_action: Invalid address to set: []string{"default_action", "0", "order"}
```

After adding the attributes to the data source and the error handling, all existing acceptance testing is now passing:

```
--- PASS: TestAccAWSLBListener_oidc (201.60s)
--- PASS: TestAccAWSLBListener_fixedResponse (212.49s)
--- PASS: TestAccAWSLBListener_BackwardsCompatibility (212.58s)
--- PASS: TestAccDataSourceAWSLBListener_basic (213.95s)
--- PASS: TestAccAWSLBListener_redirect (223.34s)
--- PASS: TestAccAWSLBListener_basic (223.43s)
--- PASS: TestAccAWSLBListener_DefaultAction_Order (224.11s)
--- PASS: TestAccDataSourceAWSLBListener_https (225.09s)
--- PASS: TestAccDataSourceAWSLBListener_BackwardsCompatibility (225.14s)
--- PASS: TestAccAWSLBListener_https (235.40s)
--- PASS: TestAccAWSLBListener_cognito (234.78s)
--- PASS: TestAccAWSLBListener_DefaultAction_Order_Recreates (255.74s)
```