r/aws_amplify_app: fix crash updating `auto_branch_creation_config`
The update operation was missing the appropriate checks to ensure nil values were not passed into the expander function.

```console
% make testacc PKG=amplify TESTS=TestAccAmplify_serial/App
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/amplify/... -v -count 1 -parallel 20 -run='TestAccAmplify_serial/App'  -timeout 360m

--- FAIL: TestAccAmplify_serial (7326.08s)
    --- FAIL: TestAccAmplify_serial/App (7326.08s)
        --- PASS: TestAccAmplify_serial/App/tags (5258.13s)
            --- PASS: TestAccAmplify_serial/App/tags/EmptyTag_OnCreate (292.74s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_providerOnly (311.60s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_nonOverlapping (302.30s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_nullOverlappingResourceTag (282.80s)
            --- PASS: TestAccAmplify_serial/App/tags/basic (310.23s)
            --- PASS: TestAccAmplify_serial/App/tags/EmptyTag_OnUpdate_Add (299.40s)
            --- PASS: TestAccAmplify_serial/App/tags/EmptyTag_OnUpdate_Replace (289.53s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_overlapping (303.28s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_updateToProviderOnly (290.14s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_emptyResourceTag (282.28s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_nullNonOverlappingResourceTag (283.03s)
            --- PASS: TestAccAmplify_serial/App/tags/ComputedTag_OnCreate (293.87s)
            --- PASS: TestAccAmplify_serial/App/tags/null (284.63s)
            --- PASS: TestAccAmplify_serial/App/tags/ComputedTag_OnUpdate_Replace (292.53s)
            --- PASS: TestAccAmplify_serial/App/tags/ComputedTag_OnUpdate_Add (291.90s)
            --- PASS: TestAccAmplify_serial/App/tags/DefaultTags_updateToResourceOnly (288.73s)
            --- PASS: TestAccAmplify_serial/App/tags/AddOnUpdate (289.13s)
        --- FAIL: TestAccAmplify_serial/App/AutoBranchCreationConfig (14.44s)
        --- FAIL: TestAccAmplify_serial/App/BasicAuthCredentials (6.04s)
        --- FAIL: TestAccAmplify_serial/App/EnvironmentVariables (19.97s)
        --- SKIP: TestAccAmplify_serial/App/Repository (0.00s)
        --- PASS: TestAccAmplify_serial/App/basic (280.71s)
        --- PASS: TestAccAmplify_serial/App/BuildSpec (292.99s)
        --- PASS: TestAccAmplify_serial/App/CustomRules (295.51s)
        --- PASS: TestAccAmplify_serial/App/Description (294.85s)
        --- PASS: TestAccAmplify_serial/App/IamServiceRole (296.00s)
        --- PASS: TestAccAmplify_serial/App/Name (287.57s)
        --- PASS: TestAccAmplify_serial/App/disappears (279.85s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/amplify    7332.066s
```

Test failures are pre-existing and present in CI, not a related to this change.