resource/aws_secretsmanager_secret: Handle additional scheduled for deletion InvalidRequestException error during immediate recreation
Previous output from acceptance testing:

```
--- FAIL: TestAccAwsSecretsManagerSecret_RecoveryWindowInDays_Recreate (6.87s)
    testing.go:538: Step 1 error: Error applying: 1 error occurred:
          * aws_secretsmanager_secret.test: 1 error occurred:
          * aws_secretsmanager_secret.test: error creating Secrets Manager Secret: InvalidRequestException: You can't create this secret because a secret with this name is already scheduled for deletion.
```

Output from acceptance testing:

```
--- PASS: TestAccAwsSecretsManagerSecret_policy (10.63s)
--- PASS: TestAccAwsSecretsManagerSecret_Basic (11.18s)
--- PASS: TestAccAwsSecretsManagerSecret_withNamePrefix (11.23s)
--- PASS: TestAccAwsSecretsManagerSecret_Description (19.12s)
--- PASS: TestAccAwsSecretsManagerSecret_Tags (33.62s)
--- PASS: TestAccAwsSecretsManagerSecret_RecoveryWindowInDays_Recreate (45.49s)
--- PASS: TestAccAwsSecretsManagerSecret_RotationLambdaARN (46.06s)
--- PASS: TestAccAwsSecretsManagerSecret_RotationRules (48.05s)
--- PASS: TestAccAwsSecretsManagerSecret_KmsKeyID (50.75s)
```