.github/workflows: fix formatting in `post_publish` shell script
A missed quote caused the script to fail during the `v5.77.0` release.

```
/home/runner/work/_temp/b9a14e53-10ad-497f-a91b-d57575e541f4.sh: line 12: unexpected EOF while looking for matching `"'
Error: Process completed with exit code 2.
```