r/aws_simpledb_domain: Implement using terraform-plugin-framework.
Acceptance test output:

% make testacc TESTARGS='-run=TestAccSimpleDBDomain_' PKG=simpledb
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/simpledb/... -v -count 1 -parallel 20  -run=TestAccSimpleDBDomain_ -timeout 180m
=== RUN   TestAccSimpleDBDomain_basic
=== PAUSE TestAccSimpleDBDomain_basic
=== RUN   TestAccSimpleDBDomain_disappears
=== PAUSE TestAccSimpleDBDomain_disappears
=== CONT  TestAccSimpleDBDomain_basic
=== CONT  TestAccSimpleDBDomain_disappears
--- PASS: TestAccSimpleDBDomain_disappears (14.60s)
=== CONT  TestAccSimpleDBDomain_basic
    domain_test.go:22: Step 2/2 error running import: exit status 1

        Error: Resource Import Not Implemented

        This resource does not support import. Please contact the provider developer
        for additional information.

--- FAIL: TestAccSimpleDBDomain_basic (18.16s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/simpledb	22.260s
FAIL
make: *** [testacc] Error 1