tests/resource/aws_dax_subnet_group: Refactor import acceptance test into basic acceptance test
The random name generation previously had issues, likely because it was failing the "must begin with a letter" condition.

* Combine import acceptance test into basic acceptance test

Previously:

```
--- FAIL: TestAccAwsDaxSubnetGroup_import (5.43s)
    testing.go:527: Step 0 error: Error applying: 1 error occurred:
        	* aws_dax_subnet_group.test: 1 error occurred:
        	* aws_dax_subnet_group.test: InvalidParameterValueException: The parameter CacheSubnetGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
```

Now:

```
--- PASS: TestAccAwsDaxSubnetGroup_basic (56.58s)
```