tests/service/ec2: Implement PreCheck for EC2 Transit Gateway support
EC2 Transit Gateway is a newer resource type that is not supported in all AWS regions and partitions. Here we implement a PreCheck function to skip their acceptance tests until they are supported instead of failing.

Previous output from acceptance testing (AWS GovCloud (US)):

```
--- FAIL: TestAccAWSEc2TransitGateway_basic (5.19s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_ec2_transit_gateway.test: 1 error occurred:
        	* aws_ec2_transit_gateway.test: error creating EC2 Transit Gateway: InvalidAction: The action CreateTransitGateway is not valid for this web service.
```

Output from acceptance testing (AWS GovCloud (US)):

```
--- SKIP: TestAccAWSEc2TransitGateway_AmazonSideASN (2.09s)
--- SKIP: TestAccAWSEc2TransitGateway_AutoAcceptSharedAttachments (2.15s)
--- SKIP: TestAccAWSEc2TransitGateway_basic (2.10s)
--- SKIP: TestAccAWSEc2TransitGateway_DefaultRouteTableAssociation (1.75s)
--- SKIP: TestAccAWSEc2TransitGateway_DefaultRouteTableAssociationAndPropagationDisabled (2.12s)
--- SKIP: TestAccAWSEc2TransitGateway_DefaultRouteTablePropagation (1.86s)
--- SKIP: TestAccAWSEc2TransitGateway_Description (1.78s)
--- SKIP: TestAccAWSEc2TransitGateway_disappears (2.12s)
--- SKIP: TestAccAWSEc2TransitGateway_DnsSupport (1.85s)
--- SKIP: TestAccAWSEc2TransitGateway_Tags (1.79s)
--- SKIP: TestAccAWSEc2TransitGateway_VpnEcmpSupport (1.82s)
--- SKIP: TestAccAWSEc2TransitGatewayDataSource_Filter (1.77s)
--- SKIP: TestAccAWSEc2TransitGatewayDataSource_ID (1.73s)
--- SKIP: TestAccAWSEc2TransitGatewayRoute_basic (2.15s)
--- SKIP: TestAccAWSEc2TransitGatewayRoute_disappears (2.14s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTable_basic (2.12s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTable_disappears (2.07s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTable_disappears_TransitGateway (2.10s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTable_Tags (2.12s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTableAssociation_basic (1.78s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTableDataSource_Filter (2.10s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTableDataSource_ID (1.88s)
--- SKIP: TestAccAWSEc2TransitGatewayRouteTablePropagation_basic (1.90s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_basic (1.80s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_disappears (1.81s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_DnsSupport (2.14s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_Ipv6Support (2.12s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_SubnetIds (2.14s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_Tags (2.11s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociation (2.08s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTableAssociationAndPropagationDisabled (2.11s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachment_TransitGatewayDefaultRouteTablePropagation (2.10s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_Filter (1.75s)
--- SKIP: TestAccAWSEc2TransitGatewayVpcAttachmentDataSource_ID (2.10s)
...
PASS
ok    github.com/terraform-providers/terraform-provider-aws/aws 5.514s
```

Output from acceptance testing (AWS Standard):

```
--- PASS: TestAccAWSEc2TransitGateway_basic (162.64s)
```