tests/resource/aws_snapshot_create_volume_permission: Use different account_id
The EC2 API stopped showing self account ID references in createVolumePermissions, so this test began failing with timeouts. We will now just set it an example account ID that matches the EC2 User Guide documentation.

Previous output from acceptance testing:

```
--- FAIL: TestAccAWSSnapshotCreateVolumePermission_Basic (1229.99s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_snapshot_create_volume_permission.self-test: 1 error occurred:
        	* aws_snapshot_create_volume_permission.self-test: Error waiting for snapshot createVolumePermission (snap-00609fc98c06a3790-*******) to be added: timeout while waiting for state to become 'granted' (last state: 'denied', timeout: 20m0s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSSnapshotCreateVolumePermission_Basic (58.80s)
```