resource/aws_db_instance: Prevent schema version 1 upgrade panic on missing state
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12771

Previously:

```
--- FAIL: TestResourceAwsDbInstanceStateUpgradeV0 (0.00s)
    --- FAIL: TestResourceAwsDbInstanceStateUpgradeV0/missing_state (0.00s)
panic: assignment to entry in nil map [recovered]
  panic: assignment to entry in nil map

goroutine 1457 [running]:
testing.tRunner.func1.1(0x6577da0, 0x7d89790)
  /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc0012f07e0)
  /usr/local/Cellar/go/1.14.3/libexec/src/testing/testing.go:943 +0x3f9
panic(0x6577da0, 0x7d89790)
  /usr/local/Cellar/go/1.14.3/libexec/src/runtime/panic.go:969 +0x166
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDbInstanceStateUpgradeV0(...)
  /Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_instance_migrate.go:381
github.com/terraform-providers/terraform-provider-aws/aws.TestResourceAwsDbInstanceStateUpgradeV0.func1(0xc0012f07e0)
  /Users/bflad/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_db_instance_migrate_test.go:47 +0x65
```