tests/service/datasync: Implement PreCheck for DataSync support
DataSync is not supported in all AWS regions and partitions. Here we implement a PreCheck function to skip their acceptance tests until they are supported instead of failing.

Previous output from acceptance testing (AWS GovCloud (US)):

```
--- FAIL: TestAccAWSDataSyncTask_basic (671.40s)
    testing.go:538: Step 0 error: Error applying: 2 errors occurred:
        	* aws_iam_role.destination: 1 error occurred:
        	* aws_iam_role.destination: Error creating IAM Role tf-acc-test-2093256190982529448destination: MalformedPolicyDocument: Invalid principal in policy: "SERVICE":"datasync.amazonaws.com"
        	status code: 400, request id: 6e5ea567-13dc-11e9-aa5a-ef5dc9a9fbf1

        	* aws_datasync_agent.source: 1 error occurred:
        	* aws_datasync_agent.source: error retrieving activation key from IP Address (160.1.20.108): error making HTTP request: Get http://160.1.20.108/?gatewayType=SYNC&activationRegion=us-gov-west-1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Output from acceptance testing (AWS GovCloud (US)):

```
--- SKIP: TestAccAWSDataSyncAgent_AgentName (28.25s)
--- SKIP: TestAccAWSDataSyncAgent_basic (17.96s)
--- SKIP: TestAccAWSDataSyncAgent_disappears (28.29s)
--- SKIP: TestAccAWSDataSyncAgent_Tags (23.88s)
--- SKIP: TestAccAWSDataSyncLocationEfs_basic (20.20s)
--- SKIP: TestAccAWSDataSyncLocationEfs_disappears (21.21s)
--- SKIP: TestAccAWSDataSyncLocationEfs_Subdirectory (24.07s)
--- SKIP: TestAccAWSDataSyncLocationEfs_Tags (23.94s)
--- SKIP: TestAccAWSDataSyncLocationNfs_AgentARNs_Multple (25.21s)
--- SKIP: TestAccAWSDataSyncLocationNfs_basic (24.53s)
--- SKIP: TestAccAWSDataSyncLocationNfs_disappears (21.70s)
--- SKIP: TestAccAWSDataSyncLocationNfs_Subdirectory (24.09s)
--- SKIP: TestAccAWSDataSyncLocationNfs_Tags (19.71s)
--- SKIP: TestAccAWSDataSyncLocationS3_basic (24.30s)
--- SKIP: TestAccAWSDataSyncLocationS3_disappears (22.41s)
--- SKIP: TestAccAWSDataSyncLocationS3_Tags (28.72s)
--- SKIP: TestAccAWSDataSyncTask_basic (25.32s)
--- SKIP: TestAccAWSDataSyncTask_CloudWatchLogGroupARN (24.80s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime (28.47s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond (23.26s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_Gid (22.59s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions (22.43s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles (21.78s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices (28.78s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_Uid (26.30s)
--- SKIP: TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode (22.55s)
--- SKIP: TestAccAWSDataSyncTask_disappears (25.39s)

PASS
ok    github.com/terraform-providers/terraform-provider-aws/aws 50.944s
```

Output from acceptance testing (AWS Standard):

```
--- PASS: TestAccAWSDataSyncTask_basic (491.08s)
```