resource/aws_kinesis_firehose_delivery_stream: Ensure processing_configuration, processors, and parameters configurations omit equals in testing and documentation
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (645.47s)
    testing.go:568: Step 1 error: config is invalid: Unsupported argument: An argument named "processing_configuration" is not expected here. Did you mean to define a block of type "processing_configuration"?

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (0.58s)
    testing.go:561: Step 0, expected error:

        config is invalid: Unsupported argument: An argument named "processing_configuration" is not expected here. Did you mean to define a block of type "processing_configuration"?

        To match:

        must be one of 'LambdaArn', 'NumberOfRetries'

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (0.61s)
    testing.go:561: Step 0, expected error:

        config is invalid: Unsupported argument: An argument named "processing_configuration" is not expected here. Did you mean to define a block of type "processing_configuration"?

        To match:

        must be 'Lambda'

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (0.59s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "processing_configuration" is not expected here. Did you mean to define a block of type "processing_configuration"?

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (0.44s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test369208788/main.tf:145,7-8: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (0.54s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test582087725/main.tf:145,7-8: Missing newline after argument; An argument definition must end with a newline.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidParameterName (1.58s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3InvalidProcessorType (1.59s)
--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (100.03s)
    testing.go:568: Step 1 error: errors during apply:

        Error: Error Updating Kinesis Firehose Delivery Stream: "terraform-kinesis-firehose-basicsplunktest-5117781729330898256"
        InvalidParameter: 2 validation error(s) found.
        - minimum field size of 1, UpdateDestinationInput.SplunkDestinationUpdate.S3Update.BucketARN.
        - minimum field size of 1, UpdateDestinationInput.SplunkDestinationUpdate.S3Update.RoleARN.

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test243512280/main.tf line 170:
          (source code not available)

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3Updates (102.96s)
    testing.go:568: Step 1 error: errors during apply:

        Error: Error Updating Kinesis Firehose Delivery Stream: "terraform-kinesis-firehose-basictest-6781643581593217393"
        InvalidParameter: 2 validation error(s) found.
        - minimum field size of 1, UpdateDestinationInput.ExtendedS3DestinationUpdate.BucketARN.
        - minimum field size of 1, UpdateDestinationInput.ExtendedS3DestinationUpdate.RoleARN.

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test134887329/main.tf line 155:
          (source code not available)

--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_importBasic (138.23s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3basic (138.55s)
--- PASS: TestAccAWSKinesisFirehoseDeliveryStream_ExtendedS3KmsKeyArn (150.44s)
--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_RedshiftConfigUpdates (927.15s)
    testing.go:568: Step 1 error: errors during apply:

        Error: Error Updating Kinesis Firehose Delivery Stream: "terraform-kinesis-firehose-basicredshifttest-384461740180170111"
        InvalidParameter: 7 validation error(s) found.
        - minimum field size of 1, UpdateDestinationInput.RedshiftDestinationUpdate.ClusterJDBCURL.
        - minimum field size of 6, UpdateDestinationInput.RedshiftDestinationUpdate.Password.
        - minimum field size of 1, UpdateDestinationInput.RedshiftDestinationUpdate.RoleARN.
        - minimum field size of 1, UpdateDestinationInput.RedshiftDestinationUpdate.Username.
        - minimum field size of 1, UpdateDestinationInput.RedshiftDestinationUpdate.CopyCommand.DataTableName.
        - minimum field size of 1, UpdateDestinationInput.RedshiftDestinationUpdate.S3Update.BucketARN.
        - minimum field size of 1, UpdateDestinationInput.RedshiftDestinationUpdate.S3Update.RoleARN.

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test622720873/main.tf line 173:
          (source code not available)

--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_ElasticsearchConfigUpdates (951.08s)
    testing.go:568: Step 1 error: errors during apply:

        Error: Error Updating Kinesis Firehose Delivery Stream: "terraform-kinesis-firehose-es-4235360875258436010"
        InvalidParameter: 4 validation error(s) found.
        - minimum field size of 1, UpdateDestinationInput.ElasticsearchDestinationUpdate.DomainARN.
        - minimum field size of 1, UpdateDestinationInput.ElasticsearchDestinationUpdate.IndexName.
        - minimum field size of 1, UpdateDestinationInput.ElasticsearchDestinationUpdate.RoleARN.
        - minimum field size of 1, UpdateDestinationInput.ElasticsearchDestinationUpdate.TypeName.

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test854467459/main.tf line 184:
          (source code not available)
```