r/aws_bedrockagentcore_agent_runtime: Add `authorizer_config.custom_jwt_authorizer.allowed_scopes` argument
```console
AWS_BEDROCK_AGENTCORE_RUNTIME_IMAGE_V1_URI=<redacted>.dkr.ecr.us-west-2.amazonaws.com/jb-test-strands-agent:latest make t K=bedrockagentcore T=TestAccBedrockAgentCoreAgentRuntime_authorizerConfiguration
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 tmp1 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/bedrockagentcore/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentCoreAgentRuntime_authorizerConfiguration'  -timeout 360m -vet=off
2026/03/09 15:01:36 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/09 15:01:36 Initializing Terraform AWS Provider (SDKv2-style)...

--- PASS: TestAccBedrockAgentCoreAgentRuntime_authorizerConfiguration (50.97s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagentcore   57.866s
```

```console
% AWS_BEDROCK_AGENTCORE_RUNTIME_IMAGE_V1_URI=<redacted>.dkr.ecr.us-west-2.amazonaws.com/jb-test-strands-agent:latest make t K=bedrockagentcore T=TestAccBedrockAgentCoreAgentRuntime_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 f-bedrockagentcore-runtime-allowed_scopes 🌿...
TF_ACC=1 go1.25.8 test ./internal/service/bedrockagentcore/... -v -count 1 -parallel 20 -run='TestAccBedrockAgentCoreAgentRuntime_'  -timeout 360m -vet=off
2026/03/09 15:16:55 Creating Terraform AWS Provider (SDKv2-style)...
2026/03/09 15:16:55 Initializing Terraform AWS Provider (SDKv2-style)...

=== CONT  TestAccBedrockAgentCoreAgentRuntime_disappears
    agent_runtime_test.go:82: Error running post-test destroy, there may be dangling resources: exit status 1

        Error: deleting Bedrock AgentCore Agent Runtime

        ID: tf_acc_test_5243252872440332914-gyGAk16Fbk
        Cause: operation error Bedrock AgentCore Control: DeleteAgentRuntime, ,
        AccessDeniedException: User:
        arn:aws:sts::<redacted>:assumed-role/<redacted>
        is not authorized to perform: bedrock-agentcore:DeleteAgentRuntime"

--- FAIL: TestAccBedrockAgentCoreAgentRuntime_disappears (40.19s)
--- PASS: TestAccBedrockAgentCoreAgentRuntime_basic (42.49s)
--- PASS: TestAccBedrockAgentCoreAgentRuntime_description (55.23s)
--- PASS: TestAccBedrockAgentCoreAgentRuntime_protocolConfiguration (55.38s)
--- PASS: TestAccBedrockAgentCoreAgentRuntime_authorizerConfiguration (56.86s)
--- PASS: TestAccBedrockAgentCoreAgentRuntime_environmentVariables (58.32s)
--- PASS: TestAccBedrockAgentCoreAgentRuntime_tags (341.97s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagentcore   348.822s
```

Note: the `_disappears` test is failing persistently during post-test destroy. However, I'm hesitant to add handling for what seems to be an incorrect, or at least misleading, permissions error. My role does have `bedrock-agentcore:DeleteAgentRuntime` as evidenced by the other passing tests, and typically this would be a "NotFound" error that is handled gracefully by the `CheckDestroy` function. Perhaps there is some eventual consistency at play here following the initial runtime destruction that should be accounted for, but without further investigation I'm not going make changes at this time.