resource/aws_autoscaling_group: Ensure launch_template configuration in tests and documentation omits equals
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSAutoScalingGroup_launchTemplate (0.62s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "launch_template" is not expected here. Did you mean to define a block of type "launch_template"?
```

Output from Terraform 0.12 acceptance testing (new failure will need to be addressed seperately):

```
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate (52.91s)
--- FAIL: TestAccAWSAutoScalingGroup_launchTemplate_update (53.76s)
    testing.go:568: Step 3 error: errors during apply:

        Error: Error updating Autoscaling group: ValidationError: Invalid launch template version: either '$Default', '$Latest', or a numeric version are allowed.
        	status code: 400, request id: f5f7c480-1a1d-11e9-b84d-a3ce0c2e314b

          on /var/folders/v0/_d108fkx1pbbg4_sh864_7740000gn/T/tf-test329221421/main.tf line 44:
          (source code not available)

--- PASS: TestAccAWSLaunchTemplate_update (55.76s)
```