r/aws_lb_listener: isolate `tcp_idle_timeout_seconds` update flow
Updates to the `tcp_idle_timeout_seconds` argument are now handled distinctly from changes to other non-tag related arguments. Additionally, the logic applied to appropriately infer the protocol for gateway load balancers during the create operation has been replicated during update. Together these changes prevent failures when updating the `tcp_idle_timeout_seconds` argument for gateway load balancers like the following:

```
Error: modifying ELBv2 Listener (arn:aws:elasticloadbalancing:us-west-2:<redacted>:listener/gwy/tf-acc-test-5332588832756138226/541226271e9ad4ec/2bbf23d4354df440): operation error Elastic Load Balancing v2: ModifyListener, https response error StatusCode: 400, RequestID: c6f51e60-0511-443d-a98e-6f51b48fce11, api error ValidationError: An action must be specified
```

Also updates the `_attributes` acceptances tests to fully exercise the update workflow:

```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2Listener_attributes
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2Listener_attributes'  -timeout 360m
2024/11/06 16:12:02 Initializing Terraform AWS Provider...

--- PASS: TestAccELBV2Listener_attributes_gwlb_TCPIdleTimeoutSeconds (210.83s)
--- PASS: TestAccELBV2Listener_attributes_nlb_TCPIdleTimeoutSeconds (238.02s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      244.440s
```