service/eks: Fix testing and eks-getting-started example for EKS API change
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/13071
Reference: https://aws.amazon.com/blogs/containers/upcoming-changes-to-ip-assignment-for-eks-managed-node-groups/
Reference: https://github.com/awslabs/amazon-eks-ami/issues/423

This also switches the ReleaseVersion testing to use the newly available SSM Parameter, so it is no longer hardcoded and stale.

Previously:

```
--- FAIL: TestAccAWSEksNodeGroup_basic (1278.58s)
testing.go:683: Step 0 error: errors during apply:
Error: error waiting for EKS Node Group (tf-acc-test-8344543808745629148:tf-acc-test-8344543808745629148) creation: Ec2SubnetInvalidConfiguration: One or more Amazon EC2 Subnets of [subnet-09e307c552d8e2396, subnet-09b4b4c79ae9b1c5a] for node group tf-acc-test-8344543808745629148 does not automatically assign public IP addresses to instances launched into it. If you want your instances to be assigned a public IP address, then you need to enable auto-assign public IP address for the subnet. See IP addressing in VPC guide: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-ip-addressing.html#subnet-public-ip. Resource IDs: [subnet-09e307c552d8e2396 subnet-09b4b4c79ae9b1c5a]

--- FAIL: TestAccAWSEksNodeGroup_ReleaseVersion (1129.51s)
testing.go:683: Step 0 error: errors during apply:
Error: error creating EKS Node Group (tf-acc-test-395161592184105116:tf-acc-test-395161592184105116): InvalidParameterException: releaseVersion 1.14.8-20191213 is invalid
```

Output from acceptance testing:

```
--- PASS: TestAccAWSEksNodeGroup_AmiType (1539.44s)
--- PASS: TestAccAWSEksNodeGroup_basic (1485.68s)
--- PASS: TestAccAWSEksNodeGroup_disappears (1425.45s)
--- PASS: TestAccAWSEksNodeGroup_DiskSize (1551.75s)
--- PASS: TestAccAWSEksNodeGroup_InstanceTypes (1545.64s)
--- PASS: TestAccAWSEksNodeGroup_Labels (1647.48s)
--- PASS: TestAccAWSEksNodeGroup_ReleaseVersion (1578.86s)
--- PASS: TestAccAWSEksNodeGroup_RemoteAccess_Ec2SshKey (1566.70s)
--- PASS: TestAccAWSEksNodeGroup_RemoteAccess_SourceSecurityGroupIds (1698.65s)
--- PASS: TestAccAWSEksNodeGroup_ScalingConfig_DesiredSize (1619.70s)
--- PASS: TestAccAWSEksNodeGroup_ScalingConfig_MaxSize (1610.20s)
--- PASS: TestAccAWSEksNodeGroup_ScalingConfig_MinSize (1551.41s)
--- PASS: TestAccAWSEksNodeGroup_Tags (1501.53s)
--- PASS: TestAccAWSEksNodeGroup_Version (1513.24s)
```