resource/aws_rds_cluster: Properly update master_password during snapshot restore
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/9492

Since we cannot read the master password from the API during `Read`, it would silently be saved with the configuration value in the Terraform state and never trigger an update. This cannot be found via the acceptance testing framework without attempting to connect to the RDS Cluster (e.g. via the mysql provider), but relatedly added a test for master_username since that was also missing during snapshot restore, which highlighted a related missing test.

```
--- FAIL: TestAccAWSRDSCluster_SnapshotIdentifier_MasterUsername (377.68s)
    testing.go:568: Step 0 error: Check failed: Check 4/4 error: aws_rds_cluster.test: Attribute 'master_username' expected "username1", got "foo"
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterPassword (378.00s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterPassword (364.62s)
--- PASS: TestAccAWSRDSCluster_SnapshotIdentifier_MasterUsername (387.26s)
```