Acceptance test output:
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccFSxOpenZFSVolume_\|TestAccFSxOpenZFSFileSystem_' PKG=fsx ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 3  -run=TestAccFSxOpenZFSVolume_\|TestAccFSxOpenZFSFileSystem_ -timeout 720m
=== RUN   TestAccFSxOpenZFSFileSystem_basic
=== PAUSE TestAccFSxOpenZFSFileSystem_basic
=== RUN   TestAccFSxOpenZFSFileSystem_diskIops
=== PAUSE TestAccFSxOpenZFSFileSystem_diskIops
=== RUN   TestAccFSxOpenZFSFileSystem_disappears
=== PAUSE TestAccFSxOpenZFSFileSystem_disappears
=== RUN   TestAccFSxOpenZFSFileSystem_rootVolume
=== PAUSE TestAccFSxOpenZFSFileSystem_rootVolume
=== RUN   TestAccFSxOpenZFSFileSystem_securityGroupIDs
=== PAUSE TestAccFSxOpenZFSFileSystem_securityGroupIDs
=== RUN   TestAccFSxOpenZFSFileSystem_tags
=== PAUSE TestAccFSxOpenZFSFileSystem_tags
=== RUN   TestAccFSxOpenZFSFileSystem_copyTags
=== PAUSE TestAccFSxOpenZFSFileSystem_copyTags
=== RUN   TestAccFSxOpenZFSFileSystem_throughput
=== PAUSE TestAccFSxOpenZFSFileSystem_throughput
=== RUN   TestAccFSxOpenZFSFileSystem_storageType
=== PAUSE TestAccFSxOpenZFSFileSystem_storageType
=== RUN   TestAccFSxOpenZFSFileSystem_weeklyMaintenanceStartTime
=== PAUSE TestAccFSxOpenZFSFileSystem_weeklyMaintenanceStartTime
=== RUN   TestAccFSxOpenZFSFileSystem_automaticBackupRetentionDays
=== PAUSE TestAccFSxOpenZFSFileSystem_automaticBackupRetentionDays
=== RUN   TestAccFSxOpenZFSFileSystem_kmsKeyID
=== PAUSE TestAccFSxOpenZFSFileSystem_kmsKeyID
=== RUN   TestAccFSxOpenZFSFileSystem_dailyAutomaticBackupStartTime
=== PAUSE TestAccFSxOpenZFSFileSystem_dailyAutomaticBackupStartTime
=== RUN   TestAccFSxOpenZFSFileSystem_throughputCapacity
=== PAUSE TestAccFSxOpenZFSFileSystem_throughputCapacity
=== RUN   TestAccFSxOpenZFSFileSystem_storageCapacity
=== PAUSE TestAccFSxOpenZFSFileSystem_storageCapacity
=== RUN   TestAccFSxOpenZFSFileSystem_deploymentType
=== PAUSE TestAccFSxOpenZFSFileSystem_deploymentType
=== RUN   TestAccFSxOpenZFSFileSystem_multiAZ
=== PAUSE TestAccFSxOpenZFSFileSystem_multiAZ
=== RUN   TestAccFSxOpenZFSFileSystem_routeTableIDs
=== PAUSE TestAccFSxOpenZFSFileSystem_routeTableIDs
=== RUN   TestAccFSxOpenZFSVolume_basic
=== PAUSE TestAccFSxOpenZFSVolume_basic
=== RUN   TestAccFSxOpenZFSVolume_disappears
=== PAUSE TestAccFSxOpenZFSVolume_disappears
=== RUN   TestAccFSxOpenZFSVolume_parentVolume
=== PAUSE TestAccFSxOpenZFSVolume_parentVolume
=== RUN   TestAccFSxOpenZFSVolume_tags
=== PAUSE TestAccFSxOpenZFSVolume_tags
=== RUN   TestAccFSxOpenZFSVolume_copyTags
=== PAUSE TestAccFSxOpenZFSVolume_copyTags
=== RUN   TestAccFSxOpenZFSVolume_name
=== PAUSE TestAccFSxOpenZFSVolume_name
=== RUN   TestAccFSxOpenZFSVolume_dataCompressionType
=== PAUSE TestAccFSxOpenZFSVolume_dataCompressionType
=== RUN   TestAccFSxOpenZFSVolume_readOnly
=== PAUSE TestAccFSxOpenZFSVolume_readOnly
=== RUN   TestAccFSxOpenZFSVolume_recordSizeKib
=== PAUSE TestAccFSxOpenZFSVolume_recordSizeKib
=== RUN   TestAccFSxOpenZFSVolume_storageCapacity
=== PAUSE TestAccFSxOpenZFSVolume_storageCapacity
=== RUN   TestAccFSxOpenZFSVolume_nfsExports
=== PAUSE TestAccFSxOpenZFSVolume_nfsExports
=== RUN   TestAccFSxOpenZFSVolume_userAndGroupQuotas
=== PAUSE TestAccFSxOpenZFSVolume_userAndGroupQuotas
=== CONT  TestAccFSxOpenZFSFileSystem_basic
=== CONT  TestAccFSxOpenZFSFileSystem_deploymentType
=== CONT  TestAccFSxOpenZFSFileSystem_storageType
--- PASS: TestAccFSxOpenZFSFileSystem_storageType (678.10s)
=== CONT  TestAccFSxOpenZFSFileSystem_securityGroupIDs
--- PASS: TestAccFSxOpenZFSFileSystem_basic (779.98s)
=== CONT  TestAccFSxOpenZFSFileSystem_throughput
--- PASS: TestAccFSxOpenZFSFileSystem_deploymentType (1501.91s)
=== CONT  TestAccFSxOpenZFSFileSystem_copyTags
--- PASS: TestAccFSxOpenZFSFileSystem_securityGroupIDs (1359.14s)
=== CONT  TestAccFSxOpenZFSFileSystem_tags
--- PASS: TestAccFSxOpenZFSFileSystem_throughput (1289.23s)
=== CONT  TestAccFSxOpenZFSFileSystem_dailyAutomaticBackupStartTime
--- PASS: TestAccFSxOpenZFSFileSystem_copyTags (772.71s)
=== CONT  TestAccFSxOpenZFSFileSystem_storageCapacity
--- PASS: TestAccFSxOpenZFSFileSystem_tags (734.05s)
=== CONT  TestAccFSxOpenZFSFileSystem_throughputCapacity
--- PASS: TestAccFSxOpenZFSFileSystem_dailyAutomaticBackupStartTime (744.93s)
=== CONT  TestAccFSxOpenZFSVolume_name
--- PASS: TestAccFSxOpenZFSFileSystem_storageCapacity (842.47s)
=== CONT  TestAccFSxOpenZFSVolume_userAndGroupQuotas
    openzfs_volume_test.go:448: Step 1/3 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout

        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_fsx_openzfs_volume.test will be updated in-place
          ~ resource "aws_fsx_openzfs_volume" "test" {
                id                               = "fsvol-0d1449f0ba72cf246"
                name                             = "tf-acc-test-8593924653345881072"
                tags                             = {}
                # (10 unchanged attributes hidden)

              - user_and_group_quotas {
                  - id                         = 0 -> null
                  - storage_capacity_quota_gib = 0 -> null
                  - type                       = "GROUP" -> null
                }
              - user_and_group_quotas {
                  - id                         = 0 -> null
                  - storage_capacity_quota_gib = 0 -> null
                  - type                       = "USER" -> null
                }
                # (2 unchanged blocks hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- PASS: TestAccFSxOpenZFSVolume_name (1057.51s)
=== CONT  TestAccFSxOpenZFSVolume_nfsExports
--- FAIL: TestAccFSxOpenZFSVolume_userAndGroupQuotas (778.11s)
=== CONT  TestAccFSxOpenZFSVolume_storageCapacity
--- PASS: TestAccFSxOpenZFSFileSystem_throughputCapacity (1269.32s)
=== CONT  TestAccFSxOpenZFSVolume_recordSizeKib
--- PASS: TestAccFSxOpenZFSVolume_nfsExports (1032.34s)
=== CONT  TestAccFSxOpenZFSVolume_readOnly
--- PASS: TestAccFSxOpenZFSVolume_storageCapacity (1022.60s)
=== CONT  TestAccFSxOpenZFSVolume_dataCompressionType
--- PASS: TestAccFSxOpenZFSVolume_recordSizeKib (1044.49s)
=== CONT  TestAccFSxOpenZFSVolume_disappears
--- PASS: TestAccFSxOpenZFSVolume_disappears (815.04s)
=== CONT  TestAccFSxOpenZFSVolume_copyTags
--- PASS: TestAccFSxOpenZFSVolume_dataCompressionType (1001.99s)
=== CONT  TestAccFSxOpenZFSVolume_tags
--- PASS: TestAccFSxOpenZFSVolume_readOnly (1021.45s)
=== CONT  TestAccFSxOpenZFSVolume_parentVolume
--- PASS: TestAccFSxOpenZFSVolume_tags (882.95s)
=== CONT  TestAccFSxOpenZFSFileSystem_multiAZ
--- PASS: TestAccFSxOpenZFSVolume_parentVolume (896.20s)
=== CONT  TestAccFSxOpenZFSFileSystem_automaticBackupRetentionDays
--- PASS: TestAccFSxOpenZFSVolume_copyTags (967.24s)
=== CONT  TestAccFSxOpenZFSFileSystem_kmsKeyID
--- PASS: TestAccFSxOpenZFSFileSystem_kmsKeyID (733.53s)
=== CONT  TestAccFSxOpenZFSVolume_basic
--- PASS: TestAccFSxOpenZFSFileSystem_automaticBackupRetentionDays (886.28s)
=== CONT  TestAccFSxOpenZFSFileSystem_weeklyMaintenanceStartTime
--- PASS: TestAccFSxOpenZFSFileSystem_multiAZ (988.42s)
=== CONT  TestAccFSxOpenZFSFileSystem_disappears
--- PASS: TestAccFSxOpenZFSVolume_basic (822.03s)
=== CONT  TestAccFSxOpenZFSFileSystem_rootVolume
--- PASS: TestAccFSxOpenZFSFileSystem_weeklyMaintenanceStartTime (821.43s)
=== CONT  TestAccFSxOpenZFSFileSystem_routeTableIDs
--- PASS: TestAccFSxOpenZFSFileSystem_disappears (748.71s)
=== CONT  TestAccFSxOpenZFSFileSystem_diskIops
--- PASS: TestAccFSxOpenZFSFileSystem_diskIops (783.62s)
--- PASS: TestAccFSxOpenZFSFileSystem_routeTableIDs (1109.79s)
--- PASS: TestAccFSxOpenZFSFileSystem_rootVolume (1536.94s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	9964.705s
FAIL
make: *** [testacc] Error 1

Failure is unrelated to this change and occurs in CI.