tests/provider: Introduce testAccMatchResourceAttrRegionalHostname() for region and partition agnostic hostname testing (#11748)
Previously in the acceptance testing in AWS GovCloud (US):

```
--- FAIL: TestAccAWSEFSFileSystem_basic (27.99s)
    testing.go:640: Step 0 error: Check failed: Check 6/6 error: aws_efs_file_system.test: Attribute 'dns_name' didn't match "^[^.]+.efs.us-west-2.amazonaws.com$", got "fs-e91c94e8.efs.us-gov-west-1.amazonaws.com"
```

Preferring usage of this new `TestCheckFunc` will be checked via static analysis linter in the future.

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSEFSFileSystem_basic (42.46s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSEFSFileSystem_basic (49.75s)
```