tests/resource/aws_s3_bucket: Prevent CheckDestroy errors due to eventual consistency
Previously, these errors could be returned since bucket deletion may take a few seconds to propagate:

```
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: AWS S3 Bucket still exists: tf-test-bucket-865512847222774644
```

Output from acceptance testing:

```
--- PASS: TestAccAWSS3Bucket_basic (26.11s)
```