resource/aws_dlm_lifecycle_policy: Ensure tags_to_add and target_tags configurations include equals
This change is backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSDlmLifecyclePolicy_Basic (0.65s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Missing required argument: The argument "target_tags" is required, but no definition was found.
        - Unsupported block type: Blocks of type "target_tags" are not expected here. Did you mean to define argument "target_tags"? If so, use the equals sign to assign it a value.
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- PASS: TestAccAWSDlmLifecyclePolicy_Basic (14.58s)
=== CONT  TestAccAWSDlmLifecyclePolicy_Full
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1431 [running]:
github.com/zclconf/go-cty/cty.Value.HasIndex(0x5716a20, 0xc0008eaa70, 0x0, 0x0, 0x57169a0, 0xc0000be96a, 0x4fd6100, 0xc0036e1080, 0x472f120, 0xc0036e0d50, ...)
  /Users/bflad/go/pkg/mod/github.com/zclconf/go-cty@v0.0.0-20181231001355-67e3da15e430/cty/value_ops.go:738 +0xa7d
```