tests/service/codebuild: Implement PreCheck for CodeBuild support
CodeBuild is not supported in all AWS regions and partitions. Here we implement a PreCheck function to skip their acceptance tests until they are supported instead of failing.

Previous output from acceptance testing (AWS GovCloud (US)):

```
--- FAIL: TestAccAWSCodeBuildProject_basic (21.76s)
    testing.go:538: Step 0 error: Error applying: 1 error occurred:
        	* aws_codebuild_project.test: 1 error occurred:
        	* aws_codebuild_project.test: Error creating CodeBuild project: RequestError: send request failed
        caused by: Post https://codebuild.us-gov-west-1.amazonaws.com/: dial tcp: lookup codebuild.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from acceptance testing (AWS GovCloud (US)):

```
--- SKIP: TestAccAWSCodeBuildProject_Artifacts_EncryptionDisabled (24.22s)
--- SKIP: TestAccAWSCodeBuildProject_BadgeEnabled (24.10s)
--- SKIP: TestAccAWSCodeBuildProject_basic (22.71s)
--- SKIP: TestAccAWSCodeBuildProject_BuildTimeout (23.39s)
--- SKIP: TestAccAWSCodeBuildProject_Cache (27.21s)
--- SKIP: TestAccAWSCodeBuildProject_Description (21.75s)
--- SKIP: TestAccAWSCodeBuildProject_EncryptionKey (22.36s)
--- SKIP: TestAccAWSCodeBuildProject_Environment_Certificate (22.02s)
--- SKIP: TestAccAWSCodeBuildProject_Environment_EnvironmentVariable_Type (27.52s)
--- SKIP: TestAccAWSCodeBuildProject_importBasic (24.23s)
--- SKIP: TestAccAWSCodeBuildProject_SecondaryArtifacts (23.68s)
--- SKIP: TestAccAWSCodeBuildProject_SecondarySources_CodeCommit (28.24s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Auth (21.94s)
--- SKIP: TestAccAWSCodeBuildProject_Source_GitCloneDepth (26.11s)
--- SKIP: TestAccAWSCodeBuildProject_Source_InsecureSSL (20.43s)
--- SKIP: TestAccAWSCodeBuildProject_Source_ReportBuildStatus_Bitbucket (27.60s)
--- SKIP: TestAccAWSCodeBuildProject_Source_ReportBuildStatus_GitHub (21.40s)
--- SKIP: TestAccAWSCodeBuildProject_Source_ReportBuildStatus_GitHubEnterprise (25.11s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_Bitbucket (22.28s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_CodeCommit (25.34s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_CodePipeline (23.15s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_GitHubEnterprise (21.73s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_NoSource (27.53s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_NoSourceInvalid (24.58s)
--- SKIP: TestAccAWSCodeBuildProject_Source_Type_S3 (21.66s)
--- SKIP: TestAccAWSCodeBuildProject_Tags (20.62s)
--- SKIP: TestAccAWSCodeBuildProject_VpcConfig (22.01s)
--- SKIP: TestAccAWSCodeBuildProject_WindowsContainer (24.27s)
--- SKIP: TestAccAWSCodeBuildWebhook_Bitbucket (20.81s)
--- SKIP: TestAccAWSCodeBuildWebhook_BranchFilter (23.75s)
--- SKIP: TestAccAWSCodeBuildWebhook_GitHub (26.27s)
--- SKIP: TestAccAWSCodeBuildWebhook_GitHubEnterprise (19.98s)

PASS
ok    github.com/terraform-providers/terraform-provider-aws/aws 51.407s
```

Output from acceptance testing (AWS Standard):

```
--- PASS: TestAccAWSCodeBuildProject_basic (23.20s)
```