tests/resource/aws_codebuild_project: Remove WINDOWS_CONTAINER acceptance test
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/16163

The API no longer allows the creation of CodeBuild Project environments using the `WINDOWS_CONTAINER` value:

```
=== CONT  TestAccAWSCodeBuildProject_WindowsContainer
TestAccAWSCodeBuildProject_WindowsContainer: resource_aws_codebuild_project_test.go:1282: Step 1/2 error: Error running apply: 2020/11/12 06:11:09 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
Error: Error creating CodeBuild project: InvalidInputException: The environment type WINDOWS_CONTAINER is deprecated for new projects or existing project environment updates. Please consider using Windows Server 2019 instead.
--- FAIL: TestAccAWSCodeBuildProject_WindowsContainer (20.91s)
```

The resource should continue supporting the value in the schema validation (so existing environments can still work), however the acceptance test should be removed to prevent the recurring failure.