resource/aws_waf_web_acl: Refactor to use keyvaluetags.WafListTags() (#10801)
Output from acceptance testing (failure unrelated):

```
--- PASS: TestAccAWSWafWebAcl_disappears (12.41s)
--- PASS: TestAccAWSWafWebAcl_basic (16.78s)
--- PASS: TestAccAWSWafWebAcl_DefaultAction (27.95s)
--- PASS: TestAccAWSWafWebAcl_Tags (42.49s)
--- PASS: TestAccAWSWafWebAcl_changeNameForceNew (51.29s)
--- FAIL: TestAccAWSWafWebAcl_Rules (61.07s)
--- PASS: TestAccAWSWafWebAcl_LoggingConfiguration (109.63s)
```