tests/service/apigateway: Use internal implementation for TLS key/certificate
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/10023

Switches `aws_api_gateway_base_path_mapping` testing to the simplest `aws_api_gateway_domain_name` configuration with `regional_certificate_arn`. Requires new environment variables for `certificate_name` testing as CloudFront now strictly requires a publicly trusted key/certificate:

```
--- FAIL: TestAccAWSAPIGatewayDomainName_CertificateName (5.58s)
    testing.go:569: Step 0 error: errors during apply:

        Error: Error creating API Gateway Domain Name: BadRequestException: The certificate that is attached to your distribution was not issued by a trusted Certificate Authority. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidViewerCertificate; Request ID: e052f947-e261-11e9-a70c-b3beead7f798)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAPIGatewayBasePathMapping_basic (103.50s)
--- PASS: TestAccAWSAPIGatewayBasePathMapping_BasePath_Empty (61.24s)

--- SKIP: TestAccAWSAPIGatewayDomainName_CertificateArn (0.00s)
--- SKIP: TestAccAWSAPIGatewayDomainName_CertificateName (0.00s)
--- SKIP: TestAccAWSAPIGatewayDomainName_RegionalCertificateName (0.00s)
--- PASS: TestAccAWSAPIGatewayDomainName_RegionalCertificateArn (20.45s)
--- PASS: TestAccAWSAPIGatewayDomainName_SecurityPolicy (104.68s)
```