tests/service/transfer: Add PreCheck for service availability
Previously from AWS GovCloud (US) acceptance testing:

```
--- FAIL: TestAccAWSTransferServer_basic (1.07s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Transfer Server: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com on 192.168.22.2:53: no such host
```

Output from AWS GovCloud (US) acceptance testing:

```
--- SKIP: TestAccDataSourceAwsTransferServer_apigateway (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferServer_forcedestroy (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferServer_vpcEndpointId (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsTransferServer_service_managed (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferSshKey_basic (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccDataSourceAwsTransferServer_basic (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferServer_apigateway (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferUser_basic (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferUser_disappears (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferServer_disappears (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferUser_modifyWithOptions (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferUser_UserName_Validation (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAWSTransferServer_basic (2.58s)
    resource_aws_transfer_server_test.go:288: skipping acceptance testing: RequestError: send request failed
        caused by: Post https://transfer.us-gov-west-1.amazonaws.com/: dial tcp: lookup transfer.us-gov-west-1.amazonaws.com: no such host
```