tests/resource/aws_ssm_activation: Fix Terraform 0.12 syntax
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSSSMActivation_basic (0.41s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test868190439/main.tf:26,56-57: Missing newline after argument; An argument definition must end with a newline.

--- FAIL: TestAccAWSSSMActivation_expirationDate (0.51s)
    testing.go:561: Step 0, expected error:

        /opt/teamcity-agent/temp/buildTmp/tf-test572685278/main.tf:26,56-57: Missing newline after argument; An argument definition must end with a newline.

        To match:

        invalid RFC3339 timestamp
```

Output from Terraform 0.12 acceptance testing:

```
--- PASS: TestAccAWSSSMActivation_basic (31.62s)
--- PASS: TestAccAWSSSMActivation_expirationDate (31.70s)
```