resource/aws_elasticache_parameter_group: Handle Elasticache reset issues with reserved-memory parameter where possible
The Elasticache API is currently always returning an `InternalFailure` when attempting to reset the `reserved-memory` parameter. The resource previously provided an uphelpful timeout error with no way to workaround the behavior to properly update `reserved-memory` to a new value or switch to the `reserved-memory-percentage` parameter.

The resource now employs some handling to skip the `reserved-memory` reset, but only after its attempted before in case the Elasticache API is fixed in the future.

Changes:

* resource/aws_elasticache_parameter_group: Code and acceptance test workarounds for `reserved-memory` parameter always returning an error during update
* tests/resource/aws_elasticache_parameter_group: Switch from bespoke import test to always testing import
* tests/resource/aws_elasticache_parameter_group: Other minor refactoring to clean acceptance testing

Previously failing acceptance testing:

```
--- FAIL: TestAccAWSElasticacheParameterGroup_removeReservedMemoryParameter (76.81s)
    testing.go:538: Step 1 error: Error applying: 1 error occurred:
        	* aws_elasticache_parameter_group.bar: 1 error occurred:
        	* aws_elasticache_parameter_group.bar: Error resetting Cache Parameter Group: timeout while waiting for state to become 'success' (timeout: 30s)

--- FAIL: TestAccAWSElasticacheParameterGroup_updateReservedMemoryParameter (76.81s)
    testing.go:538: Step 1 error: Error applying: 1 error occurred:
        	* aws_elasticache_parameter_group.bar: 1 error occurred:
        	* aws_elasticache_parameter_group.bar: Error resetting Cache Parameter Group: timeout while waiting for state to become 'success' (timeout: 30s)

--- FAIL: TestAccAWSElasticacheParameterGroup_switchReservedMemoryParameter (77.01s)
    testing.go:538: Step 1 error: Error applying: 1 error occurred:
        	* aws_elasticache_parameter_group.bar: 1 error occurred:
        	* aws_elasticache_parameter_group.bar: Error resetting Cache Parameter Group: timeout while waiting for state to become 'success' (timeout: 30s)
```

Output from acceptance testing:

```
--- PASS: TestAccAWSElasticacheParameterGroup_basic (19.94s)
--- PASS: TestAccAWSElasticacheParameterGroup_UppercaseName (23.09s)
--- PASS: TestAccAWSElasticacheParameterGroup_Description (33.43s)
--- PASS: TestAccAWSElasticacheParameterGroup_addParameter (34.66s)
--- PASS: TestAccAWSElasticacheParameterGroup_removeAllParameters (43.51s)
--- PASS: TestAccAWSElasticacheParameterGroup_removeReservedMemoryParameter (43.57s)
--- PASS: TestAccAWSElasticacheParameterGroup_updateReservedMemoryParameter (86.12s)
--- PASS: TestAccAWSElasticacheParameterGroup_switchReservedMemoryParameter (95.82s)
```