tests/resource/aws_network_acl: Ensure ingress and egress configurations omit equals
These changes are backwards compatible with Terraform 0.11.

Previous output from Terraform 0.12 acceptance testing:

```
--- FAIL: TestAccAWSNetworkAcl_CaseSensitivityNoChanges (0.64s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "ingress" is not expected here. Did you mean to define a block of type "ingress"?

--- FAIL: TestAccAWSNetworkAcl_EgressAndIngressRules (0.56s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Unsupported argument: An argument named "egress" is not expected here. Did you mean to define a block of type "egress"?
        - Unsupported argument: An argument named "ingress" is not expected here. Did you mean to define a block of type "ingress"?

--- FAIL: TestAccAWSNetworkAcl_OnlyEgressRules (0.60s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test831355750/main.tf:29,3-9: Attribute redefined; The argument "egress" was already set at /opt/teamcity-agent/temp/buildTmp/tf-test831355750/main.tf:20,3-9. Each argument may be set only once., and 2 other diagnostic(s)

--- FAIL: TestAccAWSNetworkAcl_OnlyIngressRules_basic (0.43s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test867164090/main.tf:28,3-10: Attribute redefined; The argument "ingress" was already set at /opt/teamcity-agent/temp/buildTmp/tf-test867164090/main.tf:20,3-10. Each argument may be set only once.

--- FAIL: TestAccAWSNetworkAcl_OnlyIngressRules_update (0.43s)
    testing.go:568: Step 0 error: /opt/teamcity-agent/temp/buildTmp/tf-test262142492/main.tf:28,3-10: Attribute redefined; The argument "ingress" was already set at /opt/teamcity-agent/temp/buildTmp/tf-test262142492/main.tf:20,3-10. Each argument may be set only once.

--- FAIL: TestAccAWSNetworkAcl_importBasic (0.74s)
    testing.go:568: Step 0 error: config is invalid: 2 problems:

        - Unsupported argument: An argument named "egress" is not expected here. Did you mean to define a block of type "egress"?
        - Unsupported argument: An argument named "ingress" is not expected here. Did you mean to define a block of type "ingress"?

--- FAIL: TestAccAWSNetworkAcl_ipv6Rules (0.82s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "ingress" is not expected here. Did you mean to define a block of type "ingress"?

--- FAIL: TestAccAWSNetworkAcl_ipv6VpcRules (0.57s)
    testing.go:568: Step 0 error: config is invalid: Unsupported argument: An argument named "ingress" is not expected here. Did you mean to define a block of type "ingress"?
```

Output from Terraform 0.12 acceptance testing (additional fixes required upstream in Terraform Provider SDK):

```
--- FAIL: TestAccAWSNetworkAcl_EgressAndIngressRules (21.95s)
    testing.go:568: Step 0 error: Check failed: 2 errors occurred:
          * Check 2/14 error: aws_network_acl.bar: Attribute 'ingress.1871939009.protocol' expected "6", got "tcp"
          * Check 8/14 error: aws_network_acl.bar: Attribute 'egress.3111164687.protocol' expected "6", got "tcp"

--- FAIL: TestAccAWSNetworkAcl_ipv6Rules (27.79s)
    testing.go:568: Step 0 error: Check failed: Check 3/8 error: aws_network_acl.foos: Attribute 'ingress.1976110835.protocol' expected "6", got "tcp"

--- PASS: TestAccAWSNetworkAcl_ipv6VpcRules (29.36s)
--- PASS: TestAccAWSNetworkAcl_OnlyEgressRules (29.58s)
--- FAIL: TestAccAWSNetworkAcl_importBasic (29.74s)
    testing.go:568: Step 1 error: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) (len=2) {
         (string) (len=26) "egress.3111164687.protocol": (string) (len=1) "6",
         (string) (len=27) "ingress.1871939009.protocol": (string) (len=1) "6"
        }

        (map[string]string) (len=2) {
         (string) (len=26) "egress.3111164687.protocol": (string) (len=3) "tcp",
         (string) (len=27) "ingress.1871939009.protocol": (string) (len=3) "tcp"
        }

--- FAIL: TestAccAWSNetworkAcl_OnlyIngressRules_update (29.77s)
    testing.go:568: Step 0 error: Check failed: 1 error occurred:
          * Check 3/11 error: aws_network_acl.foos: Attribute 'ingress.401088754.protocol' expected "6", got "tcp"

--- FAIL: TestAccAWSNetworkAcl_OnlyIngressRules_basic (30.07s)
    testing.go:568: Step 0 error: Check failed: 1 error occurred:
          * Check 2/8 error: aws_network_acl.foos: Attribute 'ingress.4245812720.protocol' expected "6", got "tcp"

--- PASS: TestAccAWSNetworkAcl_CaseSensitivityNoChanges (36.45s)
```