tests/resource/aws_lb_target_group_attachment: Refactoring for region/partition agnostic and blacklist usw2-az4 (#11714)
Previously in the acceptance testing:

```
--- FAIL: TestAccAWSLBTargetGroupAttachment_basic (6.93s)
    testing.go:640: Step 0 error: errors during apply:

        Error: Error launching source instance: Unsupported: Your requested instance type (t2.micro) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.
```

This refactors the base EC2 Instance and VPC configuration into a consolidated configuration with the `aws_ami` and `aws_partition` data sources so the testing is region and partition agnostic. Blacklists `usw2-az4` since the `t2.micro` EC2 Instance type is not available there. This also removes the errant and extraneous `IDRefreshName` configuration.

Output from acceptance testing:

```
--- PASS: TestAccAWSLBTargetGroupAttachment_lambda (49.63s)
--- PASS: TestAccAWSLBTargetGroupAttachment_ipAddress (112.10s)
--- PASS: TestAccAWSLBTargetGroupAttachment_disappears (122.51s)
--- PASS: TestAccAWSLBTargetGroupAttachment_basic (130.97s)
--- PASS: TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility (131.18s)
--- PASS: TestAccAWSLBTargetGroupAttachment_Port (131.87s)
```