tests/provider: Remove hardcoded aws_spot_fleet_request resource valid_until timestamps
Fixes errors in the acceptance testing due to the hardcoded timestamp that now in the past:

```
--- FAIL: TestAccAWSAppautoScalingPolicy_spotFleetRequest (608.94s)
    testing.go:615: Step 0 error: errors during apply:

        Error: Error requesting spot fleet: Error creating Spot fleet request, retrying: InvalidSpotFleetRequestConfig: Parameter: SpotFleetRequestConfig.ValidUntil is invalid.
```

Output from acceptance testing:

```
--- PASS: TestAccAWSAppautoScalingPolicy_spotFleetRequest (65.36s)

--- PASS: TestAccAWSAppautoScalingTarget_spotFleetRequest (69.39s)

--- PASS: TestAccAWSAppautoscalingScheduledAction_SpotFleet (71.95s)

--- PASS: TestAccAWSSpotFleetRequest_associatePublicIpAddress (216.48s)
--- PASS: TestAccAWSSpotFleetRequest_basic (206.35s)
--- PASS: TestAccAWSSpotFleetRequest_changePriceForcesNewRequest (533.57s)
--- PASS: TestAccAWSSpotFleetRequest_diversifiedAllocation (345.03s)
--- PASS: TestAccAWSSpotFleetRequest_fleetType (257.81s)
--- PASS: TestAccAWSSpotFleetRequest_iamInstanceProfileArn (214.58s)
--- PASS: TestAccAWSSpotFleetRequest_instanceInterruptionBehavior (270.14s)
--- PASS: TestAccAWSSpotFleetRequest_LaunchSpecification_EbsBlockDevice_KmsKeyId (164.61s)
--- PASS: TestAccAWSSpotFleetRequest_LaunchSpecification_RootBlockDevice_KmsKeyId (163.22s)
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceAzInGivenList (343.26s)
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceAzOrSubnetInRegion (262.21s)
--- PASS: TestAccAWSSpotFleetRequest_lowestPriceSubnetInGivenList (270.21s)
--- PASS: TestAccAWSSpotFleetRequest_multipleInstancePools (342.22s)
--- PASS: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameAz (268.54s)
--- PASS: TestAccAWSSpotFleetRequest_multipleInstanceTypesInSameSubnet (271.32s)
--- PASS: TestAccAWSSpotFleetRequest_overriddingSpotPrice (343.62s)
--- PASS: TestAccAWSSpotFleetRequest_placementTenancyAndGroup (57.47s)
--- PASS: TestAccAWSSpotFleetRequest_updateExcessCapacityTerminationPolicy (462.71s)
--- PASS: TestAccAWSSpotFleetRequest_updateTargetCapacity (739.95s)
--- PASS: TestAccAWSSpotFleetRequest_withEBSDisk (207.57s)
--- PASS: TestAccAWSSpotFleetRequest_WithELBs (267.87s)
--- PASS: TestAccAWSSpotFleetRequest_withoutSpotPrice (249.80s)
--- PASS: TestAccAWSSpotFleetRequest_withTags (248.02s)
--- PASS: TestAccAWSSpotFleetRequest_WithTargetGroups (355.43s)
--- PASS: TestAccAWSSpotFleetRequest_withWeightedCapacity (268.46s)
```