tests/resource/aws_elasticsearch_domain: Add ImportStateId for ZoneAwarenessConfig import testing
The resource ID is an ARN and when used during import, returns an error that cannot be parsed by the AWS Go SDK:

```
--- FAIL: TestAccAWSElasticSearchDomain_ClusterConfig_ZoneAwarenessConfig (1020.88s)
    testing.go:568: Step 1 error: SerializationError: failed to unmarshal response error
        	status code: 400, request id:
        caused by: UnmarshalError: error message missing
```

Instead, set the import test ID to the match domain name.